### ISSUE TITLE
Suggestion for more relevant statistics

### ISSUE THREAD

**Issue by Minotorious** [mainIine/foe-helfer-extension#1003]
In the new statistics menu I would recommend you either add the option or by default group entries of the same kind in one bin. As seen in the two screenshots below for the GBG and GE tabs there are multiple entries for 5xWhateverUnit or 50xWhateverGood. It would make for much more relevant and cross age statistics if all such entries were combined in a single entry on the pie chart.

For example if I currently age up from Tomorrow and thereafter check the All time data for my GE rewards I will still be seeing 5xTomorrowAgeUnit which is no longer a relevant reward for me but on the other hand it should still count towards the percentage chance of me getting a random 5xUnit reward of my new age.

Hope I explained it well enough, if you have further questions regarding the suggestion let me know :)

PS: same for medals, it doesn't matter how many medals I got as it is age dependent and I can easily find out what the amount for my age is but they should all be binned in a single "I got medals reward"

![GB](https://user-images.githubusercontent.com/40427380/81482595-8545f600-9238-11ea-9b8a-cacb5b16c1b3.PNG)
![GE](https://user-images.githubusercontent.com/40427380/81482596-85de8c80-9238-11ea-91f0-10352c1c226b.PNG)

**Comment by osv** [comment]
Know suggestion, maybe later will be done, I also interesting in it

**Comment by kwhelan1** [comment]
I would also recommend a slice of the pie for misses as well.   So that we know what percent we didn't get any reward.

**Comment by andrgin** [comment]
I agree with the chance for misses because the really important number is not how many rewards I got, but how the chance is, but I am afraid it will not be that easy to solve.

**Comment by osv** [comment]
it possible, just need parse id of rewards: e.g. "resource#marble#200"

Note: To see all known rewards you can run `await IndexDB.db.statsRewardTypes.toArray()`

anyway I have not time for it 1 month.. I will back to it later
