### ISSUE TITLE
"Double Sniper" warnings

### ISSUE THREAD

**Issue by lotti2000** [mainIine/foe-helfer-extension#1011]
Hi, es wäre cool, wenn im Eigenanteilsrechner eine Warnung erscheinen würde, wenn der Eigenanteil so hoch ist, dass daas "double snipern" erreicht ist,
also, wenn P1 + P2 * Archanteil über 2/3 des Restes liegen:
Beispiel:
LG Saatgut Stufe 79 = 6100 FP gesamt, Eigenanteil zum absichern von P1 ist 742 FP.
Rest ist 6100 -742 = 5358
An der Stelle zahlen zwei je ein Drittel vom Rest ein = 2* 1786 = 3572
Die gewinnen zusammen damit 4019 FP, machen einen reingewinn von 447 FP (bei 1,9)

Eine Warnung müsste hier bereits erscheinen bei 71 FP Eigenateil (4019*3/2 = 6029)

**Comment by andrgin** [comment]
Mir ist die Vorgehensweise beim Team Snipe schon bekannt, aber wir sind noch etwas unschlüssig, wie wir damit umgehen sollen. Wenn wir das als Feature anbieten (wenn dann als Kombination in Kostenrechner und EARechner), dann treten wir da eventuell was los, was der Community an sich vielleicht nicht unbedingt gut tut.
Wie sehr wird das denn derzeit schon eingesetzt. Ich bin bisher noch nie das Opfer eines Team Snipes geworden obwohl ich derzeit im Mars bin, wo die Nachbarschaften schon sehr klein werden und man öfters Bekannte dort trifft.

**Comment by lotti2000** [comment]
Mir ist es jetzt das erste mal untergekommen, hab allerdings nun schon einige gesprochen, die das auch schon erfahren haben. Ich denke es ist ja erst relevant durch das "1-Klick" einzahlen und die Tatsache, dass vor allem sehr große Gebäude betroffen sind, deshalb denke ich, dass es sich schnell rumsprechen und zunehmen wird in nä. Zeit.

**Comment by xLasa** [comment]
Da gibt es sicherlich Unterschiede von Welt zu Welt, aber letztendlich werden das nicht alle, die Snipen so machen, weil sie keinen Partner zum snipen haben, es nicht mögen etc. Und die die jetzt nicht snipen werden das auch nicht nutzen. 

Aber wenn ihr den Anstoß dafür nicht geben wollt, dann würd ichs maximal im EAR integrieren und nicht im KR dann ist man zwar vorgewarnt aber muss es sich bei anderen immer noch selbst ausrechnen.

**Comment by andrgin** [comment]
In erster Linie macht das Team Sniping bei P1 und P2 Sinn. Im Bereich der kritischen Zone wo P1 schon vor dem Freischalten safe ist sehe ich hier nicht so eine große Gefährdung, weil hier P1/2 ja sowieso gleich nach dem Freischalten ausgeschrieben werden sollten.
Über dem kritischen Bereich ist es außer für Archen von lvl74-80 auch nicht so ein Thema denke ich, da hier das Risiko sehr groß ist, dass der Besitzer das LG dann einfach stehen lässt und was Anderes stattdessen levelt.
Relevant ist das Team Sniping meiner Ansicht nach am Ehesten ein Stück unter dem kritischen Bereich je nach LG so um lvl25-35, wo noch sehr bedenkenlos freigeschaltet wird und schon ein paar FP Eigenanteil drin landen.

**Comment by kronikpillow** [comment]
hahaha no one uses team sniping🤦🤦🤦
