### ISSUE TITLE
Idea: Production filter in the "Event Questline"

### ISSUE THREAD

**Issue by scibuff** [mainIine/foe-helfer-extension#1013]
It would be quite useful to have the option to show all upcoming "production" quests in the questline, so that you can start the next production right away (and have the productions ready to collect when you reach that quest).

![image](https://user-images.githubusercontent.com/722049/81554884-dca6ac00-9387-11ea-9faf-914d14888ab4.png)

**Comment by andrgin** [comment]
Why are the production quests so important. Shouldnt it be things like "scout a province" or "visit friends" that you should plan ahead for?

**Comment by scibuff** [comment]
1) I believe scouting has been discontinued from event quests (as higher era players complained it takes 24+hours without diamonds)
2) even before, there was maybe one such a quest, whereas there are regularly ~10 production quests
3) it takes a lot more planning to find the space in your city (even with just blacksmiths), unless you can get ~10 of those even using the production rush is painful.

**Comment by outoftheline** [comment]
Closing this, because the feature does not exist anymore :/
