### ISSUE TITLE
#WISH Convert to Safari

### ISSUE THREAD

**Issue by coastalcrown** [mainIine/foe-helfer-extension#1017]
I know it work for both chrome and firefox.
But is it possible to convert it to Safari?

**Comment by andrgin** [comment]
There are 3 reasons why I dont think we will do it:

.) Safari extensions require more adaptions to get the chrome extension running then on Firefox which is mostly compatible with chome. Biggest problem so far was files being injected in parallel and not sequential, but after some modifications we ended up with a version that is compatible on both platforms.
.) Safari market share is a lot lower than Firefox
.) Apple can be very creative when designing app guidlines etc. I am not sure we want to deal with all that.

**Comment by whocares1111** [comment]
FYI...it is stable on Opera as I am using it on my 7 worlds opening in different tabs

**Comment by pabse** [comment]
I want to revive this issue.
Apple recently added Safari Web Extensions, which are compatible with chrome extensions and not so restrictive.
https://developer.apple.com/documentation/safariservices/safari_web_extensions

They even have a [converter command](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari)

Maybe give it a try?
