### ISSUE TITLE
Rathaus: aktueller Gewinn

### ISSUE THREAD

**Issue by AlmostAtom** [mainIine/foe-helfer-extension#1024]
Der FP-Gewinn beim Öffnen von  Rathaus->Legendäre Gebäude stimmt nicht.
Mein tatsächlicher Gewinn ist höher als dort berechnet wird. Teilweise standen da schon negative Zahlen, obwohl ich definitiv nichts verlieren würde. Ein Grund könnte sein, dass sehr alte Einzahlungen, die aufgrund von Inaktivität nie zurückkommen werden, mit einbezogen werden. Aber das Problem dabei ist, dass da scheinbar nur die Einzahlungen mit berechnet werden, aber nicht das was man als Gewinn dabei machen würde. Also quasi komplett ohne Mäzenbonus.
Entweder sollten diese "toten" Einzahlungen komplett rausfallen oder zumindest Einzahlung+Gewinn einbezogen werden. Ersteres wäre optimal, letzteres zur Not auch noch annehmbar (wenn auch genauso wenig aussagekräftig wie im Moment). Aber es kann nicht sein, dass ich bei Einzahlungen, die immer Gewinn bringen (würden) am Ende sehr kleine oder sogar negative Gewinne haben soll.

**Comment by andrgin** [comment]
Wie alt eine Einzahlung ist kann an dieser Wtelle nicht erkannt werden.
Der einzige Filter ist folgender:
Wenn in einem LG noch mehr FP frei sind als man investiert hat, dann ist der Platz definitiv nicht sicher sein. In diesem Fall wird ein positiver Gewinn nicht mitgezählt, weil davon ausgegangen wird, dass sich jemand anderer rein setzen wird.

**Comment by AlmostAtom** [comment]
Ok, aber selbst ist die Rechnung komplett falsch.
Ich habe gerade nachgerechnet und die folgenden Zahlen kommen bei mir heraus [vorher und nachher die Zahlen im Rathaus per foe-helfer angeschaut; das ist gleichgeblieben, also kein LG in der Zeit fertiggestellt worden]; grad nur paar wenige Zahlen mit 1,9-Förderung, da konnt ichs gut nachprüfen:
1) mit FoE-Helfer angezeigter Gewinn: 191
2a) derzeit sicher investierte FP [baldiges level-up]: 8869
2b) Mäzenbonus+Archegewinn von den sicher investierten FP: 8949
3a) sonstige investierte FP..kein Platz sicher..wird wohl nie gelevelt: 76
3b) davon theoretischer Gewinn [der aber bei keinem jeweils stattfinden wird und keins davon ist sicher]: 995

Gesamt ergibt sich:
sicherer Gewinn: 2b-2a=80FP 
theoretischer zusätzlicher Gewinn: 3b-3a=919.  
Egal welche der Zahlen ich nehme, es wird nie der angezeigte Gewinn von 191 FP rauskommen können. Ich weiß nicht was da gerechnet wird, aber es ist halt einfach falsch.^^ Und das ist sicher nicht mein Rechenfehler.. ich hab das an mehreren Tagen und sogar auf zwei Welten mehrfach überprüft, es stimmt einfach nicht. Und auf meiner Zweitwelt sind noch weniger Fehlinvestitionen, da kommt fast immer was negatives raus.

**Comment by andrgin** [comment]
Kannst du einmal Screenshots von den betroffenen LGs posten, das ich das nachrechnen kann. So ist es etwas schwer zu überprüfen.

Was die nicht sicheren LGs angeht:
Hier wird der Gewinn nicht gezählt aber wenn du in einem der nicht sicheren LGs Verlust machst dann schon.

**Comment by AlmostAtom** [comment]
Ist zwar jetzt ne Weile her und die aktuellen Berechnungen hab ich noch nicht wieder kontrolliert, aber kann ja mal die alten Screens hochladen. Ist halt nur die Anzeige ausm Rathaus und nicht jedes einzelne LG, falls das irgendwas bringt..
![1_](https://user-images.githubusercontent.com/65259228/83023060-b68e3680-a02c-11ea-8766-5ddc3f72322e.png)
![2_](https://user-images.githubusercontent.com/65259228/83023065-b7bf6380-a02c-11ea-947c-4f295145dde7.png)
![3_](https://user-images.githubusercontent.com/65259228/83023070-b857fa00-a02c-11ea-8272-9f1fece52e8f.png)
![4_](https://user-images.githubusercontent.com/65259228/83023072-b9892700-a02c-11ea-97e2-c1a7ad4a2834.png)
![5_](https://user-images.githubusercontent.com/65259228/83023075-ba21bd80-a02c-11ea-9330-4c6ea78f9034.png)

**Comment by andrgin** [comment]
Hhm da ist in der Tat irgendetwas schief gegangen. Ich habe es jetzt mal mit der Hand durchgerechnet und komme genauso auf 290 FP sicheren Gewinn und bei den nicht sicheren auf ca. 14FP Verlust d.h  wir suchen um die 85FP, kann mir das aber absolut nicht erklären.
Eine Möglichkeit wäre dass aus irgendeinem Grund der Archenbonus falsch ausgelesen wurde.
