### ISSUE TITLE
Kostenrechner

### ISSUE THREAD

**Issue by SmartCologne** [mainIine/foe-helfer-extension#1031]
Wäre es möglich die errechneten Kosten per Klick in die zu spendenden FP zu übernehmen?

**Comment by andrgin** [comment]
Hhm gute Frage. Bei den grünen Zeilen bzw. den Snipewerten könnte man per Klick auf die FP den Wert in die Zwischenablage kopieren.
Bei den roten Zeilen beim Fördern wird es etwas schwieriger, da hier der Spieler entscheiden muss, ob er den vorgesehenen Wert bei z.B. 1.9 einzahlen will oder den Wert, bei dem der Platz safe ist.
