### ISSUE TITLE
Feature Request: Cloud Save

### ISSUE THREAD

**Issue by frank42hh** [mainIine/foe-helfer-extension#1038]
Moin,

ich bin die Tage auf neue Hardware gewechselt und dort mal FoE gestartet. Hierbei ist mir ein massives Problem aufgefallen. Zum einen waren die Einstellungen des Plugins alle wieder auf "default" settings, also die Anordnung in der Leiste, die Position der einzelnen Fenster, aber auch die eingestellten Daten darin wie z.B. im EA die vorgegebenen Archebonuswerte. Das wäre nicht ganz so dramatisch, aber was halt auch weg ist, sind die ganzen angesammelten Daten des Statistik Moduls. Ich habe nun auf zwei unterschiedlichen Rechnern Daten, die ich nicht wirklich zusammenführen kann, wodurch die Historie (z.B. Monatsübersicht Kriegsbeute) "für'n Arsch" ist.

Ich würde mir - da ich regelmäßig auf verschiedenen Rechnern spiele - unglaublich gerne wünschen, dass die Daten des Plugins - gerne optional - serverseitig gespeichert werden. Programmiertechnisch dürfte das ja kein Problem sein, aber ich kann mir vorstellen, dass serverseitig nicht der Platz für die ganzen Daten existiert. Ich würde daher optional das Feature als "Premium Funktion" vorschlagen, das man sich z.B. mit 1€ pro Monat per PayPal freischalten kann, damit der Mehrbedarf an Speicherplatz damit abgedeckt werden kann.

Gerade für Leute wie mich, die viel zwischen Desktop und Laptop wechseln, wäre das eine gewaltige Erleichterung.

**Comment by andrgin** [comment]
Der Platz am Server ist ein Problem, aber das Ganze müsste dannauch jemand programmieren. Sobald es sich nicht nur um einsimples Export/Import Feature handelt müsste man wahrscheinlich das ganze Statistikmodul neu machen.
Dazu kommen dann noch eine Reihe ungeklärter Datenschutzfragen (je mehr Daten desto problematischer) und so Fragen wie "was ist wenn der Server mal offline ist".

**Comment by scibuff** [comment]
Well, the first order of business would be to abstract all current localStorage / indexdb calls (repository pattern, see alerts.js for an example). This is a good thing to do regardless of whether the sync will be implemented or not. 

Then, someone would have to write a generic API (for the repository to talk to the server, handle sync and and server offline stuff)

**Comment by Makla5** [comment]
I am also using plugin on 2 or sometimes on 3 computers and would like shared statistics.
