### ISSUE TITLE
Altes Ägypten

### ISSUE THREAD

**Issue by icw135** [mainIine/foe-helfer-extension#1046]
Vorschlag:
Bei der Berechnung der benötigten Beute die jeweils 30 Stück, die für die letzte Quest benötigt werden berücksichtigen. Dies scheint mir aktuell noch nicht der Fall.  

Version 2.4.5  
Welt: de14  
  
Grüße

**Comment by andrgin** [comment]
Wurde bereits vorgeschlagen, aber ich bin mir nicht mehr so sicher, ob dies eine gute Idee wäre, da es mehrere Effekte gibt, die die Menge beeinflussen und das Ganze stark von der individuellen Strategie abhängig ist:
.) Wie schon erwähnt die je 30 Güter = 1200 Beute
.) Die Quest "Sammle 300 Beute und 20 Opfergaben" vor dem Pyramidenquest. Hier kann man entweder zuerst die Beute sammeln und damit die Opfergaben herstellen. Bis hier hin kann man seine Kampfeinheiten sowieso nicht alle löschen und je nach Kosten kann es sein, dass man die Opfergaben sowieso nicht mehr braucht.
.) Auch nicht berücksichtigt ist der 4x Bonus beim Herstellen der Güter. Durch diesen kann der Bedarf an Beute bei späteren Durchläufen deutlich reduziert werden. Da dies aber Zufall ist wird der Worst case dargestellt.
