### ISSUE TITLE
Gilden-Expedition

### ISSUE THREAD

**Issue by MissSaig** [mainIine/foe-helfer-extension#1049]
Der Gilden-Begegnungs-Durchschnitt funktioniert nicht mehr

**Comment by dsiekiera** [comment]
Wo genau sollte man den sehen? Meinst du in den Statistiken?

**Comment by MissSaig** [comment]
Sorry für die späte Antwort. War im junk gelandet. Heute erst entdeckt. Ich habe bestimmt was falsch gemacht. Hier der screen: https://prnt.sc/sr0jnj
