### ISSUE TITLE
Idea: settlements improvement - estimated time

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#1060]
Hi.
Before FoE Helper I was using Excel table to view my progress in settlements.
And in that tables I have columns with estimated time need to make all goods.
1) estimated time for single building of single type of good: X = Q / 25
(X - estimated time in days, Q - rest of needed goods, 25 - about 25 goods/day production cycle (8+8+4))
2) estimated time for all buildings of single type of good counting existing buildings of that type: Y = X / N
(Y - estimated time, X - from above formula, N - count of buildings of that type)

Example on screenshot:
![2005241236](https://user-images.githubusercontent.com/35531243/82750798-5775bb00-9dbb-11ea-8999-ecd65eed774c.png)

I think that it'll be helpfull if such info will appear in Helper.
Count of buildings of each type is known for Helper, I hope.

**Comment by andrgin** [comment]
Estimated time is hard to tell because we do not know when 4X bonus appears and which goods you will get for Japanese.

**Comment by belikoviv** [comment]
Estimated time - is worst case, without 4X bonus and without Trader.
To help us understand - if we can fit in rest time for settlement, or need do spmething to speed up making goods.
And when we got 4X or goods from Trader - estimated time will change accordingly.
It need to be dynamically calculated based on present amount of goods.

**Comment by belikoviv** [comment]
This is my current situation in Vikings settlement:

![2005241349](https://user-images.githubusercontent.com/35531243/82752263-7bd69500-9dc5-11ea-93f3-16ddd21f0eae.png)

Sory - I don't know right names for goods in English or German, so let it be G1, G2, G3 and G4.

For G1 - no more goods needed (excluding last quest).
For G2 - 23 / 25 = 0.92 - estimated time 0.9 days (with one building and if we don't get 4X)
For G3 - 3.2 days for 2 buildings, and it's too much - I'm need one more building to fit in time to end of settlement period.
And so on...

I hope I'm clearly describe what I want...
