### ISSUE TITLE
Idea: settlements improvement - city map

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#1061]
Hi.
Sometimes I'm very need to look at map of settlement "from top" (f.e. to find 1x1 emty square to build 1x1 dyplomacy).
As "flat" city map from main city.

**Comment by DanChaltiel** [comment]
When you use the extension tool "city map", you can use the top-left dropdown list and select "Standard" to have a "from top" view.

![image](https://user-images.githubusercontent.com/15105152/103815195-4a17f300-5063-11eb-8524-a964deffb17b.png)

**Comment by DanChaltiel** [comment]
I agree, it would be very handy to have a map of the colony as well.
As the tools are already developed, maybe it won't be a huge workload?
