### ISSUE TITLE
suggestion: add building age to the last tab of Building Overview

### ISSUE THREAD

**Issue by FoEHats** [mainIine/foe-helfer-extension#1070]
The building overview is a great tool.  The only thing that is missing is the building's age.  Could you please add the building's age (the initials, like PME for post modern) on the last tab where all the buildings are listed?  Thanks

**Comment by andrgin** [comment]
Do you mean the production overview?

**Comment by FoEHats** [comment]
Yes,  the last tab where all the buildings are.  It will help to see what buildings need to be upgraded and by how much when moving up without having to look at every building.  Sometimes I leave a building down because the upgrade does not produce extra of some items on every upgrade.
