### ISSUE TITLE
City planner: im abgespeicherten Plan sind Gebäude um zwei Felder nach unten verschoben

### ISSUE THREAD

**Issue by WeisserStein** [mainIine/foe-helfer-extension#1081]
Nach dem Abspeichern und Neuaufrufen einer gespeicherten Stadtversion sind alle veränderten Gebäude um zwei Felder nach unten verrutscht:
![grafik](https://user-images.githubusercontent.com/65923065/82925376-ec281680-9f7d-11ea-90e2-53d3e188f902.png)
Schon beim Bauen war mir aufgefallen, dass nach dem Aufrufen der Gebäude aus dem Zwischenlager links die Gebäude zwei Felder unter dem Mauszeiger angezeigt wurden.

**Comment by dsiekiera** [comment]
Ja das hab ich gestern auch gesehen. Das Offset stimmt nicht ganz. Da muss ich noch mal ran. Der Offset von 50px haut dort rein.

**Comment by dsiekiera** [comment]
![Bildschirmfoto 2020-05-27 um 09-27-03](https://user-images.githubusercontent.com/834814/82990305-4c5d9d80-9ffc-11ea-82d4-6ef3ce60493d.png)

Hab das Offset gefixt. Mein Chrome hat mich veralbert. Im Opera passte das nun.

**Comment by dsiekiera** [comment]
Sollte nun funktionieren
