### ISSUE TITLE
Vorschlag FP-Anzeige

### ISSUE THREAD

**Issue by strongstancer** [mainIine/foe-helfer-extension#1094]
In der Produktionsübersicht gibt es ja die Anzeige, wann jeweils wwelche Produktion von FP , Münen etc fertig ist. Dort kann man auch nach Zeit sortieren, dass man die nächsten Produktionen sieht. Wenn ich bsp. noch 90FP für etwas brauche, muss ich aber jetzt selber ausrechnen, wann ich die FP zusammen bekomme. Darum hier der Vorschlag:

Man kann eine Zeit bzw. eine FP Anzahl eingeben und dann wird automatisch ausgerechnet, wie viele FP in der gegebenen Zeit eingesammelt werden können bzw. wie lange man warten muss, bis die gegebene Anzahl FP erreicht ist. Evtl. mit einer Checkbox um die stündliche FP-Generation mit zu berücksichtigen zu lassen bzw. eben nicht.

Anwendungsbeispiel: Ich möchte ein LG leveln und benötige für die Absicherung eines Platzes noch 120 FP. Ich weiß, dass ich heute Abend um 21:00 das letzte mal online kommen kann, um FP einzusammeln und auszugeben. Jetzt gebe ich in dem Rechner 21:00 ein und er spuckt mir aus, dass ich bis dahin 85 FP nur bekomme. Jetzt schaue ich, wie lange ich für die 120 FP brauche und er spuckt mir morgen 12:30 aus. Ich entscheide dann, dass ich nicht warten möchte, weswegen ich die fehlenden 35 FP anderweitig besorgen muss (GG, Lager etc.)

hoffentlich ist das irgendwie machbar :-)

LG

**Comment by andrgin** [comment]
Damit das Sinn macht müsste die Produktionsübersicht erst einmal eine Funktion bekommen um das Einsammeln bzw. starten neuer Produktionen zu tracken. Derzeit wird das alles nur beim Laden des Spiels errechnet d.h. alles was du einsammelst bleibt in der Liste.

**Comment by strongstancer** [comment]
Man könnte ja erst einmal davon ausgehen, dass abgelaufene Einträge (vor x Minuten/Stunden) eingesammelt wurden. Notfalls einen Hinweis einblenden, dass die Seite neu geladen werden muss, um korrekte Werte anzuzeigen

**Comment by andrgin** [comment]
Abgelaufene Erträge können auch einfach nur fertig sein und aufs Einsammeln warten.

**Comment by strongstancer** [comment]
Ich habe es gerade extra mit fertigen Produktionen noch mal getestet, um zu wissen wie genau es funktioniert.

Fertige Produktionen werden auch nach refresh der Seite noch angezeigt, eingesammelte nur bis zum refresh. Man müsste "nur" einen Hinweis einblenden, dass diese Funktion nur genaue Werte ermittelt, wenn die Seite zuvor neu geladen wurde. Somit sind eingesammelte Produktionen aus der Liste raus, alles andere bleibt drinnen.
