### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Dlonrab** [mainIine/foe-helfer-extension#1095]
To use FP calculator not only to calculate the costs of sniped FP  or cost to lock a position but also to calculate the extra costs per medal

Info: I use donating FP to other GB not only to obtain BP or tot snipe FP but in this stage mainly to obtain extra medals to speed up the expension of my city.

To do that I am prepared to pay extra FP to acquire a certain postion. It would be nice if those extra FP paid (already  computed by Foe Helper) would be expressed and also shown in the relevant window as med per extra FP.

example. 

![image](https://user-images.githubusercontent.com/64436664/83003620-db73b100-a00e-11ea-87b1-21c404440908.png)

Paid extra FP= 23
Gained Medals= 1159
Medals per extra paid FP 1159/23= 50

This way the user can quickly appreciate how efficient the payment of extra FP for obtaining extra medals is and look more easily for the best deal to quickly exchange extra FP for extra medals

**Comment by AlfonZ42** [comment]
Interesting, I have never paid extra FPs just to get medals.
However, I have paid extra FPs to get blueprints. For this, I set myself a limit - how much FP/BP I am willing to spend on a specific GB.

The second stage of this idea could be to be able to configure how many extra FPs the player is willing to spend per received medals and blueprint.
The medals part would be universal, the BPs part specific per GB.
For example: I am willing to spend 1 FP per 50 received medals, 10 FPs per received BP of Arc, but 0 FPs to get a Colosseum's BP.
The setting would affect all _Possible deposits_/_Cost Calculator_ calculations.
