### ISSUE TITLE
Share City Plans on the website

### ISSUE THREAD

**Issue by nryan2wc** [mainIine/foe-helfer-extension#1109]
The city planner on https://foe-rechner.de/ is an awesome tool and love being able to export my city to it, to see and play around with layouts. It would be awesome to be able to have a guildmate export their city to the website then be able to share it with me or others so we can bounce layout ideas off of each other in an easier manner. 

We can sort of do it exporting it via .png or .pdf, but there isn't a simple way to import their layout or to move buildings to offer and show suggestions

**Comment by dsiekiera** [comment]
This feature is still in progress.
