### ISSUE TITLE
Special Goods in Negotiation Helper

### ISSUE THREAD

**Issue by Norton5150** [mainIine/foe-helfer-extension#1119]
How about a checkbox to save Special Goods in Negotiation helper.  They are more valuable than even current age goods.

My example is only round 2 of negotiations, I would much prefer to exhaust all other good options before I use special goods, in my example I know Biolight is a good that is still needed, but it's not suggested, but the helper is suggesting 2 special goods that I'd prefer not to use at all if possible:

![image](https://user-images.githubusercontent.com/59580619/83219604-626f7900-a136-11ea-89ac-3f76b63ba7c0.png)

**Comment by andrgin** [comment]
Saving special goods is always on as I dont see a need to turn it off. Same applies to coins and supplies that are always used before everything else
