### ISSUE TITLE
Feature request - Ability to group (goods and units) on "Rewards"

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#1125]
See image:

![Tooltip](https://i.imgur.com/OWGWUR0.png)

I assume, for the most part, it's not really important to see the individual item for units and goods, would make the pie chart more useful. 

I'm thinking of something like a checkbox on the UI that would automatically group these.

**Comment by osv** [comment]
yes, not new idea to group by good/units. I can do it later when have time (next 3 weeks I'm busy)
