### ISSUE TITLE
Friend's List monitor request

### ISSUE THREAD

**Issue by DJKC123** [mainIine/foe-helfer-extension#1138]
I would like to see information about my friends like if they haven't logged on for a long period of time or if they do or don't m/p me.  Then I can use that info to delete friends and get more active friends.

I figure 25% of my friends are dead weight but I don't have the time to write them down and monitor them.  I could m/p by my activity list but I'd like a quick reference list of something like "this person hasn't logged on or m/p'ed you for weeks". 

Great product!!  Keep up the good work.

Thanks.

**Comment by osv** [comment]
Hi. This is not new request! There no way to know is player active or not. The easiest way is classic check who aid you and aid them, than remove friends than never aid you.
Also, before removing I'm entering to city to check tavern. If tavern is not full, than player possible is active.

Yes, Foe helper might collect such info when you visit player or check aids of players and make suggestion for you, but I think classic-friend-clean-way work fine for all.
