### ISSUE TITLE
Informationen zu einem legendären Gebäude bleiben leer

### ISSUE THREAD

**Issue by Gindi4711** [mainIine/foe-helfer-extension#1143]
Es werden zwar alle in der Gilde vorhandenen legendären Gebäude mit Anzahl angezeigt, aber wenn ich auf das Gebäude selbst klicke bekomme ich keinen Inhalt:

![Screen](https://user-images.githubusercontent.com/55417498/83449998-c5be1b80-a454-11ea-80c1-b37fa9cfedbc.png)

**Comment by dsiekiera** [comment]
I take a look as soon as possible...

**Comment by outoftheline** [comment]
Feature has been removed
