### ISSUE TITLE
Statistik - Belohnungen - "Seit Dienstag"

### ISSUE THREAD

**Issue by Muckinator735** [mainIine/foe-helfer-extension#1146]
![image](https://user-images.githubusercontent.com/66316515/83527526-32cec100-a4e8-11ea-89aa-47bb3b783782.png)

Die Statistik wird nicht am Dienstag zurückgesetzt, sondern am Mittwoch.

**Comment by osv** [comment]
So today is Tuesday. And you see rewards since last Wednesday. I think we calc last Tuesday wrongly.. 
Sadly have no time to debug next 3 weeks. If some one can, pls go ahead, or lets wait
