### ISSUE TITLE
Idea: Statistics > Rewards > "This round"

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#1149]
Currently we have these options:

- Today
- **Since Tuesday**
- Last 7 days
- This Month
- Last 30 days
- All

![image](https://user-images.githubusercontent.com/9089026/83560450-940d8900-a516-11ea-83d6-dc310173856f.png)

I highlighted the one which should be "this round", so it makes sens both for GE and GBG, not just GE. Or maybe dynamically label the button based on what is selected? The goal here is to be able to see my total income for the current round of GBG, if I'm not mistaken, this isn't really possible currently (although, in fact, the "Last 7 days" will be correct as of today :P).

**Comment by weltraumvogel** [comment]
Additional Idea: Remember the number of fights/negotiations for the selected time range, and have an checkbox to enable/disable it. 

Why? It's nice to see we have 54.2% Kits and 29.6% 10 FP. But it'd be even better to see: I've made 1000 fights and got 465 rewards (and 535times nothing)

**Comment by SkateScout** [comment]
Yeah this would be an great improvement of the statistic. Not only Tuesday but "This GG" Fights and Negotiations are Visible as long as the next GG did not start. So they are not so important.

**Comment by Nerd2020** [comment]
Have you been able to follow this issue any further? Among the newer postings was a similar one.
