### ISSUE TITLE
Vorschlag: Welt-Namen anzeigen

### ISSUE THREAD

**Issue by strongstancer** [mainIine/foe-helfer-extension#1165]
Hallo leibe Entwickler,

ich spiele auf mehreren Welten und habe oft mehrere Browser-Tabs offen. Ist es möglich, den Namen der Welt in der Leiste oben anzuzeigen? Noch cooler wäre natürlich, wenn der Broser-Tab entsprechend umbenannt werden kann, weiß aber nicht, ob das überhaupt geht.

Vielen Dank!

**Comment by scibuff** [comment]
Yes it is possible but the plugin may not be 100% multi "thread" safe esp when it comes to storing local data. For example, IndexedDB storage (which the plugin uses to store data) locks access to one tab at the time so things such as the plunderer, stats, and others may not work as expected.

**Comment by scibuff** [comment]
@dsiekiera @andrgin regarding this ^, do we need to make IndexedDB database names unique to lang/world? Otherwise, even if db locking is not an issue, the data will be mixed from all worlds

**Comment by strongstancer** [comment]
For me the plunder, statistics etc. is not mixed between worlds. They are seperate for each world. Up until now I did not find anything, that does not work for me with multiple simultaneously opened tabs.

**Comment by andrgin** [comment]
localstorage and indexedDB is already seperated by each world/language because the URL of the server is different.

**Comment by scibuff** [comment]
> localstorage and indexedDB is already seperated by each world/language because the URL of the server is different.

Ah, that makes sense

**Comment by dsiekiera** [comment]
He want the world name in the Browser Tab from the website

**Comment by strongstancer** [comment]
Only if possible. If not then at least in the top bar of FoE, mabye left of the age, opposite to the FP count
