### ISSUE TITLE
Wunsch: FP nach Set sehen

### ISSUE THREAD

**Issue by Tsching-Foe** [mainIine/foe-helfer-extension#1167]
In der Produktionsübersicht bei den FP wäre es ganz nett, wenn ich sehen könnte, was ein Set produziert und auf welcher Stufe die einzelnen Komponenten sind. Beispielsweise Kirschgarten-Set. Und wenn ich sehen könnte, welches Einzelteil noch verbessert werden könnte und was es dann bringt.

**Comment by dsiekiera** [comment]
Das ZA ist bereits in unserer Beta enthalten.

**Comment by andrgin** [comment]
Ich glaube er meint er das Verbessern der Eventgebäude mit mehreren Leveln. Das wird mit der Zuordnung aber etwas schwieriger.

**Comment by Tsching-Foe** [comment]
Ich habe Kirschgarten auf Stufe 1 stehen. Möchte in der Übersicht gerne sehen, was es an Werten bringt. Den Fels habe ich inzwischen auf Stufe 2. Jetzt würde ich gerne sehen, welche Teile ich noch verbessern kann und theoretisch (aber nicht wichtig) was es mir bringt.
Aber toll wäre eben zu sehen, was das Set bringt und dass es Komponenten gibt, die noch nicht auf Maximalstufe sind.
ZA wäre mir egal ...

**Comment by dsiekiera** [comment]
Diese Infos liegen vor. Die Frage ist wo man diese Infos noch "reinquetscht"

**Comment by Tsching-Foe** [comment]
Oben kann ich doch wählen zwischen einzeln und gruppiert. Wenn "gruppiert", dann wäre es schön, wenn die Sets mit ihren Elementen auftauchen. Würde für den Anfang doch reichen, oder?
