### ISSUE TITLE
Showing available buildings to aid by age

### ISSUE THREAD

**Issue by Bitzikc** [mainIine/foe-helfer-extension#1171]
The suggestion is to show a list of buildings that are available to mo/po (with building age) when visiting a friend\guild\neighbor. If I click a building on the list, a map will open and show its position, similarly to the plundering tool.
It would be possible to turn on/off this window from the settings window (probably default should be off). 
This feature can be awesome when looking to aid specific ages (for Truce Tower and Rain Forest).
Cheers!

**Comment by SteveCrookJr** [comment]
This is the base idea I came to request. I was thinking more in the line of the city planner, but the above sounds better.
