### ISSUE TITLE
Trade stats

### ISSUE THREAD

**Issue by vqt123** [mainIine/foe-helfer-extension#1178]
Ask:
I would like to see stats regarding what types of trades are being taken vs expiring.

Problem:
As someone who uses the marketplace heavily, i throw up hundreds of various trades a lot of which expire. It would be great to know which trades go through and which ones don't.

**Comment by andrgin** [comment]
You can already see trade events in the ingame event tab.

**Comment by vqt123** [comment]
@andrgin yea, would be nice though to have all the data collated into one place in the tor helper data charts and stats
