### ISSUE TITLE
Anzeige der Gebäudezeitalter in der Stadtkarte für den Friedensturm / Dynamischer Turm

### ISSUE THREAD

**Issue by mordillo666** [mainIine/foe-helfer-extension#1179]
Es ist, zumindest für mich, doch sehr mühselig, die entsprechenden Gebäude zu finden in der Freundesstadt, um an die gewünschten Güter mit dem Dynamischen Turm / Friedensturm zu gelangen. 

Gäbe es hier eine Möglichkeit, über die Stadtkarte, die ja auch zum Plündern benutzt wird, sich anzeigen zu lassen, wo Gebäude aus dem gewünschten ZA stehen, die auch noch moppelbar sind?

Bzw überhaupt eine Anzeige zu haben, ob in der Stadt was zu holen ist im gewünschten ZA. 

Gruß
Mordillo666

**Comment by scibuff** [comment]
Wouldn't be better to get a higher era goods and down-trade at 2-1.5:1 ?

**Comment by mordillo666** [comment]
Ofcourse, but a player in the mars era also has Buildings in the Stone age for exmaple. I have to pick the Building with the correct era manually. 
Also it's better for me to pick Arctic goods because all eras above it is difficult to trade down at the moment.
