### ISSUE TITLE
More Statistics

### ISSUE THREAD

**Issue by AmaKrass** [mainIine/foe-helfer-extension#118]
Growth / progress comparison for guild members and neighbors
Too see the pace of progress between  guild members and neighbors

**Comment by dsiekiera** [comment]
What progress should one see exactly? Do you mean the points?

**Comment by AmaKrass** [comment]
Yes Points, to see how fast the others are growing.

**Comment by dsiekiera** [comment]
You mean like this?

![Bildschirmfoto 2019-10-09 um 20-07-09](https://user-images.githubusercontent.com/834814/66507957-7a738900-ead0-11e9-8988-10508b13234f.png)

This is a part from the [foe-rechner.de](https://foe-rechner.de) side. You can register with your InGame Name and see many stats.
The english translations are in progress.

**Comment by AmaKrass** [comment]
No not exactly.
I found some nice statistics at "foe-tools.eu" but collecting the data is
boring with this tool.

[image: Statistic1.png]

[image: Statistic2.png]


Am Mi., 9. Okt. 2019 um 20:09 Uhr schrieb Daniel Siekiera <
notifications@github.com>:
