### ISSUE TITLE
Wrong Display of building in urban planning.

### ISSUE THREAD

**Issue by Qamar299** [mainIine/foe-helfer-extension#1192]
i m facing it from weeks that when i open my city in urban planning all building is 2 blocks upward from the original place. i love that planning but after that beg, i start hating it

**Comment by crios339** [comment]
Same here (W10/Chrome) !
![Capture_4](https://user-images.githubusercontent.com/64492263/84589003-6ab4fd00-ae34-11ea-9afe-a56ea30ac5af.jpg)

**Comment by dsiekiera** [comment]
I updated this tool a few minutes ago.
