### ISSUE TITLE
Ancient Egypt Loot estimate doesn't account for running productions

### ISSUE THREAD

**Issue by fedoen** [mainIine/foe-helfer-extension#1194]
Hi I just counted my productions to see if they are enough to finish gathering goods to unlock all advancements and I have enough with the current running productions (without x4 boost).
The helper doesn't account for the running productions and will show me I still need 220 loot. Not a big deal, but I just  wanted to let you know.

Great tool btw, keep up the good work!

Thank You!
![Screenshot from 2020-06-12 12-26-30](https://user-images.githubusercontent.com/9055126/84487905-1bda5c80-aca8-11ea-864e-e22893369624.png)

**Comment by andrgin** [comment]
Ja stimmt auf das habe ich bisher gar nicht gedacht.
