### ISSUE TITLE
Beute-Berechnung bei den Ägptern funktioniert nicht immer richtig

### ISSUE THREAD

**Issue by rauschm** [mainIine/foe-helfer-extension#1208]
Siehe hier:
[Screenshot](http://prntscr.com/szh62x)

**Comment by andrgin** [comment]
1.) Seltsam. Sieht so aus als würde er nur das erste Gut berechnen. Kannst du mit F12 in die Entwicklerkonsole gehen und schon ob im Konsolen Tab Fehlermeldungen (in rot) stehen?

2.) Kannst du schauen, ob es etwas damit zu tun hat, dass du einige Erweiterungen ausgewählt hast?
