### ISSUE TITLE
Wunsch: Statistiken zu "Beiträge zur Gilde"

### ISSUE THREAD

**Issue by Crolla** [mainIine/foe-helfer-extension#1212]
Nach Klick auf Global -> Deine Gilde kann man auf das quadratische Widget oben links klicken und "Beiträge zur Gilde" auswählen. Dann erhält man sehr viele Seiten, auf denen die einzelnen Gildenbeiträge (also Güterspenden) der letzten 20 (?) Tage aufgelistet sind. 

Ich würde diese Statistik sehr gern auswerten können, also z.B. sehen, wie viele Güter welcher Sorte von wem gespendet wurden. Eine solche Liste würde ich auch gern nach Spenden oder Produktionen filtern können. Weil gleichzeitig Güterentnahmen mit Namensnennung aufgelistet werden, würde ich die auch gern herausfiltern können, damit die Entnahme nicht von den Güterspenden einer Person abgezogen wird - oder die Entnahmen separat ansehen.

Wäre so etwas realistisch machbar? Falls das zu kompliziert ist, würde mir sonst auch eine Exportmöglichkeit der langen Liste z.B. in eine CSV-Datei helfen.

Vielen Dank für das wundervolle Tool, ohne das ich gar nicht mehr spielen möchte!

**Comment by DenaGoogle** [comment]
Ich kann die besagten Seiten lesen und grafisch auswerten. Habe dies auch schon Daniel vorgestellt. Auch für mich wäre eine Integration in den Helfer eine nette Zeitersparnis, wobei natürlich unser "Wettbewerbsvorteil" diesbezüglich dahin wäre.

**Comment by dsiekiera** [comment]
Steht alles noch auf dem Plan ;-)

**Comment by andrgin** [comment]
Ist mittlerweile implementiert.
