### ISSUE TITLE
Fehler bei Eigenanteils-Berechnung?

### ISSUE THREAD

**Issue by Crolla** [mainIine/foe-helfer-extension#1220]
Die Berechnung des Eigenanteils scheint manchmal ins Schlingern zu geraten.

In diesem Beispiel sind P1 und P2 belegt und sicher, P3 bringt 25 FP mal 190%, also 48 FP, P4 bringt 5 (10) FP. Insgesamt sind noch 166 FP frei. Der verbliebene Eigenanteil müsste also 108 FP sein, dann könnte jemand mit 48 FP auf P3 und jemand anderes mit 10 FP auf P4 gehen, um das LG zu leveln. Der Helfer berechnet allerdings einen restlichen Eigenanteil von 150 FP und P3 mit nur 16 FP. Ich kann diese Berechnung nicht nachvollziehen.

![AO11-12](https://user-images.githubusercontent.com/66923711/84753934-f0b17f00-afbf-11ea-8556-d01d9aefba73.png)

Windows 7 Professional SP 1 (64-bit)
Google Chrome Version 83.0.4103.106 (Offizieller Build) (64-Bit)

**Comment by Crolla** [comment]
Betriebssystem / Operating System: Windows 7 Professional SP1 (64-bit)
Verwendeter Browser inkl. Versionsnummer / Used Browser including version: Google Chrome Version 83.0.4103.106 (Offizieller Build) (64-Bit)
Forge of Empires Server: de3 (Cirgard)
Extension Version und Sprache der Extension. / Extension version and language of the extension: 2.4.6.2 Deutsch/German
Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln) / Errors in the console (press F12 and switch to console tab): 
DevTools failed to load SourceMap: Could not load content for chrome-extension://bkagcmloachflbbkfmfiggipaelfamdf/vendor/dexie/dexie.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Crolla** [comment]
Same result with Firefox:
Betriebssystem / Operating System: Windows 7 Professional SP1 (64-bit)
Verwendeter Browser inkl. Versionsnummer / Used Browser including version: Firefox 77.0.1 (64-Bit)
Forge of Empires Server: de3 (Cirgard)
Extension Version und Sprache der Extension. / Extension version and language of the extension: 2.4.6.2 Deutsch/German
Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln) / Errors in the console (press F12 and switch to console tab):
Einige Cookies verwenden das empfohlene "sameSite"-Attribut inkorrekt. 4
unreachable code after return statement
alerts.js:1516:8
mozImageSmoothingEnabled sollte nicht mehr verwendet werden. Bitte verwenden Sie die Eigenschaft imageSmoothingEnabled ohne Präfix stattdessen. ForgeHX-364b9292.js:1411:83
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. ForgeHX-364b9292.js:27418:251
mergeDatabases: Looks like your db is empty, trying to populate db using old databases indexdb.js:320:21
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 16 ForgeHX-364b9292.js:27529:237
mergeDatabases: Deleting old databases indexdb.js:320:21
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 3 ForgeHX-364b9292.js:27524:350
mergeDatabases: Done. indexdb.js:320:21
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 8 ForgeHX-364b9292.js:1369:492
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 4 ForgeHX-364b9292.js:27524:350
WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings)

**Comment by mordillo666** [comment]
Das stimmt schon:
P2 hat überbezahlt, deshalb ist P1 noch nicht sicher, denn P2 kann noch drüber. Um P1 abzusichern, müssen noch 150 EA rein, dann levelt aber P3 mit 16. ;-)

**Comment by andrgin** [comment]
Der Algorithmus des EA Rechners funktioniert so, dass die Plätze der Reihe nach abgesichert werden und nur sichere Plätze eingezahlt werden.
Du hast aber Recht, dass es wenig Sinn macht bereits eingezahlte Plätze abzusichern, wenn dadurch ein Platz weiter unten nicht mehr zur Gänze eingezahlt werden kann.

**Comment by mordillo666** [comment]
andrgin, in dem Bsp sind ja mehrere Fehler spielerseitig passiert. Zuerst hat der LG Besitzer seinen EA nicht eingezahlt. Dann hat P1 unsicher belegt. Dann hat P2 überbezahlt. Da kann ja der Rechner nichts für.
Willst du es dahingehend lösen, dass P1 unsicher bleibt, damit P3 voll einzahlen kann?

**Comment by andrgin** [comment]
Ich muss mir den Code erst noch einmal ansehen. Mein Ziel wäre:
.) Wenn P1 noch nicht eingezahlt ist, dann bleibt es wie es ist.
.) Wenn P1 bereits drin ist, dann sollte kein Absichern vorgeschlagen werden, wenn ein anderer Platz schon früher safe ist.

**Comment by mordillo666** [comment]
Nur meine persönliche Meinung, ich fände es nicht so toll.
Der Rechner arbeitet dahingehend richtig, dass eingezahlte Plätze abgesichert sein MÜSSEN. Das halte ich auch für richtig, für mich persönlich ist das sogar primär. Ich würde es niemals anders machen. Er zeigt nur nicht alle Möglichkeiten auf. Zeigt er aber generell nicht, da er immer die sichere Methode darstellt.

Was mir gerade auffällt:
Es ist kein Hinweis ersichtlich, dass P1 nicht sicher ist. Wenn man einfach nur kurz drüberschaut, scheint es von der Darstellung her, dass alles in Ordnung wäre. Alles schön grün und blau. P1 irgendwie rot zu markieren, damit das Problem direkt ins Auge sticht, fände ich hilfreich.

**Comment by andrgin** [comment]
Wenn jemand in ein LG einzahlt ohne dass dieser Platz ausgeschrieben ist, dass tut er das in eigener Verantwortung. Das ist nicht Aufgabe des LG Eigentümers das zu verhindern.

Im Normalfall schlägt der EA Rechner dann vor, dass zuerst der Platz abgesichert werden soll (Eigenanteil vor dem jeweiligen Platz).
In diesem Fall ist das jedoch kein sinnvolles Vorgehen, da ja P3 schon safe ist. Hier macht es mehr Sinn zuerst nur P3 abzusichern, diesen einzahlen zu lassen und dann erst P1 abzusichern.
