### ISSUE TITLE
verhandlungen

### ISSUE THREAD

**Issue by cemislam** [mainIine/foe-helfer-extension#1224]
Hallo, also dei verhandlungen sind nicht immer zutreffend .
anstatt alle güter die vorkommen aml zuerst einzusetzen um zu wissen, ob die überhaupt vorkommen, wird es meistens ans ende gestellt das mann des öfteren diamanten einsetzen muss, ihr müsst an der logik des aufspürenst meiner meinung nach arbeiten.
auch ist das fenster das sich vorlegt einfach zu gross das man es ständig verschieben muss und den schnellen spielverlauf erheblich stört deswegen tue ich es meistens schon von anfang an weg machen.

einem kolegen habe ich das tool empfohlen, der hat noch vista installiert und kennt sich fast gar nicht mit dem pc aus. bei dem ist das so das irgendein modul anscheind nicht richtig arbeitet oder deaktiviert dies das die fenster nicht verschoben werden können. z.b liste der möglichen Lgs wo man einlegen kann. auch sind eure fenster schon zu gross bei meienm 18zoll ding nimmt es einfcah zu viel platz weg, wäre cool wenn man diese kleiner machen könnte wie ein browserfensetr oder.

2. ideenvorschläge habe ich gesucht extra mich angemeldet hier.

schön wäre es eventuell so als markierung wenn man ein LG zum snipen gefunden hat diese so als notizzettel zu nutzen, also man setzt quasi irgendwo ein haken zu einem LG was man beobachten möchte. da man ja schon einmal auf das lg zugegriffen hat wäre es nur so eine auflistung wie bei geplünderten nachbar welche einheite sie hatten oder..
so muss man nicht überall 1 fps verteilen damit es in der liste über dem rathaus auftaucht.

3. eigenanteil rechner  für eigene lgs sehr gut, aber
wäre mal schin wenn man vorblättern könnte um zu sehen was in der nächsten oder die nächsten stufen fp gebraucht wird.

sonst ein sehr nützliches tool mit guten ansätzen und hilfestellung. vieles habe ich noch nicht entdeckt, und scheint mir auch ein wenig kompliziert zu sein, wenn es einen lerntool geben würde wo man quasi per video über die möglichen einsatzgebiete informiert wird wo man so ein beispiel mal anschauen kann, wäre auch mal super.

ansonsten viel erfolg, 

LG CemIslam

P-s  - wie kann man denn die sprache hier auf der seite ändern?

**Comment by andrgin** [comment]
1.) Der Verhandlungsassistent wählt immer den Tipp mit der höchsten Lösungswahrscheinlichkeit aus. Das Sparen von bestimmten Gütern ist nur dann aktiv, wenn es mehrere Tipps mit gleicher Lösungswahrscheinlichkeit gibt.
Leider ist es auch bei Auswahl des idealen Tipps in den meisten Fällen nicht möglich auf 100% Lösungswahrscheinlichkeit zu kommen.

2.) Vista wird seit über 3 Jahren nicht mehr mit Sicherheitsupdates versorgt. Abgesehen vom Sicherheitsrisiko durch Vista selbst bekommen auch die Browser keine Updates mehr. Neue Features werden bei uns generell nur auf der aktuellen Version von Firefox bzw. Chrome getestet und eine 3 Jahre alte Version läuft definitiv nicht, da den Browsern von damals einige Features fehlen.

3.) Wenn Fenster zu groß sind dann poste bitte einen Screenshot. Dann können wir sagen, ob das das normale Verhalten ist oder nicht.

4.) Was das Blättern der LGs angeht: Ist zwar etwas komplizierter, weil wir die Mäzenboni von P1-P5 nicht übermittelt bekommen, wäre aber zumindest für die LGs, bei denen diese Werte in der Wiki ermittelbar sind möglich. Wir werden uns ein paar Gedanken dazu machen.

**Comment by SkateScout** [comment]
Hi, die Mäzen Belohnung ist nur vom ZA des LG abhängig.
Die Kosten sind mit 1.025^X von Level 10 aus berechenbar.
Fehlende Werte kann man einfach bekommen wenn man in ForgeDB sich das Größe LG eines ZA sucht und dort einmal zurückblättert.

**Comment by mordillo666** [comment]
Aus meiner Sicht arbeitet der Assistent perfekt. Dass es Verhandlungen gibt, in denen man in 4 Zügen nicht zur Lösung kommt, ist ja nicht dem Assistenten geschuldet. 
Ich spiele seit längerem jede Woche mit dem Assistenten die GEx durch. Mehr als 5 Fehlversuche hatte ich, glaube ich, noch nicht.
