### ISSUE TITLE
Suggesition: Time settings for statistics rewards

### ISSUE THREAD

**Issue by Nerd2020** [mainIine/foe-helfer-extension#1230]
At present it is not possible to look up the rewards from the current GBG (Gildengefechte). It would be nice to include the option not only "since Tuesday" (start of GEX) but "since start of GBG". 
Alternatively to allow the user to set the day of the start of the statistics.

**Comment by Nerd2020** [comment]
Ich würde gerne nachsehen können, welche Belohnungen ich in der aktuellen GG Saison bekommen habe. Zu wählende Voreinstellungen sind der Beginn der GEX (letzen Dienstag), oder 7 Tage, der Kalendermonat; keines davon ist für diesen Zweck zu gebrauchen.
Vielleicht könnte man auch offen lassen, den Start selbst eingeben zu können?

**Comment by GeniusTimo** [comment]
Duplicate of #1149
