### ISSUE TITLE
Can we add additional Scheme's for GB spots?

### ISSUE THREAD

**Issue by fbakkes** [mainIine/foe-helfer-extension#1240]
Is it possible to add another Scheme or to create a custom scheme on the settings page?

We use the following: Name GB 5 4 3 2 1

https://github.com/dsiekiera/foe-helfer-extension/blob/c1bc70bc71d2b951f99c4ccdf1fed069dab77d67/js/web/part-calc/js/part-calc.js#L464

**Comment by andrgin** [comment]
Currently no, but we are thinking about it.
