### ISSUE TITLE
Stadtplaner - Vorschlag

### ISSUE THREAD

**Issue by GidoB** [mainIine/foe-helfer-extension#1249]
Es wäre schön wenn man eine leere Stadt anfangen könnte und dann **ALLE** Gebäude auf der linken Seite (auch die aus meinem Lager, Gebäudesets usw.) zur Verfügung hätte. Dann müsste man auf der linken Seite nach bestimmten Kriterien sortieren können.

Zum Beispiel möchte ich meine Stadt nach Güter aufbauen. Das heißt ich würde alle meine Gebäude danach sortieren wollen wieviel Güter sie pro Feld produzieren. Dann könnte ich sie einfach der Reihe nach einfügen in meiner Stadt, angefangen mit denen die am meisten Güter pro Feld einbringen.

Wenn ich nun für mich genügend solcher Gebäude eingefügt habe möchte ich vielleicht den Rest meiner Gebäude nach Medaillen oder FP sortieren und solche hinzufügen.

Das würde es mir enorm erleichtern meine Stadt meinen Wünschen entsprechend schnell und effektiv zu bauen bzw. umzubauen.

**Comment by andrgin** [comment]
Der Stadtplaner ist noch ein relativ neues Feature. Das Hinzufügen neuer Gebäude ist geplant, funktioniert aber in der aktuellen Version noch nicht.
Was das Sortieren der Gebäude nach Güter- bzw. Medaillenproduktion angeht:
Dies ist in der Extension im Spiel mit den aktuellen Gebäuden in der Produktionsübersicht bei den Medaillen schon möglich. Mit den Gütern ab dem nächsten Update (in ein paar Tagen).
