### ISSUE TITLE
Beiträge zur Gildenkasse

### ISSUE THREAD

**Issue by Dave86k** [mainIine/foe-helfer-extension#125]
Hallo,

ist es geplant das auch die Beiträge zur Gildenkasse mit in die FoE Rechner Statistik aufgenommen werden?
Das fehlt uns noch etwas, ansonsten ein Super Tool! :)

**Comment by dsiekiera** [comment]
Steht auf dem Plan und wird ähnlich der Moppelaktivität aufgebaut sein. Man klickt dann die Seiten durch, da immer nur 10 Ereignisse auf einmal übertragen werden, und die werden an den Server geschickt.

**Comment by Horst-Krawuttke** [comment]
Auch Abgänge auf der Gildenkasse wären spannend,ggf. nach Spieler sortierbar.
Außerdem ein Bestandsverlauf nach Wochen für die einzelnen Güter. Gerade in Hinblick auf die Gildengefechte, die doch noch mal anderes Kosten generieren als GEx und GvG

**Comment by Gindi4711** [comment]
Es gibt mittlerweile ein Exporttool
