### ISSUE TITLE
Sounds does not work on world/server "FR2"

### ISSUE THREAD

**Issue by lnplnp** [mainIine/foe-helfer-extension#1285]
Version 2.4.6.2
ID Monde fr2

Hi,

It's seems that the sound does not work on this world.

It is ok on other worlds I'm on.

Thanks.

**Comment by andrgin** [comment]
Which sound do you mean? The notification sound of cost calculator or infobox?

**Comment by lnplnp** [comment]
I'm mean this notification sound: //*[@id="CalculatorOverviewTone"]


In addition and on all world/server, I note that the notification sound (//*[@id="CalculatorTone"]) does not work either in the main window of the calculator either. But it bothers me less.

**Comment by andrgin** [comment]
The overview has been with todays update 2.5.0 anyway.

For the calculator: Have you muted the sound with the speaker icon?

**Comment by lnplnp** [comment]
The sound was unmuted, off course ;o)
I'll tell you later if it's ok with the new version

**Comment by lnplnp** [comment]
It's seems that CalculatorOverview has disappeared with the new version, so there is no more bug... isn't it ?

**Comment by andrgin** [comment]
Well the sound in the Calculator is still here.
