### ISSUE TITLE
Production overview box too small

### ISSUE THREAD

**Issue by LordFelix** [mainIine/foe-helfer-extension#1302]
The production overview window is too narrow in several tabs, which causes things like the age (Space Age Asteroid Belt) to need 2 lines instead of one, effectively reducing to half the number of items displayed

**Comment by andrgin** [comment]
Can you post a screenshot please.

**Comment by LordFelix** [comment]
Of course.
![Captura1](https://user-images.githubusercontent.com/17072012/85938942-e8d3d200-b911-11ea-902f-3abd9ef224e4.PNG)
