### ISSUE TITLE
Suggestion - Show all rewards from Guild Expedition

### ISSUE THREAD

**Issue by Psilemnor** [mainIine/foe-helfer-extension#1306]
Hello :-)

The statistical tool is very useful. About the GEX it shows only rewards from RELICS

Could it also collect and display all the rewards (from the chests) ?

I would like to know what I have earned over time in GEX (forge points, gold, resources ....)

Thank you !

**Comment by GeniusTimo** [comment]
A good idea, maybe GEX could be renamed into Relics and the new category could be called GEX then 👍

**Comment by Psilemnor** [comment]
> A good idea, maybe GEX could be renamed into Relics and the new category could be called GEX then 👍

I would rather have a single report showing all the rewards for GEX ;-)

But maybe with a breakdown between relics and chests (subtotal / subcategory)

**Comment by GeniusTimo** [comment]
How about this?

![current look](https://user-images.githubusercontent.com/47282153/85933682-45b39600-b8da-11ea-8cc3-dbea1ebc8a5a.png)
![maybe future look](https://user-images.githubusercontent.com/47282153/85933694-5ebc4700-b8da-11ea-9933-7918699bbca5.png)

**Comment by Psilemnor** [comment]
@GeniusTimo wonderful ! an additional filter is exactly what I had in mind :-)

so we can see them separated OR cumulated :-)
