### ISSUE TITLE
Suggestion: Town Hall Great Building Contribution List: Add expected Medals Total

### ISSUE THREAD

**Issue by DerHabs** [mainIine/foe-helfer-extension#1312]
It would be useful to have this tool also add up the expected medals from the current GB reward list.  Currently it shows "Stock + Invested + Profit = FP", it seems adding this for medals would be easy "Stock + Profit = Medals".

Thank you.

**Comment by andrgin** [comment]
You can see the sum of all medals when uploading to the foe-rechner.de website. For "stock+reward": I dont know how this information could be useful for medals.

**Comment by DerHabs** [comment]
Thank you for the reply.  I am not sure where I can view the upload.  however, it would be most useful if displayed at this location, next to the expected FP investment.  See screen shot.

![Capture](https://user-images.githubusercontent.com/47467538/85951467-3d7a4b80-b918-11ea-8027-bc37452f04b1.JPG)
