### ISSUE TITLE
New GB Investment improvement

### ISSUE THREAD

**Issue by LordFelix** [mainIine/foe-helfer-extension#1331]
On the new GB Investment window, we can configure the "Friendly investment" percentage (90% by default).

Request adding a checkbox to include in calculations snipeable buildings, calculating with:
For 1st place, lower value between 1/2 total level cost or (1+ friendly investment)*(1st prize)
For 2nd place, lower value between 1/4 total level cost or (1+ friendly investment)*(2nd prize)

This would take into account getting friendly investments on non-snipeable positions, but account for snipers.

**Comment by andrgin** [comment]
So you are ppanning to get sniped every level? Seems like you need to get faster freinds in your 1.9 group :D

**Comment by LordFelix** [comment]
I teach them to mutually snipe as it costs less FP packages, so... yes, I do plan for people getting sniped
