### ISSUE TITLE
Suggestion - Improvement of the Colony tab

### ISSUE THREAD

**Issue by Psilemnor** [mainIine/foe-helfer-extension#1346]
![image](https://user-images.githubusercontent.com/67511740/85950448-0f6b2a80-b95d-11ea-9840-34b7716e2dba.png)

1. why is there a blue "?" near diplomacy ? I can not click on it and there is no tooltip so I can not figure how to use it

2. I feel the "missing resources" are not useful where I circled in green, it is only needed for the next building to build (and moreover we have the "cumulated" box to see all the missing resources for each step

**Comment by andrgin** [comment]
After you have unlocked the first diplomacy building the tooltip will show how many diplomacy buildings you will need to build.

**Comment by Psilemnor** [comment]
@andrgin what about the second suggestion I mentioned please ?

I believe the "lacking resources" info is useful as a general total (as it is today) and for the next building, but not for the others (the figures I have circled in green on the screenshot)
