### ISSUE TITLE
Suggestion - Improvement for the "Sets, upgrades and kits" tab

### ISSUE THREAD

**Issue by Psilemnor** [mainIine/foe-helfer-extension#1347]
1) Sometimes the item and upgrade or selection kit are properly grouped and on the same line
![image](https://user-images.githubusercontent.com/67511740/85950928-0a5baa80-b960-11ea-980f-df0cd3209813.png)

2) Sometimes the items are properly grouped, but they are not on the same line
I believe the upgrade kit should be on the same line as the main item
![image](https://user-images.githubusercontent.com/67511740/85950891-d3859480-b95f-11ea-9d71-05a80e6e27ec.png)

3) Sometimes the items and pack are not on the same line but they are not even grouped together as they should be
![image](https://user-images.githubusercontent.com/67511740/85950966-45f67480-b960-11ea-95aa-9ba7b9456f67.png)
![image](https://user-images.githubusercontent.com/67511740/85950979-59094480-b960-11ea-9d47-1e28e7a64bfc.png)

4) Some selection packs appear in the first tab and some other appear in the second tab
Couldn't they all be grouped ? like the Pantheon below (items grouped), the Cherry Garden could be grouped too and not split on 2 tabs
![image](https://user-images.githubusercontent.com/67511740/85951108-5bb86980-b961-11ea-9c2a-0670a7e119fd.png)
![image](https://user-images.githubusercontent.com/67511740/85951119-63780e00-b961-11ea-8408-b264bfd4c769.png)
![image](https://user-images.githubusercontent.com/67511740/85951137-74c11a80-b961-11ea-8be1-919bb6ea3757.png)

**Comment by andrgin** [comment]
Dont know about the grouping in one line, but there are 2 different types of kits:
.) Upgrade kits: Those are used to upgrade one event building and are listed in the ifrst tab
.) Selection kits: Those are used to either build an event building or upgrade it. Sometimes you can choose between several buildings or even other benefits. Those are listed in the second tab.

**Comment by Psilemnor** [comment]
Yes you are right but so what ? I believe it would be useful to have upgrade and selection kits grouped when they are from the same "set" of buildings

And from my screenshot you can see the Pantheon is nicely grouped => **the selection kit is not in the second tab**

In fact some selection kits appear in the first tab and other kits in the second tab => my idea is to let in the second tab only kits which are not related to a set of buildings 

So : Indian Palace, Piazza, Cherry Garden, Cemetery .... should be grouped in the first tab with their corresponding buildings ;-)

**Comment by andrgin** [comment]
In your inventory you have:
.) 1 Pantheon lvl1
.) 1 Pantheon upgrade kit

Those are listed on the first tab.

You do not have a Pantheon selection kit in your inventory

The reason for the header "Panthdon selection kit" is because you have the 2 items you get by opening the selection kit. I know the name is a bit misleading, but unfortunately this is the only name we get.

**Comment by Psilemnor** [comment]
Thank you @andrgin for your explanation :-)

But you are not right about my inventory, the item is indeed a SELECTION and not and UPGRADE kit ;-)

![image](https://user-images.githubusercontent.com/67511740/85954971-bd85cd00-b97b-11ea-94f6-8fe3d7c00f32.png)

And there is no upgrade kit in my inventory, so no mistake :-)

**Comment by Psilemnor** [comment]
@andrgin are you considering the suggestion for better grouping of items please ?
