### ISSUE TITLE
Need to update Extension description

### ISSUE THREAD

**Issue by adwsystems** [mainIine/foe-helfer-extension#1358]
With the mandated removal of all of the potential investment indicators, the description for the browser extension is now incorrect and over states the functionality of the extension. 

From the installation page: 
Small tools and helpers for a better gaming experience in Forge of Empires
>> Note: We are currently looking for translators for other languages. Take a look: https://forum.foe-rechner.de/d/174-your-language-translation-is-missing <<

For the page foe-rechner.de statistics can be collected and evaluated on the website. These include guild member statistics, guild member motivation activities, friends and neighbors. And all this fully automated in the background.

For further questions you can visit our small forum (https://forum.foe-rechner.de).

Furthermore, the extension currently shows in the form of a sidebar ingame:
**- Cost calculator (costs of the respective places and / or snipe-places)**
- own account calculator (order of deposits + own account calculator)
- harvestable FPs (SdW must be motivated)
- own FP production (how many FP does my city produce?)
- Outpost - Goods overview
**- and much more**

Hints:
- requires the use of the game "Forges of Empire" in the HTML5 version

(Items to be removed highlighted in bold)

**Comment by GeniusTimo** [comment]
What do you mean, exactly?

**Comment by adwsystems** [comment]
"-and much more" can be deleted as well. I don't see anything in the extension that isn't in the list.

**Comment by GeniusTimo** [comment]
The description can only be changed by @dsiekiera 😅 So he should work this out.

**Comment by andrgin** [comment]
This list seems very old, maybe from the first release? And translation could be improved a bit :D
