### ISSUE TITLE
Suggestion - grouping rewards

### ISSUE THREAD

**Issue by Psilemnor** [mainIine/foe-helfer-extension#1366]
![image](https://user-images.githubusercontent.com/67511740/86038435-33a03780-ba41-11ea-81f4-8873d43f06a5.png)

I believe rewards of the same type could be grouped to have a more meaningful graphic :-)

For instance I am interested to know that I have earned 10 military units, but I am not really interested in the detail (especially on a pie chart)

Same for resources, we could group all resources in a single category

**Comment by TrueLolek** [comment]
since the last update, the weaker players have gone bad..because i don't see the finished production so i attack everyone and when i'm already there i take what i know.i've only gone to the point so far.just for everything. it I do not know who was good?

**Comment by TrueLolek** [comment]
since the last update, the weaker players have gone bad..because i don't see the finished production so i attack everyone and when i'm already there i take what i know.i've only gone to the point so far.just for everything. it I do not know who was good?

**Comment by osv** [comment]
yes, some group should be done, this is not new request, I will work on it soon
