### ISSUE TITLE
Add Military Power to the Production Overview

### ISSUE THREAD

**Issue by guntherwullaert** [mainIine/foe-helfer-extension#1374]
I think it would be really nice if we could see a list of all the buildings we have  and how they contribute to the attack and Defence boost of our attacking army. It would look just like how the good productions are listed or population. In addition you could include a way of seeing the percentage of how efficient a building is in providing that said bonus.

**Comment by andrgin** [comment]
Yes this is planned somewhere in the future, but I am not sure yet how we should fit those 4 tabs in the UI.
