### ISSUE TITLE
Request - Bring back the "own resources/stock list" when looting

### ISSUE THREAD

**Issue by nryan2wc** [mainIine/foe-helfer-extension#1379]
One of the biggest things I miss about the old looting setup was being able to see the status of my resources compared to the available resources to plunder. So if the person has a Brick, Glass, and Rope goods buildings that are all plunderable don't show me what amounts they are producing (like before and what inno wanted removed) but rather show me my current stock of Brick, Glass and Rope. Knowing that on the sabotage window would make my life easier than having to click back screens or trying to remember what my stockpile currently has and what good is best to fit where I'm the lowest.

**Comment by weltraumvogel** [comment]
👍➕1️⃣
