### ISSUE TITLE
Produktionsübersicht in die Zwischenablage kopieren

### ISSUE THREAD

**Issue by wrudi** [mainIine/foe-helfer-extension#138]
Hallo, 
Ist es Möglich die Tabellen zum Beispiel der Produktionsübersicht in die Zwischenablage zu kopieren, wenn man abseits von FOE die Werte verwenden möchte??
Danke W. Rudi ;-)

**Comment by dsiekiera** [comment]
Was genau hast du denn damit vor? Evt kann ich dir schon helfen?

**Comment by wrudi** [comment]
Hi Daniel.
Danke für deine schnelle Antwort. 

ich hätte einiges damit vor.
Z.B. ich bin die meiste Zeit mit der App im Spiel, eine Liste wann welches LG Levelt wäre schon was feines.
Eine Liste welches Gebäude FP bringt und diese in Excel um auch Szenarien zu generieren Wie viele FP man für unterschiedliche Ausbaustufen man benötigt ist auch nicht schlecht.
Ähnliches wäre auch für die Güterverwaltung sehr nett.
Sprich eine Möglichkeit eure Outputs als Text  zu exportieren würde ich sehr angenehm empfinden (ich schreibe so ungern ab) ;-)
Danke, Rudi Wolf
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.10.19, 23:49, Daniel Siekiera <notifications@github.com> schrieb:
Was genau hast du denn damit vor? Evt kann ich dir schon helfen?


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dsiekiera/foe-helfer-extension/issues/138?email_source=notifications\u0026email_token=ANSMTFTBKXKPDPAM2PZAXXTQQDBIJA5CNFSM4JEIFG3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECC7TAA#issuecomment-545651072",
"url": "https://github.com/dsiekiera/foe-helfer-extension/issues/138?email_source=notifications\u0026email_token=ANSMTFTBKXKPDPAM2PZAXXTQQDBIJA5CNFSM4JEIFG3KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECC7TAA#issuecomment-545651072",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
