### ISSUE TITLE
Lock The Icon Position

### ISSUE THREAD

**Issue by Ijustwanttohelp** [mainIine/foe-helfer-extension#1384]
I am always accidentally moving the menu icons as I drag across the screen.  Would you please add an 'icon position lock' option in the setup section?

**Comment by outoftheline** [comment]
is that still happening for you? we worked on it some weeks ago when introducing the new menus

**Comment by Ijustwanttohelp** [comment]
Yes it is still happening.  My suggestion was to add an option under the
Settings Menu that would allow me to lock the location of the icons on the
FoE Helper bar.

Thank You for responding.
