### ISSUE TITLE
Idee/Wunsch: Gebäude- / Auswahl-Kits Modul um "Fehlende Kits" erweitern

### ISSUE THREAD

**Issue by frank42hh** [mainIine/foe-helfer-extension#1386]
Moin,

ein Punkt der mir gerade aufgefallen ist:  Es ist super, zu sehen, welche Kits man im Inventar rumliegen hat, aber es wäre deutlich hilfreicher, wenn man auch sehen könnte, welche Kits einem noch fehlen.
Ich habe z.B. aus einem vergangenen Event ein Gebäude, bei dem die letzte Ausbaustufe fehlt. Da die Gebäude samt Stufen eh beim Starten eingelesen werden (für die Produktionsübersicht z.B.) müsste es doch irgendwie möglich sein, mehrstufige Gebäude zu erfassen und die Anzahl der jeweils fehlenden Kits in einem separaten Tab des oben genannten Moduls anzeigen zu lassen.
Gerade beim Antiquitätenhändler könnte das hilfreich sein.

**Comment by andrgin** [comment]
Dazu müsste man zuerst einmal feststellen können wieviele Ausbaustufen es gibt. Eine feste Zuordnung gibt es nicht, nur eine Namenskonbention wo wir erst prüfen müssen ob bzw. wieviele Abweichungen es gibt.
