### ISSUE TITLE
Total FP Networth in Guild Member Data when logging into website

### ISSUE THREAD

**Issue by vqt123** [mainIine/foe-helfer-extension#1389]
Would be interesting to see a cumulative sum of ALL FP used across all greatbuildings on a player. I would like to be able to click on my guild and order from top to lowest based on this value (instead of just points)

**Comment by outoftheline** [comment]
I am not sure if I understand you. The FP Networth of a user is private data, isn't it? I wouldn't want others to know how much FP I have invested or in stock.

**Comment by andrgin** [comment]
I guess what he meant was an alternate point system based on the levels of great buildings and count the FP needed to level those great buildings.

Well that would be possible, but I am not sure it is worth the effort.
