### ISSUE TITLE
Notes feature is not secure : make it secure by storing it locally

### ISSUE THREAD

**Issue by zgr421** [mainIine/foe-helfer-extension#1394]
The newly added Notes feature is interesting but it is not secure at all as everybody can query or update the notes by sending a query to the server. What the attacker needs are the player id (found the json sent by inno) and the world id. The guild id is also sent in the web query but it is useless as the user is allowed to change his guild anyway.

The only way to make it secure is to store the data locally on the browser.
At least the use of the server storage should be an option and not mandatory.

**Comment by scibuff** [comment]
There are many ways (e.g. oauth like signatures) to make it secure ...

**Comment by andrgin** [comment]
We are aware of the problem and are currently working on a solution to authenticate the extension against the server. This does not only apply to notes, but also other upload features.

Storing notes locally is no solution because localStorage gets wiped every time you clear cookies.

**Comment by SkateScout** [comment]
Hi, ich befürchte das jede Methode zur Authentifizierung an dem Problem gleichen Problem wie dem Lokalen Speichern Scheitern wird.
>> "Storing notes locally is no solution because localStorage gets wiped every time you clear cookies." 
Dazu gäbe es nur 2 Alternativen:
- Client Zertifikat
- Benutzer/Password login (Oder PIN Login)

Da auch alle sonstigen Credentials nicht dauerhaft gespeichert werden können. (Stichwort Super Cookie).
Es sei den ihr holt euch Datei Schreib/Lese Berechtigung was viele Kritisch sehen können

**Comment by andrgin** [comment]
Der Plan geht momentan in die Richtung, dass wir den Login in der Extension machen. Das wäre zwar ein größerer Umbau, würde aber auch einige andere Probleme lösen.

**Comment by zgr421** [comment]
> Hi, ich befürchte das jede Methode zur Authentifizierung an dem Problem gleichen Problem wie dem Lokalen Speichern Scheitern wird.

That's not true. With an authentication to the foe-rechner, the user could be authenticated but the link between the foe-rechner account and the foe player id must be strongly checked. The, currently not working, foe-data.ovh site used to generate a temporary unique key per website account and the player had to rename his city with his key (in one world). The website then used a player account to dump all sort of data including the player list along with their city name and so was able to securily link one of their website account with a foe player id.

Anyway, my request regarding the local storage (that can be wipe out, agreed) is to be able to use the feature without storing any of my data on the foe-rechner website.

**Comment by SkateScout** [comment]
I think this should be also possible. Because other Plugins like uBlock also store Data indepedent of the cookie Store.
The Idea to use Cityname as the Key is also not really good.
1) This key can be spoofed since it is visible for other.
2) To require that other worlds need to be checked can violate the no auto requirement.
There i would prever andrgin's idea with Login in the Extension

**Comment by scibuff** [comment]
Well, even login into the extension can be spoofed; your current user id (for example) can be easily changed via Javascript, then when you register/login into the extension you can pretend to be any user you like. 

I agree that something along the lines of, for example, adding a generated unique key to the city's description (temporarily) might be the only reliable way to authenticate game's user id against a user with javascript.
