### ISSUE TITLE
Hide not used icons

### ISSUE THREAD

**Issue by zgr421** [mainIine/foe-helfer-extension#1395]
The helper provides quite a few tools but some of player (like myself) may use only a few of them and would like to hide others.
Allowing to configure which icons are visible in the toolbar (and not only their order) would allow the users to have a smaller more useable user interface.

**Comment by andrgin** [comment]
Why not just drag the icons you need on the first page and others on the last page?

**Comment by Psilemnor** [comment]
I have the same request as zgr421 but I was not aware of the "drag and drop" possibility which is great thank you andrgin !

**Comment by zgr421** [comment]
> Why not just drag the icons you need on the first page and others on the last page?

Because there is a difference between a neat UI and a UI full of buttons I never use. I currently use only 7 buttons (including the settings button).
