### ISSUE TITLE
Infobox für GvG

### ISSUE THREAD

**Issue by sdn-br** [mainIine/foe-helfer-extension#1398]
Benachrichtigungen in der Infobox wenn man sich auf einer GvG ZA Karte befindet wären sehr interessant.
Sowas wie BA gestellt, VA angegriffen, etc
Ich könnte hier auch etwas Code beisteuern, bin aber noch etwas verloren, wo ich ansetze. Ein neues Modul zu schreiben ist was anderes als mal einen Code Tweak beizusteuern. Eure Module sind schon recht umfangreich und der Code nicht 100% aufgeräumt. Wenn ihr mich in die richtige Richtung lenkt, dann werde ich mal was anfangen..

**Comment by outoftheline** [comment]
Ist ja jetzt als eigenes Modul eingebaut. Damit ist hier eigentlich ein Haken hinter, oder?
