### ISSUE TITLE
Eigenanteilsrechner und Kosten Rechner 

### ISSUE THREAD

**Issue by LordFacky** [mainIine/foe-helfer-extension#1399]
Sälü 
Ich habe 2 Monitore 
Gestern wollte ich meine beiden Rechner auf den 2ten Monitor verschieben , kaum angekommen waren sie weg .
Jetzt kann ich sie nicht mehr öffnen , Button ist da und wird auch grün ,als wenn ich es gelöscht hätte.
Habe auch schon das Tool gelöscht und neu installiert , aber es ist  nichts vorhanden .
Was kann ich machen das es wieder funktioniert

**Comment by outoftheline** [comment]
Bitte lösche einmal in den Einstellungen die Box-Koordinaten

**Comment by andrgin** [comment]
Hast du das Browserfenster über die 2 Monitore gestreckt?

Beim Verschieben oder Öffnen einer Box wird geprüft, ob sich diese im sichtbaren Bereich befindet und falls nicht, wird sie weiter zurück geschoben. Ich vermute einmal, dass es hier zu einem Problem mit der Erkennung der Fenstergröße gekommen ist und die neue Position als "außerhalb" eingestuft wurde.

**Comment by LordFacky** [comment]
Hey Sälü

Habe die Box Koordinaten gelöscht , wie du gesagt hast und jetzt geht es wieder .

Vielen Lieben dank, auch für die schnelle Antwort

________________________________
Von: Gindi4711 <notifications@github.com>
Gesendet: Freitag, 3. Juli 2020 19:21
An: dsiekiera/foe-helfer-extension <foe-helfer-extension@noreply.github.com>
Cc: LordFacky <mitanachim@msn.com>; Author <author@noreply.github.com>
Betreff: Re: [dsiekiera/foe-helfer-extension] Eigenanteilsrechner und Kosten Rechner (#1399)


Hast du das Browserfenster über die 2 Monitore gestreckt?

Beim Verschieben oder Öffnen einer Box wird geprüft, ob sich diese im sichtbaren Bereich befindet und falls nicht, wird sie weiter zurück geschoben. Ich vermute einmal, dass es hier zu einem Problem mit der Erkennung der Fenstergröße gekommen ist und die neue Position als "außerhalb" eingestuft wurde.
