### ISSUE TITLE
Gestion des GM

### ISSUE THREAD

**Issue by French-Kiss** [mainIine/foe-helfer-extension#1406]
Bonjour,

Le sujet des GM est très important dans le jeu.
Vous avez fait un beau travail sur le « Calcul de PF pour mes GM » concernant la gestion d’1 GM
Sauriez vous créer 2 documents complémentaires :
1	– Un tableau récapitulant tous les GM présents dans notre ville avec comme info :

•	Nom du GM / Niveau / Total PF / PF restants à poser
P1 (besoin ; posé) / P2(besoin ; posé) / P3(besoin ; posé) P4(besoin ; posé) P5(besoin ; posé)
•	Nom du GM / Niveau / Total PF / PF restants à poser
P1 (besoin ; posé) / P2(besoin ; posé) / P3(besoin ; posé) P4(besoin ; posé) P5(besoin ; posé)
•	Nom du GM / Niveau / Total PF / PF restants à poser
P1 (besoin ; posé) / P2(besoin ; posé) / P3(besoin ; posé) P4(besoin ; posé) P5(besoin ; posé)
Etc..

2	– Un tableau récapitulant tous les GM extérieurs sur lesquels nous avons posé des PF  (mêmes infos que pour 1)

On pourrait imaginer des codes couleurs indiquant si les places sont snipable, par exemple Vert non, rouge oui.

Cdt

**Comment by andrgin** [comment]
I dont know if I understood your wish correctly, but we only get the ranking information (reward of P1-P5 and who paid the FP) when opening each individual great building.

**Comment by SkateScout** [comment]
Über setzt will er eine Tabelle mit der Übersicht seiner LG's mit Max/Curr und ob P(N) belegt oder sicher ist.
Und die Gleiche Tabelle für die LG's die er Belegt hat. Bei einem Abspeichern der Werte in der Index.DB sollte
so eine Übersicht machbar sein.  Die Frage ist ob es Sinn macht. Fremde LG's sieht man im Rathaus. Eigene 
beim Versand dort immerhin MAX+CUR.
