### ISSUE TITLE
Idee: Preisample für Markt

### ISSUE THREAD

**Issue by YaSoFies** [mainIine/foe-helfer-extension#1409]
Die Spalte Kurs ist zwar gut gemeint aber kann schnell in die Irre führen wenn man das ZA nicht beachtet. So kann es besonders neuren Spieler oder auch müden schnell passieren zu übersehen das sie über 2 ZA tauschen und schon ist ein Kurs von 2 schon nicht mehr so gut. Ganz besonders wenn die ZA sogar verkehrt sind.

1. Somit sollte die Preisample vor inversen und unpassenden ZA warnen.
2. Die Preisample könnte auch die Gütergebäudegrundfläche mit berücksichtigen
3. falls vorhanden Durchschnittswerte angeben zu denen das Güterpaar gehandelt wurde

Hier ein schönes Beispiel für 1.:
![image](https://user-images.githubusercontent.com/5526277/86532172-05e74280-bec8-11ea-8dc8-3ac19550f7c4.png)
Mit Andy handeln wäre kein Gewinn, aber die Angebote von Berit sind ein echtes Schnäppchen.

Nextstep: eine überarbeitung des UIs um sich wieder holende Angebote zu stacken.

**Comment by SkateScout** [comment]
Achtung Markt ist kein Fenster des FOE-Helfer ich denke hier kann man nicht einfach das Layout ändern.

**Comment by YaSoFies** [comment]
Hmm, dachte das wäre möglich wie bei einer Webseite. So wie oben auch die FP vom Inventar angezeigt werden können.

Alternativ geht vielleicht eine überblendung.

Ansonsten einfach ein extra fenster das man links oder rechts davon hinschieben kann mit der Preisample und ggf. weiteren Zusatzinformationen wie z.B. der Felderbedarf des Produktionsgebäudes (besonders bei Trades im selben ZA)

**Comment by SkateScout** [comment]
Nein das Problem ist das der Markt mehr Zeilen lädt als Sichtbar sind.
z.b. 50 und damit kannst du dort Plättern ohne das die FOE-Helfer weis auf welcher Seite du bist.

**Comment by YaSoFies** [comment]
Achso, der FoE-Helper bekommt das dann nicht mit? Hmm. Schade ich hatte gehöfft der FoE-Helper könnte ggf. sogar die Liste neu sortieren. Könnte man ggf. den Button zum Seite wechseln mit einem FoE-Helper-Button überdecken welcher dann den sowohl den Button darunter auslöst als auch die FoE-Helperinhalte anpasst?

**Comment by SkateScout** [comment]
Nein das würde als Eingriff in das Click Verhalten gezählt werden.
Stell die das Ganze so vor FOE als VideoPlayer und den FOE-Helper als Fenster das sich Drüber legt. 
Du kannst Inhalte anzeigen aber aber keine Änderungen durchführen oder Aktionen auslösen.

**Comment by YaSoFies** [comment]
Ok die sind mal echt streng. Manipulation der Aktion hätte ich ja noch verstanden.

Gut aber ganz verstanden warum der Helper das Seitenumblättern nicht mit bekommen soll hab ich nicht. Bei den Ereignissen tut er das ja auch. Workaround wäre vielleicht ein Button beim FoEH mit dem man die "Ample" auch umblättern könnte. Durch wiederholung der Symbole oder Zahlen in dem extra Fenster könnte man auch verdeutlichen das dort noch die Werte zur letzten Seite stehen.

**Comment by Th3C0D3R** [comment]
das handelfenster hat eine feste Anzahl an Angeboten die angezeigt werden pro Seite.
Da alle Angebote beim öffnen geladen werden kann man so die Angebote teilen und in einem extra fenster dein gewünschter Vorschlag anzeigen, somit wäre die Seite im FOE-Helfer-Fenster gleich der Seite im Markt.

**Comment by SkateScout** [comment]
Mir stellt sich die Frage wie man raus bekommt auf welche Seite FOE gerade ist wenn doch alle Seiten geladen wurden.
Müsste man dazu nicht auf interne Variablen der Seite zugreifen ?

**Comment by Th3C0D3R** [comment]
wenn man den markt auf macht ist man immer auf Seite 1, wenn man im Helfer die Angebote genauso anzeigt wie im markt (was ja relativ einfach ist: 100 Angebote geladen, 10 Angebote pro Seite -> 10 Seiten)
dann kann man im helfer durchklicken und sieht, aha Seite 5 gibts ein gutes Angebot dann geht er in FoE auch auf seite 5 und holt sich das angebot. Das muss man natülich alles erstmal testen. Ist grad eher nur so theorie xD

**Comment by SkateScout** [comment]
> Gut aber ganz verstanden warum der Helper das Seitenumblättern nicht mit bekommen soll hab ich nicht.

Bei Ereignisse und Anderen Aktionen bekommt er nicht den "Click" mit sondern die HTTP Nachrichten und reagiert auf diese.
Also nur Indirekt auf den Click. Bei dem Blättern jedoch (Genauso wie Bestenliste und anderen Listen) wird mehr Geladen als Angezeigt und das Blättern erfolgt zum Teil oder Komplett ohne HTTP Nachrichten.

**Comment by YaSoFies** [comment]
Die Idee ist super, den Helfer unabhängig zu machen. 

So könnte man auch im Helfer frei sortieren und gleich die Seite mit angezeigt bekommen auf der man das Angebot dann findet. Ist zwar vom UX her ein Workaround, aber immer noch schneller als sich in FoE durch zu klicken.

**Comment by YaSoFies** [comment]
Soll ich noch mal ein neues Mockup machen?

**Comment by Th3C0D3R** [comment]
Wenn du willst 👍🏻

**Comment by YaSoFies** [comment]
Ok, hat etwas länger gedauert. Dafür ist mir noch was nettes eingefallen. Filter und sortieren ist jetzt zwar nicht dabei. Dafür sieht man den zukünftigen Lagerbestand kummuliert, also mit jedem Angebot größer, wenn sie unter einander sind und den gleichen Werten.
So wie rechts eine Anzeige für in Angebotenen gebundenen Güter die man durch auflösen dieser frei machen könnte.

![image](https://user-images.githubusercontent.com/5526277/88211308-d40b0580-cc55-11ea-9adc-ba591ee05167.png)

**Comment by GeniusTimo** [comment]
@andrgin bereitet da gerade etwas vor 😉 

![grafik](https://user-images.githubusercontent.com/47282153/88214638-c99f3a80-cc5a-11ea-8794-449f11098733.png)

**Comment by YaSoFies** [comment]
Nice, gibts da dann eine Beta. Melde mich als Tester :D

**Comment by andrgin** [comment]
Du brauchst du den Beta Branch laden. Da ist das Markttool schon drin.
