### ISSUE TITLE
Aufnahme von Ereignisbelohnungen in die Statistiken

### ISSUE THREAD

**Issue by DasKashi** [mainIine/foe-helfer-extension#1412]
Der Titel sagt prinzipiell schon alles aus.
Ich fänd' es interessant, wenn die Belohnungen der Ereignisse in den Statisken miterfasst werden würden. Denn vor allem bezüglich des aktuellen Events haben sich da bei mir und meiner Frau auf verschiedenen Welten extreme Unterschiede dargestellt.

**Comment by Parama91** [comment]
Es gibt die Möglichkeit die Ereignisse und Events in den Statistiken anzuschauen.
