### ISSUE TITLE
GB Investment extension to any GB and any level

### ISSUE THREAD

**Issue by Minotorious** [mainIine/foe-helfer-extension#1441]
Would be nice if I could somehow see how many FPs I need to invest for say X levels of the Y GB at a Z Arc boost rate. Like the existing GB Investment tool that shows you the recommended GBs and levels for better FP rewards but for any GB and any level I set.

**Comment by b-tomasz** [comment]
There are some more Calculators on their Homepage.
Do you search this?

https://foe-rechner.de/invest/level?lg=thearc&min=36&max=146

or this?

https://foe-rechner.de/ownpart/index

**Comment by Minotorious** [comment]
The former you posted. Would be convenient to have it in game though

**Comment by andrgin** [comment]
Yes this is on my todo list
