### ISSUE TITLE
City planner: coordinates confused

### ISSUE THREAD

**Issue by capshort** [mainIine/foe-helfer-extension#1458]
Hi,

this is about the first feature mentioned in #1103 .
In the city planner filter the size coordinates are exactly the other way around as in the game. Hanami bridge and its fully upgraded versions (Mikawa bridge, Mikoto bridge) are "4x6" but they are sorted into category "6x4" in the city planner as can be seen in the screenshots.

![Screenshot_20200708_110358](https://user-images.githubusercontent.com/25132855/86900149-4682ce00-c10b-11ea-9746-fa347850dacb.png)
![Screenshot_20200708_103921](https://user-images.githubusercontent.com/25132855/86900167-4be01880-c10b-11ea-9972-e7dd714cee20.png)

**Comment by dsiekiera** [comment]
I may have just twisted that. My mistake.
