### ISSUE TITLE
Ressourcenschonender Einsatz im Verhandlungsassistenten

### ISSUE THREAD

**Issue by IlleWayne** [mainIine/foe-helfer-extension#1469]
Wenn es nur drei verschiedene Einsatzmöglichkeiten gibt (z.B. Münzen, Vorräte, Gut aus dem letzten ZA), dann gibt es bei drei Versuchen eine Strategie, die sicherstellt, dass man am wenigsten Güter verbraucht: 
1. Versuch: alle Plätze Münzen
2. Versuch: alle verbleibenden Plätze Vorräte
3. Versuch: alle verbleibenden Plätze Güter

Wenn in der Taverne der Boost für die Verhandlung aktiviert wurde geht das ganze auch für 4 Einsatzmöglichkeiten.
Insbesondere in bestimmten ZAs (z.B. Arktische Zukunft, Ozeanische Zukunft) sind Spezialgüter ggf. noch wertvoller als normale Güter des ZAs.
Vielleicht kann man zusätzlich zum ZA noch den Quotient (Anzahl des Guts im Inventar) / (Anzahl des Guts benötigt für Einsatz) als Ranking nehmen.

Diese Strategie braucht vielleicht mehr Versuche aber verbraucht dabei weniger wertvolle Ressourcen bei den Verhandlungen.

**Comment by andrgin** [comment]
1.) Ja würde sich machen lassen, dass bei den kleinen Verhandlungen (Güter <= Runden) auch in der ersten Runde alle Kombinationen getestet werden. Die Frage ist jedoch wozu man bei 3 Gütern überhaupt den Verhandlungsassistenten braucht.

2.) Spezialgüter werden erst bei den höheren Verhandlungen mit mehr Gütern benötigt. Dort macht alles außer 5 verschiedene Güter in Runde1 sowieso keinen Sinn bzw. ist es bei 4 Runden dann aus Performancegründen sowieso nicht mehr möglich alle Kombinationen zu testen.

3.) Der Lagerstand wird bei der Reihung der Güter bereits berücksichtigt.

**Comment by Nerd2020** [comment]
Es stimmt, bei Verhandlungen mit 3 Alternativen und 3 Versuchen, 
bzw. bei 4 Alternativen und 4 Versuchen, 
braucht man den Verhandlungsassistenten eigentlich gar nicht. 

Dennoch weiß ich von Spielern, die von diesen ersten Begegnungen und den "falschen" Vorschlägen davon abgehalten wurden, den Helfer zum Verhandeln zu nutzen, weil sie von dort den Eindruck mitgenommen hatten, der Helfer mache schlechtere und weniger sparsame Vorschläge als sie das per Hand getan hätten. 

Es tut also einfach dem ersten Eindruck und dem Renommee des Helfers nicht gut, das so wie momentan zu belassen.
