### ISSUE TITLE
Feature Request: Push Notifications

### ISSUE THREAD

**Issue by frank42hh** [mainIine/foe-helfer-extension#1482]
Hi,

Sometimes I participate on powerlevel activities, and I try to follow via the infobox module. So I just had the idea, if it could be possible to send push notifications through the browser in certain situations. For example, if one would be able to select "GB has been leveled up" in a checkbox menu - similar to the infobox message type selection - and get a ping when this happens, even if the game is not in the focus. As far as I know, push notifications are part of the FoE android App, so it shouldn't be a problem for InnoGames if this would be implemented for browser players as well.
I know the infobox has it's own PING device but push notifications might be required on different settings as the infobox message display configuration (for example I want the infobox to show chat messages but I don't want them to ring).

Besides that, perhaps it's even worth a shot thinking about migrating all audio notifications to the browser's push notification system?

**Comment by scibuff** [comment]
Yes, notifications/alerts are under development at the moment.
