### ISSUE TITLE
Fehler in der Konsole beim Schließen der Notizen

### ISSUE THREAD

**Issue by GeniusTimo** [mainIine/foe-helfer-extension#1488]
Beim Schließen der Notizen kommt es zu einem Fehler, wenn man noch keine Notizen/Notizgruppe erstellt hat
> Uncaught (in promise) TypeError: Cannot read property 'findIndex' of null
https://github.com/dsiekiera/foe-helfer-extension/blob/191dae1935f4c0780464569d6caa23cfd62df434/js/web/notice/js/notice.js#L427

> Uncaught (in promise) TypeError: Cannot read property 'items' of undefined
https://github.com/dsiekiera/foe-helfer-extension/blob/191dae1935f4c0780464569d6caa23cfd62df434/js/web/notice/js/notice.js#L428

**Comment by outoftheline** [comment]
ist das noch so? ^^

**Comment by GeniusTimo** [comment]
Ja das Problem besteht immer noch @outoftheline 🙈
