### ISSUE TITLE
Einbindung externer Statistikseiten

### ISSUE THREAD

**Issue by Kijaho** [mainIine/foe-helfer-extension#149]
Moin Moin!
Ich kann schlecht einschätzen inwiefern das umsetzbar wäre, aber was ich sehr praktisch fände, wäre eine direkte Verlinkung ingame zu den jeweiligen Spielerprofilen auf Statistikseiten wie [https://foe.scoredb.io/Worlds](url) oder 
[https://foestats.com/](url).
Damit könnte man zum Beispiel bei Freunden schnell überprüfen ob sie noch aktiv sind.

LG, Kij

**Comment by Bluep** [comment]
Ha - wer suchet, der findet; das wollte ich auch gerade vorschlagen ^^
_________________________
**ScoreDB** ist extrem leicht umzusetzen, und wegen Aktivitätskalender und Geschwindigkeit mein Favorit. 

Spieler: https://foe.scoredb.io/DE1/Player/4953734
Gilden: https://foe.scoredb.io/DE1/Guild/8233
... entsprechend gameVars.world_id und Spieler- oder Gilden-ID
_________________________
**ForgeDB** ist leider schnarchlangsam, hat aber definitiv Vorteile wie die LG-Listen mit 24h-FP-Veränderung oder die längeren Zeiträume für die Diagramme mit Kampfanzahl und Punkteverlauf (2 Jahre statt 30 Tage)
Links sind dort unnötig kompliziert (nur world=Klarname kann weggelassen werden, sieht nur minimal unschöner aus)

Spieler: https://foestats.com/de/de1/players/profile/?server=de1&world=Arvahall&id=4953734
Gilden: https://foestats.com/de/de1/guilds/profile/?server=de1&world=Arvahall&id=8233
_________________________

Schön fände ich ein Auswahl-Popup (auch hinsichtlich anderer Seiten, die ich nicht kenne oder nutze - gibt sicher noch mehr); die zweitschönste Variante wäre eine Vorauswahl in den Einstellungen; und falls das alles zu kompliziert ist, dann ist auch _eine_ verlinkte DB-Seite schon 100% mehr als aktuell möglich ist 😉

Auf jeden Fall vielen Dank für euren Einsatz und die ganze Arbeit mit dem Helfer!  👍🙏

**Comment by outoftheline** [comment]
Tach du! 

An welcher Stelle wäre das denn deiner Meinung nach sinnig? 
Spieler werden in der Extension aktuell nur im Assistenten angezeigt.

**Comment by Bluep** [comment]
Huhu 🥝 ^^

Richtig, hauptsächlich und zuallererst für den Assistenten; möglich wäre es auch noch in der Infobox (wie aktiv / groß ist der Spieler, der gerade bei der Auktion geboten hat? Oder die Gilde, die im GG am selben Sektor knabbert wie wir - wie groß sind die, wie aktiv die Mitglieder?)
