### ISSUE TITLE
Filter für die Moppel-Auswertung

### ISSUE THREAD

**Issue by GeniusTimo** [mainIine/foe-helfer-extension#1490]
Hallo zusammen, 
könnte ich einen Filter vorschlagen in der Moppel-Auswertung, sodass man die Freunde aussortieren kann die einem keine Besuche abstatten? Es wäre eine Riesenhilfe, wenn man die Inaktiven freunde entfernen möchte. Momentan zeigt es mir dort nur die Nachbarn an , vielleicht sind da auch alle (Freunde, Nachbarn, Guildies) dabei, aber ein filter würde die Sache erleichtern. Es wäre unter https://foe-rechner.de/stats/events/motivations
> Anfrage von Sunny24 via Discord

**Comment by outoftheline** [comment]
Der Teil ist jetzt in der Extension :-) Da sind auch Filter
