### ISSUE TITLE
Bug: Eigenanteilsrechner

### ISSUE THREAD

**Issue by b-tomasz** [mainIine/foe-helfer-extension#1512]
Version 2.5.1.0

Ich habe den Eigenanteilsrechner bei allen LGs aktiviert.

Bei einem Nachbar ist mir dieses LG aufgefallen.  Er hat viel zu viel selber eingezahlt und Platz 1 hat den Platz extrem unterbelegt, P1 kann nur noch von P2 überholt werden, welcher korrekt eingezahlt hat.

Nun rechnet der Rechner dass man noch 512 einzahlen soll. Danach levelt der P3. Und P 4 und 5 kann nicht mehr einzahlen.

Ich vermute dass der Rechner versucht P1 Abzusichern, so dass dieser nicht mehr von P2 überholt werden kann. Was in dieser Situation aber komplett sinnlos ist.

![tempsnip](https://user-images.githubusercontent.com/60810950/87574449-ac082900-c6ce-11ea-80cf-262df19362fd.png)

Dies ist nicht so dringen, denn dies ist eine Situation, die eigentlich nie Passieren sollte.

**Comment by andrgin** [comment]
Dafür gibt es schon ein Issue ist aber etwas komplizierter zu lösen denke ich:
https://github.com/dsiekiera/foe-helfer-extension/issues/1220
