### ISSUE TITLE
Settings: Defaulteinstellungen werden zu spät geladen und sind beim StartUp Paket noch nicht verfügbar

### ISSUE THREAD

**Issue by Gindi4711** [mainIine/foe-helfer-extension#1529]
Da der Ladevorgang der Preferences erst mit dem Beginn der StartUp Funktion geladen werden, stehen diese während der Behandlung des StartUp Pakets noch nicht zur Verfügung

**Comment by SkateScout** [comment]
⚠Achtung wenn der Benutzer auswählt das Keine Übertragung an FOE-Helfer erfolgen soll und es durch eine Fehler beim Startup dennoch zu einer Übertragung kommt dann kann das evtl als ein Verstoß gegen die DSGVO behandelt werden, Da damit ein Alias das dem Nutzer fest zugeordnet ist plus IP und Aktivitätszeitpunkt gegen de willen des Benutzers übertragen wird.
Gleiches gilt wenn die Übertragung als Default Einstellung ohne Zustimmung aktiv ist.
Ich denke hier sollte man noch mal einen Kritischen Blick haben.

**Comment by dsiekiera** [comment]
Das ist bekannt. Und sollte in der Beta schon behoben sein

**Comment by SkateScout** [comment]
In der Beta ist mir aufgefallen das "OwnLG" weiterhin übermittelt wird auch wenn die Übermittlung eigentlich abgeschaltet ist.
Das sollte auch nicht passieren.

**Comment by outoftheline** [comment]
fixed afaik
