### ISSUE TITLE
Web: GEX Stats have wrong sorting

### ISSUE THREAD

**Issue by Arctos7777777** [mainIine/foe-helfer-extension#1544]
Ordering GEX stats (https://foe-rechner.de/stats/gex/index) by Number of Solved Encounters ("Begegnungen") is broken:

Guildmates with 5/48 encounters are located between those with 49/48 and 50/48

Player X |   | 32.999 | 50 / 48
Player Y |   | 8.620 | 5 / 48
Player Z |   | 331.951 | 49 / 48

Obviously, re-ordering fails due to the missing leading "0"

**Comment by GeniusTimo** [comment]
Thank you for bringing this problem to our attention - I think @dsiekiera will take care of it 🙂

**Comment by outoftheline** [comment]
Feature has been removed
