### ISSUE TITLE
Save and replicate button layout and FoE Helper settings

### ISSUE THREAD

**Issue by lnplnp** [mainIine/foe-helfer-extension#1548]
Hello,

Could you make it possible to replicate a configuration of FoE Helper from one server to another and from one browser to another.

I use FoE Helper on several computers and I would like to reproduce the settings I have from one computer to another ... and I play on several FOE servers, so I would like to be able to export / import my configuration from buttons and from one FOE server to another.
I think it would be possible to output this setting in a CSV file for example.

Unless you know which cookies should be copied to replicate the configuration FoE Helper.

Thank you.

**Comment by dsiekiera** [comment]
This is the repo from the "FoE Helper".
U know this?

**Comment by lnplnp** [comment]
Yes I know ... sorry for the error but I mean "FoE Helper" actually.

**Comment by dsiekiera** [comment]
Then pls go to the the settings menu at the bottom of the ingame menu.
There is a Import/Export function for all settings.

**Comment by lnplnp** [comment]
Thanks again... 

It works for almost all settings and options ... but it doesn't "work" for negotiation setup. Unless this is wanted?

Perhaps you could export at least the two options: "NegotiationSaveCurrentEraGoods" and "NegotiationSaveMedals". It may not be very relevant to export the order of resources because it is not very generic.

**Comment by andrgin** [comment]
We are saving the whole localStorage including these 2 options.

The order of the goods is not saved at all. Reordering goods only applies to the current negotiation and is recalculated every time based on which goods are used, your current stock etc.
