### ISSUE TITLE
LG Investitionen für Kampf LG oder nicht FP Produzierende LG 

### ISSUE THREAD

**Issue by SmartCologne** [mainIine/foe-helfer-extension#1550]
Hi,
wie wäre es wenn man die LG Investitionen erweitert um einen Reiter Kampf-LG und Sonstige-LG.
Dort könnte man die empfehlenswerten Investitionen Anhand des verbleibenden Eigenanteils bzw bei Kampf-LG aus FP pro % Angriffsbonus errechnen.

Mfg

**Comment by Chendalein** [comment]
Finde ich eine gute Idee, zumindest für den Kampfbonus (TA, CdM, Aachener, Zeus). Bei den anderen Gebäuden wüsste ich nicht anhand welcher Kriterien man die Rangliste machen könnte.
Das ginge vll. noch für Güter produzierende Gebäude und Gebäude mit Zufriedenheit.

**Comment by Rainer-Zufall** [comment]
Anhand des Eigenanteils bei 190% Förderung

**Comment by andrgin** [comment]
Bei Kampfbonus etc. wäre das grundsätzlich möglich.

Güter werden kompliziert, da die Güter aus verschiedenen ZAs sind. Himeji/Frachter liefern aus dem aktuellen ZA, Star Gazer von 1 ZA darunter, Rest 3 ZA darunter.

Was die anderen Effekte wie Zufriedenheit, Bevölkerung, Vorräte usw. angeht:
Hierbei handelt es sich in der Regel ja um Sekundäreffekte. Klar kann ich jetzt z.B. vorschlagen: Bau die Gaea Status. Die bringt mehr Zufriedenheit als das Alcatraz aber die Frage ist, ob so eine Rechnung sehr sinnvoll ist.

Generell ist die Frage, ob sich hier der Aufwand wirklich lohnt vor allem, weil sich das ja noch relativ einfach manuell abschätzen lässt.

**Comment by Arctos7777777** [comment]
Ich fände 4 Aspekte Interessant: 
1a) Kampfkraft Angriff
1b) Kampfkraft Verteidigung
2) Güter (egal welches ZA - Kategorie reicht)
3) "Das billigste" - manchmal muss man einfach FP unterbringen. Oder ist dem Endgame nahe und will einfach das LB wissen welches am schnellsten levelt
4) Zufriedenheit: Während man den Inno levelt ist das z.B. durchaus relevant...

**Comment by Gindi4711** [comment]
Güter sind bereits vorhanden. Kampfkraft wird ab dem nächsten Update unterstützt.

Detaillierte Diskussion siehe: https://github.com/mainIine/foe-helfer-extension/issues/1830
