### ISSUE TITLE
[Guild Expedition] missing data

### ISSUE THREAD

**Issue by Beta-Wolf** [mainIine/foe-helfer-extension#1562]
![chrome_2020-08-14_17-28-33](https://user-images.githubusercontent.com/31244425/90266098-cd863d00-de53-11ea-8b7a-86f26e761859.png)
A few player names are missing in the table. Reason is unknown.

**Comment by Beta-Wolf** [comment]
![chrome_2020-09-01_19-56-14](https://user-images.githubusercontent.com/31244425/91888849-39a6d480-ec8d-11ea-8f40-28a6ba36e7ce.png)

I checked it out, and it should be this player who isn't displayed:

![chrome_2020-09-01_20-00-20](https://user-images.githubusercontent.com/31244425/91889251-d2d5eb00-ec8d-11ea-9334-68cafed25d1f.png)

**Comment by outoftheline** [comment]
Feature has been removed
