### ISSUE TITLE
Over view Invested FP

### ISSUE THREAD

**Issue by Dlonrab** [mainIine/foe-helfer-extension#1570]
In FOE Power Tools were beside forbidden tools like snipe scouting and plunder scouting also tools available that I can not see why the developers of Innogames would have any problem with those.

One of those handy things was the FP investment overview : How many free FP do you have, how many have do you have that are invested but are still locked in buildings of other players,  in total, how many FP do you have in total if these fixed FP are being freed by leveling the building.

Could you guys incorporated a similar tool in FOE Helper?

would be nice

Thanks

Anton

**Comment by b-tomasz** [comment]
Do you mean something like this?
![grafik](https://user-images.githubusercontent.com/60810950/90665347-343c9980-e24c-11ea-91da-5bf64aa4afcb.png)
This alredy exists.

You need to open your Investments over the Town Hall to get the needed information from the server. If you have activated in the Settings, this window automatically appears if you open the investments.

If you activate the data transmission, you could see some more informaion on the homepage:
https://foe-rechner.de/

**Comment by Dlonrab** [comment]
Vielleicht noch ein Tip zur Verbesserung des FP Rechners:

Automatisch scannen von Legendäre Gebäude für "Snipebare" platze hat 
Innogames nicht gestattet (reduziert das Anzahl von Klicks). Aber 
manuell klicken auf ein Gebäude und dann der FP Rechner öffnen zur 
Ausführung von Berechnungen an das Gebäude ist wohl gestattet.

Die Option um Gleich den Gewinn zu zeigen beim snipen ist im Juni 
gestrichen. Aber wenn es ein normale Rechenhilfe Funktion ist sollte es 
vielleicht doch gestattet sein, nachdem man ein extra Klick einbaut auf 
das grüne Nummer was im FP Rechner gezeichnet wird wenn ein snipebaren 
Platz/Gebäude ist.

Nach dem Klick sollte man FOE Rechner ein neues Subfenster öffnen lassen 
können, welches der Berechnungen gehörende beim Snipen zeichnet. (Anzahl 
FP benötigt auf Grund 50% des resultierenden FP, eventuell erhöht mit 
50% von durch andere Spieler schon eingelegte Punkte, Gesamt Anzahl von 
benötigte Punkte und Gewinn (Ausbeute incl Arc bonus) minus Einlage) usw,

Auf dieser weise wird kein Information geboten welches die Spieler auf 
das Moment und auf die gleichen Platz im Spiel auch niet selber 
berechnen könnte.

Vielleicht ist das ein gute weitere Ausbau diese FOE Helper Function

mit freundliche Grüße

Anton Beyer



Op 19-8-2020 om 18:51 schreef b-tomasz:

**Comment by b-tomasz** [comment]
Ich denke nicht dass etwas in diese richtung umgesetzt wird. Die Entwikler wurden vonn Inno gebeten diese Funktion zu entfernen. Da ist es egal ob noch ein klick mehr nötig ist oder nicht. 

Die vorgaben von Inno werden von den Entwiklern Strikt eingehalten, denn es bringt niemandem etwas, wenn Inno den Helper verbietet und die Nutzer Bannt.

**Comment by andrgin** [comment]
Die Regeln hierzu sind:
1.) Man darf nichts machen was Klicks spart also nicht schreibend  in irgendeiner Form ins Spiel eingreifen noch aktiv Daten vom Inno Server abfragen. Foe Helper hat dies nie getan, selbst nicht in der alten Version, Powertools schon.

2.) Man darf keine Tools einsetzen die dem Spieler einen "unfairen Vorteil" verschaffen.  Was dabei ein unfairer Vorteil ist, das definiert das Commu ity Management von Inno.
Stand Ende 2019 war die Definition vom deutschen Community Management, dass alles erlaubt ist, solange es nicht aktiv ins Spiel eingreift (also Punkt 1). Von den anderen Sprachen hatten wir kein Feedback also haben wir uns damals nach der Definition gehalten (also Snipen + Plünderhelfer)

Stand ab Juni 2020 waren die genauen Vorgaben welche Features zu entfernen/ändern sind mit der Grundaussage "keine Features verbauen, die vorwiegend das Spielerlebnis von anderen Spielern negativ beeinflussen" (kein exaktes Zitat sondern frei interpretiert).

Offiziell von uns unterstützt wird nur mehr das Fördern mit dem Kostenrechner. Man kann diesen jedoch durch die Features, die zum Fördern benötigt werden wenn man etwas kreativ ist immer noch zum Snipen nutzen. Anleitungen dazu will ich jedoch keine geben, sonst kommt Inno noch auf die Idee uns den Fördermodus auch zu verbieten.
