### ISSUE TITLE
Anzeigefehler bei den Statistiken

### ISSUE THREAD

**Issue by b-tomasz** [mainIine/foe-helfer-extension#1575]
Wenn ich im Browser den Zoom auf <90% stelle, können oben nicht mehr alle Symbole auf einer Zeile angezeigt werden.
So sieht man nur noch die hälfte der Symbole.

Helper Version:     2.5.2.0
Firefox Version:     79.0

![grafik](https://user-images.githubusercontent.com/60810950/91193202-1dd48900-e6f7-11ea-889f-c15528fdcb8f.png)

**Comment by outoftheline** [comment]
Resolved
