### ISSUE TITLE
City Planer: Export/Import layout to support different players

### ISSUE THREAD

**Issue by WulfgarCA** [mainIine/foe-helfer-extension#1576]
Hi there,
it would be nice if you could import and export city layouts so we can help our smaler guild members to layout their city.

Thanks!

**Comment by Beta-Wolf** [comment]
That would be awesome.

**Comment by Sebien72** [comment]
I contribute to this idea.
If there are limitations from inno, just allow it for the guild members.
If I'm not wrong, it was possible to see the plan of others cities before.
