### ISSUE TITLE
Statistik der GG auf der Homepage

### ISSUE THREAD

**Issue by Blackfir5** [mainIine/foe-helfer-extension#1579]
Hallo.

Analog zu den Ergebnissen/Stationen jedes Spielers der Gildenexpedition welche ja als Statistik auf der Homepage verfügbar ist:
Wäre es möglich, die Ergebnisse, bzw. die einzelnen Werte aller Spieler (Gilde) zu den Statistiken auf der Homepage zu übertragen?
Oder zumindest die "Spieler Übersicht" kopierbar zu machen, bzw. in Excel exportieren zu können?

LG

**Comment by outoftheline** [comment]
Wir entfernen die Übertragung dieser Daten komplett und bauen sie stattdessen in die Extension ein.
