### ISSUE TITLE
Negotiation helper with only 3 items

### ISSUE THREAD

**Issue by Minotorious** [mainIine/foe-helfer-extension#1580]
When in a negotiation like the image below with 3 turns and 3 resources the helper to save valuable resources should propose first all coins, then in the remaining targets all supplies and finally goods in the leftover targets but it currently proposes a mixture of everything from the first step. Not a big deal but thought I might mention it :)

![image](https://user-images.githubusercontent.com/40427380/91869153-d52c4b00-ec75-11ea-964d-9ef3bd780755.png)

**Comment by Julian2424** [comment]
Same with only 2 things: It could say, that you have to only use coins and then only supplies (depends on how many you have of course)

**Comment by andrgin** [comment]
The problem atm is that the first guess is hardcoded. I agreee it would make more sense starting with the cheapest good on all places if the number of goods is equal or lower than the rumber of rounds.

**Comment by thethinker990** [comment]
\+
