### ISSUE TITLE
Settlements Helper - text instead icons.

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#1585]
Hi.
I don't like the way in wich Inno realised its own helper - very long scroll with large icons.
And today I see icons in your Helper.
![2009051414](https://user-images.githubusercontent.com/35531243/92303993-c221bf80-ef82-11ea-82b9-a4a6f67e4eb3.png)
I don't know - perhaps most players like comics - but I prefer text.
Is it possible to realise some setting - using icons or text in Settlement helper?

And if you plan to replace bulding names on left side with icons - please (!!!) do not do such mistake...

**Comment by andrgin** [comment]
We did not replace buildings because it would increase in size.

For good icons width has been reduced. Also it solves some problems with certain languages that have longer names.

**Comment by belikoviv** [comment]
> We did not replace buildings
This is good :)
> For good icons width has been reduced. Also it solves some problems with certain languages that have longer names.
Is it mean that you don't plan to let us switch between icons and text?
(I'll prefer cutted text instead icons)
