### ISSUE TITLE
GBG Info screen

### ISSUE THREAD

**Issue by enerbe** [mainIine/foe-helfer-extension#1594]
It would be nice to have an overlay or something similar to the layout for the GBG displaying the following info:
- Ownership of the sector (by color)
- The openning time of a sector (local time)
~~- Number and type of the buildings in a sector~~

If we could mark the sectors and press a copy button would be nice to get something like this in the clipboard:

10:52 D3Z ~~3SC~~
10:55 D3Y ~~2SC 1TR~~

~~_SC means Siege Camp around the destination sector owned by the players guild.~~
~~TR means Traps in the destination sector_~~

update: as we receive building info only when opening a sector it is not possible to include in the info.

**Comment by belikoviv** [comment]
Are you think that english is single language in the world?

**Comment by enerbe** [comment]
It could be also localized. Or simply using the name as the browser displays it.

**Comment by frankmorgner** [comment]
The overlay could at least show how many build slots are on a sector....

**Comment by scibuff** [comment]
> The overlay could at least show how many build slots are on a sector....

Again, that data is not available until you open a particular sector

**Comment by frankmorgner** [comment]
> Again, that data is not available until you open a particular sector

Thanks for the quick reply. The number of build slots of stays the same for 12 days, this information could easily cached, once the users clicks on a particular sector

**Comment by frankmorgner** [comment]
But as stated by the original poster, the most useful information would be a copy of the short name of a sector ("C3 X") along with the local time when the sector gets available ("23:00") minus an optional delta of one or two minutes. This is heavily used when collecting players for an upcoming battle/race...

**Comment by frankmorgner** [comment]
The target time is actually why someone wants to have the current time to be displayed in full screen mode (https://github.com/dsiekiera/foe-helfer-extension/pull/1825)
