### ISSUE TITLE
GB Investment tab amounts

### ISSUE THREAD

**Issue by drvnsnow** [mainIine/foe-helfer-extension#1603]
The amounts to level buildings on the GB Investment tab are incorrect. For example, the GB Investment tab currently shows 728 FP to reach the next level, while the actual "owner to add" FP amount is 803. The values are incorrect across all buildings listed on the GB investment tab.

**Comment by drvnsnow** [comment]
Ok so on further examination I realize that the collection of the building on the next level may be taken into account. This is fine just with the consideration that it may be confusing to some. Thanks!

**Comment by andrgin** [comment]
The important value is the "costs/daily FP". The costs column is only there so that you get a rough idea how much it will cost.
