### ISSUE TITLE
Relikttempel in LG Investitionen aufnehmen

### ISSUE THREAD

**Issue by Chendalein** [mainIine/foe-helfer-extension#1604]
Ich möchte anregen den Relikttempel in die Liste der Empfehlungen von auszubauenden FP produzierenden Gebäuden aufzunehmen. Idealerweise mit einer Möglichkeit die üblicherweise bewältigten Begegnungen einzugeben, ansonsten auf Basis aller 64 Begegnungen.

**Comment by andrgin** [comment]
Die Frage ist, ob das viel Sinn macht. Ich habe das einmal grob überschlagen:
Relikttempel lvl1 deckt von den FP her in etwa seinen Flächenbedarf.
Von lvl1 bis 60 bringt er um die 10FP mehr am Tag für ca. 14K also 1400FP/tgl. FP
Damit macht dieser nur sehr sehr spät Sinn wenn alle anderen FP Gebäude schon deutlich über lvl80 sind.
Der Vorteil den Relikttempel hochzuziehen liegt in erster Linie darin, dass er mehr seltene Relikte abwirft (Jade) und man so ein paar Renokits bzw. Terrassenfelder bekommt aber das kann man nur schwer in FP konvertieren.

**Comment by SkateScout** [comment]
Ich denke das sehr viele Spieler nicht nur Level 1 Spielen sondern die Woche sich reinhängen und auch den Helper nutzen werden L4 schaffen. Damit sind es 4 Mal so viele FP.
Also 40FP Pro Tag mehr bei 14.000FP Einsatz => 350 Tage bis er sich "nur" wegen der FP rechnet.
Da gibt es sehr viele LG's die Empfohlen werden die sich erst nach viel mehr Tagen Rechnen.

**Comment by andrgin** [comment]
Meine Rechnung war schon mit 64 Begegnungen...
