### ISSUE TITLE
goods overview

### ISSUE THREAD

**Issue by drpes** [mainIine/foe-helfer-extension#1605]
what I really miss in FOE is to have an overview about all my goods including these currently offered in the market. Would it be possible to add it to the FOE-helper?

**Comment by dsiekiera** [comment]
An overview with filters is already available. To integrate your own should also be possible.

@andrgin evt mit einem weiteren Tab?

**Comment by SwSoC** [comment]
Hi,
this is a nice feature I would really appreciate.
