### ISSUE TITLE
web portal problem

### ISSUE THREAD

**Issue by ecthelioni** [mainIine/foe-helfer-extension#1625]
Hello
I have a problem with the web portal. I have players from another guild in the section Statistics - Mitgliered and Legendare Bauwerke. Section Motivieren is correctly. 
I worked with the 19.10 portal and everything was corectly,  but a month ago I had the same problem as today.

Thank you for help

**Comment by ecthelioni** [comment]
This screenshot is from today:
https://ctrlv.cz/opKF

This screensot is from 19.10 (this is corectly):
https://ctrlv.cz/eITE

**Comment by comm1968** [comment]
Nearly the same here... but the guild-members are right, but bottom line of website shows the right world, but the wrong guild: here Guild "Wolfsbrüder", must be "Die Drachenreiter"... also the stats of Guild-Members are wrong: 18 Members, but places shown 6 -108!? also sorting in this stats points are from 1-9 (a-z) instead the numbers... (Player 10432154 - 7702)

**Comment by outoftheline** [comment]
Feature has been removed
