### ISSUE TITLE
Battle outcome tracker

### ISSUE THREAD

**Issue by gamecodelife** [mainIine/foe-helfer-extension#1628]
Suggested feature: show the user their history of troop compositions and win/loss against a given troop comp.

Use case: I'm about to battle 4 Cannons / 4 Imperial Guards. Which troop comp that I've used before has led to the best outcomes (highest win %, fewest troops lost)?

Does the extension have the info? Yes. This would only track battles by this player done in the browser. Just store the attacking & defending troop compositions (which type of unit) and the outcome (win or loss, # of troop deaths, maybe the battle score if relevant). Then display these, indexed by defense comp, sorted by best to worst average outcome (Win % and then fewest troops lost), and then display the corresponding attacker comps.

This feature would be far more powerful if it stored the stats on a central server and aggregated them across all users (no need to identify the contributor at all), but I believe this extension works with no central database, so this is unnecessary. The feature would be very useful all on its own.  And unlike the negotiation helper, this encourages players to experiment with different troop comps and actually learn more about battle strategy.

Note: This is very different from "Rejected Idea 4" because it's not predicting outcomes or computing anything about the battle. It's simply keeping track of stats, just like the other stat menus already do (troop production, GBG fight stats, etc).

**Comment by JhonnyBn** [comment]
This would be awesome.
Keeping the battle score is nice because it would be possible to calculate average score per death in a given composition

**Comment by dsiekiera** [comment]
This has happened before. It also showed what had been looted and much more.

Inno has forbidden it. Therefore we removed it again.

**Comment by SkateScout** [comment]
Hi, i think the this is not about PvP fights, it is about an statistik what combinations lead to which result. Not based on one player.
So that is the reason why he said it is not about the forbiden statikstik per player.

**Comment by gamecodelife** [comment]
Correct -- I'm thinking about Guild Expedition or Guild Battleground. This is different from the neighborhood PVP fight log that was removed from the extension before.

**Comment by dsiekiera** [comment]
OK. This is plausible. I think this could be possible.

**Comment by andrgin** [comment]
In kost cases battle outcome depends more on the attack/defense boni than the actual units used.
Lets say I am doing my first fight in GBG with 350/250% attack bonus against 0%. The outcome will be pretty clear no matter which troops I use.
With 40 attrition against 400% attack/defense boni things will be a lot different.

Another example from the iron age:
Lets say you have 200% attack bonus and 100% defense bonus against a bunch of cavalry with 0%:
The best choice is 8 artillery as you will shoot them down before they land the first hit while every other combination will at least damage some units, maybe killing one.

If you are both having no attack/defense bonus you better use light infantry as it has a counter against cavalry.

**Comment by gamecodelife** [comment]
@andrgin I agree with your point, but I think the feature is still useful anyway.

On the specific cavalry example -- even with over 200% attack bonus my artillery do not 1-shot kill same-age cavalry. So I would still use light infantry even with 0% bonus opponents.

But I do agree that in general you'll get worse outcomes as attrition climbs. But the troop comp that you're up against will be randomly distributed over the attrition (or GE level bonus) distribution, which means the combination that works best in general will still be apparent from the data. And given that this is simply informational statistics to the user, not designing their troop comp for them, the user can interpret the data and use whatever comp he/she wants. It will still tell them how well each has worked in the past.
