### ISSUE TITLE
Show % chance of not increasing attrition level for for sectors

### ISSUE THREAD

**Issue by Redline1969** [mainIine/foe-helfer-extension#1639]
I would like to request a feature for GBG. In order to calculate the chance to not increase attrition level on a given sector, currently you have to open each sector that you own around the sector in question to see how many siege camps are in each sector, Then you add up each siege camp (24% chance to not increase attrition level) to get total chance to not increase attrition level. 

So for example, if there is 1 siege camp in 1 sector and 2 siege camps in another sector, both touching the sector you are interested in, you would have 72% chance of not increasing attrition level.

If this can be done, I could see two ways. 

1. You can just show the % chance of not increasing attrition level for each sector the is owned by your guild 
2. Show the % chance of not increasing attrition level for the sector that you are attacking based on calculating as shown above.

This would be awesome. Thanks for considering.

**Comment by outoftheline** [comment]
Unfortunately, the data for the buildings is only transmitted when opening them in each sector, so we cannot display it in advance.

**Comment by des2k7** [comment]
@outoftheline 
It might be an idea, after opening the sector, to add the buildings as small icons on the sector on the gbg map

for example if you have 3 Siege camps, after opening the sector, it will show 3 little siege camps on the overview map on the sector

for example, you're trying to see if attacking A1M is feasible, you open all adjacent sectors, foe helper draws little icons on all the sectors, and we have a visual idea of how many siege camps we have

it's probably too dangerous to calculate the % attrition spared (stale data), but having a visual of which buildings are on sectors would be sweet

to counter the stale data problem (as camps might be deleted or destroyed after taken over) you could add a tag after it like "updated 30m ago"
