### ISSUE TITLE
Eigenanteilsrechner zeigt nichts an

### ISSUE THREAD

**Issue by klansoft** [mainIine/foe-helfer-extension#1644]
Ich hab eine - vielleicht nicht so übliche - Konstellation, bei der P1 und P2 gleichstark belegt sind. Dabei zeigt der Eigenanteilsrechner nichts mehr für die unteren  Plätze an. Oder mache ich da einen Denkfehler? 
![Foe-Helfer1](https://user-images.githubusercontent.com/25074133/100339718-870bb700-2fda-11eb-8f51-9f591c95f5fe.png)
![Foe-Helfer2](https://user-images.githubusercontent.com/25074133/100339794-9985f080-2fda-11eb-9b0e-5bee02b0320f.png)

**Comment by klansoft** [comment]
Ach ja: Browser: Opera - neueste Version:72.0.3815.400 unter Windows 10 (ebenfalls aktuell). Aber ich denke damit hat das eh nichts zu tun...

**Comment by andrgin** [comment]
Die Ursache liegt daran, dass der EARechner versucht zuerst einmal P1 abzusichern und dann bleibt nicht mehr genug Platz für die restlichen Plätze.

Dass das in manchen Fällen nicht unbedingt sinnvoll ist, darüber habe ich mir auch schon Gedanken gemacht. Ich bin aber noch etwas unschlüssig, wie ich das am Besten lösen sollte.

**Comment by Parama91** [comment]
Sind dafür nicht die neuen Checkboxen "Absichern" und "Vertrauen"? Denke das kann man jetzt dafür gut verwenden.

**Comment by Gindi4711** [comment]
Ja für solche Fälle kann man nun die Option "Absichern" deaktivieren.

**Comment by klansoft** [comment]
Ja. Danke für den Hinweis. Ich hab die Frage im November 2020 gestellt. :) Da gab es die Optionen noch nicht :D
