### ISSUE TITLE
Antiquitätenhändler: Statistik über Auktionshandel

### ISSUE THREAD

**Issue by esride-mag** [mainIine/foe-helfer-extension#1645]
Vorschlag für eine neue Funktionalität:

Es wäre hilfreich, wenn das Tool Statistiken zu abgeschlossenen Auktionen vorhalten würde.
![AntiquesAuction](https://user-images.githubusercontent.com/954299/100437687-69555500-30a1-11eb-80ef-37ae259908c2.png)

So in die Richtung:
-Üblicher/Durchschnittlicher bzw. höchster Verkaufspreis
-Häufigkeit, die der Artikel angeboten wird bzw. zuletzt angeboten

**Comment by dsiekiera** [comment]
Du redest von einer Art Datenbank um zu schauen was die Teile im Schnitt kosten?

**Comment by esride-mag** [comment]
Ja genau, dazu müssten vergangene Auktionen geloggt werden.
