### ISSUE TITLE
Suggestion: GVG overview

### ISSUE THREAD

**Issue by NaAMm** [mainIine/foe-helfer-extension#1654]
Hello,Is it possible to add an overview for gvg? It would be nice if we can see how many fights or DA everyone contributed in gvg. Thank you so much for this great tool.

**Comment by outoftheline** [comment]
the helper can only track actions happening while you are online (and on the specific gvg map i reckon) or if the actions are still in the gvg log. 
you'd only get a glimpse of everyones actions then, so I wouldnt know if the data really helps?

**Comment by NaAMm** [comment]
If the helper can provide data (who fought and the number of fights) accurately while online it would be perfect. But if it depends on the event log I don't think it would be accurate.
