### ISSUE TITLE
sugestion: CB list of total fights/negotiations should have information about each day

### ISSUE THREAD

**Issue by misobab** [mainIine/foe-helfer-extension#1678]
It could by nice, to have option check who make how many fights/negotiations during each day period.

**Comment by JhonnyBn** [comment]
Like this? You can download this data in excel format and write some formula to check daily

![image](https://user-images.githubusercontent.com/29382833/101851465-5c714080-3b3a-11eb-94c6-e66d7bf4c3b9.png)

![image](https://user-images.githubusercontent.com/29382833/101851538-83c80d80-3b3a-11eb-9f20-9a88d1ee682b.png)
