### ISSUE TITLE
Neuen FP Collector um Snipes erweitern

### ISSUE THREAD

**Issue by Winter1976** [mainIine/foe-helfer-extension#1679]
Finde den neuen Punkt FP Collector im Tool super, meine Frage:
Könnten dort auch die FP aufgeführt werden welche als Gewinn in anderen LG's gemacht werden? In den Investitionen sind ja bereits die Gewinne enthalten. Es wäre für micht interessant zu sehen wie viele FP da im Durchschnitt so täglich zurück kommen als Reingewinn.
Danke!

**Comment by andrgin** [comment]
Wir haben das länger diskutiert, sind aber zu dem Ergebnis gekommen, dass sich das mit vertretbarem Aufwand nicht realisieren lässt. Grundsätzlich gibt es nur die folgenden Stellen, wo wir die Daten erfassen können:
.) Beim Einzahlen selbst. An dieser Stelle ist aber noch nicht klar, ob man überhaupt auf jedem jeweiligen Platz landen wird (falls Platz nicht abgesichert ist) bzw. ob das LG überhaupt gelevelt wird bzw. wann.
.) Beim Öffnen der LG Übersicht: Hier ist dann nicht einmal mehr klar, welche LGs abgesichert sind oder nicht. Das kann hier nur geschätzt werden. Auf hier gilt: Wir wissen nicht, wann es gelevelt wird bzw. ob überhaupt.
.) In der Ereignisanzeige: Hier ist zwar bekannt, welches LG gelevelt wurde, wodurch sich der Ertrag errechnen lässt (anhand der Mäzen Tabellen aus dem Wiki). Was wir dort jedoch nicht wissen ist wieviel man dafür eingezahlt hat, wodurch sich erst Recht kein Gewinn errechnen lässt.

Hier müsste ein sehr komplizierter Weg gegangen werden, dass LGs bei der Einzahlung vorgemerkt werden und später in der Ereignisanzeige wieder neu gesucht werden jeweils in einer eigenen Datenbank und selbst dann zweifle ich daran, dass dies durchgehend richtige Ergebnisse ausspucken wird:
.) Was ist mit LGs, wo man am PC 1FP eingezahlt hat, später jedoch am Handy aufgestockt hat. Eines solcher LGs bringt die ganze Statistik durcheinander.
.) Was ist mit Förderketten, Güterkäufen oder anderen FP Tauschsystemen. Hier handelt es sich ja nicht um keinen echten Verlust, da man ja eine andere Gegenleistung erhalten hat.
