### ISSUE TITLE
Building Level-Up message has incorrect FP totals

### ISSUE THREAD

**Issue by franzwa-foe** [mainIine/foe-helfer-extension#1689]
Windows 10 64 Bit
Version 87.0.4280.88 (Official Build) (64-bit)
us21 (V)
2.5.3.2 US
![image](https://user-images.githubusercontent.com/75922064/102003281-4945a880-3cd3-11eb-8fce-16748d7af7b5.png)

Message indicates I took 2nd place (correct) but the 84 FP is incorrect (with my Lvl 75 arc the return was 197)

**Comment by andrgin** [comment]
Did you get another reward a short time before or afterwards?

**Comment by franzwa-foe** [comment]
There were multiple events, all around the same time.  (within an hour or so)  - I did not see the same issue in a different world - perhaps there was some cache that either needs to be cleared, or was?
