### ISSUE TITLE
Bug: Negotiation Helper

### ISSUE THREAD

**Issue by HAL09001** [mainIine/foe-helfer-extension#1718]
The 5th good  will not be displayed correctly with 3440x1440 screen settings & 10 Goods. With 9 Goods it is all fine. See screenshots. 
Browser: Chrome
Version: 2.5.4.1

in former times the good #1 and #5 have been distorted, since some versions only good 5 is not displayed correctly if  it is to choose out of 10 goods.
![image](https://user-images.githubusercontent.com/48470058/102689770-ff901d00-4200-11eb-91db-e5ba722d190e.png)
![image](https://user-images.githubusercontent.com/48470058/102689815-66153b00-4201-11eb-88af-c46064bd0ff3.png)

**Comment by andrgin** [comment]
Tritt das bei dir nur mit 3440x1440 auf oder mit allen Auflösungen

**Comment by dsiekiera** [comment]
There is a zoom active?! @HAL09001

**Comment by HAL09001** [comment]
Changing the Chrome zoom doesn't change the behaviour, with the most recent version (2.5.4.2) it also applys with 9 goods, 
Language is German, the new wording seems to break it. Chance vs Wahrscheinlichkeit.

![image](https://user-images.githubusercontent.com/48470058/102697313-35e78f80-4235-11eb-9a5a-b118d9b0540f.png)

**Comment by HAL09001** [comment]
Just tested, it is not related to the resolution, it is related to the fontsize, which was one larger than the recomendet. (Groß)

**Comment by andrgin** [comment]
Yes changing font size will break most boxes.
Zooming on the other hand should work in most cases as boxes are increased in size as well.

But I have restored the old translation
