### ISSUE TITLE
Möglicher Fehler im Moppelassistent

### ISSUE THREAD

**Issue by mordillo666** [mainIine/foe-helfer-extension#1728]
Mir ist jetzt aufgefallen, dass bei 2 Spielern, die noch nie gemoppelt hatten, auf einmal 3 Einträge erscheinen, der letzte von vor 14 Tagen...

Ich gehe täglich im Rathaus die Ereignisse durch, um den Assistenten aktuell zu halten und ich hatte vor paar Tagen den Helfer neu installiert, um den Fehler mit der leeren Marktübersicht einzugrenzen.

**Comment by andrgin** [comment]
War der jeweilige Spieler vielleicht bisher z.B. kein Freund aber ein Gildenmitglied?

**Comment by mordillo666** [comment]
Hi andrgin,

nein, sind beide schon länger nur in der FL.
Vielleicht hat auch bei mir einfach was gehängt, und durch die Neuinstallation ist es jetzt behoben...
Ich werde es auch mal weiter beobachten. 
Ansonsten funktioniert der Assistent ja prima. Tolle Arbeit. :-)

**Comment by mordillo666** [comment]
Also mir ist jetzt die Tage nichts mehr aufgefallen. Scheint wohl doch irgendwie bei mir gehängt zu haben.
