### ISSUE TITLE
Idea - Coin and Supply gathering

### ISSUE THREAD

**Issue by adwsystems** [mainIine/foe-helfer-extension#1730]
Implement greedy algorithm in a window to display the best order of available collections to meet a target collection amount.

For example.
Collect 100,000 supplies
New function of sub function from production overview that displays the best order to collect buildings that add to that amount.

If buildings available were 10k, 20k, 30k, 40k, 50k, 60k.
FoE Helper would indicate to collection 60k and 40k. Once those are collected it would then indicate to collect 50k, 30k, and 20k.

**Comment by belikoviv** [comment]
I have small addition to this proposal:
to display (in small window anywere on screen with adjustable position) how many money/supplies are rest to collect in current recurring quest.
