### ISSUE TITLE
Error: Motivation helper icon not always shown in menu bar.

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#1731]
Hi.

After loading (or reloading) FoE page, Helper menu bar may load without Motivation helper icon. Other icons not disappear.
Reloading page (possible several times) solves problem.

Different browsers (Chromium, Yandex, Brave, Vivaldi - all based on Chrome engine)

**Comment by andrgin** [comment]
Maybe settings are not loaded yet when menu is generated?

**Comment by belikoviv** [comment]
> Maybe settings are not loaded yet when menu is generated?

I doubt it.

When I check the settings, the "Motivation Activity" checkbox is present.
(But now with wrong translation to russian - translation talks about sending data - not about displaying icon. I'll check traslation right now.)

The last time the icon didn’t appear, I just refresh the page a few times until the icon appears.

**Comment by belikoviv** [comment]
I have big doubts about the translation - the English phrase is also not quite correct :(

An English phrase should be something like this:

Should the other players activities be tracked when the player opens the Event Log (sorry, don't know right name of event log in Town Hall in english).

I'll do nothing with translation to russian while english variant not right.

**Comment by belikoviv** [comment]
version 2.5.4.3

Today, after the next page refresh, the icon disappeared. After the next refresh - returned.

**Comment by belikoviv** [comment]
2.5.5.0.
Icon periodically disappears.
