### ISSUE TITLE
Stadtplanerdatei

### ISSUE THREAD

**Issue by GermanCatracho** [mainIine/foe-helfer-extension#1735]
Die Idee ist das File des Stadtplaner herunterzuladen (nicht als PDF o. PNG)und wieder (auch von anderen Spielern) von der Festplatte hereinladen zu können.
Der Vorschlag des Planungstools wurde abgelehnt, jedoch könnten so andere (für Planung talentierere Spieler) helfen und nicht nur Tipps geben.
Wie die Files zwischen den Spielern hin und her geschickt werden sollen sie unter sich ausmachen.

**Comment by mordillo666** [comment]
Ja, so eine Option fehlt mir zZ auch. Ich mach bei uns in der Gilde Bob der Baumeister ^^
Den neuen Spielern das per Chat alles zu erklären ist doch sehr mühsam...

**Comment by dsiekiera** [comment]
Diese Option habe ich bereits begonnen zu implementieren.

Das hab ich in ein paar Tagen fertig.

**Comment by SpellfireCA** [comment]
Ist glaube ich das gleich was ich in  #1576  angeregt habe.

**Comment by dsiekiera** [comment]
foe-rechner.de wird in ein paar Tagen zu foe-helper.com. Dort ist die neue Version bereits integriert.

Man kann sich dann einen Link erzeugen mit jemand anderes diese Vorlage bearbeiten kann.

![Bildschirmfoto 2021-03-02 um 09-34-44](https://user-images.githubusercontent.com/834814/109620799-913dd400-7b3a-11eb-83f9-ad024be1bf64.png)

Derzeit nicht Online verfügbar!
