### ISSUE TITLE
idea: GBG attack speed / delta time

### ISSUE THREAD

**Issue by hire-vladimir** [mainIine/foe-helfer-extension#1736]
The GBG overview feature presently shows number of fights that a player has completed since last time the screen was open. As a fun feature to show how competitive players are, it would be great if the tool would also show:

* Speed at which each fight/negotiation was done (# of encounters / time since last data point collection)
* Delta time, the time difference between your speed and player above you
* A variation on Delta time could be showing a ratio of # of encounters you did vs player above.. ie i am 1.5 times slower to next player

It would be even better to be able to trend this time over-time, that way as the player improves their city (by leveling GB's getting special building to increase attack/def) they can see it live. This feature would be great as it allows to compare players / gives something to aspire to! For example,

**Comment by outoftheline** [comment]
I am not entirely sure if this is useful.

Let's say I opened the list before we started fighting and then after finishing up one province.
The speed can be seen by dividing the # of fights and the minutes that is shown in the window title.
The person that did more fights is "better".

If you open the window after an hour though, your added information wouldnt have a meaning.
Also: it is unknown how much attrition each participant has, so it's hard to compare the numbers. The speed depends a bit on the era and your device (i'm much slower on mobile, connection issues).
