### ISSUE TITLE
Sortierbare Spalten in der GG Spieler Übersicht

### ISSUE THREAD

**Issue by frank42hh** [mainIine/foe-helfer-extension#1739]
Ich kopiere diese Frage mal aus dem Discord hier rein, weil der neue #ideas das so sagt :)

Moin, darf ich mal nen Verbesserungsvorschlag für die GG Spieler Übersicht einwerfen?
Ich mache immer Snapshots direkt vor Start und direkt nach Ende eines Kampfes um einen wichtigen Sektor, um zu sehen, wer sich beteiligt hat.
In dem Zuge wäre es unglaublich hilfreich, wenn man die Spalten der Spieler Übersicht durch click auf die Spaltentitel sortieren könnte (so wie z.B. im Moppelassistent oder der Produktionsübersicht) , und zwar logischerweise bei Verhandlungen, Kämpfe und Gesamt (da die ja aktuell statisch nach Gesamtwert sortiert sind) nach der in grün angegebenen Zuwachsrate (z.B. abwechselnd pro Click "Gesamt rauf, Gesamt runter, Diff rauf, Diff runter") - damit könnte man direkt auf einen Blick sehen, wer mit wie vielen Punkten dabei war ... klingt das kompliziert oder wäre das umsetzbar?

P.S. Könnte man bei der Gelegenheit den kleinen grünen Diff Indikator auch bei der Spalte "Gesamt" nachtragen?

**Comment by outoftheline** [comment]
ich denke nur die "grünen" herauszufiltern ist ein bisschen kompliziert. 

der rest klingt machbar.

**Comment by frank42hh** [comment]
Gerade "nur die grünen" wäre aber das, was am Interessantesten an dem Pugin ist. Die Liste der Spieler und ihre Gesamtpunkte sehe ich auch in dem spielinternen "Mitglieder-Aktivität" Popup. Insofern hat die foe-helfer Spieler Übersicht aktuell nur den Mehrwert, dass halt in grün die Veränderung zum vorigen Snapshot angezeigt wird.
Selbst wenn man die Spalten nach den absoluten Zahlen sortieren könnte, wäre das eher egal, weil die ist ja schon nach "Gesamt" sortiert und die beiden anderen sind mehr so zweitrangig, aber eine Möglichkeit, nur die grün markierten Spieler anzeigen (und ggf. nach dem Differenzwert sortieren) zu lassen, das wäre unglaublich hilfreich bei der GG Planung und Auswertung.
