### ISSUE TITLE
Idee: Hervorheben/Markieren von neuen Freunden im Moppelassistent

### ISSUE THREAD

**Issue by andy71** [mainIine/foe-helfer-extension#1755]
Wäre es evtl. möglich neue Freunde und Gildenmitglieder in irgendeiner Form zu markieren? Die Info von neu gebildeten Freundschaften oder neuen Gildenmitgliedern findet sich ja in der Ereignis-Übersicht. Gerade in der Freundschaftsliste fände ich eine kleine Markierung sinnvoll wenn diese Person mich noch nicht gemoppelt hat. z.B. eine kleine Markierung ala "Neu seit x Tagen", gern auch nur als mit * markiert und den Text als Mouseover und diese maximal für z.B. 7 Tage anzeigen (oder vielleicht in den Einstellungen definierbar).

**Comment by Bluep** [comment]
Die Idee hatte ich in den letzten Tagen ebenfalls - mit einer kleinen Erweiterung: Auch Spieler, die aus der Liste gefallen sind, noch mit aufführen.
- für Gildies einfach, weil es im Log steht
- für Freunde etwas komplizierter - Annehmen lässt sich leicht loggen, aber wenn man nicht selbst aufkündigt müsste das über Snapshots ähnlich wie im GG laufen, wer ist seit dem letzten Snapshot weggefallen? Anzeige dann entsprechend "Freundschaft in den letzten x Tagen gekündigt"

Spontan würde ich das in einen eigenen Tab im Moppelhelfer packen - "Änderungen (3)" - mit der Zahl der neuen Einträge im Reiter.
Für neue Freunde macht aber Andys Vorschlag - Markierung (auch) in der jeweiligen Liste - definitiv auch Sinn, schließt sich ja nicht aus.
