### ISSUE TITLE
Nutzernamen auf forge-db.com verlinken

### ISSUE THREAD

**Issue by alexander-bogomolov** [mainIine/foe-helfer-extension#176]
Wäre praktisch, um zu sehen, ob der Nutzer noch aktiv ist.
Beispiel-URL: https://www.forge-db.com/de/de12/players/profile/?server=de12&world=Mount%20Killmore&id=1931107

**Comment by dsiekiera** [comment]
@alexander-bogomolov welche Info genau wäre denn da relevant?

**Comment by alexander-bogomolov** [comment]
@dsiekiera, ich erhoffe mir einen einfacheren Überblick über die Aktivität des Spielers. So ist man recht sicher, ob man in das LG mal eben 2k FPs reinwerfen soll oder nicht. ;)

P.S.: Vielen Dank für die super Erweiterung!

**Comment by outoftheline** [comment]
Duplicate, see #149
