### ISSUE TITLE
Ability to calculate attack % vs FP value per city square

### ISSUE THREAD

**Issue by bbehrens** [mainIine/foe-helfer-extension#1761]
In planning my city, I really don't know how to evaluate different items other than a simple gut feel.  For me, this boils down to not really being able to quantify how many FP 1% attack correlates to.  Furthermore, this number will likely be different for most players and dependent on what GBG league they are in, how many camps they anticipate fighting with and how high they can run their attrition.

Here are some of the numbers I think might be relevant --

A random example might be:

I am in diamond league
I'm comfortable at 70 attrition
I normally fight with 4 camps

There is a correlation between --

On average, I'm rewarded 1.75FP per fight.  50% I get a reward at all, 35% I get FP as my reward.  10FP = 
.5*.35*10 = 1.75

With 4 camps, there's a 4% chance I get attrition so on average I should be able to fight 25 times before I gain an additional attrition point (I think)

That means 1 attrition point = 25 fights = 43.75 FP.  So, then the question becomes, how many attack points do I need to gain an additional attrition point

**Comment by JhonnyBn** [comment]
Could this be an extension feature? The end of the issue seems like a general game question.
Have you seen this video from FoEhints? It explains attack in CBG
https://www.youtube.com/watch?v=_3PplYM7FcI
