### ISSUE TITLE
Website > Statistiken > Mitglieder und Legendäre Bauwerke nicht korrekt

### ISSUE THREAD

**Issue by McLeise** [mainIine/foe-helfer-extension#1765]
Ich sehe bei mir zwei Probleme in der Statistik-section der Website:

1. Die angezeigten Gildenmitglieder sind nicht korrekt.
    a. Die Punkte stimmen nicht
    b. Die Mitglieder ansich sind nicht korrekt -> Dazu habe ich gestern ein Mitglied mit dem Entfernen-Button entfernt und bin davon ausgegangen, dass bei erneuter Übertragung die korrekten Gildenmitglieder angezeigt werden. Die Übertragung scheint auch grundsätzlich zu funktionieren, da ich das kleine Fenster bekomme, dass die LB des Mitglieder upgedated wurden, wenn ich deren Stadt besuche. Nun fehlt das gelöschte Mitglied ganz, die Nummerierung beim Rang überspringt einfach diese Position (... 18, 19, 21, 22...)
2. Die Legendären Bauwerke sind nicht korrekt.
    a. Es wurden mir gestern nur 3 Galata-Türme angezeigt, es haben aber wesentlich mehr Mitglieder dieses Bauwerk. Nachdem ich nochmal alle Gildenmitglieder besucht habe und auch das Fenster eschien, dass die LB upgedated wurden, sehe ich auf der Website jetzt nur noch einen (meinen) Galataturm. D.h. es hat ein Update stattgefunden, aber leider nicht korrekt.
    b. Auch beim Klick auf die Mitglieder in der Mitglieder-Liste sind die angezeigten LB Stufen teilweise nicht korrekt und zeigen veraltete Werte an, bzw. LBs (wie z.B. o.a. Galataturm) fehlen ganz.

**Comment by darylam** [comment]
weitere Stastik gaps: 
auch die eigenen LB Daten stimmen nicht immer.
Und bei den Investitionen werden dadurch auch nicht die letzten Lbs der Gildenteilnehmer verwendet und stimmen nicht immer.

**Comment by outoftheline** [comment]
Feature has been removed
