### ISSUE TITLE
Production overview incomplete

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#1767]
Hi.

One of tabs in Production overview - army tab.

But there I can see only "unusual" sources of military units, such as Alkatraz or Town hall.
And I can't fid "regular" military buildings like Spearfighter Barracks, Warrior Barracks, etc. They are completely absent in any kind of overview.

**Comment by andrgin** [comment]
This is because we only list production of unattached units. Listing attached and unattached units in the same tab does not make much sense in my opinion, but it is also not really worth its own tab.
