### ISSUE TITLE
Produktionsübersicht: FP-Effizienz bei Set-Gebäuden

### ISSUE THREAD

**Issue by frankmorgner** [mainIine/foe-helfer-extension#1773]
Beispieldaten: Immergrün-Express mit 5 Schlafwagen
Angezeigt werden: Menge: 18, Größe 22, Effizienz 0,82

Offensichtlich wird bei der Effizienz nur die Größe des Immergrün-Express eingerechnet; tatsächlich müsste aber auch die Größe der Schlafwagen berücksichtigt werden (zusätzliche Größe: 5*2*3=30 Felder; korrekte Effizienz: 0,35).

Grundsätzlich sollte eine Effizienz-Anzeige bei Set-Gebäuden für das gesamte Set möglich sein. Z.B. macht es auch keinen Sinn die effizienz des Mondtors vom 2020 st patricksday event ohne die berücksichtigung der anderen 4 set gebäude zu machen.

FoE - Helfer 2.5.4.4 für Chrome (Deutsch)

Vielen Dank für eure tolle Arbeit!

**Comment by andrgin** [comment]
Theoretisch ist dies teilweise möglich, in der Praxis ist der Aufwand dafür jedoch enorm und steht in keinem Verhältnis zum Nutzen.
