### ISSUE TITLE
Event: Forge Ball verbesserung.

### ISSUE THREAD

**Issue by HAL09001** [mainIine/foe-helfer-extension#1776]
1. Im Event ist die Reihenfolge der Angebote anders als die dargestellte. ich hatte (zufällig) die ersten in der reihenfolge und dann erstmal einige einfach aufgrund der Position in der Liste ausgewählt. Wenn die Ausgabereihenfolge nicht bestimmbar ist, evtl. sortieren, mit markieren der Sortierreihenfolge.
![image](https://user-images.githubusercontent.com/48470058/105234209-32646280-5b6b-11eb-89ea-9bdd34b0dae9.png)

2. es wäre schön, wenn es ein weiteres highlight gäbe, bei dem bei kleinen Unterschieden (<0,5) die Kreuzung auch zu markieren, evtl. in Orange.
![image](https://user-images.githubusercontent.com/48470058/105234777-f251af80-5b6b-11eb-80ea-bdada248bd5f.png)

Ansonsten Danke für das tolle Tool!

**Comment by andrgin** [comment]
1.) Ja die Reihenfolge in der die Spieler im Spiel dargestellt werden entspricht nicht immer der Reihenfolge in der diese im Helper angezeigt werden. Das lässt sich aber leider nicht lösen ohne Speziallogik die gezielt auf einzelne Events zugeschnitten wird, was wir vermeiden wollen, da wir dann unseren Updatezeitplan nur von diesem einen Model abhängig machen müssten.

Derselbe Code wird 1:1 bei einer Menge unterschiedlicher Events eingesetzt, die alle demselben Muster folgen. Das ist z.B. auch das Herbstevent, wo man aus verschiedenen Zutaten diverse Dinge backen muss, nur mit dem Unterschied dass dort die Preise oft gleich sind (2 Rezepte mit je 1 Zutat) und würden wir für das Football Event die Reihenfolge umdrehen würde das spätestens im Herbstevent nicht mehr funkitionieren.

2.) Was die kombinierten Auswahlvorschläge angeht, so ist das zwar grundsätzlich eine sinnvolle Idee, allerdings wird es hier bei der Priorisierung sehr schnell kompliziert. Ein Spieler will zu 90% auf Hauptpreise setzen und zu 10% auf Tagespreise, der andere umgekehrt und am Schluss ist vermutlich niemand wirklich glücklich damit, wenn ich hier eine einfache 50/50 Priorisierung festlege und eine individualle Tuningoption (wie z.B. beim BG Helfer) wäre wahrscheinlich für den Großteil der Spieler zu verwirrend.
Aber vielleicht fällt mir da noch eine Lösung dazu ein.
