### ISSUE TITLE
Anzahl der Freigaben im GvG

### ISSUE THREAD

**Issue by chrisnain** [mainIine/foe-helfer-extension#1781]
Was sicher viele Mitglieder von GvG-Gilden brauchen könnten wäre eine Infobox, wie viele Freigaben man selbst bereits seit der Abrechnung (20 Uhr) im GvG getätigt hat.
Vielleicht könnte man die Information auch im Header ergänzen, so wie die Anzahl der Forge Punkte im Header steht.
Wenn man beispielsweise eine GvG-Karte öffnet rechts neben der Herunterlaufenden Uhrzeit bis zur nächsten Abrechnung.

---

A lot of members of GvG-Guilds might be interested in an infobox about the remaining Releases they could use in GvG.
Maybe the information could be added to the header similarly to the Forge Point Number. Possibly right next to the countdown of the next billing/clearing (Machpunke-Abrechnung?).

![Attemps-Suggenstion](https://user-images.githubusercontent.com/1774063/105552735-a5551100-5d04-11eb-815c-c3dd1bc69cdc.JPG)

**Comment by outoftheline** [comment]
gute idee, ich hab letztens eine taktik vergeigt, weil ich zu wenig sektoren freigeben konnte

**Comment by outoftheline** [comment]
![image](https://user-images.githubusercontent.com/7482863/112753801-7f383f80-8fd9-11eb-9ed7-a4d396174fbb.png)

Beta-Testing :)
