### ISSUE TITLE
trade window on continent map

### ISSUE THREAD

**Issue by exstreme** [mainIine/foe-helfer-extension#1786]
Opening any province on continent map show this window: https://yadi.sk/i/7b1EE8WXMPerfA

**Comment by outoftheline** [comment]
it's a feature, you can disable it in the settings:
![image](https://user-images.githubusercontent.com/7482863/105599869-ebf24c00-5d94-11eb-922b-eb19f4900dfb.png)

**Comment by dsiekiera** [comment]
Yes, that's correct. When you open a province, this box prevents you from accidentally negotiating instead of fighting. It disappears to fight and then reappears:

![Bildschirmfoto 2021-01-23 um 16-06-14](https://user-images.githubusercontent.com/834814/105601439-5efbc280-5d95-11eb-9498-2e4e6037f104.png)

**Comment by exstreme** [comment]
Index: js/web/maptradewarning/js/maptradewarning.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/web/maptradewarning/js/maptradewarning.js	(revision 30f15296aff7991c96b30914caeb3306dfce0cff)
+++ js/web/maptradewarning/js/maptradewarning.js	(revision 7e98aa517ff74d6f88b72b9abfd391198d1a3439)
@@ -26,6 +26,13 @@
 	if(!Settings.GetSetting('ShowMapTradeWarning')){
 		return;
     }
+
+	// if provinces are already owned?
+	let provincesArePlayerOwned = data.responseData.filter(arr => arr.isPlayerOwned === false);
+	if(provincesArePlayerOwned.length === 0) {
+	    return
+    }
+
     //closes box if still open for some reason
     HTML.CloseOpenBox('mapTradeWarningDialog');

**Comment by exstreme** [comment]
Cannot add pull request(
