### ISSUE TITLE
Reset FoE Helper reset/lock configuration option

### ISSUE THREAD

**Issue by NickRing** [mainIine/foe-helfer-extension#1795]
After some messing around, I have got three worlds with different layouts/settings.
Is it possible (manually?) to reset the configuration data? If not, could this be implemented?

The configuration I am talking about it the number of icons visible, order, activation, and anything else the user can change.

Maybe I need to split this into another issue, but how about a locking option too?

**Comment by vegaz337** [comment]
Its already saving your position etc. Do you have your chache activate?

**Comment by dsiekiera** [comment]
U can download the current settings: 
![Bildschirmfoto 2021-02-01 um 16-22-52](https://user-images.githubusercontent.com/834814/106478702-c3133a80-64a9-11eb-970a-d3272f1d261e.png)

Upload them to the other worlds and the settings would be on all worlds the same...
