### ISSUE TITLE
Handel-Vermeidung an falscher Stelle

### ISSUE THREAD

**Issue by Blackfir5** [mainIine/foe-helfer-extension#1823]
Hallo.
1. Auf der Karte/Provinz kommt das Fenster schon zu früh und man kann nicht jeden Sektor gut auswählen
![image](https://user-images.githubusercontent.com/55910235/107358745-0b4ae200-6ad4-11eb-8b88-b52f9f28fa68.png)

2. Bei den Vorkommen ist es an der falschen Stelle, wenn man zuvor unbeabsichtigt die Provinz geöffnet hat und dann das Vorkommen anklickt.
![image](https://user-images.githubusercontent.com/55910235/107358454-b1e2b300-6ad3-11eb-9024-620d6e0b01d2.png)

**Comment by Th3C0D3R** [comment]
Dass das Fenster davor erscheint ist leider anders nicht möglich, da beim auswählen eines Sektors keine Anfragen mehr geschickt werden und wir so nicht mitbekommen ob man ein Sektor öffnet

Für das 2. Problem lässt sich bestimmt ne Lösung, leider bin ich erst in der VZ was KdK angeht (und AZ was Zeitalter angeht) somit kann ich da nichts machen. müssen welcher der höheren ZAs sich anschauen
