### ISSUE TITLE
Ereignisse auf Autobahn werden nicht angezeigt

### ISSUE THREAD

**Issue by Cratus80** [mainIine/foe-helfer-extension#1827]
Hallo,

mir ist aufgefallen, das Ereignisse auf der Autobahn nicht erkannt werden. Kann gerne einen Screenshot liefern, wenn wieder ein entsprechendes Ereigniss auftaucht.

Ereignisse auf der normalen zweispurigen Straße werden erkannt

Passiert auch, wenn ich das Spiel neu geladen habe. Neue Ereignisse werden zuverlässig ohne neuladen erkannt. Zeitalter ist "Die “Moderne”

Hier ein Screenshot:

![autobahn](https://user-images.githubusercontent.com/78846558/107485860-a26f7280-6b84-11eb-86a3-885c86af2d62.gif)

**Comment by andrgin** [comment]
Kannst du überprüfen ob Datum/Uhrzeit auf deinem System korrekt eingestellt sind. Damit könnten wir das Problem besser eingrenzen.

**Comment by Cratus80** [comment]
Hallo,
Datum und Uhrzeit sind richtig eingestellt.
Viele Grüße
