### ISSUE TITLE
Disable "leave all" button

### ISSUE THREAD

**Issue by Siguana** [mainIine/foe-helfer-extension#1828]
Sometimes, when we want to mark all conversations as read, by error we click on "leave all" button.

I think it would be a good idea to have a small windows over "leave all" button for avoiding this mistake.

**Comment by outoftheline** [comment]
Hm, this never happened to me. There is a confirmation window for this, and this should stop you for a second. 
It's not like you do this multiple times in a row like with deleting buildings in the settlement and sometimes clicking on the wrong thing and deleting it by accident.
