### ISSUE TITLE
Fehlt:  1) Info für alle Güter über Bestand =  im Inventar + angeboten am Markt ; 2) Sortiermöglichkeit im "Markt-Filter" nach Angebot/Bedarf/Spieler

### ISSUE THREAD

**Issue by Max3141** [mainIine/foe-helfer-extension#1842]
Im "Markt" oder im Inventar sehe ich nur die Anzahl der jeweiligen Güter im Inventar.
Im "Markt-Filter" kann ich mir die selbst angebotenen Güter anzeigen lassen.
Was mir fehlt ist eine Möglichkeit je Gut zu sehen wieviel ich insgesamt angeboten habe
(und sinnvolle Gesamtsummen je ZA und insgesamt)
Also zb.: Bronzezeit / Holz:  30 im Inventar, 175 angeboten am Markt = Gesamt: 205
              Bronzezeit / Stein:  ........
              Bronzezeit / Gesamt ....
              Eisenzeit / ...
              .....
              Gesamt.
 
Außerdem wäre es super hilfreich und wahrscheinlich relativ simpel im Marktfilter auch noch Sortiermöglichkeit nach "Angebot", "Bedarf" und "Spieler" hinzu zu fügen.

**Comment by Max3141** [comment]
Ist die Idee umsetzbar? Falls ja, wann wäre es ungefähr verfügbar? Schon mal vielen Dank für eine Info

**Comment by andrgin** [comment]
Ich bin noch unschlüssig wie die Idee ins Gesamtkonzept des Marktfilters passt. Der Hauptsinn des Tools war, dass man Handel finden kann, die je nach Situation lukrativ erscheinen z.B. OZ in AZ runter handeln oder alle Kleinmengen, wo die Handelsgebühren zu teuer werden ausblenden.

Die eigenen Angebote passen hier schon einmal nicht wirklich rein und ich bin noch nicht sicher, ob wir dieses Feature nicht wieder entfernen und stattdessen in anderer Form implementieren.

Was die Ermittlung der Gesamtsumme angeht:
Hier ist die Frage wie es sinnvoll ist zu zählen:
.) Inventar + angebotene Güter, da man den Handel ja jederzeit wieder löschen kann
.) Inventar + erhaltene Güter: Hier geht man davon aus, dass der Handel ja irgendwann angenommen wird und somit die angebotenen Güter ja schon verplant sind. Allerdings ist das ja oft nicht sicher und einige Spieler stellen ja auf Verdacht alles zu teuren Konditionen in den Markt, rechnen aber nicht damit, dass sie alles anbringen.

Was die Filterung angeht: Diese ist bewusst so gewählt, dass die Reihenfolge mit der im Markt übereinstimmt. Dann muss man weniger suchen.

**Comment by Max3141** [comment]
Danke für die Rückmeldung!

Vielleicht zum besseren Verständnis meiner momentanen, sehr zeitraubenden Problematik
Aus dem Alltagsleben eines "Händlers":
Ich bekomme Anfrage ob ich x Stück von Gut G habe (zB 300 Algen). 
Im Moment muss ich im Lager nachsehen. 
Wenn ich es dort nicht habe, dann muss ich mühsam alle Handelsangebote durchschauen und 
händisch zusammen zählen wieviel ich tatsächlich im Moment habe.
Der Marktfilter erspart mir zumindest schon mal das mühsame Durchschauen aller Handelsangebote, da er meine eigenen Handelsangebote für ein Gut kompakt darstellt. Allein was noch fehlt wäre eine Gesamtsumme.
Oder natürlich alternativ ein anderes Toll mit dem man auf einem Blick seine eigenen Bestände je Gut sieht,
egal ob im Lager oder gerade als Handelsangebot, am Besten noch mit den Summen für die jeweiligen ZA.

"Inventar+angebotene Güter" : genau wie du sagst - Handel kann ich jederzeit löschen, deshalb fast so gut wie im Lager.  
"Inventar+erhaltene Güter" : macht für mich keinen Sinn, da ich ja nicht weiß ob Angebot jemals angenommen wird.
Wüßte auch keine praktische Verwendung für so eine Summe.

**Comment by Max3141** [comment]
Nachtrag: Marktfilter ist auch super wichtig und hilfreich um einen Überblick über die eigenen Angebote zu erhalten, damit ich eben auch weiß welche noch fehlen, oder welche ich herausnehmen sollte und wo ich diese dannr auf den 100 Markt-Seiten finde. 
Also bitte auf jeden Fall beibehalten und nicht entfernen!!

**Comment by andrgin** [comment]
"Inventar+erhaltene Güter" : 
Hier ist die typische Situation für mich die:

Tag1:
Ich will OZ in AZ Güter runter handeln. Deshalb stelle ich ein paar Handel rein jeweils 200 von jedem OZ Gut gegen 300 von jedem AZ Gut bzw. gleiche bei den Mengen unterschiedliche Lagerstände aus.

Tag2:
Die Hälfte meiner Handel wurde schon angenommen, die andere Hälfte noch nicht. Ich will noch ein paar Handel zusätzlich rein schießen, habe jetzt aber keinen Plan wovon ich wieviel habe, da ein Gut vielleicht etwas knapper ist, dafür aber noch alle 5 Handel drin stehen.

Die Situation, die du beschreibst habe ich eigentlich so gut wie gar nicht, da ich Güter, die schon knapper werden gar nicht erst in den Markt stelle, da ich als Güterverkäufer jederzeit damit rechne, dass die jemand haben will. Das einzige, was mir gelegentlich passiert ist, dass ich ein paar Schnäppchen im Markt finde und dann feststelle, dass ich bei einem Gut so gut wie pleite bin.

**Comment by Max3141** [comment]
Danke, für dein Beispiel ...
Ich glaube der Haupt-Unterschied ist, du bist schon weit fortgeschritten und hast nur einen Teil deine Güter im Angebot.
Meinereiner ist erst seit Dezember bei FoE, bin also eher ein "kleiner" Spieler, und bei mir sind gut 90-95% meiner Güter
ständig als Handelsangebote am Markt. Einzig die Güter die ich selbst brauchen könnte innerhalb der nächsten "24 Stunden" nicht.

Wenn also beide Möglichkeiten Sinn machen, weshalb nicht einfach ein Kästchen mit dem zwischen beiden Optionen wechseln kann ?

Mir würde es auch bereits sehr das Leben erleichtern einfach im Marktfilter eine Gesamtsumme zu sehen, wenn ich mir zB alle angebotenen Algen anzeigen lasse (zB wenn jemand Güter für die Arche anfragt). 
Müsste dir ja eigentlich auch helfen, wenn die Summe bei "Bedarf" für deine Angebote angezeigt wird. 

Ein eigenes "Händler Tool" wäre natürlich noch besser 
(mit Übersicht für jedes ZA/Gut über "Lagerbestand" + "angebotene" bzw. "zu erhaltende") , 
aber lieber quick fix "morgen" als die "perfekte Lösung" in "ein paar Monaten" ... 
Ich kann natürlich den spezifischen Programmier-Aufwand nicht abschätzen.
Allerdings würde ich vermuten, dass im Normalfall Summen einfügen wesentlich leichter sein müsste, als ein neues Tool.  

Viele Grüße. Max

**Comment by Max3141** [comment]
Gibt es eigentlich eine Möglichkeit, die im Marktfilter angezeigte Tabelle irgendwie nach Excel zu kopieren um mir das händische Summieren zu ersparen ? Schon allein jedes Gut einzeln durchzugehen kostet viel Zeit, aber auch noch händisch alles zusammen zu zählen macht es echt zur Qual :-(

**Comment by Max3141** [comment]
Bitte um kurzes update ... Hatte zumindest auf rasches Einfügen von Summen gehofft
