### ISSUE TITLE
alerts Ringtones

### ISSUE THREAD

**Issue by Untenshu** [mainIine/foe-helfer-extension#1843]
_France:_ Bonjour, votre idée d' alerte est bien mais le serait mieux si on pouvait télécharger une sonnerie personnel car la vôtre est beaucoup trop discrète et trop courte

---

_Rest of the world:_ Hello, your alert idea is good but it would be better if we could download a personal ringtone because yours is much too discreet and too short...

**Comment by dsiekiera** [comment]
This sound is your PC. Not the Extension. But it is possible to play a sound while the alert is ringing.

**Comment by Untenshu** [comment]
Bonjour et merci du " retour " .
J' avoue que je ne sais pas où faire ce réglage. Mais merci car cet extension est vraiment superbe.
Cordialement.
