### ISSUE TITLE
Alerts and GM investments bugs on Mozilla Firefox

### ISSUE THREAD

**Issue by IngenieurMeca** [mainIine/foe-helfer-extension#1856]
The alerts can't be create with Firefox addin and the GM investments don't work anymore.

**Comment by outoftheline** [comment]
what exactly is not working anymore with the investments?

**Comment by IngenieurMeca** [comment]
It's not really on the GM investments but on the little window we had with "invested + gain + in stock PF". Now, the window is totally empty

**Comment by IngenieurMeca** [comment]
![PF investments](https://user-images.githubusercontent.com/79056153/107915637-2484e000-6f65-11eb-9e69-8b3678927557.JPG)

**Comment by outoftheline** [comment]
Hm, that is not intended. What browser are you using? Is there an error in the console?

**Comment by IngenieurMeca** [comment]
I'm using Mozilla Firefox. But before the new version, that was functioning very well.

**Comment by IngenieurMeca** [comment]
![Alerts bug](https://user-images.githubusercontent.com/79056153/107933345-ec8a9680-6f7e-11eb-8683-87ac8353551d.JPG)

**Comment by IngenieurMeca** [comment]
And for the alarms, I can push one or many times, it doesn't create the alarms and "Aperçu" doesn't work also.

**Comment by outoftheline** [comment]
the alert issue has been reported #1848 

i just installed the newest update on firefox and do not have an issue with the investments. please check again after the update.
