### ISSUE TITLE
Foe Rechner Galataturm

### ISSUE THREAD

**Issue by Jessyfoosy** [mainIine/foe-helfer-extension#1860]
Moin,

beim Galataturm wird zum Beispiel bei Stufe 5 angezeigt das es 270FP Gesamt sind. Passen tun aber nur 210FP.

**Comment by outoftheline** [comment]
Meinst du die Website oder den Helfer im Spiel?

**Comment by Jessyfoosy** [comment]
Die Website. 
Der Helfer im Spiel ist richtig.

Sorry...

**Comment by outoftheline** [comment]
Danke für die Klarstellung!

**Comment by dsiekiera** [comment]
Die Daten in Kürze von der Hauseigenen API geholt die auch sämtliche Boni der einzelnen Stufen enthält...
