### ISSUE TITLE
Alarm - GG: Kopieren von Uhrzeit + Sektor in die Zwischenablage

### ISSUE THREAD

**Issue by Biber42** [mainIine/foe-helfer-extension#1863]
Die Alarmfunktion ist richtig nett... und Ihr habt die Gildengefechte implementiert. Als GG-Koord wäre es super, wenn Uhrzeit (weniger Datum) und Sektor in die Zwischenablage kopiert werden könnte, um es für den GG-Channeleintrag mitverwenden zu können 😊

**Comment by vegaz337** [comment]
wurde nicht gewollt wegen der übersichtlichkeit ;)

**Comment by outoftheline** [comment]
Man kann die Einträge markieren und kopieren, einfach ausprobieren

**Comment by sdn-br** [comment]
Ein Copy to Clipboard feature wäre aber schon ganz nett :)

**Comment by frankmorgner** [comment]
Markieren und Kopieren funktioniert -- eigentlich. Wenn das Chat-Fenster geöffnet ist, lassen sich nur die Zeilen aus der Info-Box selektieren (die ist dann dunkler); der Text selber kann dann nicht mehr markiert werden. Ist dieser Fehler bekannt (FoE-Helfer 2.5.6.3 für Chrome)?
