### ISSUE TITLE
(Idea) Additional feature - Player/Guild look up

### ISSUE THREAD

**Issue by RabaDabaDoba** [mainIine/foe-helfer-extension#1875]
I often check players to see if they are active, or how many points they've gotten the pastime, etc. Hence I was wondering if it's possible to maybe integrate foestats/forgeDB to the helper. I don't know how much information that is available for you when developing. But it would be nice in some ways to have a tool that opens a new tab with the information about the player, or guild. Since the query for forgeDB is straight forward.  Ex:

You open the application in the menu.
The window have one "first time screen", where you add your country and which server. These are the saved and can be changed later on.
Then for the main window. You can search for any player or guild, a toggle of some sort.
When all is filled, it just opens a new tab with the details about this player or guild. I think making it error proof, i.e. checking if the player actually exist might be too much work. 

Just one idea that I had, thanks.

**Comment by RabaDabaDoba** [comment]
Or if it would be possible to have it when right clicking another player, or to have it in the little menu one gets when pressing a name. FYI: I know nothing about the coding part, just ideas so no hate =)

**Comment by outoftheline** [comment]
thanks for your idea! 
there is already a similiar one (in german though): #149 

we'd have to get in contact with the stats site admins before implementing, ofc.

**Comment by outoftheline** [comment]
We'll be implementing links to scoreDB.io
