### ISSUE TITLE
Calculate optimum buildings for increased attack %

### ISSUE THREAD

**Issue by fizxguy2512** [mainIine/foe-helfer-extension#1878]
A useful feature (similar to the FP building leveling up calculator) would be to show the best way to increase attack %.  For example in my city the Japanese Garden Sets take a lot of space for the amount of attack % they provide.  I suppose I'm looking for a % efficiency (use of space compared to attack) just like you do with forge points

**Comment by andrgin** [comment]
1.) In the productions overview the current version does not only show FP production, but also all buildings giving attack/defense bonus with size and efficiency rating (attack per tile considering street requirements).

2.) Currently each building is counted individually. Comparing whole sets is not supported as it would be too much work copying the full set logic including more complicated sets like winter train.
Also be aware that buildings with low attack/square ratings may have other benefits like FP or goods.

**Comment by fizxguy2512** [comment]
Thank you for the response!
