### ISSUE TITLE
*.json settings export/import doesn't work.

### ISSUE THREAD

**Issue by thethinker990** [mainIine/foe-helfer-extension#1880]
Hi, I exported my settings via *json and applyed it to a second world but it don't work. I've looked into the json but there is no playername or world mentioned. Also JSONLint doesn't produce any alert. Firefox and Chrome, both are not working. Reloading and reinstalling the addon didn't fix it but did reset my settings.

```json
{
	"HiddenRewardBoxCords":"293|224",
	"eventchestsCords":"95|618",
	"InvestmentCords":"123|122",
	"fp-collectorCords":"187|99",
	"PartsTone":"deactivated",
	"UnitOverviewCords":"389|451",
	"BackgroundInfoCords":"1082|459",
	"infoboxTone":"deactivated",
	"CalculatorTone":"deactivated",
	"moppelhelperCords":"185|25",
	"MarketCords":"168|356",
	"costCalculatorCords":"464|54",
	"campagneCords":"390|453",
	"AlertsCords":"277|101",
	"MenuSort":"[\"hiddenRewards\",\"moppelhelper\",\"outpost\",\"investment\",\"market\",\"campagneMap\",\"calculator\",\"partCalc\",\"negotiation\",\"citymap\",\"technologies\",\"productions\",\"notice\",\"Alerts\",\"gildfight\",\"unit\",\"settings\",\"stats\",\"chat\",\"kits\",\"greatbuildings\",\"fpCollector\",\"infobox\"]",
	"negotiationBoxCords":"64|583",
	"InvestmentSize":"773|233",
	"moppelhelperSize":"921|368",
	"ProductionsCords":"160|137",
	"technologiesCords":"388|454",
	"outpostConsumablesCords":"316|242",
	"CalculatorForderBonus":"0"
}
```

**Comment by dsiekiera** [comment]
@thethinker990 

This information is not even necessary. You are already uploading the data in a certain world in which your ID and name are already known.

Was genau funktioniert den nicht? Es werden wie du oben siehst hauptsächlich Koordinaten übergeben. Was fehlt dir?

**Comment by thethinker990** [comment]
Mainly the sorting of the quick access bar is not applied. This is the main reason why I want to export settings. I want to have the same sorting on every world.

Another feature request: The settings inside the app could be exported (like anti-negotiate-setting in the campaign)
