### ISSUE TITLE
Feature request: FP investments improvement

### ISSUE THREAD

**Issue by thethinker990** [mainIine/foe-helfer-extension#1882]
Hi, I like this new FP investments feature very much. A little improvement could be on which site and position the GB is (like in the market filter). 

And I got some issues with reloading of the window. Replicating:
1. Open the GB Overview in the town hall
2. Wait for the GB investment list
3. Open a GB
4. Close the GB investment list
5. Close the GB
6. Issue: The GB investment list re-opens again

Another issue:
If I use the sort function (e.g. FP left) then the sorting is reset after I open a GB or change the site.

**Comment by danielvoigt01** [comment]
This "special" behavior when opening and closing GB from the overview will be fixed in the next version.
Regarding the sorting function we will have a look.

**Comment by thethinker990** [comment]
Thank you very much, I appreciate your work.
