### ISSUE TITLE
give GB Calc->Power level screen ability to have the owner contrib in a copy paste

### ISSUE THREAD

**Issue by coderwolf2015** [mainIine/foe-helfer-extension#1888]
I can copy the data from the GB Calc->Power level screen.  But when I do it does not include the owner contrib.  I normally use this for placing the levels when doing a power level run.  It is nice to include my part in that list as well.
That or have a message creation option like on the GB Calc screen for all levels with owner contrib.

**Comment by Gindi4711** [comment]
Included in the next update
