### ISSUE TITLE
Eigenanteilsrechner "Ext" und "Arche" Wert für jedes LG einzeln speichern und nicht global für alle

### ISSUE THREAD

**Issue by Big-Iron** [mainIine/foe-helfer-extension#1893]
Es wäre super wenn man für ein LG bei "Ext" oder "Arche" im Eigenanteilsrechner etwas einträgt, das dieser Wert nur für dieses LG gespeichert wird und nicht für alle.

**Comment by andrgin** [comment]
1.) Beim Ext Wert stimme ich dir zu. Das wäre sinnvoller, wenn dies pro LG angezeigt werden würde.
Das Problem: Dieser Wert wird derzeit gar nicht permanent gespeichert, sondern bleibt nur im Fenster stehen solange man das Spiel nicht neu lädt.
Permanent speichern ist aber auch nicht gut (selbst pro LG) weil es einige Spieler gibt, die dort dann was Falsches eingeben würden und das bleibt dann ewig erhalten. Da die Ext Spalte ja nur für temporäre Simulationen sinnvoll ist (z.B. wie sieht es aus wenn ich Spieler X 500 FP einzahlen lasse) ist das ganz gut, dass bei Neuladen wieder alles zurückgesetzt wird.

Aber ich denke da werde ich mir etwas überlegen. Eventuell immer bei LG oder Level Wechsel auf 0 setzen.

2.) Bei den Archespalten weiß ich nicht, ob das eine gute Idee ist. Ja klar wenn man z.B. einzelne Plätze mit 1.92 vergibt ist es blöd wenn man vergisst wieder zurück zu stellen. Allerdings würde eine Speicherung pro LG bedeuten, dass bei neuen LGs immer automatisch 1.9 voreingestellt ist. Das ist wiederrum für Spieler blöd, die grundsätzlich alles mit 1.85 fördern. Genauso gibt es auch Spieler, die z.B. P1 und P2 immer mit 1.92 belegen lassen und zwar egal welches LG und wenn die immer 10-20 LG umstellen müssen ist das blöd.

**Comment by Big-Iron** [comment]
1. Die Ext. Spalte wird ja sehr häufig beim Güterverkauf oder wenn ein netter Nachbar drin sitzt verwendet.
Reset beim leveln wäre also super.

2. 1.9 voreingestellt ist doch jetzt schon. Wird da nicht die Arche ausgelesen? mein aktueller Wert kam auch automatisch.
Für die 1.92 Spieler ist es einmal Arbeit, so müssten sie das jetzt nach jedem neuen laden machen.

Wenn diese Funktion global in den Einstellungen erst aktiv geschaltet werden muß (kann) fällt keiner auf die Nase.
