### ISSUE TITLE
Idea: Show buildings which are currently plunderable (in the own town)

### ISSUE THREAD

**Issue by RAT198** [mainIine/foe-helfer-extension#1904]
I didn't found any in the open / dismissed posts
Would help to earn them first.

DE: Anzeige von plünderbaren Gebäuden in der eigenen Stadt wäre eine Hilfe um sie bei der Ernte zuerst einzusammeln.

**Comment by andrgin** [comment]
There is already the production overview that show which buildings have finished productions and when the next productions are finished.
Also if the 5 dia collect all icon is visible this is an indication that something can be collected.

**Comment by RAT198** [comment]
Yes, thats true. But it don't shows me if the building will be plunderable. I think it could be helpfull to decide, which of my buildings I should earn first.

**Comment by andrgin** [comment]
If a production is finished why not collect it?
The old plunder helper had quite some special logic that was tuned for individual buildings. I dont think that it is worth the effort maintaining the building lists only for a very rare case in your own city.

**Comment by RAT198** [comment]
OK, it was only an idea.
I prefer to collect all at the same time (in a time slice from maybe 30-40 minutes to successfully complete as much Château-loops I can do, especially for coins). The harvest of all buildings also spawns in a window up to 40 minutes.
If I could see which buildings are plunderable I would earn them first. Thats all.
I don't know if the information about plunderability is a property of an existant building and if its possible to grab this information at run time - or if the information about plunderability have to store in a database. If the database the only solution, forget my idea. But if its a property of a building it will be easy possible to extend the existent harvest overview with 1 column more.

**Comment by MrPeteH** [comment]
I agree with this suggestion. Perhaps simply add an icon to the production overview?
