### ISSUE TITLE
idea request: adjust % in preset donation spaces in GB Cost calculator

### ISSUE THREAD

**Issue by boeffie** [mainIine/foe-helfer-extension#1906]
There are preset 80%-85%-90%-max%  spaces in the GB cost calculator.

Would it be possible to make those adjustable, with some guilds having different % donation threads?  
I personally don't use either the 80% or 85% on some worlds, but have 1.91 or 1.92 threads on others, so for now keep using the adjustable box, but means going back and forth from 90 to 91 to 92 etc
If I could use the 80%/85% for a different amount, then could swap around much more rapidly

**Comment by andrgin** [comment]
You can already adjust the percentage values with the settings icon:

![Screen](https://user-images.githubusercontent.com/55417498/111072854-b63c2a80-84dc-11eb-955d-1229424c461d.png)
