### ISSUE TITLE
Falsche FP-Anzeige in Infobox bei LB-Fertigstellung

### ISSUE THREAD

**Issue by Adversarius13293** [mainIine/foe-helfer-extension#1907]
FoE Helfer Version 2.5.6.1
Windows, Chrome, deutsch, de18

Habe bei jemandem in der Freundesliste einen Platz in der Blauen Galaxie belegt. Der Platz gibt 5 FP Belohnung, mit meiner Arche 7 FP. In der Infobox wurden mir vom FoE Helfer bei Fertigstellung jedoch 15 FP angezeigt.
https://i.imgur.com/CmZGflp.png

**Comment by Alpha-Centauri-B** [comment]
Bei mir tritt das Problem ebenfalls auf.

Beispiele:

- Galaturm Stufe 20 Platz 3: 25 FP + 12 FP (Arche), im FOE-Helper werden 7 FP angezeigt
- Castel del Monte Stufe 35 Platz 5: 5 FP + 2 FP (Arche), im FOE-Helper werden 52 FP angezeigt

**Comment by Alpha-Centauri-B** [comment]
Mir ist gerade aufgefallen, dass bei diesem Bug wohl die FP-Belohnungen zwischen Bauwerken verwechselt werden. Die eben angezeigte Anzahl an FP gehörte zu dem Bauwerk, bei welchem ich davor ebenfalls FP erhalten hatte.

**Comment by Gindi4711** [comment]
Should be fixed in next upate
