### ISSUE TITLE
Falsche Berechnung von limitierten Boni

### ISSUE THREAD

**Issue by Bluep** [mainIine/foe-helfer-extension#1911]
Hallo zusammen,

nachdem heute zum zweiten Mal in kurzer Zeit die Produktionsübersicht leicht falsche Werte angezeigt hat (Münzen), bin ich auf die Suche gegangen.

Ergebnis: Mein Markusdom war bereits gelevelt, die neue Aufladung aber noch nicht eingesammelt, weil noch gut 60 "alte Aufladungen" mit 5% weniger Boost vorhanden waren.
Der Helfer hat also beim Start den Bonus aus den citymap-entities eingelesen, statt den aktuellen aus BonusService.getLimitedBonuses  
Das letztere Servernachricht [vermutlich] eh für die Anzeige / Aktualisierung der anderen Boni wie Kraken, Frachter, Burg und Fitzelturm ausgelesen wird, wäre es wohl recht einfach, die aktuellen Boni quasi in Echtzeit abzugreifen und bei der nächsten Berechnung zu verwenden.
Wahrscheinlich ist es mit anderen Boni genauso? Also zumindest M/V, aber eventuell auch z.B. der Archen-Mäzenbonus? (Der läuft ja bei Inno auch als "limited" - kann ich aber nicht bestätigen, habe ich in letzter Zeit nicht gelevelt.)  

Zeugs fürs Protokoll:
Windows 10 64 Bit / Chrome 89.0.4389.90 x64 / de1 / 2.5.6.1 - Deutsch

**Comment by andrgin** [comment]
1.) Das Problem im Productions ist, dass man generell nicht weiß, ob für das Einsammeln einer Produktion ein Bonus verwendet werden wird oder nicht. Es gibt hier 2 Möglichkeiten:
a) Man hat noch Limited Boni, diese reichen jedoch nicht für alle Gebäude aus
b) Man hat keine LimitedBoni mehr, bekommt jedoch bis zum Einsammeln wieder welche (z.B. weil der Markusdom zuerst eingesammelt wird).

Man kann hier jetzt wahrscheinlich ziemlich lange Diskussionen führen unter welchen Konstellationen welche Verteilung der Boni nun am Wahrscheinlichsten ist mit den verschiedensten Ansätzen (höchste Münzproduktion zuerst, Durchschnittswert, bewerten nach Reihenfolge wann was fertig wird (was jedoch wieder nicht stimmt wenn alles gleichzeitig fertig wird) usw. Jeder dieser Ansätze wäre irgendwie falsch und das Ergebnis pro Tag stark schwankend.
Deshalb habe ich mich für die einfachste Lösung, dass davon ausgegangen wird, dass genug Boni vorhanden sind und den jeweils aktuellen Bonus der aktuelle Bonus des LG verwendet wird.

2.) Tatsächlich noch verbesserungsbedürftig ist jedoch, dass die aktuellen Werte beim Leveln des LG derzeit nicht aktualisiert werden und nur beim Laden des Spiels ermittelt werden. Ich werde mir einmal ansehen, wie viel Aufwand es wäre das zu fixen und ob sich der Aufwand lohnen würde.

**Comment by Bluep** [comment]
Die schönste Option fände ich eine Option ^^
Und zwar ein optionales "real time update" wie bei der Galaxie, so dass nach jedem Einsammeln die Tabelle aktualisiert wird. (Optional deshalb, weil die Neuberechnung auf langsameren PCs etwas länger dauert).

Und noch was wäre schön: Eine Checkbox, um nur fertige Produktionen (ggf. auch < 2 Minuten oder so) anzuzeigen - momentan mache ich das mit einem kleinen Scriplet manuell:
`javascript:jQuery("#ProductionsBody table > tbody > tr").not(".sorter-header").not(function() {return $("strong.success", this).length === 1;}).remove()`
... als Behelfslösung - weil die Produktionsübersicht eh manuell durch neu öffnen aktualisiert werden muss - ist das ok, sonst aber etwas brachial *g*

**Comment by andrgin** [comment]
1.) Es gibt im letzten Tab einen Filter für fertige Produktionen.

2.) Ein Auto Update der Productions ist etwas mühsam. Da müsste man denke ich einigen Code umbauen. Das Problem ist hierbei, dass man auch die ausgewählten Tabs und die Checkboxen beibehalten müsste.

**Comment by Bluep** [comment]
Ich fange mal hinten an ^^

2) Ich dachte an dasselbe Prinzip wie bei der Galaxie - dort wird auch die Tabelle bei jedem Einsammeln aktualisiert:
- die Option "Güterfaktor" bleibt erhalten <=> Tab und Sortierung werden temporär gespeichert
- alle Zeiten werden aktualisiert; war das eingesammelte Gebäude in der Liste wird es entfernt <=> Zeiten aktualisieren, Tabelle neu sortieren, mit Option "nur fertige" entsprechend andere ausblenden (CSS?)
- bei Prod.Übersicht => vergleiche zuletzt [für die Berechnungen] verwendete Boost-Werte mit denen, die zuletzt aus der Servernachricht abgegriffen wurden. Sind sie unterschiedlich, berechne auch die [betroffenen] Werte neu.

Ich hatte mir die Erweiterung vor einigen Wochen mal angesehen, in der Hoffnung dass ich selbst was beitragen könnte - leider hat die Zeit noch nicht gereicht, mich in a) die Feinheiten von Erweiterungen und b) in den modularen Aufbau des Helfers reinzufuchsen... ich bin eher der Vertreter "Userscript, tausende Zeilen Spaghetti in einer Datei, aber alles meins" * g *
Aber vielleicht wird es ja noch...

1) Dieser Filter (bzw. die Ansicht) bringt mir leider nichts. Ich drehe gerne Münz-Schleifen bei der Ernte, da hab ich den Münz-Tab der Prod.Übersicht offen, Ertrag absteigend sortiert (und per Scriplet gefiltert), um möglichst effizient die geforderte Quest-Menge zusammenzupuzzlen.
(Die größten kenne ich auswendig, aber bei Kleinvieh - oder wenn ein anderer Boostfaktor durch z.B. Taverne oder Münz-Trank ins Spiel kommt - ist die Übersicht sehr nützlich. Fast perfekt, wenn man sie nicht immer schließen und neu öffnen müsste ^^)
