### ISSUE TITLE
Falsche Ereignisse (zweispurige Strasse)

### ISSUE THREAD

**Issue by Alpha-Centauri-B** [mainIine/foe-helfer-extension#1914]
Ich bin gerade vom Industriezeitalter in die Jahrhundertwende gewechselt. Nun werden im Ereignisfenster 4 Ereignisse auf einer zweispurigen Straße angezeigt, obwohl ich noch gar keine zweispurigen Straßen gebaut habe: 3 Bäume (incident_fallen_tree_2x2) und 1 incident_pothole_2x2.

**Comment by Alpha-Centauri-B** [comment]
![Ereignisse](https://user-images.githubusercontent.com/80858070/111651540-37a5fc80-87fe-11eb-9aca-767726544f7e.png)

**Comment by outoftheline** [comment]
das liegt daran, dass es diese ereignisse auch gibt. 
ab jahrhundertwende bis einschließlich arktische zukunft werden vom spiel ereignisse auf 2 spurigen straßen erstellt, egal ob man welche hat oder nicht. wir zeigen diese nur an.

**Comment by andrgin** [comment]
Also e8nfacher gesagt: Bau eine 2 spurige Straße und lade das Spiel neu, dann tauchen die Ereignisse auf ;-)
