### ISSUE TITLE
Idee: Questabschluss-Notification in Gildengefechten

### ISSUE THREAD

**Issue by FalkoVPart** [mainIine/foe-helfer-extension#1915]
Moin,

ich habe das "Problem", dass ich im Asteroidengürtel immer die Schleifenquests mache, wo gekämpft werden muss. In den Gildengefechten, sieht man jedoch nirgendwo die Quests, weshalb man auch nicht mitbekommt, ob man durch diesen Kampf jetzt eine abgeschlossen hat, was regelmäßig dazu führt, dass man mehr Kämpfe macht, als notwendig, weil man noch weiterkämpft, obwohl die Quests bereits abgeschlossen sind, was wiederum Ressourcen und Zermürbung verschwendet.

Ich habe mir also gedacht, ob es nicht möglich wäre, in den GG eine zusätzliche kleine Notification zu haben, die grün wird, sobald eine Quest abgeschlossen wird, ähnlich wie der kleinen Anzeige, wie viele Effekte der Burg Himeji man noch hat. Alternativ könnte sogar angezeigt werden, wie viele Quests abgeschlossen sind. Ein Beispielbild habe ich angehängt.

Die Informationen, ob nach einem Kampf eine Quest abgeschlossen wurde, kann zu mindestens ausgelesen werden. Nach jedem Kampf kommt eine JSON-Response, die unter anderem ein Update des QuestService enthält. Dort könnte man bspw. einmal alle Quests durchgehen und zählen, bei wie vielen der state="collectReward" ist.

Würde mich sehr freuen und mir und vielleicht auch ein paar anderen Leuten sehr helfen in den GG zu Schleifen.

Beste Grüße
Falko

Konzeptbild:
https://ibb.co/HDnDwHX
JSON-Location:
https://ibb.co/JBncmMJ

**Comment by FalkoVPart** [comment]
Hey @andrgin ,
ich habe gerade das neuste Update installiert und das Symbol für die Quests in den GG ist auch vorhanden, allerdings ändert sich dies nicht nach den Kämpfen. Auch wenn die JSON-Updates vom Server kommen und Quests mit state="collectReward" enthalten.

![FoE-Helper Questupdate in GG](https://user-images.githubusercontent.com/40738463/112005458-122d3180-8b23-11eb-9f3e-f825fc3f6289.png)

Beste Grüße
Falko

**Comment by andrgin** [comment]
Ich sehe schon das Problem. Wir haben noch keinen Code für "aus rot mach grün+Zahl einblenden", sondern nur für "aus grün mach rot+Zahl ausblenden", da die Limited Boni ja nur runter zählen können und nicht rauf.

Ich lasse mir da morgen was einfallen.
