### ISSUE TITLE
GB calculator

### ISSUE THREAD

**Issue by Pumbaa672** [mainIine/foe-helfer-extension#1921]
With the Flying Island open, I can not open the GB calculator tool.  And when I have it open from another GB, it does not change to the Flying Island when I open that GB.

I looked and did not see anyone else posting about this issue, but I might have missed it.

Thanks.

Version 2.5.6.1
World zz1
Windows Chrome both running current versions.

**Comment by frank42hh** [comment]
Hmmm, sounds like Beta Server. Perhaps that's the problem, this GB is not yet known to the calculator.

**Comment by dsiekiera** [comment]
Correct, we have no data for it.
