### ISSUE TITLE
City planner buildings disappear!

### ISSUE THREAD

**Issue by TheCreatrix** [mainIine/foe-helfer-extension#1926]
Hello, I just redesigned my city and when I copied it to try another design, the city planner got weird.  The buildings started overlapping on the sidebar when I removed them manually, and when I clicked remove buildings they all disappeared, except for the bits of road that were left over from the first city plan.  Then when I sorted by Great Building everything vanished. 
![Bug report remove buildings](https://user-images.githubusercontent.com/81334886/112395864-91fafd80-8cd5-11eb-9dd6-9c0d022ec93b.png)
![Bug report buildings vanished](https://user-images.githubusercontent.com/81334886/112395887-97f0de80-8cd5-11eb-88ab-89722cc37f9d.png)

**Comment by TheCreatrix** [comment]
I'm using Firefox 87.0 on Windows 10 Pro v. 1909
64-bit

**Comment by TheCreatrix** [comment]
You closed this with no explanation or resolution?  Was it fixed?  Sheesh!

**Comment by outoftheline** [comment]
If you want to, I can reopen it. I am not involved with anything website related, but there have been a few updates in the meantime, so I was hoping this issue has been resolved by now.
