### ISSUE TITLE
Chat button does not work

### ISSUE THREAD

**Issue by pippo73** [mainIine/foe-helfer-extension#1929]
Hi, I don't use it much, but just to emprove your great app, I would like to notify you that pressing the **"chat to all button"** (chat live della gilda) nothing happens.

![2021-03-26 09_02_09-](https://user-images.githubusercontent.com/757121/112600991-28343e00-8e12-11eb-8f27-877d25b42902.png)

**Comment by outoftheline** [comment]
Which browser are you using?

**Comment by pippo73** [comment]
Firefox, but if you want, I can try with Chrome or edge

**Comment by andrgin** [comment]
Can you please use the bug report template:
https://github.com/dsiekiera/foe-helfer-extension/issues/620
