### ISSUE TITLE
Guild Battleground Attrition Reduction

### ISSUE THREAD

**Issue by Norton5150** [mainIine/foe-helfer-extension#1930]
It would be nice on the Guild Battleground Helper if it showed Attrition reduction in a sector from it's adjacent sectors.

Example on the timer tab, if if showed that a sector that was about to open in xx minutes, it told you the 3 sectors you currently own that touch will provide an 72% reduction (3 SC).

**Comment by outoftheline** [comment]
This information is only available (=transmitted to the browser) when you open the building slots of a province, so we cannot display it in advance.

**Comment by Norton5150** [comment]
Too bad, thanks for looking into it.
