### ISSUE TITLE
Comments / Notizen buggy

### ISSUE THREAD

**Issue by G-Bigo** [mainIine/foe-helfer-extension#1934]
The comments function within FoE helper is buggy.

Three errors I noticed recently:

(a) After adding more than 6 neighbors at one stroke it is impossible to enter anything in the comment area. Completely closing and reopening the the comment area clears this issue, but it shouldn't happen at all.

(b) After having opened, added a neighbor and closed the comment function several times, adding a new neighbor resulted in him being added several times. It gets more when repeating the procedure.

(c) The status prompt in the upper right is wrong. After adding a neighbor it states 'neighbor: false'

I'm playing on server de12 using the German language overlay.

-----

Die Notiz-Funktion des FoE-Helfers enthält Bugs.

Drei Fehler, die ich kürzlich beobachtet habe:

(a) Nach Hinzufügen von mehr als 6 Nachbarn in einem Rutsch ist es unmöglich, irgendwas in den Notizbereich zu schreiben. Schließen und erneutes Öffnen der Notizen behebt dies, aber es sollte gar nicht erst passieren.

(b) Wiederholtes Öffnen, Hinzufügen und Schließen der Notizen führte dazu, dass beim Hinzufügen eines neuen Nachbarn dieser mehrfach hinzugefügt wurde. Um so mehr Auftreten, je häufiger dies wiederholt wurde.

(c) Die Status-Anzeige oben rechts ist fehlerhaft. Nach Hinzufügen eines Nachbarn erscheint dort: 'neighbor: false'

Ich spiele auf dem Server de12 in deutscher Sprache.

**Comment by Aberhubert** [comment]
Ich kann im Notizblock keine einzige Gruppe anlegen. Der Fehler tritt aber nur auf einer Welt auf - in den anderen funktioniert es wunderbar :?
