### ISSUE TITLE
City Planer import no longer working

### ISSUE THREAD

**Issue by WulfgarCA** [mainIine/foe-helfer-extension#1936]
Hi team,
i am trying to use the city planer on the webpage which i have don multiple times. But now after I hit the tansferbox ingame and i switch to the webpage login and want to create a city with my city data, it always uses and old version of my city.
I did try a new browser profile and used the newest version of foe helper:

Beispiel / Example:
Windows 10 64 Bit
Edge Version 89.0.774.63 (Official build) (64-bit)
de10 (Korch)
Version
2.5.6.3 Deutsch
Player ID: 9890584
Guild ID: 6034
World: de10

Thanks for the good work!

**Comment by dsiekiera** [comment]
I cannot confirm this. I just tried it directly and was able to load my new city immediately.

**Comment by SpellfireCA** [comment]
Did you use it peviuously? Or did you have old cities saved? It does work for some of us in the guild but i know at least two others in my guild were it doenst work. I also saw a guy on discord he mentioned he had the same issue.

**Comment by mainIine** [comment]
Both. I can use older savings or send a new one (change a building position) to the server too. I will include a small debug to uncover any error.

**Comment by mainIine** [comment]
One question first. If the transmission box was used and the console is open beforehand, does a request to the server also appear?

![Bildschirmfoto 2021-04-06 um 12 06 03](https://user-images.githubusercontent.com/834814/113695025-b345eb80-96d0-11eb-9f55-bf06e97ed352.png)

**Comment by WulfgarCA** [comment]
Hi mainline,
i also tried todo some research in discord yesterday with Gindi and Slowalker.
I do see the api call and I also debug and the structure look filled:
![image](https://user-images.githubusercontent.com/11575228/113777562-1d19c180-96e0-11eb-8b81-f216d1b74112.png)
![image](https://user-images.githubusercontent.com/11575228/113777584-21de7580-96e0-11eb-8fcb-e0c454875077.png)

**Comment by WulfgarCA** [comment]
here also with status ok
![image](https://user-images.githubusercontent.com/11575228/113778549-64548200-96e1-11eb-9e0d-2c7a0aed78a1.png)

**Comment by Gindi4711** [comment]
Account specific issue and already solved.

**Comment by kuligramm** [comment]
Sorry, but I have the same issue, it's not solved.
I tried several browsers, several version of helper. Even with version 2.5.7.1 it is not working.
When opening the cityplanner I always see a town which was imported some weeks ago.
This seems to be a general problem.
Version 2.5.7.1
Spieler Id: 10447001
Welt: de21
