### ISSUE TITLE
Guild member overview

### ISSUE THREAD

**Issue by lafawnduh2015** [mainIine/foe-helfer-extension#1938]
I changed guilds Monday 29 mar 2021 and have reloaded the game many times. The Helper overview is still showing info from the guild I left instead of my current guild. I am a leader in my current guild, and was not in the one I left. 

https://prnt.sc/111zkg9

![Guild overview](https://user-images.githubusercontent.com/81785449/113369126-84c1bc80-932e-11eb-9735-69f680b2962f.png)

**Comment by danielvoigt01** [comment]
Thanks for reporting the issue. There was no check to see if the guild had been changed. This has now been added and all old members will be removed. Furthermore, an option was added in the settings to be able to delete ex members immediately.
