### ISSUE TITLE
Technologies window disappears when dragging to secondairy screen

### ISSUE THREAD

**Issue by JPHuls** [mainIine/foe-helfer-extension#1939]
Dear,

I've a dual screen setup and am playing FoE in the right screen. Today I accidentally dragged the Technologies Helper window too far to the left and it disappeared. It can't be moved back to the right screen. I've tried a new tab session, as well as restarting the Chrome browser but without success. Some of the other Helper windows (like Chat) can be moved without an issue to the left screen. Is this a bug and how to resolve it and get the Helper windows back?

Kind regards,

Jean-Pierre

My system info:
Windows:
   Edition	Windows 10 Pro
   Version	20H2
   Installed on	‎13-‎09-‎2020
   OS build	19042.867
   Experience	Windows Feature Experience Pack 120.2212.551.0

Google Chrome
   Version	89.0.4389.90 (Official Build) (64-bit)

FoE Helper:
   Versie:	2.5.6.3
   Speler-ID:	10397435
   Gilde-ID:	36
   Wereld:	us6
   Language:	dutch

**Comment by JPHuls** [comment]
I had to go into the developer pane and set the left CSS property from -728px to 0px to get it back. So I kind of found a workaround. Still it would be nice if the Helper addon takes proper care when dragging a window outside the screenborders.

**Comment by Th3C0D3R** [comment]
Chat is a separate Browser-Window.
everything else is just a box displayed on the foe webpage
