### ISSUE TITLE
Motivate/Polish Helper - add CSV export

### ISSUE THREAD

**Issue by PompDaddy** [mainIine/foe-helfer-extension#1945]
Hello.

If possible, could you please add CSV export buttons (one for each of the three tabs - Neighbors, Guild Members, and Friends), so that once we successfully fully populate the data, we can then easily import the data into a spreadsheet.  I am guessing this would be accomplished in the same manner as the CSV export button for the Guild Treasury Contributions (which, by the way, thank you so very much.  Very much appreciated).  Any and all data that can be included in the CSV is fine.  We can always clean up and "massage the data" after it has been imported into a spreadsheet.

Thank you for your time and consideration.
PompDaddy

**Comment by andrgin** [comment]
This has already been implemented in beta branch and will be released with the next update.

**Comment by PompDaddy** [comment]
Oops...  Didn't see that.  Good to hear.  Thank you for the prompt response. Closing ticket.
