### ISSUE TITLE
Berechnung "Blaue Galaxie Helfer"

### ISSUE THREAD

**Issue by Muckinator735** [mainIine/foe-helfer-extension#1948]
Es wäre nice, wenn in der Liste die Möglichkeit bestünde, auch Diamantenproduktion zu berücksichtigen.
Aktuell werden Diamanten komplett vernachlässigt, jedoch erachte ich die Ernte eines Gebäudes mit 8 FP und 25 Dias als wesentlich höherwertiger als die Produktion von 8 FP und 10 Gütern.

Kann man da was machen?

**Comment by andrgin** [comment]
Könnte man allerdings ist eine bevorstehende Diamantenproduktion eine Information, die nicht ohne Zusatzmittel oder Entwicklerkonsole im Spiel sichtbar ist und ein Feature, das diese Information gezielt ausnutzt könnte als "unfairer Vorteil" interpretiert werden. Besonders bei Premiumwährung sehen wir das als heikel an und haben uns deshalb dafür entschlossen dies nicht umzusetzen.

**Comment by Th3C0D3R** [comment]
Trotzdem ist es über einen zwischenschritt möglich die Blaue Galaxie auf ein Diamant-Gebäude zu nutzen, ;)

**Comment by Muckinator735** [comment]
Schon klar.
Nur vielleicht sollten wir diesbezüglich einfach den Mund halten und die Sache als "politisch nicht gewünscht" abhaken...
