### ISSUE TITLE
Guild members overview - (Przegląd członków gildi)

### ISSUE THREAD

**Issue by tpaciorek** [mainIine/foe-helfer-extension#1949]
Hi,
This is a great feature. However, if I would like to view all OBS from the guild. Who has which level. I need a lot of clicking. Could use some export of this data to CSV or something else.
Best regards, Pacior

**Comment by danielvoigt01** [comment]
In the next release, you will have the option to export the data for each selected tab. 
Example tab: Guild Buildings
![Auswahl_033](https://user-images.githubusercontent.com/46729881/116113823-27b0f080-a6b9-11eb-963d-27da7363f875.jpg)
![Auswahl_034](https://user-images.githubusercontent.com/46729881/116113826-28498700-a6b9-11eb-9665-a813f704e8f5.jpg)

**Comment by ecthelioni** [comment]
Hello
I find issue in this new funkcion. ecthelioni is my account. I think, that other guilds members are correctly.

![image](https://user-images.githubusercontent.com/60727513/118924463-6bf08300-b93d-11eb-81a3-b6c317ada22a.png)
![image](https://user-images.githubusercontent.com/60727513/118924616-a22e0280-b93d-11eb-85e3-d7c2476c311d.png)

**Comment by danielvoigt01** [comment]
Yes I see it, I will have a look.

**Comment by danielvoigt01** [comment]
I think I've got it. It only affected your own buildings. Since you are using the beta branch, can you please test it again on your end?

**Comment by ecthelioni** [comment]
It is same

![image](https://user-images.githubusercontent.com/60727513/118949329-64d76e00-b959-11eb-9d45-95e2c615ba0d.png)

**Comment by danielvoigt01** [comment]
I've revised it once again. Can you try it again please?

**Comment by ecthelioni** [comment]
I find new issue ;-), Eras section not  working

![image](https://user-images.githubusercontent.com/60727513/119029831-70528580-b9a9-11eb-9f2d-d90883b8c18f.png)

**Comment by danielvoigt01** [comment]
I couldn't reproduce this. Can you open developer console in browser (Ctrl + Shift + i or F12) whether an error is displayed there.

**Comment by ecthelioni** [comment]
Hello,
I find one more small issue in this new funkcion.
I have 8x Statue of Honor (Socha cti) in Future Era (Budoucnost) and 3x Statue of Honor in Arctic Future Era. 
On the GuildBuldings tab I see correctly 3x  Statue of Honor in Arctic Future Era but only 7x Statue of Honor in Future Era
I think, that other members of guild are correctly.

![image](https://user-images.githubusercontent.com/60727513/119223418-9edf7600-baf9-11eb-8e28-79e29a9c31ca.png)
![image](https://user-images.githubusercontent.com/60727513/119223437-b880bd80-baf9-11eb-8922-7c7ab0acbc7b.png)
