### ISSUE TITLE
Stadtdaten werden nicht übertragen

### ISSUE THREAD

**Issue by Omega-die-Grosse** [mainIine/foe-helfer-extension#1950]
Seit ca 2 Wochen werden meine Stadtdaten nicht mehr an den Stadtplaner nicht übertragen.

**Comment by mainIine** [comment]
Dann benutzt du nicht den originalen FoE Helfer.

**Comment by xorxus** [comment]
Hallo,
ich habe das gleiche Problem. habe es in Chome und  Opera versucht mit aktueller FOE-Helper Version.
Es wird immer eine Stadt von vor ein paar Wochen angezeigt.
Woran könnte es liegen?
Danke für einen Tip.

Gruß

**Comment by Asrael01** [comment]
Möchte mich dem Posting anschliessen, Stadtdaten werden offensichtlich nicht übertragen:
Browser: Opera mit Chrome Extension
FOE-Helper: Version 2.5.6.3
Spieler Id: 7733581
Gilden Id: 14133
Welt: de16

**Comment by Omega-die-Grosse** [comment]
Ich benutze den Original Foe Helfer mit der neusten verfügbaren Version. Daran kann es nicht liegen.  Wäre schön, wenn es wieder funktionieren würde

**Comment by xorxus** [comment]
Das Problem ist, wenn du dich nur einmal mit einer Version eingeloggt hast,
die nicht offiziell oder zu sehr veraltet ist, ist dein FOE Helper Account
gesperrt. Da hilft es auch nicht, danach wieder den offiziellen Helper zu
installieren.
Der Account muss einmal wieder entsperrt werden.

Omega-die-Grosse ***@***.***> schrieb am Sa., 17. Apr. 2021,
17:08:

**Comment by Omega-die-Grosse** [comment]
Oh, das wusste ich nicht, ich hoffe, ich hab jetzt überall die neuste Version an. Könntest du mich bitte wieder aktivieren?

**Comment by andrgin** [comment]
Für accountspezifische Supportfälle meldet euch bitte auf Github. Da können wir das Problem in einem privaten Chat lösen ohne dass ihr eure Spielerdaten hier öffentlich posten müsst:
https://discord.gg/z97KZq4
