### ISSUE TITLE
Keine Übertragung der Stadt-Daten trotz aktueller Version

### ISSUE THREAD

**Issue by xorxus** [mainIine/foe-helfer-extension#1953]
Hallo,

seit ca. 2-3 Wochen werden die Stadtdaten nicht mehr übertragen. Die Übertragungsbox zeigt keine Fehler, aber es wird später immer eine alte Stadt-Version angezeigt.
Ich habe sicherheitshalber die FOE-Helper Extension komplett in Chrome deinstalliert neu gestartet und die aktuelle Version wieder installiert.

Auch in Opera und Firefox zeigt sich das gleiche Problem.

Danke für einen Tipp, was zu tun ist.

Bilder angehängt.

Gruß.
![01](https://user-images.githubusercontent.com/82369298/114373512-f3024c80-9b82-11eb-8a07-e3e53ecb058a.jpg)
![02](https://user-images.githubusercontent.com/82369298/114373526-f695d380-9b82-11eb-9552-db9060bf0072.jpg)

**Comment by xorxus** [comment]
zur Info:
Ein Freund hat sich auf meinem Rechner mal mit seinem Account eingeloggt. Bei ihm funktioniert es.
Es scheint also irgendwie an meinem Account zu liegen.
Soweit ich es sehen konnte, sind die Einstellungen im FOE-Helper die gleichen.

Gruß

**Comment by outoftheline** [comment]
Gib mal bitte deine Spielwelt und deine Spieler-ID durch :)

**Comment by xorxus** [comment]
Hallo,
kann ich auch persönlich direkt auf die E-Mail antworten?

Ich versuche es mal.

Spieler ID: 10019295
Vingrid

Gruß

Am Mo., 12. Apr. 2021 um 16:08 Uhr schrieb Yvi ***@***.***>:

**Comment by xorxus** [comment]
Hallo,
kann man auch persönlich darauf antworten oder nur hier öffentlich? :-)

Gruß

**Comment by outoftheline** [comment]
Hier nur öffentlich, persönlich im Discord

**Comment by xorxus** [comment]
Spieler ID: 10019295 Vingrid

**Comment by bthau** [comment]
Ich habe genau das selbe Problem

**Comment by bthau** [comment]
Spieler ID: 3256902 Greifental

**Comment by outoftheline** [comment]
Sorry, hat ein bisschen gedauert. Es musste noch was vorbereitet werden, damit ich mir das anschauen kann.

Also folgendes: Eure Stadtdaten werden nicht übertragen, weil eure Accounts gesperrt sind.
Das hat folgenden Grund: Wir bieten unsere Funktionen auf der Website generell nicht für Drittanbieter an.

Wir können Ausnahmen machen, wenn mit dem Anbieter des Forks folgendes abgestimmt ist:
a) Es ist abgesprochen wann bzw. wie oft welche Daten gesendet werden. Beispielsweise darf es keinen automatischen Stadt-Upload bei jedem Start geben.
b) Die Extension muss sich an die aktuelle Auslegung der Spielregeln von InnoGames halten. Wenn sie Features enthält, die wir bereits in ähnlicher Form entfernen mussten, dann verstößt sie definitiv dagegen.

**Comment by xorxus** [comment]
OK, ich habe einen Moment gebraucht, bis ich verstanden habe, was damit gemeint ist - jetzt hat es Klick gemacht.
Ich habe im Firefox scheinbar eine Version, die gar nicht von Euch stammt, bzw. modifiziert ist - das war mir so nicht bewusst.

Wenn ich diese Firefox-Extension sofort entferne und ab jetzt nicht mehr einsetze, wärt Ihr dann bereit, die Account-Sperre wieder aufzuheben? Mir ist die gar nicht so wichtig, habe sie nur aus Gewohnheit verwendet und deinstalliere sie sofort, wenn ich dafür wieder den Stadtplaner nutzen kann.

Danke für eine kurze Info.
Gruß

**Comment by outoftheline** [comment]
Ja, sag Bescheid, ich geb deinen Account dann wieder frei!

**Comment by xorxus** [comment]
Ist hiermit geschehen. Extension wurde deinstalliert.
Danke für Deine Hilfe.

**Comment by outoftheline** [comment]
Erledigt!

**Comment by xorxus** [comment]
Perfekt. Geht wieder!
Danke.

**Comment by bthau** [comment]
Ich denke, bei mir ist das Problem das gleiche. Die Extension habe ich jetzt deinstalliert. Wäre super, wenn ihr mich wieder freischaltet - vielen Dank

**Comment by Th3C0D3R** [comment]
> 
> 
> Ich denke, bei mir ist das Problem das gleiche. Die Extension habe ich jetzt deinstalliert. Wäre super, wenn ihr mich wieder freischaltet - vielen Dank

Erledigt

**Comment by xorxus** [comment]
Könnt Ihr das bitte auch noch für meinen Account auf dem Betaserver wieder freischalten?
Danke.

**Comment by outoftheline** [comment]
@xorxus beta hat nochmal eine andere ID, bitte die nochmal durchgeben. zz1 ist klar :)

**Comment by xorxus** [comment]
ok: 
249205
