### ISSUE TITLE
Stadtdaten werden nicht übertragen

### ISSUE THREAD

**Issue by Asrael01** [mainIine/foe-helfer-extension#1954]
Hallo,
Ich hab den FOE-Helper vor ca 7 Tagen heruntergeladen und installiert.
Nun wollte ich meine Stadt effizienter gestalten und umplanen, aber meine Daten werden offensichtlich nicht übertragen.

Betriebssystem: Windows 10 64 Bit
Version: 10.0.19041
Browser: Opera Version:75.0.3969.171
Chrome Extension 2.5.9
FOE-Helper: Version 2.5.6.3
Spieler Id: 7733581
Gilden Id: 14133
Welt: de16

LG
Asrael01

**Comment by Asrael01** [comment]
hm, interessiert wohl niemand hier?

**Comment by Asrael01** [comment]
Ich verwende für das Spiel nur Opera, jedoch habe ich auch Edge für was anderes in Verwendung.
Firefox ist zwar installiert, wird aber nicht verwendet, weil er ziemlich buggy ist.
Opera wird automatisch aktualisiert, der läuft an sich ziemlich problemlos.

**Comment by andrgin** [comment]
Ich habe dir das Konto wieder freigeschaltet.

Extrem alte Versionen (vor Mitte 2020) enthalten Features, die mittlerweile von Inno verboten wurden und in der aktuellen Version entfernt sind (z.B. Verhandlungsassistent in den GG, Plünderfeatures etc.)

Da wir nicht warten wollen, bis Inno mit der großen Bannkeule wieder einmal uns alle trifft haben wir uns entschlossen hier präventiv vorzugehen und selbst allen Spielern, die alte Versionen mit verbotenen Features oder manipulierte Versionen, die nicht von uns stammen den Zugang zu unseren Servern zu sperren.

In Fällen wo der Einsatz dieser Versionen unabsichtlich passiert ist bieten wir an, den Account wieder zu entsperren, was ich in deinem Fall gerade getan habe. Das ist jedoch pro Spieler nur einmal möglich.

**Comment by Asrael01** [comment]
Ah, ok, das wußte ich nicht, daß diese ältere Version des Helpers gegen irgendwelche Regeln verstieß.
Zudem habe ich die schon ewig lange nicht mehr benutzt, da wie gesagt, Firefox buggy war und der ausgeschieden wurde.
Wird die neue Version des Helpers automatisch aktualisiert, oder muß ich da auf was achten?
Nicht, dass sowas noch einmal passiert, immerhin war da beim ersten mal auch keine Absicht dahinter.

LG
Asrael

**Comment by Gindi4711** [comment]
Ich benutze Opera zwar nicht aber eigentlich sollten sich alle Erweiterungen automatisch updaten genauso wie bei Chrome.
Bei Firefox kann man automatische Updates ausschalten, was du wahrscheinlich getan hast.

**Comment by Asrael01** [comment]
Ok, habs grad mitbekommen, Opera hat mich gefragt, ob ich ein Update zulassen möchte, damit ist diese Frage beantwortet, danke! 😊
