### ISSUE TITLE
Stadtplaner: Button "Copy citymap data" kopiert nichts in die Zwischenablage

### ISSUE THREAD

**Issue by xorxus** [mainIine/foe-helfer-extension#1955]
Hallo,

nach dem Drücken des Buttons "Copy citymap data" dauert es zwar etwas länger, aber irgendwann erscheint die Infobox, dass die Daten in den Zwischenspeicher kopiert wurden.
Allerdings sind danach keine Daten im Zwischenspeicher vorhanden.

Woran kann das liegen?

Danke und Gruß.

**Comment by outoftheline** [comment]
Die Daten sind für ein externes Tool, was genau möchtest du damit machen?

**Comment by xorxus** [comment]
Nichts Konkretes. Mich hatte einfach interessiert, was da ausgespuckt wird.
Habe mittlerweile festgestellt, dass der Export über Firefox funktioniert.
Bei Chrome und Edge funktioniert es nicht.

Gruß.

**Comment by cjust1** [comment]
I have this same issue.  The export works in Firefox, but not in Chrome.
