### ISSUE TITLE
Verhandlungsassistent öffnet sich bei Gildengefechten nicht

### ISSUE THREAD

**Issue by Pakuna** [mainIine/foe-helfer-extension#1956]
Weder unter Chrome noch unter Firefox öffnet sich der Verhandlungsassistent, wenn eine Verhandlung in einem Gildengefecht gestartet wird. Das nur bei mir so? Werden weitere Infos benötigt? :)

![2021-04-15 GVG Verhandlungsassistent](https://user-images.githubusercontent.com/2675994/114845005-44a11600-9dd3-11eb-9b8e-935f4446fbe1.jpg)

**Comment by outoftheline** [comment]
Nein, das ist so korrekt. Der Assistent funktioniert an dieser Stelle nicht, weil InnoGames sagt das gibt einem einen unfairen Vorteil (zB durch Schnelligkeit, überlegen fällt weg) anderen gegenüber.

**Comment by Pakuna** [comment]
Okay, verstanden! Vielen Dank für die schnelle Rückmeldung :)
