### ISSUE TITLE
GB Calculator doesn't work with new GB - Flying Island

### ISSUE THREAD

**Issue by NickRing** [mainIine/foe-helfer-extension#1961]
Hi,
If the GB Calculator is opened, while I am viewing my Flying Island GB, it doesn't open correctly.
If I view my Arc, and then open my GB Calculator, it opens correctly. Closing my Arc and opening my Flying Island doesn't update the display (as it still contains the information for my Arc).

Guessing, it is missing X_SpaceAgeVenus_Landmark1 from 
https://github.com/mainIine/foe-helfer-extension/blob/master/js/web/greatbuildings/js/greatbuildings.js#L59

**Comment by andrgin** [comment]
This has been fixed with todays update 2.5.6.4

Greatbuildings.js only contains data of great buildings producing FP or goods that are supported by the GB investments module (the one giving suggestions which GB you should do next for best ROI).
