### ISSUE TITLE
Tonausgabe abstellen

### ISSUE THREAD

**Issue by Rondrasil** [mainIine/foe-helfer-extension#1965]
Der neu eingeführte Signalton bei Erledigung einer Schleifenquest wenn man in GG kämpft.... der nervt extrem.

Jegliche Tonausgabe der extension muss unbedingt deaktivierbar sein! Leider habe ich keine entsprechende Funktion gefunden.

Vermutlich bin ich in diesem Forum falsch mit meinem anliegen, aber ich wusste nicht wo ich das sonst am besten platzieren kann.

Ansonsten natürlich grosses Lob für die tolle Arbeit. Nur bitte stellt das "Pling" ab. :-(

**Comment by Gindi4711** [comment]
Ab dem nächsten Update gibt es eine globale Einstellung zum Deaktivieren aller Soundausgaben im Helfer
