### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by IngweLand** [mainIine/foe-helfer-extension#1966]
Got a null reference exception (or whatever it's called in Javascript). As the result - the game hangs and has to be reloaded. I think, that you must add all possible checks so in a worse scenario, the extension will not block the game.
![image](https://user-images.githubusercontent.com/3942153/115196330-75958980-a0f8-11eb-8396-4c061e5c5229.png)

**Comment by outoftheline** [comment]
how did you trigger the error?
latest version on chrome i guess?

**Comment by IngweLand** [comment]
Yes. Updated today. If i recall correctly, i got it when returning from GE screen

**Comment by IngweLand** [comment]
I would strongly suggest to wrap all your code in try/catch blocks. That's not a brilliant practice in general, but this will avoid game hang/crash.

**Comment by outoftheline** [comment]
this is the first time this ever happened iirc. we'll have to have a look. 
i clicked around on beta for a bit, but had no luck triggering the error.

**Comment by IngweLand** [comment]
That's not the first time the game hangs for me. While I have not checked the reasons before, I am pretty sure that happened because of extension (as it started happening after I installed it)

**Comment by Gindi4711** [comment]
This is an exception caused by Inno. I have seen the same exception in my game as well, but I dont know Inno code enough to have an explanation why this happend.

The reason why it gets logged into the console is because we have a listener to all exceptions thrown in the game.
