### ISSUE TITLE
Cannot see my actually town data

### ISSUE THREAD

**Issue by Trahorn** [mainIine/foe-helfer-extension#1968]
hello, when I start to send my town data to Foe-helper, alway I see an earlier town. Not my actually. What can I do? It ist only my town on Noarsil. Also when I want to use my info-pad I get the message, open a new group. The i named it doit for Friends, but i cannot save. I tried it with Microsoft Edge, Chrome and firefox. I cannot do it by all these diffrent programs

**Comment by cjust1** [comment]
I am also having this same issue.  It was reported by another user 14 days ago and is under investigation.  It appears that it is not impacting everyone.
When I watch the console during submit, I can see the Post to the server and it is populated with the city data.    I get an 'OK' status, but I do not receive the 'process' in the status return.

**Comment by Gindi4711** [comment]
You have been banned from using our servers for using versions that contain features violating the current game rules.

Make sure you remove those versions and contact us on our discord channel so we can remove the ban. This will only be done once per player.

**Comment by Trahorn** [comment]
Hello, Icannot use discord, because i don't know discord. Also I habe problem to use Github. Is there any reason to remove the ban with mail ?
