### ISSUE TITLE
Opera meldet Fehler

### ISSUE THREAD

**Issue by Asrael01** [mainIine/foe-helfer-extension#1969]
Hi,
nach dem Update kam folgendes:
![Fehler](https://user-images.githubusercontent.com/82448638/115236303-8277a480-a11b-11eb-8ac7-147531acd178.png)
![Fehler1](https://user-images.githubusercontent.com/82448638/115236329-8acfdf80-a11b-11eb-9961-947ddac1ceb8.png)

Ich kenne mich mit js nicht aus, kann also nix genaueres dazu sagen....

LG
Asrael

**Comment by Gindi4711** [comment]
1.) Denselben Fehler hatte ich auch im Log jedoch war dieser nicht reproduzierbar. Ich vermute einmal, dass dies während dem Updatevorgang passiert ist.

2.) StrategyPoints ist die Anzeige des FP Lagers oben in der Leiste. Wird die bei dir noch korrekt angezeigt?

**Comment by Asrael01** [comment]
Ja, habs nachgerechnet, die Anzeige stimmt mit der Realität überein.
