### ISSUE TITLE
Infobox odd behavior with ">" and "<" in chat titles

### ISSUE THREAD

**Issue by webmosher** [mainIine/foe-helfer-extension#1972]
I'm seeing HTML entities going a bit berserk in the Infobox.  See attached images. 
![image](https://user-images.githubusercontent.com/17073137/115331224-c1751c80-a152-11eb-86f3-cb569ae10feb.png)

Actual guild titles included as well. 
![image](https://user-images.githubusercontent.com/17073137/115331336-f7b29c00-a152-11eb-9ca0-b6b16027ba00.png)

**Comment by sdn-br** [comment]
Have a fix for it ready
