### ISSUE TITLE
Infobox: posts in der Box mit Link zum post im Thread

### ISSUE THREAD

**Issue by elGaitano** [mainIine/foe-helfer-extension#1974]
Die Infobox ist ja ein sehr nützlicher Helfer um schnell über alle neuen posts der Gilde informiert zu werden. Die Hilfe wäre aber deutlich höher, wenn diese posts durch einen Klick in der Infobox direkt aufrufbar wären.

**Comment by outoftheline** [comment]
Wir können nur Informationen darstellen, keine Spielfunktionen steuern.
