### ISSUE TITLE
Export aus Handel fehlerhaft

### ISSUE THREAD

**Issue by TribbleFun** [mainIine/foe-helfer-extension#1975]
Die Exportfunktion aus dem Handel (sehr cool, super Sache) hat leider einen Fehler und gibt nicht den Bedarf aus, sondern zwei Mal das Angebot. Das CSV sieht so aus (Namen ausgekreuzt):

Offered goods;Offered amount;Offered goods;Offered amount;Rate;Player
Eisen;5;Eisen;5;1;xxx
Ebenholz;75;Ebenholz;75;0,67;xxx
Juwel;75;Juwel;75;0,67;xxx
Eisen;75;Eisen;75;0,67;xxx
Marmor;40;Marmor;40;0,5;xxx

**Comment by Gindi4711** [comment]
Du hast Recht. Kleiner Copy Paste Fehler.
