### ISSUE TITLE
Gilden Mitglieder Übersicht zeigt auch Mitglieder aus alter Gilde

### ISSUE THREAD

**Issue by TribbleFun** [mainIine/foe-helfer-extension#1978]
Macht man die Liste auf, dann sind da auch Mitglieder aus alten Gilden enthalten.

**Comment by danielvoigt01** [comment]
Welche Version des Helpers benutzt du?
Generell sollte in der aktuellen Version automatisch überprüft werden, ob die eigene Gilde noch mit den Mitgliedern übereinstimmt und wenn nicht, die Liste aktualisieren und ehemalige Gildenmitglieder entfernen.

Du kannst alternativ auch über das Einstellungsmenü der Box bei "lösche Ex-Mitglieder" auf "sofort" stellen, dann werden die ehemaligen Mitglieder auch entfernt.

**Comment by TribbleFun** [comment]
2.5.7.1 auf Firefox
