### ISSUE TITLE
Eigenanteilsrechner - eigene LGs

### ISSUE THREAD

**Issue by G-Bigo** [mainIine/foe-helfer-extension#1980]
Der Eigenanteilsrechner für den Preis von Plätzen in eigenen LGs (Extension) spinnt bei mir gerade.

Im Cape Canaveral Stufe 26->27 stecken 104 FP EA sowie 618 FP (93% Förderung) für P1.
Auf der Website 
https://foe-helper.com/ownpart/index
wird für P2 bei 93% Förderung korrekt 309 FP angezeigt.

Die Extension schlägt dagegen 614 FP für P2 vor und merkt korrekterweise noch an, dass das 305 FP Überzahlung wären.

![FoE-Helfer_EA-Rechner](https://user-images.githubusercontent.com/37943206/115950664-f24fab80-a4dc-11eb-98fe-a1ebb7c41106.jpg)

??!?

**Comment by Gindi4711** [comment]
P1 hat 4 FP zu wenig bezahlt. Der EARechner geht also davon aus, dass P1 gesniped wurde und versucht diesen hinunter zu drängen, was auch noch möglich ist, da dieser nicht safe ist.
Du hast nun folgende Möglichkeiten:
.) Wenn es tatsächlich ein Sniper war: P1 um 1 Platz auf P2 hinunter drängen, P1 vergeben und das LG ohne Eigenanteil leveln, so wie es der Helfer vorgeschlagen hat.
.) P2 darauf hinweisen, dass er 4 FP zu wenig gezahlt hat.
.) Im EARechner die 93 von P1 auf 92 korrigieren und dann wird dir der EARechner vorschlagen 8FP Eigenanteil drauf zu legen um P1 abzusichern.
