### ISSUE TITLE
Export Handel in XLS oder CSV

### ISSUE THREAD

**Issue by wildwillem** [mainIine/foe-helfer-extension#1982]
Die Exportfunktion aus dem Handel gibt keine anzeigen in XLS und CSV .
Ebenfall ist die auftrag der Waren falsch.    Eisen vor dem Juwel, oder Albast vor dem Kopfer.

**Comment by Gindi4711** [comment]
Ich habe zwar kein Wort verstanden aber ich vermute du meinst diesen Bug: https://github.com/mainIine/foe-helfer-extension/issues/1975

**Comment by wildwillem** [comment]
Sorry for the bad translation.   
The problem with the export of Guild good is mentioned, but is the difference of  the order of the good in FOE en FOEhelper know?
In Foe the order is  Doek ; Ebbenhout ; Juwelen ; IJzer ; Kalksteen.  In the XLS sheet it is: Doek ; Ebbenhout ; **IJZER** ; **Juwelen** ; kalksteen.  So the order is different.
![image](https://user-images.githubusercontent.com/83128464/115967445-f9a1a400-a532-11eb-9620-c12d5b88d43b.png)
![image](https://user-images.githubusercontent.com/83128464/115967774-c102ca00-a534-11eb-8fb2-5056bbe59a62.png)

**Comment by Gindi4711** [comment]
OK now I see the problem. Goods order has been hardcoded in the Stats module and does not match the ingame order.

**Comment by wildwillem** [comment]
Hello Daniel,

the problem still exist.  In the xls sheet generated in  Statistic / all
guild goods in treasury, the order of display of the guild goods is
different to the order of guild goods in treasury as presented by FOE.
The update did do a change in order, but is still the wrong order of
display.
stay healthy    Willem

Op ma 24 mei 2021 om 15:12 schreef Daniel Siekiera ***@***.***
