### ISSUE TITLE
Stadtdaten Fehler

### ISSUE THREAD

**Issue by cepastscho** [mainIine/foe-helfer-extension#1983]
Hallo, bei dem FOE Helper werden meine Stadtdaten anscheind nicht übermittelt. 
Bei einer neuen Stadt zeiht er sich immer die Stadtdaten die ich bei meinem letzten Umbau benutzt hatte.
Habe das Problem sowohl bei Chrome wie auch bei Firefox. Auch der Server scheint egal zu sein.

**Comment by Gindi4711** [comment]
Du hast dir einen Bann eingefangen weil du eine veraltete oder manipulierte Helfer Version eingesetzt hast.

Geh am Besten in unseren Discord und schreibe da einen der Entwickler an, damit wir dich freischalten. Das machen wir allerdings nur einmal also sorg dafür, dass du alle alten Versionen entfernt hast.
