### ISSUE TITLE
Blaue Galaxie Helfer: Anzahl als Badge

### ISSUE THREAD

**Issue by Estigy** [mainIine/foe-helfer-extension#1984]
Hi!

Ich fände es sehr toll, wenn der Blaue Galaxie Helfer genau wie das "Ereignisse"-Feature die Anzahl verbleibender Möglichkeiten direkt beim Icon als kleine Zahl einblenden könnte.
Das Fenster an sich braucht ja ziemlich viel Platz, mir würde die Anzahl als Richtwert völlig reichen.

Danke :-)

**Comment by Gindi4711** [comment]
Wird mit dem nächsten Update hinzugefügt
