### ISSUE TITLE
Add more statistics to statisics module

### ISSUE THREAD

**Issue by Julian2424** [mainIine/foe-helfer-extension#1985]
Some that would be interesting:
Flying Island incident rewards (especially the chances)
general incident rewards
seed vault rewards
quest rewards

**Comment by outoftheline** [comment]
Problem with FI, SV: we need to have it, so we can test stuff ^^ .. i dont want to build it.

Quest rewards have already been suggested

That leaves incident rewards - I don't really know if it's that interesting tbh :P

**Comment by neveneffecten** [comment]
One thing that I've thought about in the past: have the option to see the last 14 days in the GbG statistics to see your drops from over the previous season

**Comment by outoftheline** [comment]
@neveneffecten you mean like this?

![image](https://user-images.githubusercontent.com/7482863/117257222-f4562a80-ae4b-11eb-9709-9e3d4cca2d2a.png)

**Comment by neveneffecten** [comment]
![image](https://user-images.githubusercontent.com/57371863/117334966-ebd91080-ae9a-11eb-8d5a-52bce3cc8d13.png)

No like this, but then with 14 days/2 weeks. though I get the confusion

**Comment by Sysics** [comment]
Hello!
Wird die Implementierung des Saatgut Tresors noch vorgesehen? @outoftheline

**Comment by SkateScout** [comment]
@outoftheline In the FP collection window there is already an date picker even with range.
Can this not be also used in the statistik window ?

**Comment by Sysics** [comment]
> Hello! Wird die Implementierung des Saatgut Tresors noch vorgesehen? @outoftheline

Hello,
ich würde das hiermit gerne nochmal pushen. Falls ich aushelfen könnte, würde ich das gerne machen. Ich habe gelesen das es damals nicht umgesetzt wurde weil der Saatgut Tresor nicht so häufig gestellt wurde.
