### ISSUE TITLE
Town Overview: total squares Bug

### ISSUE THREAD

**Issue by tample17** [mainIine/foe-helfer-extension#1986]
Hello!

<details>
  <summary>Here is my city stats</summary>

![image](https://user-images.githubusercontent.com/62431934/115999386-1b169480-a5f4-11eb-9c32-42920a1a0e6d.png)

</details>

<details>
  <summary>And city of another player</summary>

![image](https://user-images.githubusercontent.com/62431934/115999390-24076600-a5f4-11eb-8c91-431645314341.png)

</details>

**Comment by Gindi4711** [comment]
Cities of other players should not show "total squares" as there is no way of determining unlocked extensions.

**Comment by Gindi4711** [comment]
Will be fixed in next update
