### ISSUE TITLE
City Planer didn't show acualy City Datas

### ISSUE THREAD

**Issue by tommy99hh** [mainIine/foe-helfer-extension#1987]
If I send my actually City Datas to Foe-Rechner.de via FoE-Helper Ver 2.5.6.3 the city planner shows only an old city, Not the actually one. And i can't add any new City Field. I would like to plan the city for the new Event.
Thanks Tommy

**Comment by Th3C0D3R** [comment]
You don't use the latest version of the helper

**Comment by Gindi4711** [comment]
Please update to the current version of the game. If it still does not work contact a developer on our dicord channel.
