### ISSUE TITLE
Ereignisanzeige: Bei den Scherben der fliegenden Insel fehlt die Bezeichnung

### ISSUE THREAD

**Issue by Gindi4711** [mainIine/foe-helfer-extension#1991]
Ereignisanzeige: Bei den Scherben der fliegenden Insel fehlt die Bezeichnung

Wird mit dem nächsten Update gefixed

**Comment by Julian2424** [comment]
Es fehlt auch ein Bild von dem Ereignis. Das fehlt auch noch in der neusten Beta.
