### ISSUE TITLE
City Planer import does not work

### ISSUE THREAD

**Issue by kuligramm** [mainIine/foe-helfer-extension#1992]
I have still the same problem described in #1936. It is not solved.
I tried several browsers, several version of helper. Even with version 2.5.7.1 it is not working.
When opening the cityplanner I always see a town which was imported some weeks ago.
This seems to be a general problem.
Version 2.5.7.1
Spieler Id: 
Welt: de21

But overall: Thank you for this very helpful FoE-Helfer

**Comment by Gindi4711** [comment]
You have been banned from our servers for using a Foe helper version containing forbidden features.

This can be either a very old version from earlier than mid 2020 or a manipulated version.

Please remove all forbidden versions from all your devices. Then I can restore your account. Please be aware that this can only be done once. If you get caught again the ban willnbe permanent.

**Comment by kuligramm** [comment]
sorry that's ridiculous. I tried to find your bug in this buggy software.
I wrote that I tried several versions to give you more information about this bug.
And you? You are banning me for this help?
Very strange!

**Comment by Gindi4711** [comment]
There is no bug. The reason why you cant transmit data is your banned account.

**Comment by kuligramm** [comment]
Oh, I don't know that city planing tool was forbidden. Of cause I disabled automatic updates of all Add-Ons due to security reasons because automatic updates can cause major security issues.
I installed foe-helfer from browsers Add-On store. Some weeks ago city planner suddently displayed faulty cites. After that I tried several things to solve the bug.
Unlocking my account would be helpful.

**Comment by Gindi4711** [comment]
1.) City planning tool is not forbidden. Using very old versions that had features for plundering, sniping or negotiation helper in GBG is.

2.) Turning off updates is not a good idea. We do not support any outdated versions (even if they dont contain forbidden features) and it is expected to cause problems as either Inno is changing stuff on their side or we are changing communication to our server.
If you want to validate every new update you may do so, but not installing updates at all will not work.

**Comment by kuligramm** [comment]
I updated foe-helper again as suggested. But even with latest update of foe-helper the city planning tool is not working correctly. 
Still the same bug. Only old city data visible.

**Comment by Gindi4711** [comment]
Please read my first post again. You have been banned because you used old versions in the past. If you tell me your player ID and world I will unlock your account again.

**Comment by kuligramm** [comment]
Hello,

my foe-helper add-on is updated.

player=10447001
world=de21

Thank you in advance for unlocking my account.




Am 04.05.2021 um 12:40 schrieb Gindi4711:

**Comment by Gindi4711** [comment]
You have been unlocked
