### ISSUE TITLE
Handel Export als CSV

### ISSUE THREAD

**Issue by dashofi69** [mainIine/foe-helfer-extension#1993]
Hallo 
Ich wollte die Daten vom Güterhandel mit einem CSV exportieren und dort weiter verarbeiten. 
Leider gibt es beim Export einen Fehler. 
Beim öffnen der CSV Datei wird das Bedarfsgut mit dem angebotenen Gut überschrieben und auch die Handelsrate wird falsch berechnet. 
Gibt es da eine Lösung?

**Comment by Gindi4711** [comment]
Das ist ein bekannter Bug siehe https://github.com/mainIine/foe-helfer-extension/issues/1975
