### ISSUE TITLE
share button  

### ISSUE THREAD

**Issue by Konni66** [mainIine/foe-helfer-extension#1996]
der share link den  ich  mein freund geschickt  habe vom stadplaner   kann  nicht   vom  freund  gesehen werden,  es wird   seine  eigene stadt angezeigt stattdessen.
er will  mir   bei  der planung  helfen, aber sieht  nichts. was  kann  ich tun  ?

![0b501-95935b44-93e7-43d1-b037-c6397f3a699c](https://user-images.githubusercontent.com/83518214/116795503-c1bbd300-aad5-11eb-9d95-22fe867086a1.png)

**Comment by mainIine** [comment]
Da Du diesen Fehler bisher allein und zuerst gemeldet hast gehe ich mal von einem Bedienerfehler aus.

Gehen wir mal die Schritte durch.
1. Du schickst ihm deinen Link
2. bevor er deinen Link anklickt muss er bereits eingeloggt sein
3. er sieht dann sofort deine Stadt, nicht in der Übersicht sondern schon im Bearbeitungs-Modus

Und da sieht der seine eigenen Stadt? Da es bei allen anderen klappt, sehe eure Städte evt ähnliche aus?
