### ISSUE TITLE
GB investment bug

### ISSUE THREAD

**Issue by enriqueglopez** [mainIine/foe-helfer-extension#1998]
Since yesterday I can't open the tool that calculates the amount of FP needed to invest another player GB.

I can use the own calculator to calculate external but I prefer the other one. Video attached, please check it. Nothing happens with my click. 

The error message says "Disabled: You must enter another player GB first."
![foe error](https://user-images.githubusercontent.com/61711086/116865017-1e6bda80-ac09-11eb-956a-9088f4f43e67.gif)

**Comment by Gindi4711** [comment]
Maybe you have dragged it outside the screen. You can reset box coordinates in the settings menu.

If that does not solve the problem please use the bug report template.

**Comment by enriqueglopez** [comment]
That was the problem. Thanks
