### ISSUE TITLE
Konfiguration: "Menü Inhalt" Buttons sind nicht alle sichtbar

### ISSUE THREAD

**Issue by Soulprayer79** [mainIine/foe-helfer-extension#1999]
Hallo,

könnt ihr euch das mal bitte angucken? 
Firefox 88.0 64bit, FoeHelper 2.5.7.1

Ist das ein Fehler den ich beheben kann irgendwie oder passiert das auch anderswo?
![unknown](https://user-images.githubusercontent.com/82806099/117060502-48b0bb80-ad21-11eb-8fb8-7fd0707a5bc5.png)

**Comment by Gindi4711** [comment]
Habe das Ganze reproduzieren können. Das Problem tritt immer dann auf wenn das Menü an der rechten Seite verwendet wird. Wird das Menü unten oder als Box verwendet, so werden die Icons korrekt angezeigt.

Anmerkung: Im Beta Branch ist das Ganze so weit gefixed, dass die Icons alle in der Box sitzen und man runter scrollen kann. Allerdings wird weiterhin nur eine Spalte angezeigt.

Kurzfristiger Workaround:
Menüposition auf unten umstellen, dann Menüinhalt konfigurieren und dann falls gewünscht wieder zurückstellen.

**Comment by Soulprayer79** [comment]
Ok, danke!
