### ISSUE TITLE
Idea: Battleground sectors - fight count tracker

### ISSUE THREAD

**Issue by szazadikablak** [mainIine/foe-helfer-extension#2001]
Is it possible to make a report on a given sector(for example A2:B) who hit that and how many times? It would be nice to know,who is participating actively on a give sector(only own clan) and who is just waiting for the 5 tower sectors.

**Comment by outoftheline** [comment]
it's not possible. see #860 

> 3.) Guild battleground log
> Idea: A tool showing which player attacked which sector
> Reason: We do not receive this information from the server
