### ISSUE TITLE
Configuration export/import is incomplete

### ISSUE THREAD

**Issue by Alpha-Centauri-B** [mainIine/foe-helfer-extension#2005]
Die configuration export/import function does not export/import all setting. I miss following settings:

- Settings at the negotiation assistant:
  - Save current goods
  - Save medals

- Settings of the activated boxes

**Comment by Gindi4711** [comment]
Just looked at the code. Currently these Settings are being exported:

Cords: Position of the boxes
Size: Size of the boxes
CopyName: Used in the copy box of the GB calculator
MenuSort: Order of menu items
Tone: Enable/Disable sound of boxes
ForderBonus: Is used in GB cost calcutor to specify if doing 1.9/1.85 etc.

I agree there are many more important settings in the current version.
