### ISSUE TITLE
Province Map - little but important changes. Thank You!

### ISSUE THREAD

**Issue by rafger5** [mainIine/foe-helfer-extension#2010]
Why we have some empty space on the right? Is it possible to fix it?

![image](https://user-images.githubusercontent.com/10143990/118133432-209c1900-b401-11eb-8099-aecf9ba1e792.png)

Also I would like to suggest creating an additional button "download map as PNG" in medium-high resolution. At this moment we have only countours (right mouse button on picture -> save graphic as a picture) as you see below. I think we should have a whole map with background, really

![image](https://user-images.githubusercontent.com/10143990/118133897-9f915180-b401-11eb-852b-3d59b8bd834c.png)

THANKS

**Comment by outoftheline** [comment]
You can change the size of the window yourself.

For the background image: not sure if it would be an issue, as the image is quite large and it would have to be painted directly onto the canvas.

**Comment by rafger5** [comment]
...thanks for reply, but it's not as that simple. Really pls check this and maybe you can fix this with only a little effort?

**Comment by outoftheline** [comment]
okay, how did you manage to get the map to that size? it shouldn't do that.

we'd need browser information (which one, version)
