### ISSUE TITLE
Floating menu gone

### ISSUE THREAD

**Issue by Frecklesnhyd** [mainIine/foe-helfer-extension#2012]
When attempting to move around my city, I accidentally grabbed the floating menu for foe helper and drug it off the screen. I can't get it back. I've uninstalled and reinstalled. Tried the wide monitor instead of the tall one. Tried spreading it across three monitors. It's just gone. How can I reset it? I'm using chrome.

**Comment by outoftheline** [comment]
![image](https://user-images.githubusercontent.com/7482863/118178464-41ca2d00-b434-11eb-8507-ade6fea77f5b.png)

Reset all Box Coordinates

**Comment by Frecklesnhyd** [comment]
My whole FOE helper main menu was set to the floating box. All of my foe helper float box is gone so I can't access the settings menu. Any other ideas?

**Comment by outoftheline** [comment]
aaaaah, sorry.

can you try to zoom out as much as possible and grab it then?

**Comment by Frecklesnhyd** [comment]
No luck. It's not visible at all. 25% is as far as it will zoom out. And nothing there. I can't use any of foe helper at all because my main menu is gone.

**Comment by outoftheline** [comment]
There is another way. I'll make a detailed "how to" tomorrow. Good night.

**Comment by outoftheline** [comment]
![image](https://user-images.githubusercontent.com/7482863/118249698-f486a380-b4a5-11eb-83b6-42b1b9d4fd91.png)

Press F12 (or Menu: More tools > Developer tools)
Find the <div id="menu_box"> element and click it.
Edit the element.style by clicking on the value for "left" and enter 0, maby repeat the same for "top".

**Comment by Frecklesnhyd** [comment]
You are awesome. I can't thank you enough. Worked like a charm.
