### ISSUE TITLE
Problem with Troop-Production-Menu

### ISSUE THREAD

**Issue by zZerstoerer** [mainIine/foe-helfer-extension#2013]
Dear Foe Helper Team! I don't know if I can write this in German, so I will just stick with English. I have a problem with my Troop-Production-Menu. My Level 7 Alcatraz produces unattached Troops for me as it should. I also tested it this morning. There are 2 Factories for Breech-loading guns from the Industrial Era and 4 Rogue Hideouts in my City. I manually checked that the Alcatraz produced 2 Breech-loading guns and 4 Rogues (I know the numbers are kind of randomly fitting, but that's not the point). When I check my Foe Helper it's shown that It produced 1 Ulan, 2 Rogues and 3 Marksmen and that my next production is coming in xx hours. So it's showing something that I didn't produce instead some other troops.  I teared down my other Troop Factories about 3 days ago and this is being shown to me since then. Either the Foe Helper not refreshing itself or it is a bug. Every other great feature from Foe Helper is perfectly working and helping immensely. I also had this bug when going from Colonial Era to Industrial Era, when I teared down the Colonial Era Troop Buildings. Back then there was the same thing but with troops from Colonial Era still getting shown, but after some days it went away. It is not a big problem for me, but I'd like it getting fixed, so I can see my real troop production. Thanks for your time 😁

**Comment by Gindi4711** [comment]
This shows the last recorded collection. If you collect your alcatraz on mobile or a different PC/browser it is not refreshed.
If it still does not get refreshed when collected on the same PC/browser please follow these steps:
.) Open developer tools (F12) and go to console tab.
.) Collect your Alcatraz
.) Look if new error messages appear. If yes please post them here
