### ISSUE TITLE
Idea for GBG related to Attrition

### ISSUE THREAD

**Issue by AnotherIanStone** [mainIine/foe-helfer-extension#2018]
Is there a way that in the GBG section we can see how much support sectors / upcoming sectors have from things like Siege Camps and Watch Towers? By support I mean chance of attrition not increasing.  A column for total percentage of support would be great. 

Each adjacent province a guild owns can add support. If your guild has a Siege Camp you get 24% chance of attrition not increasing and Watch Towers give you 8% chance of attrition not increasing. This all add up so if one adjacent province had 2 Siege Camps and another adjacent province had 2 Watch Towers then the province in the middle would have a total support of 24+24+8+8 = 64% chance in attrition not increasing.

This support % is often used to decide which province to attack next so a column for both current provinces and upcoming provinces would be very useful.

Thanks for considering,
Ian

**Comment by outoftheline** [comment]
Unfortunately no, see #860 - 8
