### ISSUE TITLE
Blue Galaxy Helper Diamants 

### ISSUE THREAD

**Issue by WH1TE-SHAD0W** [mainIine/foe-helfer-extension#2024]
Hi, 
I am using Foe helper for a while, thank you. I have an idea if you can improve the blue galaxy helper, it will be great to prioritize diamantes producing buildings to the top. Instead of going to the production section to check if any of my buildings haven't produced some diamantes.  
Thank you

**Comment by outoftheline** [comment]
Thanks for your idea! We will not implement this though, see #1656
