### ISSUE TITLE
www.foe-helper.com: login not working at all

### ISSUE THREAD

**Issue by Bembler** [mainIine/foe-helfer-extension#2030]
Hi 
as I used the new extension today I now wanted to add some changes to my planned city.
Now the extension does not load at all.

Go and click city planner button, then the homepages will be reloaded, not the city planner.
Tried with Chrome (what initially worked fine(-ish...))
Then after it refused to work I tried with FF, same error.
Will not try other as I doubt it is browser related.

THX
Cheers

**Comment by outoftheline** [comment]
Do you mean the Website?! Hard to tell.

**Comment by Bembler** [comment]
what do you mean? What is hard to tell? Go the the website, click on city manager, be prompted to log in, click log in…..
and nothing happens.
Like there is no way to use the city planner.

**Comment by Midnightcrusher** [comment]
I Have the same problem in Chrome - I submit data and then can't log in or get access to see the cityplanner.

**Comment by Midnightcrusher** [comment]
Now I can log in - but shows a blank screen - https://foe-helper.com/login

**Comment by Midnightcrusher** [comment]
login:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by Midnightcrusher** [comment]
Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by Bembler** [comment]
Not for me, still not working at all.
Login is not even telling that I have a wrong pass. Some white area is popping up at the bottom, but no reaction at all.
Tried with several browsers, all the same mess.

**Comment by outoftheline** [comment]
Are you able to login again?

**Comment by Bembler** [comment]
Yes. 
In case you did something: thanks. 
In case Not: thanks anyways:-)

**Comment by outoftheline** [comment]
Okay, thanks. I personally didn't do anything, but @mainIine fixed it :)

Closing this then.
