### ISSUE TITLE
Town Overview: create building 'highlight' filter by building class

### ISSUE THREAD

**Issue by coderwolf2015** [mainIine/foe-helfer-extension#2032]
When there are a lot of buildings in the city footprint, it can be difficult(potentially time-consuming and fraught to error) to find a particular building class in the city footprint.  This can be for quests, making sure the proper troops are being made in the traz. etc...
I would propose that there be a filter mechanism by Building class(residential/production/goods/cultural/decoration/military/roads/great buildings/special(or event) buildings).  This can take the form of a 'highlight' the same way the 'old' buildings are highlighted currently.  That is to say, the selected type can be diagonally hatched.  
I would recommend this be a method to only allow one type selection at a time to avoid confusion.
![2021-05-27 12_39_02-Window](https://user-images.githubusercontent.com/13156002/119864746-f3fbfd00-bee8-11eb-8fda-09af08dce6db.png)

**Comment by Gindi4711** [comment]
There is no class of event buildings. Most event buildings are residential buildings, but can also be production buildings or decoration buildings which is the reason we did not invest much time in those classes as most players will not care if a building is a residential or production building as long as it produces FP.

**Comment by coderwolf2015** [comment]
The event buildings being residential is a learning issue.   That only looks at a single-use case.  This feature can be used to find small quicker and easier(ie you are removing a rogue hideout/den to change the load on a traz, or 1x1 decorations).  This can make for quick location identification.
