### ISSUE TITLE
Gildenmitgliederübersicht |  Guild Membership Overview

### ISSUE THREAD

**Issue by AsatruLPZ** [mainIine/foe-helfer-extension#2033]
Die Arche wird ja schön ausgelesen, kann man das nicht für alle Legendären Gebäude machen? Das man nachschauen kann welcher Member derzeit bei LG XxX welches Level hat?

The ark is read out nicely, can't you do that for all legendary buildings? That you can see which member is currently at LG XxX which level?

**Comment by outoftheline** [comment]
Wofür würdest du diese Information benutzen? Rein aus Neugier gefragt.

**Comment by AsatruLPZ** [comment]
Angenommen man ist auf der Suche nach Blaupausen da kann man sich die 
Gildenmitglieder anzeigen lassen die ein mittelmäßiges Level haben wo es 
schön viele Blaupausen gibt und ich kann gezielt auch die Leute 
anschreiben. Es geht nur um Gilden intern
Am 31. Mai 2021 08:41:44 schrieb Yvi ***@***.***>:

**Comment by danielvoigt01** [comment]
Eine Liste aller LG der Gildenmitglieder ist mit dem nächsten Update in der Gildenmitglieder Übersicht enthalten. 

A list with all GB of the guild members is included in the guild member overview with the next update.
