### ISSUE TITLE
Berechnung des LG-Gewinns nach Arche-Leveln

### ISSUE THREAD

**Issue by 777Frank** [mainIine/foe-helfer-extension#2035]
Wenn in ein LG investiert wird und bevor dieses LG gelevelt wird, der Investor seine eigene Arche levelt, wird der tatsächliche Gewinn nicht angezeigt, sondern der (veraltete und zu geringe) Wert des Investitionsdatums

**Comment by danielvoigt01** [comment]
Stimmt, der Wert wird erst in dem Moment neu berechnet, wenn eine Veränderung bei den Einzahlungen erfasst wird. Wird mit dem nächsten Update korrigiert.
