### ISSUE TITLE
[Eigenanteilsrechner] Blaupausen und Medaillen per Zahnrad ausblenden

### ISSUE THREAD

**Issue by Sysics** [mainIine/foe-helfer-extension#2036]
Hello,

über das Zahnrad kann man bisher den Arche Bonus konfigurieren. Ist es möglich das man als Nutzer des FoeHelpers die Blaupausen und Medaillen ausblenden kann? Für Mittel- bis Langspieler hat dies mMn keine Relevanz mehr und spart etwas Platz.

Grüße!

**Comment by outoftheline** [comment]
Hatte ich auch schon einmal überlegt

**Comment by Gindi4711** [comment]
Das Problem ist, dass wir dann beim Umdesignen der Buttons oben und unten nicht nur verschieden lange Bezeichnungen in 18 Sprachen sondern auch 2 verschiedene Designs mitberücksichtigen müssen. Deshalb versuche ich das Design so einheitlich wie möglich zu halten.
