### ISSUE TITLE
FOE speichert überhaupt keine Einstellungen beim verlassen des Spiels.

### ISSUE THREAD

**Issue by Cloeh1** [mainIine/foe-helfer-extension#2038]
Jedes mal muss alles, alles neu eingestellt werden. Selbst die %-Zahlen beim Eigenanteilsrechner.

**Comment by outoftheline** [comment]
Löscht du beim Schließen deines Browsers die Website Daten? All diese Daten werden in deinem Browser gespeichert, solange du sie nicht löscht. 
Das Speichern funktioniert übrigens nicht im Incognito Modus, falls du sowas nutzt.

**Comment by Cloeh1** [comment]
Nein, ich lösche beim Schließen des Browsers keine Website Daten. Nein, ich spiele nicht im Incognito Modus. Ich spiele am PC mit dem Vivaldi-Browser Version 3.8.2259.42 (64bit) unter Windows 10 Version 20H2.

**Comment by Gindi4711** [comment]
Also ich habe mir Vivaldi installiert und mit Defaulteinstellungen habe ich keine Probleme.

Kannst du die Bug Report Vorlage hier verwenden:
https://github.com/mainIine/foe-helfer-extension/issues/620

**Comment by Cloeh1** [comment]
Tu mir ja leid Leute, aber ich habe eben Vilvaldi komplett gelöscht und neu installiert. Es werden weiterhin keine Daten vom FOE-Helfer gespeichert.

**Comment by Cloeh1** [comment]
Windows 10 Version 20H2
Vivaldi 3.8.2259.42 (64bit)
de19 Tuulech
2.5.8.0 - Deutsch
OneTab, IDM Integration Module

**Comment by Cloeh1** [comment]
Hallo liebe Leute, ich hab's jetzt aufgegeben mit Vivaldi.  Früher hatte da alles funktioniert.
Ich bin jetzt zu Opera gewechselt, dort geht alles.  Dabei habe ich auch bemerkt, das Vivaldi sich zwar das Passwort für das FOE-Spiel merkt, aber nicht anwendet. Bei Opera funktioniert das alles. Wer weiß schon, an welcher versteckten Stelle da bei Vivaldi was nicht stimmt. Danke für eure Versuche, mir zu helfen. 😊 Cloeh
