### ISSUE TITLE
Ereignisse falsch angezeigt

### ISSUE THREAD

**Issue by Tunsel** [mainIine/foe-helfer-extension#2039]
Ich hatte eine zweispurige Strasse, diese wieder gelöscht. Nun werden mir ständig Ereignisse auf zweispurigen Strassen angezeigt, die aber nicht mehr existieren. Wie kann ich dies ändern?

**Comment by Gindi4711** [comment]
Indem du wieder eine 2 spurige Straße baust und das Spiel mit F5 neu lädst. Dann sollte ein Ereignis auftauchen.

**Comment by Tunsel** [comment]
Hallo, vielen Dank - das hat geklappt. Muss ich das jetzt jedesmal so machen, oder erkennt das Programm zukünftig dass ich keine doppelspurige Strasse mehr habe?

 
 

Gesendet: Dienstag, 01. Juni 2021 um 20:47 Uhr
Von: "Gindi4711" ***@***.***>
An: "mainIine/foe-helfer-extension" ***@***.***>
Cc: "Tunsel" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Ereignisse falsch angezeigt (#2039)


 

Indem du wieder eine 2 spurige Straße baust und das Spiel mit F5 neu lädst. Dann sollte ein Ereignis auftauchen.

**Comment by outoftheline** [comment]
Wir zeigen lediglich die Ereignisse an, die das Spiel generiert. Das Spiel erstellt die Ereignisse unabhängig davon, ob du eine zweispurige Straße hast oder nicht.

**Comment by Tunsel** [comment]
okay, danke. das bedeutet, dass der Fehler bei FOE liegt. kann ich FOE anschreiben und darauf verweisen, dass der FOE-Helfer mir anzeigt, dass das Spiel einen Fehler hat? oder ist das dann ein Problem für mich?

 

Vielen Dank für die Unterstützung.

 
 

Gesendet: Mittwoch, 02. Juni 2021 um 11:42 Uhr
Von: "Yvi" ***@***.***>
An: "mainIine/foe-helfer-extension" ***@***.***>
Cc: "Tunsel" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Ereignisse falsch angezeigt (#2039)


 

Wir zeigen lediglich die Ereignisse an, die das Spiel generiert. Das Spiel erstellt die Ereignisse unabhängig davon, ob du eine zweispurige Straße hast oder nicht.

**Comment by Gindi4711** [comment]
Auch wenn es theoretisch ein Fehler im Spiel ist, wird Inno den Bug nicht anerkennen, da diese "falschen" Informationen ja ohne Helfer nirgendwo sichtbar sind.

Was die Anzeige im Helfer angeht:
Dass die doppelten Straßen auch angezeigt werden wenn der Spieler keine doppelten Straßen besitzt ist so gewollt. Dadurch hat der Spieler die Chance doppelte Straßen zu bauen, um das Ereignis einzusammeln.
Falls der Spieler noch nicht in der Jahrhundertwende ist, blenden wir das Ereignis jedoch aus.

**Comment by Tunsel** [comment]
Guten Morgen,

 

vielen Dank für die hilfreiche Antwort. Ich weiss jetzt gut damit umzugehen, und belasse es auf sich.

 

Viele Grüße

Stefan Franke

 
 

Gesendet: Freitag, 04. Juni 2021 um 22:12 Uhr
Von: "Gindi4711" ***@***.***>
An: "mainIine/foe-helfer-extension" ***@***.***>
Cc: "Tunsel" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Ereignisse falsch angezeigt (#2039)


 

Auch wenn es theoretisch ein Fehler im Spiel ist, wird Inno den Bug nicht anerkennen, da diese "falschen" Informationen ja ohne Helfer nirgendwo sichtbar sind.

Was die Anzeige im Helfer angeht:
Dass die doppelten Straßen auch angezeigt werden wenn der Spieler keine doppelten Straßen besitzt ist so gewollt. Dadurch hat der Spieler die Chance doppelte Straßen zu bauen, um das Ereignis einzusammeln.
Falls der Spieler noch nicht in der Jahrhundertwende ist, blenden wir das Ereignis jedoch aus.
