### ISSUE TITLE
Idea/Request A small window to block unwilling attack in Guild Battleground

### ISSUE THREAD

**Issue by plahitte** [mainIine/foe-helfer-extension#2040]
Hi, 

My suggestion is the following : 

A small window that prevents negotiation by misclick on the campaign map. It would be useful to program a similar window to appear when the number of fights reaches a given number (let say 140/160 in diamond league). It would help to prevent the unwilling validation of sectors.

**Comment by Gindi4711** [comment]
And how should the tool know if you want to invade a sector or not? Only way I could think of is if there is a "dont attack" flag, but somebody has to set that.

**Comment by ecthelioni** [comment]
I think it's an interesting idea. This "Windows" can work just like Windows to prevent an attack only with rogue. I will set a limit (for example 140/160) and when the province has this limit, the "Dont attack more" window will open and I can close the X window and continue the attack. If I don't set the limit, the window will never open.

**Comment by outoftheline** [comment]
Well, what about all those mobile players?

**Comment by ecthelioni** [comment]
Im sorry, but your question is irrelevant, FoE helper is aplication for PC version of game, all funkcion is not for mobile players.

**Comment by outoftheline** [comment]
I should have been more clear: why would such a button make sense when it only affects a fraction of people playing GBG? I don't see the point.

**Comment by JhonnyBn** [comment]
This is now implemented in game
