### ISSUE TITLE
FP overview wrong date 09-1906

### ISSUE THREAD

**Issue by Rebia999** [mainIine/foe-helfer-extension#2047]
When I open the window I can see today, but when I want to change it to yesterday I see september 1906.

![image](https://user-images.githubusercontent.com/85393784/120889046-af184a80-c5fb-11eb-81b7-f2918d9b55bc.png)

**Comment by Gindi4711** [comment]
This is a language specific bug that is caused by the Dutch date format of "DD-MM-YYYY".

**Comment by Gindi4711** [comment]
Wird mit dem nächsten Update gefixed

**Comment by Rebia999** [comment]
Danke Gindi,

I changed the language to english and its fixed for now.
