### ISSUE TITLE
LG Investitionen

### ISSUE THREAD

**Issue by Heiko1984** [mainIine/foe-helfer-extension#2048]
Hallo,
ich habe jetzt ein paar mal festgestellt das die Liste mit investierten FP nicht richtig ist. dort werden teilweile Gebäude noch gelistet die schon 2 mal weiter gelevelt wurden.
Wenn man das gebaude dann öffnet und anschleißend wieder in die Invest Liste schaut dann ist es verschwunden.
Ist es möglich da was zu ändern?

**Comment by Gindi4711** [comment]
Um die gesamte Liste zu aktualisieren musst du die LG Investitionen Liste im Rathaus öffnen. Rechts unten in dem jeweiligen Fenster siehst du, wann das das letzte Mal passiert ist.

Automatisieren lässt sich das leider nicht ohne aktiv Daten vom Inno Server abzufragen was ein Verstoß gegen die Spielregeln wäre.
