### ISSUE TITLE
Mitglieder in den Gefechten wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by Grafixpower** [mainIine/foe-helfer-extension#2051]
Hallo,
in den Gildengefechten wird die Mitgliederliste nicht mehr angezeigt.

**Comment by Gindi4711** [comment]
Kannst du bitte die Bug Report Vorlage verwenden:
https://github.com/mainIine/foe-helfer-extension/issues/620

**Comment by Grafixpower** [comment]
Hallo,
in den Gildengefechten wird die Mitgliederliste nicht mehr angezeigt.

Windows 10 64 Bit
Firefox 90.0b6 64-Bit
de21 (Vingrid)
2.5.8.0 - Deutsch

**Comment by Gindi4711** [comment]
Wird die gesamte Liste nicht mehr angezeigt?

Falls ja kann es sein, dass du diese aus dem Fenster raus geschoben hast.
In diesem Fall klick auf Einstellungen (Zahnradsymbol im Menü) => Erweiterung => Boxen Koordinaten und dann auf Löschen. Dadurch werden alle Fensterpositionen wieder auf den Standardwert zurückgesetzt

Falls die Titelleiste der Box angezeigt wird aber kein Inhalt:
Öffne die Entwicklertools und geh auf den Tab "Konsole". Öffne dann die Mitgliederliste erneut schau nach, ob dort neue Meldungen auftauchen.

**Comment by outoftheline** [comment]
Es gab keine weitere Rückmeldung, daher mach ich hier zu.
