### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by exstreme** [mainIine/foe-helfer-extension#2054]
In every GB this error:
VM332:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at _main.js?v=2.5.8.0:1509
(anonymous) @ _main.js?v=2.5.8.0:1509
Promise.then (async)
(anonymous) @ _main.js?v=2.5.8.0:1510
Promise.then (async)
send2Server @ _main.js?v=2.5.8.0:1506
OwnLG @ _main.js?v=2.5.8.0:1587
lgUpdate @ _main.js?v=2.5.8.0:1003
(anonymous) @ _main.js?v=2.5.8.0:937
_proxyAction @ _main.js?v=2.5.8.0:455
proxyAction @ _main.js?v=2.5.8.0:468
xhrOnLoadHandler @ _main.js?v=2.5.8.0:569
load (async)
XHR.send @ _main.js?v=2.5.8.0:584
load @ ForgeHX-c1b729e5.js:28310
__loadText @ ForgeHX-c1b729e5.js:28313
loadText @ ForgeHX-c1b729e5.js:28311
loadString @ ForgeHX-c1b729e5.js:28468
load @ ForgeHX-c1b729e5.js:29252
_loadRequest @ ForgeHX-c1b729e5.js:573
_send @ ForgeHX-c1b729e5.js:572
_doRequest @ ForgeHX-c1b729e5.js:569
_processNextRequest @ ForgeHX-c1b729e5.js:567
_pushRequest @ ForgeHX-c1b729e5.js:569
_sendAllBufferedRequests @ ForgeHX-c1b729e5.js:568
send @ ForgeHX-c1b729e5.js:565
call @ ForgeHX-c1b729e5.js:538
_callWithFuture @ ForgeHX-c1b729e5.js:550
contributeForgePoints @ ForgeHX-c1b729e5.js:13177
_callContributeService @ ForgeHX-c1b729e5.js:4995
_contributeForgePoints @ ForgeHX-c1b729e5.js:4993
_useForgePoints @ ForgeHX-c1b729e5.js:4989
execute @ ForgeHX-c1b729e5.js:4988
execute @ ForgeHX-c1b729e5.js:29336
routeEventToCommand @ ForgeHX-c1b729e5.js:29337
h @ ForgeHX-c1b729e5.js:29334
__dispatchEvent @ ForgeHX-c1b729e5.js:18
dispatchEvent @ ForgeHX-c1b729e5.js:15
dispatch @ ForgeHX-c1b729e5.js:524
_onProgress @ ForgeHX-c1b729e5.js:18596
routeEventToListener @ ForgeHX-c1b729e5.js:29342
k @ ForgeHX-c1b729e5.js:29340
__dispatchEvent @ ForgeHX-c1b729e5.js:18
__dispatchEvent @ ForgeHX-c1b729e5.js:50
__dispatchWithCapture @ ForgeHX-c1b729e5.js:51
dispatchEvent @ ForgeHX-c1b729e5.js:47
_onButtonClicked @ ForgeHX-c1b729e5.js:18569
__dispatchEvent @ ForgeHX-c1b729e5.js:18
__dispatch @ ForgeHX-c1b729e5.js:49
__dispatchStack @ ForgeHX-c1b729e5.js:29028
__onMouse @ ForgeHX-c1b729e5.js:29040
onMouseUp @ ForgeHX-c1b729e5.js:29022
dispatch @ ForgeHX-c1b729e5.js:28356
handleMouseEvent @ ForgeHX-c1b729e5.js:28326
Show 20 more frames

**Comment by Gindi4711** [comment]
Are there any side effects except the error messages?

**Comment by exstreme** [comment]
No, but appeared recently

**Comment by mainIine** [comment]
Fixed
