### ISSUE TITLE
GB listing - feature request

### ISSUE THREAD

**Issue by WelverinXarann** [mainIine/foe-helfer-extension#2055]
Would there be a way to get a searchable (isolate) listing of GBs among friends, hoodies, guild? When print hunting it takes forever to go thru and find those that have the more hard to find buildings and a way to get an active list where specific ones can be isolated with the owner's name and maybe list number. I would expect it to need each person's city to be visited for the list to update should anything change, similar to how the guild member overview works.  I would figure the easiest way would be a drop-down menu with the buildings which would then list the players that have them by searching thru the player list. The person's city to be visited individually to get them added and updated on the list. Again, this would be primarily be used to search for GBs to invest in for print hunting. As some GBs seem to be really rare, it's ridiculously hard to keep track of the few players that have them.

Sorry if this has already been requested.

**Comment by Gindi4711** [comment]
We will have a similr feature in the next update, but only for guild members.

**Comment by WelverinXarann** [comment]
Would it be possible to expand upon it to at least friend list as well if not all 3 lists? I expect it would go a fairly long way for some of us who are looking for something specific that may not be popular or available in guild.

**Comment by Gindi4711** [comment]
For neighbors definitely not because this would be used as a sniping feature.

For friends it could be possible, but currently it is implemented as part of the guild statistics, so friends do not really bit there, so it is currently not planned, but not ruled out either.

**Comment by WelverinXarann** [comment]
That makes sense for neighbors. If it could be implemented for friends tho that would be great as many of us add people specifically because they have a gb we look to get prints from but later forget who exactly it was that had that specific one when they hit a roadblock themselves and can't push it any further. I think it would make it a lot easier to keep track of who had what instead of trying to keep up with where paper notes disappeared to with similar lists.

**Comment by TechWizard80** [comment]
Ok... it was mentioned that you are working on it?
When will this be available? :)

**Comment by danielvoigt01** [comment]
It is already available in the guild member overview:
![Auswahl_054](https://user-images.githubusercontent.com/46729881/128644732-e8ca673e-4d4d-4e98-9021-eb0ab9c1ed06.jpg)
