### ISSUE TITLE
Helper klappt zusammen und kann nicht mehr bedient werden

### ISSUE THREAD

**Issue by Player1O** [mainIine/foe-helfer-extension#2056]
Hallo,

ich habe die Helper-Extension für Microsoft Edge geladen. Soweit alles perfekt.
Dann habe ich in den Einstellungen die Position für die Leiste von "unten" auf "rechts" geändert.
Dann wanderte sie auch nach rechts, aber die beiden dicken Navigationspfeile sind zusammengeklappt und es kann nichts mehr bedient oder genutzt werden.
Die Extension zu entfernen, den Browser neu zu starten und dann die Extension neu zu installieren bringt keinen Erfolg.
Mein System: 
Windows 10 Home
Microsoft Edge
Version 91.0.864.48 (Offizielles Build) (64-Bit)

Ich freue mich über Hilfe.

Viele Grüße
Player1On
<img width="209" alt="FoE-Helper zusammengeklappt" src="https://user-images.githubusercontent.com/86010371/122253819-d0671980-cecc-11eb-9755-cd44ec4e2f82.PNG">

**Comment by outoftheline** [comment]
Dann hast du wohl leider nicht genug Platz, um das Menü rechts anzeigen zu lassen - wir müssen da einen gewissen Abstand nach oben für aktive Boosts von Inno lassen.

Am besten veränderst du den Browser-Zoom bis dir wieder mindestens ein Menüpunkt angezeigt wird und navigierst von da aus zu den Einstellungen, um die Menüposition wieder zu verändern.

**Comment by Player1O** [comment]
Hallo Yvi,

vielen Dank für die super schnelle Hilfe! So war es dann auch. Hat bestens geklappt und ich bin sehr glücklich (mit der Menüposition unten).

Viele Grüße
Player1O
