### ISSUE TITLE
attempted looting- feature request

### ISSUE THREAD

**Issue by thepab** [mainIine/foe-helfer-extension#2059]
it would be nice to also see the looting attempts in the Po / Mo wizard.

![image](https://user-images.githubusercontent.com/61996796/122666461-a43de800-d1ad-11eb-8f38-06909432ced5.png)
with the symbol 
![image](https://user-images.githubusercontent.com/61996796/122666486-c7689780-d1ad-11eb-963a-26aed7993357.png)
instead of
![image](https://user-images.githubusercontent.com/61996796/122666497-dea78500-d1ad-11eb-94b7-28ca9b85bd82.png)

**Comment by Gindi4711** [comment]
Should definitely be included. Unfortunately I do not have a Galata, so I do not know how the communication looks like in this case and cannot test ist.
