### ISSUE TITLE
InfoBox - Displays incorrect FP awarded for new GB level

### ISSUE THREAD

**Issue by blikefritz** [mainIine/foe-helfer-extension#2065]
When a new level is reached on a Great Building the user contributed towards, it lists the amount of FP that would be awarded toward the most recently building the user contributed rather than the building that actually leveled up.

For example, if I contributed 19 FP toward someone's Zues and expect 19 FP back.  Then after contributing to a Zues, I now contribute toward an Arc and expect to receive 300 FP back on that Arc.
Then the Zues levels up, since the Arc was the most recently contribution, the Info box will tell me the Zues leveled up, what place I received but then say I received 300 FP in rewards but in reality I only received 19 FP.

**Comment by Gindi4711** [comment]
This is already a known issue: https://github.com/mainIine/foe-helfer-extension/issues/1907

**Comment by Gindi4711** [comment]
Should be fixed in next update
