### ISSUE TITLE
double collection

### ISSUE THREAD

**Issue by enricomg** [mainIine/foe-helfer-extension#2066]
you could enter the data to make a double collection, the written own contribution comes out, remaining points to completely close the ge, but not to make a double collection

thank you

![Immaginepp](https://user-images.githubusercontent.com/61316507/122804084-bc098f00-d2c7-11eb-9f17-cd61428ea623.png)

**Comment by Gindi4711** [comment]
Sorry, but I dont understand your question.
What should I do with the double collection (in this case 85FP)?
What are the 1149 you are showing?

**Comment by enricomg** [comment]
Hi, to cover all positions at once leaving 29 points for closing

I solved in a Spartan way for now :


        h.push('<td class="text-center">' + i18n('Boxes.OwnpartCalculator.OwnPartdoublecollection') + ': <strong class="' + (PlayerID === ExtPlayerID ? 'info' : '') + '">' + HTML.Format( EigenTotal - EigenStart - Rest ) + '</strong></td>');

**Comment by enricomg** [comment]
can I add this change?

**Comment by Gindi4711** [comment]
Your calculation is wrong. Double collection is one daily production of your great building. For arctic orangery it is 85FP, but other buildings will give you something different like goods, units, gold etc. For some buildings like Himeji it is more complicated as it gives you 9 more chances for a reward which equals 80 FP, but only if you actually do those attacks. For  blue galaxy it depends on which buildings you have to collect.
Also you will get double collection after leveling your GB, so at the moment you will need the full amount. Double collection only gets relevant when doing multiple levels at once so it was added to power leveling calculator and LG investments, but in this tool I think it would be more confusing.

**Comment by enricomg** [comment]
ok got it thanks, even if I would have liked it only for the ge that give pf and unit
