### ISSUE TITLE
Cost of all buildings in the antique dealer

### ISSUE THREAD

**Issue by bajahranks** [mainIine/foe-helfer-extension#2068]
Is it possible to have an option to search of any building and get the price of that building in the Antique Dealer. Similar to https://foe-assistant.com/en/antiques-dealer

**Comment by Gindi4711** [comment]
Currently we do not know the sell value of items before you have them in inventory so we would need to manually add items to this list.
We do not want to make tools that need ongoning maintenance as this will bind resources for creating new content and manpower is our biggest issue atm.

**Comment by bajahranks** [comment]
Ok. Understood.
