### ISSUE TITLE
Nachricht - Welt Name im Titel - feature request

### ISSUE THREAD

**Issue by thepab** [mainIine/foe-helfer-extension#2070]
![image](https://user-images.githubusercontent.com/61996796/123066442-5e348e80-d410-11eb-90ad-f589ec0df530.png)

ein Verbesserung - Idee : nach dem Titel der Nachricht einfügen den Weltnamen. 
wie : Antiquaire **- Brisgard** 

Sonst du muss dem welt immer einfügen im Meldung wie in mein Beispiel

**Comment by Parama91** [comment]
alerts.js Zeile 1218? Genügt es dort den Titel zu erweitern oder haben wir da die Daten für den Weltnamen nicht mehr und es muss schon im data gesetzt werden?
