### ISSUE TITLE
City Planner using old data

### ISSUE THREAD

**Issue by JohnKleb** [mainIine/foe-helfer-extension#2071]
I have been unable to update the City Planner for some time.  When I create a "New City" the data used is from many months ago.  The Show Submit box functions and tells me the upload has been successful, but when I open in foe-helper.com the data is from an old city configuration.  I have illustrated a couple of simple differences here.

![image](https://user-images.githubusercontent.com/13572588/123274151-42dd8800-d4d1-11eb-8d81-39ebb065f840.png)
![image](https://user-images.githubusercontent.com/13572588/123274201-4ffa7700-d4d1-11eb-90f9-484bf8b7e5b1.png)
![image](https://user-images.githubusercontent.com/13572588/123274357-71f3f980-d4d1-11eb-90cc-51e698655e4e.png)
![image](https://user-images.githubusercontent.com/13572588/123274483-8df79b00-d4d1-11eb-9ec3-435760ed262e.png)

Thanks

**Comment by outoftheline** [comment]
Hi there!

There might be an issue with your account. We'd need your player ID and game world (eg. us4) to have a look :)

**Comment by JohnKleb** [comment]
Thanks! TaglotnUS14 and US20.  Neither of them work. Sent from Mail for Windows 10 From: YviSent: Thursday, June 24, 2021 11:34 AMTo: mainIine/foe-helfer-extensionCc: JohnKleb; AuthorSubject: Re: [mainIine/foe-helfer-extension] City Planner using old data (#2071) Hi there!There might be an issue with your account. We'd need your player ID and game world (eg. us4) to have a look :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Gindi4711** [comment]
Your account has been banned from our servers for either using a modfied Foe helper version or a very old version that contains features that have been forbidden by Inno.

I have unbanned both worlds. Please make sure you do not use these versions any more.

**Comment by JohnKleb** [comment]
How do I do that?  I uninstalled and reinstalled the extension when I was
trying to figure out the problem.  Do I have a rogue version of the
extension on some computer?

//John  +1.630.935.2127

**Comment by JohnKleb** [comment]
It works now.  Thanks. Sent from Mail for Windows 10 From: Gindi4711Sent: Thursday, June 24, 2021 5:11 PMTo: mainIine/foe-helfer-extensionCc: JohnKleb; AuthorSubject: Re: [mainIine/foe-helfer-extension] City Planner using old data (#2071) Your account has been banned from our servers for either using a modfied Foe helper version or a very old version that contains features that have been forbidden by Inno.I have unbanned both worlds. Please make sure you do not use these versions any more.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
