### ISSUE TITLE
Eigenanteilsrechner: Verbesserungen für "Werte kopieren"

### ISSUE THREAD

**Issue by frank42hh** [mainIine/foe-helfer-extension#2073]
Moin,
Vorschlag #1:
Wenn man ein recht kleines LG levelt, hat man es meist, dass P5 und manchmal auch P4 keine FP werfen, aber BP. Deshalb werden die gerne trotzdem mit angeboten, normalerweise dann halt mit 1 FP.
Es wäre sehr handlich, wenn man es einstellen könnte, dass Plätze, die 0 FP geben, auf 1 FP "aufgerundet" werden, denn Plätze mit 0 FP zu posten, macht irgendwie meines Erachtens keinen Sinn, passiert aber, wenn man "alle + leere" auswählt.

Und Vorschlag #2:
Wenn ich in einem teilbelegten LG "Alle" auswähle, werden auch die Plätze in die Vorschau gepackt, die bereits belegt und safe sind. Ich gehe gern mal hin und lasse P1 und P2 an anderer Stelle fördern als P3-P5 und wenn ich P3-P5 in einem Rutsch mache, funktioniert das mit "Auto" nicht (weil der nur P3 nimmt, da P4 und P5 in dem Moment noch nicht safe sind), also wähle ich P3 P4 und P5 manuell aus, weil "Alle" die bereits belegten mitnimmt.
Ich fände es sehr geil, wenn safe belegte Plätze hier rausgenommen werden könnten, ich glaube nicht, dass irgendjemand auf die Idee käme, Plätze zu posten, die man gar nicht mehr belegen kann.

**Comment by Gindi4711** [comment]
1.) Ab dem nächsten Update werden Plätze ohne FP generell min 1 FP geben. Wer das nicht haben will, kann die P1 Plätze ja manuell abwählen oder man kann es nachträglich raus löschen.

2.) Die Option "Alle" existiert in erster Linie zum Speedleveln damit man alles ausschreiben kann falls Mobilespieler ohne Helfer nicht selbst rechnen wollen.
Jetzt haben Spieler ohne Helfer öfters die Angewohnheit nicht alle FP sofort einzuzahlen sondern zuerst den Nettomäzen und dann den Archebonus dazu.

Dadurch kommen oft solche Situationen im Helfer zu Stande:
P1 380 FP
P2 190 FP - eingezahlt 200 (+10)
P3 35 FP
usw.

Tatsächlich hat aber P2 nicht überzahlt sondern legt gleich nochmal 180FP drauf um auf P1 zu kommen.

Mit der von dir vorgeschlagenen Funktion würde hier P2 nicht ausgeschrieben werden obwohl er noch fehlt.

Wenn dann müsste ich eine zusätzliche Option machen "Alle ohne belegte". Die Frage ist, ob das dann nicht generell etwas zu überladen wird. Die Defaulteinstellung ist ja schon Auto d.h. in deinem Beispiel müsste man nur P4 und P5 klicken (2 Klicks), während "Alle ohne belegte" 1 Klick ist d.h. man spart sich nur 1 Klick in einem Sonderfall, hat aber das Risiko, dass man dabeindie falschen Plätze erwischt.

3.) Es wird für die Copyfunktion im nächsten Update generell einige Änderungen bzw. neue Features geben,  wobei ich hier noch dabei bin das Handling in der Praxis zu testen (wer es schon einmal testen will einfach den Beta Branch downloaden und als Extension einbinden).
Der Hauptunterschied ist, dass die Kopieren/Merken Buttons nun zusätzlich auf der Hauptseite sind und man die Copybox nur mehr öffnen muss, wenn man Plätze manuell auswählen oder die Einstellungen ändern will.

**Comment by frank42hh** [comment]
Wäre vielleicht Folgendes eine denkbare Alternative?
Der EA Rechner kennt ja die Werte, die bei der gewählten Mäzenstufe gesetzt werden (z.B. 3458 FP bei 190% bei einer 100er Arche auf P1). Wenn man nun sagt, dass beim "Werte kopieren" die Plätze ignoriert werden, die 1:1 dem berechneten Wert entsprechen, würde das ja im Prinzip schon ausreichen, und die Fälle, die du genannt hast, wären auch safe.

Abgesehen davon: 1) und 3) find ich super :)

**Comment by Gindi4711** [comment]
Dann hat man aber wieder Probleme jedes Mal wenn ein Platz gesniped wurde oder jemand etwas zu viel/zu wenig gezahlt wurde. Das wird etwas zu willkürlich.

Eine Variante wäre:
.) Ich füge wirklich eine zusätzliche Option "Alle ohne vergebene" (oder so ähnlich) hinzu. Beim Speedleveln mit fester Platzvergabe und gleichzeitigem einzahlen verwendet man "Alle" und beim regulären Leveln mit sequentieller Einzahlung dann "Alle ohne vergebene"

Eine andere mögliche Variante wäre:
.) Ich blende bei "Alle" Plätze nur dann aus, wenn kein vorheriger Platz mehr offen ist. Ist dies der Fall, so ist der entsprechende Platz nicht mehr mit den geplanten FP belegbar und sollte gefahrlos selbst während dem Speedleveln entfernt werden können. Allerdings ist warte ich hier auf die Tickets von den Spielern, die die Funktionsweise nicht verstehen, weil es eben nicht "Alle" Plätze sind, aber immer noch mehr als angezeigt.

Ich werde mir das noch etwas durch den Kopf gehen lassen, ob mir da nicht was Besseres einfällt, denn beide Lösungen oben haben immer noch den Nachteil, dass man dafür die Copybox öffnen muss.

**Comment by Gindi4711** [comment]
Ich habe es nun so gelöst:
.) Die Option "Alle + Leere" fällt weg, da nun alle Plätze ohne FP mit 1 FP belegt werden. Somit gibt es keine leeren Plätze mehr. Wer die 1FP Plätze nicht vergeben will, der muss sie ja nicht vergeben.
.) Stattdessen gibt es eine Option "Auto + Nicht sichere", die alle noch freien Plätze ausschreibt. Hier ist der Spieler in der Verantwortung, dass er diese nicht nutzt, wenn Spieler gerade halb eingezahlt haben.
