### ISSUE TITLE
Blaue Galaxie Helfer für Dias

### ISSUE THREAD

**Issue by DasLetzte92** [mainIine/foe-helfer-extension#2074]
Moin, könnte man bei dem "Blaue Galaxie Helfer" nicht auch eine Bewertung für Dias in FP hinzufügen, wie es auch schon mit den Gütern gemacht wird?
Dann kann man damit nämlich wunderbar die Wunschbrunnen oder auch Große Leuchttürme, die Dias bringen, verdoppeln.
Würde mich freuen, wenn das mal umgesetzt werden würde.

Des weiteren priorisiert der Blaue Galaxie Helfer die 7 FP einer Opulenten Apfelmühle, obwohl die Ehrenstatuen auch 7 FP + einige Weitere Vorteile bringt.
Vielleicht kann man das auch irgendwie fixen, indem vielleicht bei gleicher FP Zahl das Gebäude mit der höheren Münzproduktion priorisiert wird.

**Comment by Gindi4711** [comment]
1.) Was Dias angeht so würde das zwar funktionieren, wir haben uns jedoch dazu entschieden es nicht zu machen, da dies von Inno als "unfairer Vorteil" angesehen werden könnte, da die Information welcher Wunschbrunnen gerade dias produziert nicht im Spiel selbst ersichtlich ist (zumindest nicht ohne Hilfsmittel wie Entwicklertools).

2.) Was Münzen etc. angeht: Da wird es schnell einmal kompliziert und unübersichtlich, wenn das auch alles mitberücksichtigt werden muss. In der Regel geht es den Spielern ja um FP und Güter.

**Comment by DasLetzte92** [comment]
Zu 1.:
In der Produktionsübersicht sehe ich doch auch, welcher Wunschbrunnen Dias Produziert.
Wird also ohnehin schon angezeigt, nur leider in nem anderen Fenster.

**Comment by Gindi4711** [comment]
Da hast du Recht. Allerdings war das Diamantenfeature in der Produktionsübersicht bei der letzten Überprüfung von Inno vor einem Jahr bereits vorhanden und wurde nicht bemängelt, da sie es vermutlich übersehen haben. Deswegen bleibt es dort erst einmal drin solange Inno nicht verlangt, dass wir es entfernen.
Neue Features dieser Art werden wir allerdings nicht erstellen.
