### ISSUE TITLE
Idee: Kosten für Gebäude im Gildengefecht erfassen

### ISSUE THREAD

**Issue by teageek** [mainIine/foe-helfer-extension#2076]
Es ist immer recht mühsam, sich die Kosten für die Gebäude (vor allem BLs und WTs ;) in den einzelnen Sektoren im Gildengefecht rauszuschreiben und nachzuhalten.
Ich konnte die Daten definitiv im json sehen, wenn ich die Gebäude  öffnete.
Ja ich weiss, das man da immer erst mal den Sektor haben muss und das Menü öffnen, aber das würde ja auch normalerweise 11 Tage statisch sein.
On Top wäre natürlich das direkt mit der Gildenkasse zu korrelieren und anzuzeigen wie viele Gebäude man noch bauen kann.

**Comment by outoftheline** [comment]
So statisch sind die Daten leider gar nicht. Wenn zum Beispiel jemand forscht, können sich die Kosten ändern.. oder auch einfach so: https://forum.de.forgeofempires.com/index.php?threads/g%C3%BCter%C3%A4nderung-auf-sektoren-bei-gg.51002/

**Comment by teageek** [comment]
Ich schrieb ja auch normalerweise ;)
und blind traut man dem ja eh nicht.
Und die Gildengüterproduktionen muss ja auch andauernd aktualisieren.
Wäre halt ungemein cool, wenn man da eine Übersicht hätte.

**Comment by outoftheline** [comment]
> und blind traut man dem ja eh nicht

Sagst du ^^ ich seh schon die Beschwerden reinflattern..
