### ISSUE TITLE
Expedition results.

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#2077]
Hi.

There is possibility to export Battleground results as CSV or jSON file.

I'm very need same functionality in Expedition results.
Some time ago I may get Expedition results from Helper site (in PDF, that is sligtly useable), but it was removed from site.
So please let us get this results.

**Comment by Parama91** [comment]
There is an GEX overview in the beta right now which shows various stats, but i don't know if and when it will be released. Also the export is not implemented, maybe this overview is ok as a first step?! ;)

**Comment by danielvoigt01** [comment]
There is already the possibility to export the guild battleground results, see picture.
![Auswahl_046](https://user-images.githubusercontent.com/46729881/124514500-7a0b3d80-dddd-11eb-82ea-95cccf9c918f.jpg)

Furthermore, with the next update there will be the already mentioned Gex statistics. The possibility to export the Gex statistics data has now also been integrated and will also be available with the next update.
