### ISSUE TITLE
VZ Gütermenge für Marszeitalter in Technologien falsch berechnet

### ISSUE THREAD

**Issue by Melkor73** [mainIine/foe-helfer-extension#2078]
Die Summe der benötigten VZ Güter im Zeitalter Mars stimmt nicht.

**Comment by outoftheline** [comment]
Welche Einstellungen hast du denn gehabt und was genau hat nicht gestimmt?

**Comment by Gindi4711** [comment]
Im Marszeitalter gibt es einige optionale Technologien. Je nach Einstellung kann man wählen, ob diese mitgezählt werden sollen oder nicht.

**Comment by Melkor73** [comment]
OK das war das Problem. Danke
