### ISSUE TITLE
Feature request: import/export city data of another user

### ISSUE THREAD

**Issue by Bozer-der-Barbar** [mainIine/foe-helfer-extension#2079]
I like to help others in my guild with the planning of their city.  As such, it'd be helpful if I could export their city data, import it into my account, make my suggested changes and export the information so that the other user, in turn, can import it into his account to view the changes.

There's already a feature in the city overview ("Stadtübersicht") to copy the city data as a JSON string to the clipboard.  If you could include this in the city overview when I'm visiting another player as well as the ability to import/export JSON data into https://foe-helper.com/citymap/overview, it should be all that's needed.

----

Falls einfacher, einmal auf Deutsch.

I helfe gerne andere Gildies bei der Planung ihrer Städte.  Es wäre daher hilfreich, wenn ich deren Stadtdaten exportieren könnte, sie in mein Konto unter https://foe-helper.com importieren könnte, meine Vorschläge einbauen und die Daten exportieren könnte, sodass der anderer Spieler sie wiederum in sein Konto importieren könnte, um sie Vorschläge anzuschauen.

Wenn ich in meiner Stadt bin, gibt es in der Stadtübersicht schon die Möglichkeit, die Daten als JSON-String in die Zwischenablage zu kopieren.  Wenn es diese Funktion gäbe, wenn ich eine fremde Stadt besuche sowie die Möglichkeit, diese JSON-Daten unter https://foe-helper.com/citymap/overview zu importieren/exportieren, dann hätte ich alles, was ich bräuchte.

**Comment by Gindi4711** [comment]
Der betroffene Spieler kann sofern er selbst den Foe Helfer hat seine Stadt hochladen und dann einen Link generieren mit dem die Stadt bearbeitet werden kann.
Fremde Städte können aus datenschutztechnischen Gründen nicht hochgeladen werden.

**Comment by Bozer-der-Barbar** [comment]
Das Feature kannte ich nicht.  Werde ich ausprobieren.  Setzt aber eben voraus dass andere Gildies aufm PC spielen und den Helfer installiert haben, was nicht immer der Fall ist.

Das mit dem Datenschutz verstehe ich nicht.  Ich würde ja nicht auf mehr zugreifen, was mein Browser eh schon ausliest.  Aber gut.  Ich kann mir vorstellen, dass es etwas ein Drahtseilakt zwischen euch und Inno.

Danke für die schnelle Rückmeldung.

**Comment by Gindi4711** [comment]
Ach Inno ist das ziemlich egal. Es sind eher diverse Spieler mit Aluhut, die uns das Leben schwer machen.
