### ISSUE TITLE
Ansicht Handel

### ISSUE THREAD

**Issue by Selene443Foe** [mainIine/foe-helfer-extension#2080]
Hallo miteinander,
wir sind gerade dabei eine verbesserte Ansicht des Handelstools zu basteln und greifen dafür die CSV Ausgabe des foe Helfers ab.

Die Frage nun:
wäre es möglich eine erweitere Anzeige zu generieren die anzeigt, wer welches Angebot angenommen hat?
Also quasi das, was man jetzt händisch im Rathaus zusammen sammeln muss.

Dies ließe einen besseren Schluss auf die optimalen Angebotsverhältnisse zu. 
Und man könnte eventuell mit Spielern wo man erkennt, dass diese häufiger Angebote annehmen in Kontakt treten, um die Angebote besser gestalten zu können.

Bsp.:
Wenn ich im Infofenster beobachte, dass ein Spieler mehrere meiner gleichen Angebote annimmt, dann wäre es für mich beim Einstellen einfacher und für ihn beim annehmen billiger gewesen, wenn ich ein höheres Angebot eingestellt hätte. 
Nur dazu müsste man wissen, wie viele solch hoher Angebote Sinn gemacht hätten.
Man könnte das natürlich händisch probieren, jedoch ohne wirkliche Nachkalkulation ergibt sich keine gescheite Aussage und es bleibt mehr oder weniger eine Vermutung.

Viele Grüße
Selene

**Comment by Gindi4711** [comment]
Hallo Selene

Schön mal wieder etwas von dir zu hören.

Der Markt Filter verwendet die Liste der Angebote. Die wird in einem Stück zur Gänze übertragen sobald man den Markt öffnet. Erst dann wird das Tool im Menü grün.

Die Handelsereignisse (wann jemand welches Angebot angenommen hat) werden da jedoch nicht übertragen. Die werden nur übertragen, wenn man:
.) Im Rathaus durch die Ereignisse klickt
.) Man gerade zufällig on ist (sieht man z.B. in der InfoBox)

Wenn dann würde ich da eher den Moppelassistenten erweitern. Der zeichnet ja (sofern man regelmäßig durch die Ereignisanzeige im RH klickt) ja schon alle Ereignisse auf, derzeit nur ohne Details (also keine Information welche Güter bzw. wieviele man getauscht hat, nur wer das Angebot angenommen hat. Ich werde mir einmal Gedanken machen, ob man das irgendwie erweitern kann.

Muss es eigentlich zwingend eine CSV Datei sein oder würde JSON auch gehen?

**Comment by Selene443Foe** [comment]
Hiho...
ich hab letztens schon mit dir geschrieben, aber da hast du mich nicht
erkannt :D

JSON - ich hab ehrlich gesagt keinen Schimmer wo man die verwendet.
Ich bin, nachdem du mich damals auf Google Docs bzw Google Sheets
aufmerksam gemacht hast, bei Google mehr oder weniger hängen geblieben und
nutze nun tatsächlich dies.
Ich möchte also die Daten nach Google Sheets ziehen und dort auswerten
lassen.

Hintergrund der Sache ist, dass wir immer von jedem Gut etwas im Handel
stehen haben wollen. Das Sheet soll prüfen ob und wieviel angenommen wurde
und im Idealfall von wem um besagte Angebote anpassen zu können.
Das Problem ist ja folgendes:
Wenn man die Güter einstellt, dann kann man sich ziemlich sicher sein, dass
man alle Kombinationen der Güter zueinander eingestellt hat. Aber sobald
jemand etwas annimmt, fehlt das Angebot ja nun.
Wenn man da nicht ständig das Rathaus im Auge behält und die nun fehlende
Kombination wieder auffüllt, dann merkt man das "Angebotsloch" nicht und
füllt das erst wieder auf, wenn man den ganzen Schwung nach Rückgang ins
Inventar nach einer Woche erneut einstellt.
Das Sheet zeigt nun nach Übernahme der Daten "die Löcher" an und man weiß
so schnell und einfach was man wieder auffüllen muss und ist quasi immer
mit vollem Einsatz im Handel ohne das man sich da durchwuseln muss.
Inno hat es ja noch nicht geschafft ein gescheites Handelstool für den PC
zu stricken. In der App ist das ja ok. Aber am PC... Da ist der foe Helper
eine gigantische Hilfe.
Überhaupt war ich schwer beeindruckt als ich ihn voller Vorfreude das erste
Mal nach einem Jahr wieder angeworfen habe.
Wundervolle Arbeit!
Meinen größten Respekt und Dank.

**Comment by Selene443Foe** [comment]
...ach und was mir gerade aufgefallen ist... auch wieder dieselbe Geschichte - wenn man das Rathaus nicht im Auge hat, dann merkt man nicht mal, dass die Woche um ist und die Güter schon wieder zurück gekommen sind - man quasi gar nichts im Handel mehr stehen hat... :(

Schade, dass Ihr den Teil auf der Webseite, mit dem man die automatische Datenübernahme des Rathauses realisieren könnte, immer noch nicht gefunden habt. Der hat sich aber wirklich gut versteckt was? 
:(

Hab mal geschaut - das was man bisher vom Moppelassi via CSV übernehmen könnte ist ja quasi ein Zahlenwust, kann man nicht wirklich irgendwie verwerten...

**Comment by Gindi4711** [comment]
Kannst du mir eventuell einen Link zu deinem Sheet zukommen lassen. Dann fällt mir eventuell etwas dazu ein.
Versuchst du mit der Methode Güter runter zu handeln oder tauschst du im selben ZA Güter hin und her? Denn du immer das auffüllst, was am Meisten nachgefragt wird, dann wird dein Lagerstand ja immer unausgeglichener. Ich mache es jormalerweise eher umgekehrt, dass ich versuche unterschiedliche Lagerstände auszugleichen.

**Comment by Selene443Foe** [comment]
Das Prinzip ist so:
Wir (FMA, Kolo und PoMo) produzieren/bekommen zum einen täglich Venus Güter
und wir bekommen in unregelmäßigen Abständen Angebote wo Spieler Astrogüter
gegen verschiedene untere Güter tauschen.
Das heißt, es kommen immer mal wieder / mehr oder weniger regelmäßig, hohe
Güter bei uns an die wir immer nach unten tauschen.
Hier spielt also das Gut selbst überhaupt keine Rolle was wir tauschen. Es
geht nur darum, die Mengen von oben nach unten durch zu bekommen.
Die obersten drei ZA werden quasi immer leer geschaufelt zum runter
handeln. Alle weiteren ZA darunter werden nicht geleert sondern nach und
nach angehäuft, verkauft, verschenkt oder ausgegeben.
Wenn man vernünftig haushaltet, dann entsteht kein Loch in der Güterkette
und man hat immer genügend Vorrat von jedem Gut.
Natürlich hat man eine Zeitlang von irgendeinem Gut mal mehr mal weniger.
Aber das gleicht sich beim nächsten Handel wieder aus.

Um das einfach zu halten, soll es so wenig wie möglich Arbeit beim
einstellen der Güter machen. Also keine unnötigen Angebote.
Und gleichzeitig soll aber immer von jedem Gut irgendwas im Handel sein,
falls irgendwer gerade was annehmen will, dann muss was drin stehen.
Und es soll für den der annimmt die ideale Kombination und Menge sein,
damit er auch immer unsere Angebote annimmt und nicht die der Konkurrenz.
Um das einstellen zu können, müsste man wissen wer denn welche Angebote
annimmt.
Wenn sich da zeigt, dass immer mal wieder derselbe kommt, dann kann man
entsprechend seinem Handelsverhalten etwas stricken oder aber mit ihm
direkt in Kontakt treten.
Auch müsste man sehen können, welche Angebotsverhältnisse am besten laufen,
also welche Güter gehen in welcher Angebotsmenge und im Idealfall bei wem
weg.

Das Sheet nun ist gerade in der Entstehung. Also nichts von dem was du
siehst ist wirklich fertig. Wir überlegen noch, was man aus den Daten noch
an Infos zusammen ziehen kann und wie man das alles darstellt, ohne das es
einen erschlägt.

Wir übernehmen jetzt also die Daten vom foe Helper.
Das Sheet sortiert die Angebote nach ZA.
Dann prüft es, ob die Angebote korrekt sind.
Wir haben drei Vorteils-Stufen -10, -20, -30. Alles was darunter oder
darüber liegt gilt als Fehleingabe und wird so angezeigt.
Aktuell baue ich hier gerade an der ZA Prüfung. Also ob man sich beim
Einstellen nicht vertan hat und wirklich nur ein ZA tiefer eingestellt hat.
Dann prüft es auf fehlende Konstellationen. Also es soll immer ein
Großbuchstabengut des hohen ZA mit jedem Kleinbuchstabengut ein ZA darunter
kombiniert werden.
A mit a, b, c, d, e
B mit a, b, c, d, e
C mit a, b, c, d, e
usw und zeigt die fehlenden Kombinationen an.
Es zeigt an, in welchem ZA die Güter hängen bleiben.
Es zeigt die Gesamtmenge an Gütern an die aktuell zur Verfügung steht
(falls man Güter zurück ziehen will um ein anderes Angebot zu basteln, oder
für sonst was verwenden will)
Es weist aus, wie weit man von der maximal möglichen Anzahl an Angeboten
(1000) noch weg ist.
...ich glaube das wars bisher...

Und wie ich beim basteln gerade festgestellt habe, weist der foe Helper
(mindestens) ein Gut falsch aus. Da hab ich mir jetzt erstmal einen Wolf
gesucht, warum das Sheet was falsches anzeigt :D
[image: image.png]


Was ich auch noch fragen wollte - die Investitionsanzeige wird nicht
korrekt aktualisiert. Also die Anzeige wo meine Punkte drin stecken.
Wie kann die sich denn überhaupt aktualisieren, wenn der Spieler nicht mehr
mein Nachbar ist und damit gar nicht mehr auf der aktuellen Webseite drauf
ist?

Hier der Link zum Sheet:
https://docs.google.com/spreadsheets/d/14dYjUA4zJ-xUNJDed1Rkl3DqB7MME4O75X7cL0gjWMI/edit?usp=sharing






Am Di., 6. Juli 2021 um 19:24 Uhr schrieb Gindi4711 <
***@***.***>:

**Comment by Selene443Foe** [comment]
Ich hab garnicht geguckt - das steht jetzt (mit dem Link) so aber nicht auf GitHub oder??? 
🤯😳😳🤯

⁣BlueMail for Android herunterladen ​

Am 7. Juli 2021, 01:29, um 01:29, Selene FoE ***@***.***> schrieb:
>Das Prinzip ist so:
>Wir (FMA, Kolo und PoMo) produzieren/bekommen zum einen täglich Venus
>Güter
>und wir bekommen in unregelmäßigen Abständen Angebote wo Spieler
>Astrogüter
>gegen verschiedene untere Güter tauschen.
>Das heißt, es kommen immer mal wieder / mehr oder weniger regelmäßig,
>hohe
>Güter bei uns an die wir immer nach unten tauschen.
>Hier spielt also das Gut selbst überhaupt keine Rolle was wir tauschen.
>Es
>geht nur darum, die Mengen von oben nach unten durch zu bekommen.
>Die obersten drei ZA werden quasi immer leer geschaufelt zum runter
>handeln. Alle weiteren ZA darunter werden nicht geleert sondern nach
>und
>nach angehäuft, verkauft, verschenkt oder ausgegeben.
>Wenn man vernünftig haushaltet, dann entsteht kein Loch in der
>Güterkette
>und man hat immer genügend Vorrat von jedem Gut.
>Natürlich hat man eine Zeitlang von irgendeinem Gut mal mehr mal
>weniger.
>Aber das gleicht sich beim nächsten Handel wieder aus.
>
>Um das einfach zu halten, soll es so wenig wie möglich Arbeit beim
>einstellen der Güter machen. Also keine unnötigen Angebote.
>Und gleichzeitig soll aber immer von jedem Gut irgendwas im Handel
>sein,
>falls irgendwer gerade was annehmen will, dann muss was drin stehen.
>Und es soll für den der annimmt die ideale Kombination und Menge sein,
>damit er auch immer unsere Angebote annimmt und nicht die der
>Konkurrenz.
>Um das einstellen zu können, müsste man wissen wer denn welche Angebote
>annimmt.
>Wenn sich da zeigt, dass immer mal wieder derselbe kommt, dann kann man
>entsprechend seinem Handelsverhalten etwas stricken oder aber mit ihm
>direkt in Kontakt treten.
>Auch müsste man sehen können, welche Angebotsverhältnisse am besten
>laufen,
>also welche Güter gehen in welcher Angebotsmenge und im Idealfall bei
>wem
>weg.
>
>Das Sheet nun ist gerade in der Entstehung. Also nichts von dem was du
>siehst ist wirklich fertig. Wir überlegen noch, was man aus den Daten
>noch
>an Infos zusammen ziehen kann und wie man das alles darstellt, ohne das
>es
>einen erschlägt.
>
>Wir übernehmen jetzt also die Daten vom foe Helper.
>Das Sheet sortiert die Angebote nach ZA.
>Dann prüft es, ob die Angebote korrekt sind.
>Wir haben drei Vorteils-Stufen -10, -20, -30. Alles was darunter oder
>darüber liegt gilt als Fehleingabe und wird so angezeigt.
>Aktuell baue ich hier gerade an der ZA Prüfung. Also ob man sich beim
>Einstellen nicht vertan hat und wirklich nur ein ZA tiefer eingestellt
>hat.
>Dann prüft es auf fehlende Konstellationen. Also es soll immer ein
>Großbuchstabengut des hohen ZA mit jedem Kleinbuchstabengut ein ZA
>darunter
>kombiniert werden.
>A mit a, b, c, d, e
>B mit a, b, c, d, e
>C mit a, b, c, d, e
>usw und zeigt die fehlenden Kombinationen an.
>Es zeigt an, in welchem ZA die Güter hängen bleiben.
>Es zeigt die Gesamtmenge an Gütern an die aktuell zur Verfügung steht
>(falls man Güter zurück ziehen will um ein anderes Angebot zu basteln,
>oder
>für sonst was verwenden will)
>Es weist aus, wie weit man von der maximal möglichen Anzahl an
>Angeboten
>(1000) noch weg ist.
>...ich glaube das wars bisher...
>
>Und wie ich beim basteln gerade festgestellt habe, weist der foe Helper
>(mindestens) ein Gut falsch aus. Da hab ich mir jetzt erstmal einen
>Wolf
>gesucht, warum das Sheet was falsches anzeigt :D
>[image: image.png]
>
>
>Was ich auch noch fragen wollte - die Investitionsanzeige wird nicht
>korrekt aktualisiert. Also die Anzeige wo meine Punkte drin stecken.
>Wie kann die sich denn überhaupt aktualisieren, wenn der Spieler nicht
>mehr
>mein Nachbar ist und damit gar nicht mehr auf der aktuellen Webseite
>drauf
>ist?
>
>Hier der Link zum Sheet:
>https://docs.google.com/spreadsheets/d/14dYjUA4zJ-xUNJDed1Rkl3DqB7MME4O75X7cL0gjWMI/edit?usp=sharing
>
>
>
>
>
>
>Am Di., 6. Juli 2021 um 19:24 Uhr schrieb Gindi4711 <
***@***.***>:

**Comment by Selene443Foe** [comment]
Stand doch auf GitHub 🙈
Habs dort gelöscht und hoffe dass es bei dir als Email noch da ist...

[Selene FoE - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=13tw7n)	[13tw7n]

**Comment by Selene443Foe** [comment]
...was noch cool wäre, wenn man seinen eigenen Güterstand importieren könnte. 
Dann könnte man im Sheet sich Limits für das entsprechende ZA setzen, wenn man bestimmte Güterstände nicht unterschreiten will. Vielleicht spart man ja irgendwas an. 
Dazu entsprechend die fehlenden Konstellationen ausweisen. 

Und ja, ich weiß. Das ist alles sehr speziell und wahrscheinlich wird sich für die Allgemeinheit nicht soo viel davon als brauchbar erweisen, als dass man das direkt in den FoE helper einbauen könnte / sollte. 

Daher die Anfrage, für die entsprechenden Importfunktionen. 


⁣Gesendet mit BlueMail ​

**Comment by Selene443Foe** [comment]
Auch cool wäre, wenn der foe helper "live aufpassen" würde wenn man ein Angebot einstellt, ob man sich nicht vertan hat. Der PC Handel ist ja für sowas prädestiniert so gruselig wie der gestaltet ist. 
Jetzt muss man erst den Handel in das Sheet importieren. Das Sheet prüft auf Richtigkeit und man geht dann im Zweifel wieder in den Handel zurück das falsche Angebot suchen und korrigieren.

Und ja - man könnte den Faktor beachten. Aber der meldet nicht, wenn man sich im ZA vertut. 


⁣Gesendet mit BlueMail ​

**Comment by Selene443Foe** [comment]
Ja, du siehst, Ameise Selene ist schon wieder wie früher am Ideen sprudeln 🙈

⁣Gesendet mit BlueMail ​

**Comment by Selene443Foe** [comment]
...die Frage nach der Investitionsanzeige - ich glaube mir ist es wieder eingefallen. 
Das ist dasselbe Problem wie beim Moppeln. Das Rathaus muss doch bestimmt erst wieder im richtigen Fenster geöffnet werden...
Muss ich nachher Mal testen. 

⁣Gesendet mit BlueMail ​

**Comment by Selene443Foe** [comment]
...und - was mir gerade auffällt - man sieht nirgends seinen "echten" Güterbestand. Also das, was man im Inventar hat + das, was im Handel steht, aber noch nicht angenommen wurde und somit noch zu meinen Gütern gehört.

**Comment by Gindi4711** [comment]
So nachdem das nächste Update ziemlich fertig ist, habe ich Zeit um mich wieder ein paar neuen Baustellen anzunehmen :D

1.) Ich denke, dass die Export Optionen etwas zu spezifisch sind, da alle anderen, die dein Excel Sheet nicht haben, damit wahrscheinlich nicht allzu viel anfangen können, vor allem, da du ja mehrere Export Optionen brauchst.

Ich denke es würde eher Sinn machen, das Ganze gleich als eigenes Tool in den Helfer zu integrieren. Damit würden sich einige Probleme lösen lassen z.B.:
.) Wenn das Tool selbst weiß welche Handel im Markt stehen sollen, muss man nicht durch das RH scrollen. Da reicht es einfach den Markt aufzurufen und Soll/Ist Vergleich zu machen. Dann weiß das Tool ja welcher Handel entweder angenommen oder 
zurück gekommen ist und kann anhand des aktuellen Lagerstandes vorschlagen, den Handel entweder zu erneuern oder nicht.
.) Man muss nicht immer ständig alles hin und her kopieren
.) Die irrtümlich rein gestellten Handel: Ohne zu wissen was der Spieler rein stellen sollte ist das schwer möglich. Woher soll das Tool z.B. wissen, ob mein 1:1 Handel Mars gegen VZ Absicht war oder nicht.

Dazu würde ich das Excel Sheet aber gerne zuerst einmal sehen, damit ich weiß, auf was ich mich einlasse :D
Leider ist in meinem Email Postfach nichts mehr, da ich auf Github die Email Benachrichtigungen aus habe. Kannst du mir den Link noch mal per privater Nachricht (z.B. Discord oder falls WhatsApp falls du meine Nummer noch hast) zuschicken.

2.) Eine komplette Aktualisierung der Investitionsanzeige passiert nur, wenn man die Liste der legendären Gebäude im RH öffnet. Dazwischen gibt es zwar ein paar kleinere Updates wenn man z.B. irgendwo einzahlt aber den Großteil bekommt man nur mit, wenn man die Übersicht öffnet.

3.) Was den "echten" Güterbestand angeht, so gibt es hier 3 verschiedene Standpunkte:
a) Man geht davon aus, dass alles, was in den Markt gestellt wird auch früher oder später angenommen wird und rechnet schon mit den nachgefragten Gütern.
b) Man stellt generell viel Zeugs in den verschiedensten Kombinationen in den Markt zu Konditionen, die für einen selbst günstig sind (z.B. 1:1.1 im selben ZA). Man geht davon aus, dass die Handel noch nicht getauscht sind und man sie jederzeit wieder auflösen könnte, wenn man die Güter selbst benötigt
c) Man weiß nicht, was angenommen wird und was nicht und geht deshalb vom Worst case für beide Güter aus. Das ist das, was man sieht wenn man in das Inventar sieht.

Deshalb ist es schwierig hier eine Anzeige zu schaffen, mit der alle glücklich sind. Ich müsste also alle 3 Werte anzeigen.
