### ISSUE TITLE
Feature Request: Kosen für Freischaltung von GEX errechnen und Gildengütern gegenüberstellen

### ISSUE THREAD

**Issue by roadrash2108** [mainIine/foe-helfer-extension#2082]
Hallo,

bin großer Fan des FOE-Helpers und wir nutzen das auch zur Übersicht, welche Güter von wem über welche LG kommen. Dementsprechend wäre es total hilfreich, wenn die Kosten für die Freischaltung der GEX (https://de.wiki.forgeofempires.com/index.php?title=Gilden-Expeditionen:_Freischalten_der_Schwierigkeitsstufen) dem gegenübergestellt werden könnten.

Eine Idee wäre den Tab "Zeitalter" und/oder "Gildengüter" der "Gilden Mitglieder Übersicht" zu erweitern und rechts daneben die Kosten für die Freischaltung der GEX anzuzeigen.

Viele Grüße

PS: Gerne würde ich auch mitarbeiten - gibt es eine Anleitung, wie man am besten mitentwickelt?

**Comment by Parama91** [comment]
Genügt es dir die Güter auf Zeitalter Ebene oder willst du wirklich die Güter pro Spieler vergleichen?

Zeitalter würde ich dann im Tab "Gildengüter" und pro Spieler im "Gildenmitglieder" vorschlagen, passt dann so glaub ich am besten dazu.

**Comment by roadrash2108** [comment]
Es würde meiner Meinung nach schon reichen, wenn die Güter pro Zeitalter angezeigt/verglichen werden - so dass man gut sehen kann, wieviele Güter pro Zeitalter eingebracht werden durch die Gildengebäude und wieviele pro GEX-Runde benötigt werden.

**Comment by roadrash2108** [comment]
Hi, das ist jetzt kommentarlos geschlossen worden - PR dazu finde ich keinen, daher nehme ich an, dass das abgelehnt wurde. Wäre es möglich irgendeine Form von Begründung für das Schließen zu bekommen?
