### ISSUE TITLE
Only show new version popup when the game is actually active

### ISSUE THREAD

**Issue by Sepherane** [mainIine/foe-helfer-extension#2093]
It's incredibly annoying to always get this popup when the extension updates, even when the game isn't open on any of the tabs, which makes asking to reload the game pointless. So I suggest only showing this message immediately if the game is open in the current tab, or if the game is open in any tab, when the player switches to that tab.

**Comment by JhonnyBn** [comment]
An option to disable this popup entirely would be nice as well
