### ISSUE TITLE
Coin production numbers increase every time Production overview is closed and reopened

### ISSUE THREAD

**Issue by CedarB** [mainIine/foe-helfer-extension#2094]
Chrome OS 91.0.4472.147 64-bit
Chrome 91.0.4472.147
us22 (Walstrand)
2.5.9 English

If the Production Overview is closed and then reopened, the coin production values that are listed increase. They reset when the game is reloaded.

**Comment by Gindi4711** [comment]
Seems like the 20% boost generated by happiness is applied multiple times for for coins and supplies.

**Comment by Gindi4711** [comment]
Fixed in next update
