### ISSUE TITLE
Liste der Ereignisse mit Mouseover anzeigen - Feature request

### ISSUE THREAD

**Issue by Parama91** [mainIine/foe-helfer-extension#2106]
Derzeit hat die Box der Ereignisse ja keine Funktion, sie informiert nur über die vorhandenen Ereignisse. Dies könnte man vereinfacht per Mouseover beim Icon auch anzeigen, dann braucht man keine Box auf-/zumachen und sieht trotzdem auf einem Blick was herumliegt.

**Comment by outoftheline** [comment]
Je nach Positionierung der Box und Platz auf dem Bildschirm sehe ich hier Probleme auf uns zu kommen. Deshalb würde ich das lieber konstistent halten.

**Comment by Parama91** [comment]
Passt, dann schließe ich das mal wieder. ;)
