### ISSUE TITLE
Player's ID in ScoreDB link is undefined

### ISSUE THREAD

**Issue by JhonnyBn** [mainIine/foe-helfer-extension#2108]
In the Guild Member Overview box, Great Buildings tab, the first member in each of some great buildings list has a link for ScoreDB with undefined ID: https://foe.scoredb.io/BR6/Player/undefined

![image](https://user-images.githubusercontent.com/29382833/126850288-2596bd6c-9119-42de-bc90-5b916fdd95b7.png)

![image](https://user-images.githubusercontent.com/29382833/126851164-8b87ffed-1bb9-44b3-9e1b-069d97bbbc27.png)

**Comment by Gindi4711** [comment]
It happened to one player in each group. Name change has no influence.

This will be fixed in the next update
