### ISSUE TITLE
Tab "Rangliste" von Funktion "GEX-Ergebnisse" zeigt keine Daten

### ISSUE THREAD

**Issue by roadrash2108** [mainIine/foe-helfer-extension#2114]
Betriebssystem: Windows 10
Verwendeter Browser inkl. Versionsnummer: Firefox 90.0.2 (64-Bit)
Forge of Empires Server: de6
Extension Version und Sprache der Extension: 2.5.9 / de
Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln):
unreachable code after return statement
dexie-export-import.js:1689:16
Die drawWindow-Methode von CanvasRenderingContext2D ist veraltet. Verwenden Sie stattdessen die Erweiterungs-API tabs.captureTab https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab pagedata-script.js:1:12465
mozImageSmoothingEnabled sollte nicht mehr verwendet werden. Bitte verwenden Sie die Eigenschaft imageSmoothingEnabled ohne Präfix stattdessen. ForgeHX-dcad0a52.js:1425:396
WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. 26
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2021-07-29T17:2:23, _f: undefined, _strict: undefined, _locale: [object Object]
t/<@moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/vendor/moment/moment-with-locales.min.js?v=2.5.9:16:3368
va@moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/vendor/moment/moment-with-locales.min.js?v=2.5.9:16:21539
Sa@moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/vendor/moment/moment-with-locales.min.js?v=2.5.9:16:22250
Ha@moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/vendor/moment/moment-with-locales.min.js?v=2.5.9:16:22332
l@moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/vendor/moment/moment-with-locales.min.js?v=2.5.9:16:209
update@moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/js/web/alerts/js/alerts.js?v=2.5.9:1042:21
setActions/<@moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/js/web/alerts/js/alerts.js?v=2.5.9:1420:30
dispatch@https://foede.innogamescdn.com//cache/merged-3rd-party-c92e8acd.js:3:43064
add/v.handle@https://foede.innogamescdn.com//cache/merged-3rd-party-c92e8acd.js:3:41048
moment-with-locales.min.js:16:2962
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://13e482fd-5f73-480d-8fa3-720006d81b28/vendor/dexie/dexie-export-import.js?v=2.5.9
Source-Map-Adresse: dexie-export-import.js.map

​
Sind andere Extensions installiert? ja, AdBlock Plus, Cookie Editor, Video Download Helper, dict.cc

Der Bug ist, dass in der neuen GEX-Übersicht im Tab "Rangliste" immer die Meldung kommt "Keine Daten vorhanden! Bitte besuche die Ergebnisseite der GEX-Übersicht um die Daten zu aktualisieren" - obwohl ich das mache, kommen keine neuen Daten. Die Tabs "Mitgliederbeteiligung" und "Verlauf" füllen sich aber korrekt!?

**Comment by danielvoigt01** [comment]
Die Warnungen können erst einmal nicht der Grund für den Fehler sein. Hast du wie im Bild unten auf beide Stellen geklickt um die Daten zu holen bzw. zu aktualisieren?
![Auswahl_053](https://user-images.githubusercontent.com/46729881/127487139-ce857c21-71d7-4c7d-b7b5-f06c84650379.jpg)

**Comment by roadrash2108** [comment]
Oh, jetzt hab ich den Zusammenhang verstanden! Der Tab "Rangliste" bezieht sich auf die Gilden-Rangliste (bei Dir im Bild mit "1" beschriftet) - dort hab ich nie hingeklickt (weil es mich auch gar nicht so interessiert). Hatten an eine Rangliste innerhalb der Mitglieder gedacht und war verwirrt.

Dann werden die Daten eh richtig gesammelt und alles passt - danke für die Klärung!
