### ISSUE TITLE
GB Investment tool says Atlantis Museum gives twice the goods it actually does

### ISSUE THREAD

**Issue by djjeffers** [mainIine/foe-helfer-extension#2116]
Title should be a good enough summery of the issue.

https://github.com/mainIine/foe-helfer-extension/blob/master/js/web/greatbuildings/js/greatbuildings.js#L56

**Comment by Gindi4711** [comment]
You are right. Seems the wikia was wrong a few months ago when I copied the values.

**Comment by Gindi4711** [comment]
Fixed in next update
