### ISSUE TITLE
Load old city everytime

### ISSUE THREAD

**Issue by Kayfos9** [mainIine/foe-helfer-extension#2118]
Hello.
every time i want to load a new city, it runs my old city. What am I doing wrong?

**Comment by Kayfos9** [comment]
Jedes Mal, wenn ich im Foe-Helfer meine neue Stadt nach dem Umbau laden möchte, lädt er meine alte Stadt. Warum?

**Comment by mainIine** [comment]
Hört sich an als ob Du von unserer API wegen einer falschen oder stark
veralteten Version gesperrt wurdest.

Schick mir doch bitte mal deine Spieler ID + Welt (Kennung deXX)

>

**Comment by Kayfos9** [comment]
ID: 4023650 
Rugnir

**Comment by Kayfos9** [comment]
Ach so....und ich habe 2 Monitore und habe die Stadtübersicht auf den anderen Monitor ziehen wollen und dann war sie auf einmal weg. Nun zeigt er mir gar nichts mehr an

**Comment by Kayfos9** [comment]
de.17

**Comment by Kayfos9** [comment]
Einstellungen vom Helfer > Erweiterung > Box Koordiniaten > "Löschen!"

Super! Das hat schon mal geklappt, nur noch nicht das Laden der Stadtdaten

**Comment by mainIine** [comment]
Hab einen Eintrag zu Dir gefunden: " Geblockt wegen falscher oder fehlender
Version!"

Mit welcher Version spielste denn? Offenbar nicht mit der richtigen.

Am Do., 5. Aug. 2021 um 12:00 Uhr schrieb Kayfos9 ***@***.***

**Comment by Kayfos9** [comment]
Version: 2.5.9.1

**Comment by Kayfos9** [comment]
Mittlerweile. Ich habe gehofft, dass durch die neue Version das Problem nicht mehr existiert.

**Comment by Kayfos9** [comment]
Ist das die falsche Version?

**Comment by mainIine** [comment]
Ich hab Dich entsperrt. Bleib immer bei der aktuellen, ansonsten kommt die Sperre direkt wieder. Das ist automatisch.

**Comment by Kayfos9** [comment]
Super!!! Es hat geklappt! VIELEN DANK!  - Wann erfahre ich, dass eine neue Version kommt?

**Comment by Gindi4711** [comment]
Am Besten lässt du die Auto Update Funktion des Browsers bei den Extensions aktiv.

Aber keine Sorge: Es gibt keine Banns nur weil du nicht ganz das aktuelle Update hast.
Die Banns verteilen wir für Bestimmte ganz alte Versionen vor über einem Jahr. Grund ist, dass diese Features enthalten, die nach der aktuellen Regelauslegung von Inno nicht mehr erlaubt sind.
Da diese alten Versionen teitweise aktiv verteilt wurden und sich sozusagen ein Schwarzmarkt dafür entwickelt hat haben wir beschlossen. dass wir diesen Spielern den Zugang zu unserem Server sperren.
