### ISSUE TITLE
FoE-Helfer Import/Export

### ISSUE THREAD

**Issue by Hugra** [mainIine/foe-helfer-extension#2119]
Hallo, ich habe ein kleines Problem beim Import/Export beim FoE-Helper
Version     2.5.9.1 - Win10 - Firefox aktuell.
Wenn ich im Menue "Einstellungen"- "Erweitert" - "Import/Export" die ganze Vorschläge Exportiere werden zwei Files angelet einmal xxx.zip und xxx.har. Egal welche von den beiden Dateien ich Importieren möchte kommt eine Fehlermeldung. "Diese Datei kann nicht verarbeitet werden oder hat nicht das richtige Format".
Kann mir jemand erklären wie ich richtig Importiere bzw. Exportier

**Comment by danielvoigt01** [comment]
Also eine har Datei erzeugen wir nicht beim Export. Das klingt nach einer anderen Browser-Erweiterung die da mit eine Rolle spielt. Was für Dateien sind denn in der zip Datei enthalten und wie lautet der Dateiname der exportieren zip Datei?

**Comment by Hugra** [comment]
Am Rechner wurde der Cach gelöscht. mit CCleaner den Speicher gesäubert.
HAR-Datei wird nicht mehr erzeugt. Fehler meldung die gleiche. Zip in anhang
[de19_foe_helper_export_210805-2016_850332767.zip](https://github.com/mainIine/foe-helfer-extension/files/6940891/de19_foe_helper_export_210805-2016_850332767.zip)

**Comment by danielvoigt01** [comment]
Kannst du bitte die Daten mal ohne die "lokalen Einstellungen" exportieren und testen ob der Import dann fehlerfrei durchläuft?

**Comment by Hugra** [comment]
Exportiere ich nur die "lokalen Einstellungen" kommt keine Fehlermeldung,aber er verharrt im Lademodus.
Exportiere ich 2 oder mehr der restlichen Dateien kommt die Fehlermeldung.
eine einzelne Datei, ausser "lokare Einstellungen" kann nicht Exportiert werden.

**Comment by danielvoigt01** [comment]
Danke dir! Ich habe einen Fehler gefunden, welcher bei dir zu Problemen beim Import deiner lokalen Einstellungen geführt hat. 
Ich werde das Ganze morgen nochmal in Ruhe testen und dann sollte der Import bei dir nach dem nächsten Update funktionieren.
