### ISSUE TITLE
Feature Request: GvG Overview. Neutral sectors.

### ISSUE THREAD

**Issue by LordFelix** [mainIine/foe-helfer-extension#2120]
In the GvG Overview, request the neutral sectors to have a line at the bottom (preferably separated from the guild ones) to reflect the information about neutral sectors.
Specifically, the number and total power of neutral sectors in a given GvG era.

**Comment by outoftheline** [comment]
Just wondering if the total power of an era would be interesting to know? I could include a "total" somewhere.

**Comment by LordFelix** [comment]
I believe it would also be interesting, yes.
