### ISSUE TITLE
idee: Siedlung Benötigte Münzen letzte Quest

### ISSUE THREAD

**Issue by HAL09001** [mainIine/foe-helfer-extension#2125]
Ich fände es hilfreich wenn zusätzlich noch die benötigten Münzen für die letzte Quest angezeigt würden, ähnlich wie bei dem Screenshot. 
![image](https://user-images.githubusercontent.com/48470058/128982160-de2d7a17-2ad9-4524-a47f-eb31c8928503.png)
Wobei ich nicht die münzen für die Quest selber meine, sondern die Münzen für die Güterproduktion, so wie es ja bisher auch ist. Die Münzen für die Quest selber könnte man evtl. anders darstellen.
Das macht einem die Planung für Münzen einfacher.

**Comment by Parama91** [comment]
Die Münzen für die letzte Quest würde ich da jetzt nicht auflisten, da das wirklich die Güter/Münzen sind die man schon im Vorhinein ansammeln kann um dann in einem Zug durch die Questreihe zu rauschen. Aber das mit den zusätzlichen Münzen für die letzte Quest hört sich plausibel an, ist das bei jeder Siedlung gleich? Also 4 unterschiedliche Güter und jeweils 10 Stück davon? (Hab derzeit nur Wikinger gezockt)

**Comment by HAL09001** [comment]
Hi, leider ist es nicht so einfach:

Azteken: 20. 3000 Kakao-Bohnen sammeln UND je 20 Güter sammeln ​​​​​​​(Gemüse, Kopfbedeckung, Mais, Steinfiguren)
Ägypten: Sammle 30.000 Deben UND 30 Gerste, 30 Keramik, 30 Blumen, 30 Opfergaben
Japan: Ernte  2000 Koban und  10 von jedem Gut
Wikinger: Gather 10 of each Viking good and 2500 Copper Coins
Mughai: "Have 1,500 diplomacy" and "Gather 50 Basmati" and "Gather 50 Saree" and "Gather 50 Spices" and "Gather 50 Lotus"

Quellen:
https://gdz.bplaced.net/index.php/forum/showposts/index/topicid/118
https://gdz.bplaced.net/index.php/forum/showposts/index/topicid/89
https://gdz.bplaced.net/index.php/forum/showposts/index/topicid/50
https://gdz.bplaced.net/index.php/forum/showposts/index/topicid/161
https://forgeofempires.fandom.com/wiki/Mughal_Empire#Quests

**Comment by Parama91** [comment]
Wenn die Quests alle gleich bleiben, dann kann man das natürlich umsetzen. ;)

**Comment by Gindi4711** [comment]
1.) Die Frage ist hier, ob man die Münzen, die man für die letzte Quest produzieren muss hier abzieht oder nicht. Theoretisch könnte man ja eine 4/8h Produktion starten und bis die fertig ist die restlichen Münzen sammeln.

2.) Der Bedarf an Münzen hat sowieso noch eine sehr große Unschärfe, da das Tool immer vom Worst case ausgeht, dass man keine 4fach Produktion bekommt. Gerade wenn man schon die 15. Runde spielt wird der reale Münzbedarf in der Regel deutlich niedriger sein.

**Comment by HAL09001** [comment]
zu 1: Was da interessiert, ist wie viele Münzen brauche ich, damit definitiv ich alle Produktionen starten kann. Die zu sammelnden Münzen interessieren mich da eher nicht, das passiert ja während der Produktion.
Hintergrund ist, dass ich oft zu viele Münzen habe und dann Münzproduktionen vorher Abreiße um Güter zu produzieren. 
Und da ist es mir schon passiert, dass ich mit 10 Gütern gerechnet hatte und 20 brauchte. Das hatte halt extra Zeit gekostet. Ich habe noch keine Ahnung was die Produktion im Mogul Reich kostet, aber 50 Produktionen dürften nicht so günstig sein.

zu 2. das ist für mich zumindest ok, mir geht es ja auch um den Worstcase. Und wenn ich die Münzen habe, sind Münzgebäude halt definitiv über.
