### ISSUE TITLE
Idee: Burgsystem Versuche anzeigen

### ISSUE THREAD

**Issue by HAL09001** [mainIine/foe-helfer-extension#2126]
Beim neuen Burgsystem gibt es ja verschiedene Counter, z.B. für Angriffe, Verhandlungen.
Was ich mir da wünschen würde, wäre eine Anzeige, ähnlich wie die für die Ereignisse, in denen die Anzahl der noch offenen Versuche angezeigt werden. Gerade die Angriffe & Verhandlungen fehlen mir gerade sehr.

**Comment by Gindi4711** [comment]
Inno sendet nicht die Anzahl der Versuche, die man noch hat, sondern lediglich die Anzahl der Punkte, die man für Kämpfe/Verhandlungen/GEX Stufen bekommt.
Hier müssten wir eine statische Tabelle hinterlegen (z.B. "20 Punkte aus Kämpfen bedeutet man hat noch 10 Kämpfe"). Falls Inno nicht vor hat diese Verteilung ständig zu ändern könnte man das grundsätzlich schon machen.

Die Frage, die ich mir stelle ist jedoch, ob die Burgen in ein paar Monaten für den Großteil der Spieler noch so interessant sein wird, dass sie dafür extra Kämpfen/Verhandeln gehen. Also ich lasse ehrlich gesagt jetzt schon die letzten 5 Verhandlungen sausen sobald mein Frachter verbraucht ist. Die paar Burgpunkte sind den Güterbedarf nicht wert.

**Comment by HAL09001** [comment]
Als Erinnerung, dass ich es noch nicht getan habe, fände ich es sehr nützlich. Selbst nur die Punkte Anzahl würde mir helfen, dann muss man da nix hinterlegen.

Das mit den Verhandlungen geht mir ähnlich, die letzten nutze ich selten. Gerade jedoch auf einer Welt wo es um LVL 2 der Burg ging, musste jeder Versuch ran. Und dort hätte mir auch noch eine Anzeige geholfen, wie viele Burgpunkte mir fehlen, so habe ich die LVL1 Truhe aufgemacht und damit die LVL 2 Truhe verschenkt. Da hätte ich mich über eine Box drüber wie bei den Kontinentkartenkämpfen gefreut. 

Aber ich befürchte, da hast du recht, ab LVL 7 der Burg interessiert das wahrscheinlich kaum noch.

**Comment by Alpha-Centauri-B** [comment]
Dieses Feature hätte ich auch gern.

**Comment by HAL09001** [comment]
Ist Implementiert, kann geschlossen werden.
![image](https://user-images.githubusercontent.com/48470058/148193830-6bfb3f25-8400-4c70-8edd-9780409e875c.png)
