### ISSUE TITLE
GB investment problem

### ISSUE THREAD

**Issue by ronintje** [mainIine/foe-helfer-extension#2134]
I have 14K fp invested in GB's according to helper, but i have nothing invested in GB's.

![GG investering fout](https://user-images.githubusercontent.com/65129679/131197555-739a9bba-29db-4d4c-89ed-6d16a42a5502.png)

**Comment by Moofies** [comment]
The data is from 19-08 as you can see at the bottom right of the window. Weird. Have you tried deleting your cookies and "restarting" FoE Helper?

De data is ook van 19-08 zoals je rechts onderin het venster kan zien. Gek. Heb je al eens geprobeerd je cookies te verwijderen om FoE Helper opnieuw te "installeren"?

**Comment by danielvoigt01** [comment]
You need to visit the full GB list in your town hall touUpdate the Helper investment data.

**Comment by danielvoigt01** [comment]
Which version of the helper and which browser are you using?

**Comment by danielvoigt01** [comment]
And could you please test whether the list is updated again when you invest in a GB and then call up the overview of GBs in the Town Hall.

**Comment by ronintje** [comment]
> And could you please test whether the list is updated again when you invest in a GB and then call up the overview of GBs in the Town Hall.

That worked.

**Comment by danielvoigt01** [comment]
This  issue will be fixed with the next update.
