### ISSUE TITLE
Include "active" and "battles" in members export

### ISSUE THREAD

**Issue by Bozer-der-Barbar** [mainIine/foe-helfer-extension#2137]
Wenn exporting members information to CSV or JSON, it'd be helpful to include two additional pieces of information:

- **active (yes/no)** - if you select the option to keep track of members who have left the guild, these players are included in the export, but there's no way of differentiating these from active guild members
- **total number of battles** - besides the number of points a member has, it'd also be interesting to include the total number of battles a player has won.

**Comment by danielvoigt01** [comment]
A active member flag in the export data will be added with the next update.

Unfortunately, the total number of battles when clicking on the player or the guild overview is not transmitted by Inno, which is the reason why we are not able to display it.

**Comment by Bozer-der-Barbar** [comment]
Übertragen wird's schon, ist aber irgendwo versteckt.  Beispiel:

![image](https://user-images.githubusercontent.com/79040934/131492853-314d3863-cf74-44da-bad4-c6a82abacf26.png)

![image](https://user-images.githubusercontent.com/79040934/131492884-64a7a01a-1450-4a95-b0d1-8410ae57794a.png)

Aber toll, wenn schon mal die Angabe übertragen wird, ob ein Spieler aktiv ist oder nicht! 👍

**Comment by Bozer-der-Barbar** [comment]
Ein Traum!  😁

**Comment by danielvoigt01** [comment]
Ist im nächsten Update Beides mit enthalten.
