### ISSUE TITLE
LG-Investitionsliste wird nicht aktualisiert

### ISSUE THREAD

**Issue by Parama91** [mainIine/foe-helfer-extension#2138]
IST: Ist aktuell keine Investition in fremde LGs offen, heißt es kommt bei Rathaus -> Neuigkeiten -> Legendäre Bauwerke kein Eintrag von FOE, dann wird auch die Liste der Investitionen nicht aktualisiert und die alten Einträge bleiben drinnen.

SOLL: Liste sollte selbst ohne aktive Investitionen aktualisiert werden und keine Einträge anzeigen.

**Comment by danielvoigt01** [comment]
Ist mit dem nächsten Update behoben.
