### ISSUE TITLE
Idea: add update date column to investments

### ISSUE THREAD

**Issue by Bozer-der-Barbar** [mainIine/foe-helfer-extension#2141]
The investments list offers a great overview of what's been invested where, what the profit is, etc.  It also includes information on the history of subsequent investments in the GB, i.e. when others have invested in the GB after my initial investment.  What would be cool is if the last updated date were available as a sortable column so that I can quickly see where there's been recent activity.

![image](https://user-images.githubusercontent.com/79040934/131860758-66dd123f-2863-4e3c-8de2-9ad63c75737a.png)

**Comment by danielvoigt01** [comment]
optionally selectable after the next update:
![Auswahl_055](https://user-images.githubusercontent.com/46729881/131889052-fd03b8f5-5ad4-4214-8288-daccbd5b428d.jpg)

**Comment by Bozer-der-Barbar** [comment]
Wow!! 👍
