### ISSUE TITLE
Open cost Calculator automatically

### ISSUE THREAD

**Issue by tMFh225** [mainIine/foe-helfer-extension#2143]
1: Is there anyway to add a feature when opening up a players gb & instead of having to open up the cost calculator- It pops up automatically? & when you exit the gb then the cost calculator goes away? 
Also is it possible 

2: Also is it possible to have the cost calculator work for the owner gb? So say when power leveling through a gb you can have the cost calculator open for easy access to numbers?

**Comment by tMFh225** [comment]
I seen gb calculator for owner so I guess that removes the 2:. But the auto open calculator for other players gb would be awesome

**Comment by Gindi4711** [comment]
There are 2 tools:

GB Cost calculator is used from the perspective of the investor and shows how much you need to pay for 1.9 (or whichever percentage you want) and if the place is save.
This algorithm only works for GBs of other players and does not make sense for your own.

GB calculator gives you a full investment plan for the current level and shows show much the owner and all places have to pay and in which order. Also it can generate copy strings that you can paste in 1.9 groups.
GB calculator works for your own GBs AND GBs of other players.

For speedleveling I suggest using GB calculator.
For regular 1.9 groups I suggest using GB calculator if it is your GB and cost calculator when investing into a GB.

For the auto open idea:
.) Auto open would be possible, but I think this will be annoying pretty fast. Also I do not know if you want to use cost calculator of GB calculator.
.) Auto close is not possible as we cannot grab that event without client/server communication, but GB/cost calculator will refresh its content if you ipen another GB, so if you have a bigger screen it might be best to keep them open while clicking through your GBs/1.9 groups
