### ISSUE TITLE
[Idea] - Log number of finished (recurring) quests

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#2144]
Show the amount of (recurring) quests that were finished. Maybe next to, or under the "skipped quests" counter.

**Comment by Gindi4711** [comment]
You mean the sum of recurring quests finished per day?
Or the number of recurring quests that are done and ready to collect the reward?

**Comment by Arklur** [comment]
The sum of recurring quests finished per day. I know it's somewhat comes from how much quests you skipped, but in some cases, for example, I'm not skipping some of those quests, and would be better to see a more "precise" number of finished quests (because of CF).
