### ISSUE TITLE
PRODUCTION OVERVIEW

### ISSUE THREAD

**Issue by PRAGAL11** [mainIine/foe-helfer-extension#2155]
Production overview box is empty, does not show when collections are due. Problem only in Beta server

**Comment by Gindi4711** [comment]
This was fixed in update 2.5.9.2 see this thread: https://github.com/mainIine/foe-helfer-extension/issues/2122

For Firefox users the update should already be available
For Chrome users the update is still in validation by Google and should start rolling out soon

**Comment by PRAGAL11** [comment]
Thank you
