### ISSUE TITLE
[Statistics module] Wrong age inserted into database for units won

### ISSUE THREAD

**Issue by capshort** [mainIine/foe-helfer-extension#2157]
I am in Indy since one month and have camped LMA for at least 4 months. However, when I win units in GBG, PvP Arena or from a relic they always show up as HMA units in the statistics. I've set a breakpoint here:
![Screenshot_20210922_182915_breakpoint](https://user-images.githubusercontent.com/25132855/134386035-fdac989a-2f0a-4ea8-a371-39a3af11f0a0.png)

Which yielded this when I won 5 heavy units of Indy (Howitzer - that's "Haubitze" in german):
![Screenshot_20210922_182955](https://user-images.githubusercontent.com/25132855/134386381-895171a3-d0fa-4cb8-a4d7-ff5855d0af80.png)

However, that is what I see when afterwards looking at the statistics for PvP arena (filtering only for today's rewards) where I won them:
![Screenshot_20210922_184705](https://user-images.githubusercontent.com/25132855/134386699-c8f082e8-5619-40bd-82b0-ab23b6639d83.png)
("Schwere Infanterie" is the HMA heavy unit, Heavy Infantry.)

I have also remarked this behaviour for units won from relics and GBG.

**Comment by Cady36** [comment]
I noticed this today. I was in LMA, and aged up to CA the first day of GBG. The troops I won were definitely CA troops. Statistics correctly shows the CA goods. But at one point, it was telling me I had won legionnaires and other odd troops. After exiting and fighting a couple of more battles, I pulled up statistics again, and some of the troops had changed - legionnaires disappeared - but still not to the CA troops I actually won.

![image](https://user-images.githubusercontent.com/52673062/149677663-d40e3bc5-adf5-445a-b973-dd1d66af9dde.png)
