### ISSUE TITLE
Bug: Power Levelling Temple of Relics

### ISSUE THREAD

**Issue by jolyonb** [mainIine/foe-helfer-extension#2158]
The power levelling window for Temple of Relics has a "double collection" amount for flipping the temple. However, the temple doesn't give any rewards directly, and so should have no double-collection.

Browser: Chrome
FoE Version: 1.213.3d29d2a161b (15.09.2021 14:26)
Helper Version: 2.5.9.2

**Comment by Gindi4711** [comment]
This is already fixed in the beta branch and will be released with the next update
