### ISSUE TITLE
"Production Overview" not working for new cities.

### ISSUE THREAD

**Issue by vmeloz** [mainIine/foe-helfer-extension#2161]
How to Reproduce:
1. Start a new city and complete the tutorial.
2. Click on "Production Overview"

The dialog does not open and the following is reported: "TypeError: Cannot read properties of undefined (reading 'value')".

Fix: https://github.com/vmeloz/foe-helfer-extension/commit/109ca4e33655591e9f9bfe088fc7c46c32df4cc7

**Comment by Gindi4711** [comment]
Will be fixed in next update
