### ISSUE TITLE
Production Overview colony update

### ISSUE THREAD

**Issue by gameoverbg** [mainIine/foe-helfer-extension#2162]
Hello,

When you go to colony from SAM, SAAB or SAV with no production buildings in it, the information from Production Overview disappear.

**Comment by Gindi4711** [comment]
Will be fixed in the next update

**Comment by Lokisenkel** [comment]
![screen_Produktionsübersicht](https://user-images.githubusercontent.com/89934896/135267363-97ca6fc4-fcb5-4eae-b7c7-cd3fc3dd59e5.jpg)

it also looks like this after visiting my colony with production buildings.
