### ISSUE TITLE
Statistik Güter ohne ZA

### ISSUE THREAD

**Issue by SmartCologne** [mainIine/foe-helfer-extension#2166]
Moin,

wie wäre es die FP mit in die Statistik aufzunehmen und gleichzeitig die Statistik etwas anzupassen / skalieren.
Denn bei hohen beständen von Münzen und Vorräten kleben die anderen Balken am Boden:

![image](https://user-images.githubusercontent.com/16509118/135214158-643c3528-fde5-4ee7-8eba-c8cc598b7695.png)

**Comment by HAL09001** [comment]
Evtl. Log Skalen umschaltung?

**Comment by SmartCologne** [comment]
Alles wird kommentarlos geschlossen?
