### ISSUE TITLE
Tabelle in Marktübersicht skaliert nicht korrekt

### ISSUE THREAD

**Issue by SwSoC** [mainIine/foe-helfer-extension#2195]
![image](https://user-images.githubusercontent.com/14109258/139391446-cd0ebcdd-b6ef-4504-8a9e-c7fbb5f4a790.png)
![image](https://user-images.githubusercontent.com/14109258/139391521-4ce564dc-b438-474c-9478-ecc845601111.png)

Wie auf den Bildern zu sehen, kann man zwar das Fenster verkleinern, die Tabelle hat jedoch eine minimale Größe, die nicht unterschritten werden kann. Diese ist "Kopfzeile"+ 4 Handelseinträge bzw. 14 Handelseinträge.

Verdeckt die Tabelle die Handelseinträge, Können diese nicht ausgewählt werden:
![image](https://user-images.githubusercontent.com/14109258/139392234-17452f78-b1f8-4896-8e33-f68dd068fd8d.png)

Windows 10, Chrome Version 95.0.4638.54

**Comment by outoftheline** [comment]
tritt das problem immer noch auf?

**Comment by SwSoC** [comment]
ist behoben, vielen Dank!
