### ISSUE TITLE
Negotiation Helper does not show on GB negotiations

### ISSUE THREAD

**Issue by MiroJ** [mainIine/foe-helfer-extension#2196]
I am using the extension in Edge and the Negotiation Helper is disabled for Guild Battlegrounds.

![image](https://user-images.githubusercontent.com/1686322/139397399-d98ab975-bae4-4263-942b-06f0eb537a87.png)

It shows and works well on Guild Expansions. The setting for Active is ON.

**Comment by Gindi4711** [comment]
This is by design. Inno requested negotiation helper to be disabled for GBG because it has a negative impact on balancing.
