### ISSUE TITLE
All Age buildings

### ISSUE THREAD

**Issue by Pumbaa672** [mainIine/foe-helfer-extension#2199]
I did not see anyone posting about this (if so than please delete this post).  In the production overview it is showing my all age and the auto aged buildings as an age that I would have never got them in.  Example I was never in Iron age when I received my 1st Sent Outpost.  But it is showing Iron age.  Another example is my Harvest field (scarecrow). They should be SAV and shows OF.  The goods are SAV.  On the city map everything is showing the correct age.

![image](https://user-images.githubusercontent.com/75749807/139587532-9ba464ad-212c-4313-8c08-316c78db4af2.png)

![image](https://user-images.githubusercontent.com/75749807/139587674-506442f6-7e23-4c98-982e-fc226b677995.png)

**Comment by Ed4now** [comment]
I have the same issueI have the same issue

**Comment by Beelzebob6666** [comment]
Well, it is not an issue, only cosmetics... but maybe we change it to be consistent with the city overview and display the current age.

When there is no production, the buildings age in the data is the age in which it was placed. When there is a production, the buildings age is the players current age.

**Comment by Gindi4711** [comment]
The planned behaviour is:
.) If the building is era specific (for example Blacksmith in Iron age) it should show that era.
.) If the building is a multi era building, but has a specific era (for example terrace farms) it should show that era. Those are the buildings you can upgrade with a level up kit.
.) If a building does not have an era (for example great buildings or buildings that are automatically upgraded) it should show the current era.

This should be consistent across all modules.

**Comment by Gindi4711** [comment]
Productions is still using an old code to determine era of a building.

Funny thing: 
Inno indeed sends BronzeAge era for some of the sentinel outposts although it should not have any era as it is an AllAge building.

Will be fixed with the next update
