### ISSUE TITLE
City map

### ISSUE THREAD

**Issue by Pumbaa672** [mainIine/foe-helfer-extension#2200]
The background on the city map has one of the load splash as its background.  Only on the live worlds.  Doesn't happen on Inno Beta world.

Live world
![image](https://user-images.githubusercontent.com/75749807/139587819-18961da9-35a8-4b83-bc3e-0bbd902bba45.png)

Beta world
![image](https://user-images.githubusercontent.com/75749807/139587922-d51eb581-2dcf-4ebc-b8cd-dc6e05ca35d6.png)

**Comment by oesi03** [comment]
das ganze ist passiert weil “Inno” eine Änderung an der Bezeichnung seines Start screens gemacht hat😂
jetzt gibt es eine Überschneidung mit dem FoE-Helfer. 

https://github.com/mainIine/foe-helfer-extension/blob/55525ef0d98511fcb89546352748e8e3d0de3b4b/js/web/citymap/js/citymap.js#L117
ändern in/change to:
w = $('<div />').attr({'id':'CityMapWrapper'});


https://github.com/mainIine/foe-helfer-extension/blob/55525ef0d98511fcb89546352748e8e3d0de3b4b/js/web/citymap/css/citymap.css#L25
ändern in/change to:
#city-map-overlayBody #CityMapWrapper {

**Comment by Pumbaa672** [comment]
I think it is "cool".  Only thing I would change is where the data is on the right to a solid background or put a dark outline on the data (so it would standout.
