### ISSUE TITLE
Position Ereignisse: cityUnderwater

### ISSUE THREAD

**Issue by komma4** [mainIine/foe-helfer-extension#2206]
see attachment

shows position:cityUnderwater 
and a tree
![2021-11-14_06-22](https://user-images.githubusercontent.com/10896749/141662194-3854a3ee-c1a9-442e-a565-cf6a5077fd08.png)
!
not able to find it

**Comment by Pilsvernichter** [comment]
Same to me, can't find it. It happens since a view days and it seems to available only for a view hours not for 24 hours as normall. Only seen in the morning around 7:00 am.

**Comment by Bozer-der-Barbar** [comment]
I get this every now and then, too.  I dumped everything to a HAR file and found two occurrences of "cityUnderwater" in the data.  Attached, please find the two lines from the HAR file.  The complete HAR is a 27 MB zip file that I can send if needed.

[cityUnderwater.zip](https://github.com/mainIine/foe-helfer-extension/files/7601606/cityUnderwater.zip)

**Comment by Parama91** [comment]
We (developers) also dont know what it is and where to find it, but right now we dont want to hide it. This occures since the last FoE update, so maybe part of a new feature, but as i said we dont know yet ;)

**Comment by outoftheline** [comment]
This incident - whatever it does - is hidden now.
