### ISSUE TITLE
[IDEA] Indicator of which guilds have moved their HQ in GvG

### ISSUE THREAD

**Issue by Bozer-der-Barbar** [mainIine/foe-helfer-extension#2209]
Was im GvG sehr hilfreich wäre ist wenn man wissen würde, ob eine andere Gilde deren HQ bereits verschoben hat oder noch die Möglichkeit, das zu tun und somit die Möglichkeit hat, weiter zu attackieren.

Wie ich mir eine Logik vorstellen könnte:

- Öffnet man eine ZA-Karte im GvG das erste Mal werden Datum/Uhrzeit und die Koordinaten der HQs der gegnerischen Gilden notiert
- Das nächste Mal, wenn man die ZA-Karte öffnet wird zunächst geprüft, ob's in derselben GvG-Runde ist, d.h. vor 20h des nächsten Tages.
  - Wenn ja (also innerhalb derselben GvG-Runde), wird geprüft, ob die HQs verschoben wurden
    - Wenn ja, der Sektor aber inzwischen einer anderen Gilde gehört, dann kennzeichnen, dass das HQ ggf. von der anderen Gilde geschoben wurde
    - Wenn ja, der Sektor aber immer noch derselben Gilde gehört, dann kennzeichnen, dass die Gilde das HQ geschoben hat
- Anschließend werden Datum/Uhrzeit und die Koordinaten wieder aktualisiert

**Comment by outoftheline** [comment]
Ich weiß nicht. Im Fall, dass der ursprüngliche HQ-Sektor der Gilde nicht mehr gehört - was in Kriegen ja ständig passiert - bringt das nicht viel. Ein HQ kann ja mehrfach geschoben werden und zusätzlich durch strategische Sektor-Freigaben ganz woanders landen als man vermuten würde. 
Mir wäre ein solcher Indikator zu unsicher, um damit planerisch irgendwas anfangen zu können.
