### ISSUE TITLE
GBG Negotiation Helper Not Working

### ISSUE THREAD

**Issue by mistybc87** [mainIine/foe-helfer-extension#2216]
Operating System- Windows 10 Home 64-bit

Browser- Google Chrome 96.0.4664.45 (Official Build) (64-bit)

FOE Server Information- 1.218.0a4c5fd81ac (24.11.2021 13:51), NinjaCatstronaut (9350724), us13, en_US, Windows 10, Chrome/96.0.4664.45, 1366x663, OpenGL Vendor=WebKit Version=WebGL 2.0 (OpenGL ES 3.0 Chromium) Renderer=WebKit WebGL GLSL=WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)

Extension Version/Language- 2.5.9.3 English

Other Extensions Installed- Google Docs Offline v 1.35.0
Chrome Apps Installed- Docs v 0.10, Sheets v 1.2, Slides v 0.10

Error Messages- FOE Helper version 2.5.9.3 started. ID: bkagcmloachflbbkfmfiggipaelfamdf
_main.js?v=2.5.9.3:2044 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
alerts.js?v=2.5.9.3:134 Alerts - Garbage collection failed
alerts.js?v=2.5.9.3:134 Error: EXT-API error: response timeout for: {"type":"alerts","playerId":0,"action":"getAll"}
    at Object.sendExtMessage (_main.js?v=2.5.9.3:1295)
    at async Object.refresh (alerts.js?v=2.5.9.3:341)
    at async Object.garbage (alerts.js?v=2.5.9.3:303)
index:1 The resource https://us13.forgeofempires.com/cache/ForgeHX-3531448d.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
2ForgeHX-3531448d.js:30246 Updating state in a binding
set @ ForgeHX-3531448d.js:30246
merged-3rd-party-02f0f892.js:3 The specified value "null" cannot be parsed, or is out of range.
(anonymous) @ merged-3rd-party-02f0f892.js:3
merged-3rd-party-02f0f892.js:3 The specified value "null" cannot be parsed, or is out of range.
(anonymous) @ merged-3rd-party-02f0f892.js:3
ForgeHX-3531448d.js:629 WebSocket connection to 'wss://us13.forgeofempires.com/socket/' failed: 
_connectToSocket @ ForgeHX-3531448d.js:629
ForgeHX-3531448d.js:629 WebSocket connection to 'wss://us13.forgeofempires.com/socket/' failed: 
_connectToSocket @ ForgeHX-3531448d.js:629
ForgeHX-3531448d.js:629 WebSocket connection to 'wss://us13.forgeofempires.com/socket/' failed: 
_connectToSocket @ ForgeHX-3531448d.js:629
ForgeHX-3531448d.js:629 WebSocket connection to 'wss://us13.forgeofempires.com/socket/' failed: 
_connectToSocket @ ForgeHX-3531448d.js:629

Description Of Issue- As described in Title. Also, the box is red. When I hover over it, it says "Disabled, Start a negotiation first!" even though I have a negotiation open in GBG.

Other Issues- discuss.foe-helper.com won't let me create an account to submit this. It says "There was an error submitting reCAPTCHA. Try again." and "ERROR for site owner:
Invalid domain for site key".

Lastly, I'd like to thank Gindi4711 for the pinned template; hopefully all of this information helps whoever is looking into the bugs. I would also like to humbly suggest an addition for said post.. https://github.com/mainIine/foe-helfer-extension/issues/620#issue-573028706 ..for my laptop f12 activates airplane mode. The method I used to find the error messages was right clicking on the FoE Helper menu, then Inspect, then Console.

**Comment by Arklur** [comment]
Negotiation helper is disabled in GBG, it's working as intended.

**Comment by mistybc87** [comment]
Well I'm glad I took the time and effort to generate this. It used to work before the castle system went into effect. Maybe that changed something?

**Comment by Arklur** [comment]
It was removed around 2020.06.19: https://foe-helper.com/ (https://foe-helper.com/news/changes-to-the-foe-helper). You were probably not using the most recent version.

**Comment by mistybc87** [comment]
Ah ok. Thank you for the clarification. I see in note 3 it says it will not apply to GBG. I appreciate the time and effort spent to answer my post, and I am sorry to have wasted your time with such an easy thing to find. I am still glad to have the opportunity to create a ticket like this. I know where to look and what to do if there really is a problem. Thank you again! :D
