### ISSUE TITLE
Foe Helper in unpacked mode

### ISSUE THREAD

**Issue by exstreme** [mainIine/foe-helfer-extension#2218]
Hello!
I'm using extension in unpacked mode.
Unfortunately, my account was banned for using scripts. Can Innogames track helper using in development mode and if they can, so how?

**Comment by Parama91** [comment]
No Inno cant track if you are using beta or the version from the store. Did you update it to the latest version? Do you have other plugins installed, because i am also using and developing on the beta version and didnt get a ban since the beginning.

Its recommended to use the version from the store, because of automated updates and because it's a stable version, ONLY use beta if you know what you are doing (recommended only for us developers)

**Comment by exstreme** [comment]
> Did you update it to the latest version?
Of course

> No Inno cant track if you are using beta or the version from the store.
My friends, the moderators, shared information that they now have a priority to search for foe helper in unpacked mode.

> No Inno cant track if you are using beta or the version from the store.
I believe they can. First, I thought, that they can parse value from
`devMode=${!('update_url' in chrome.runtime.getManifest())};`
But removing this line don't help.

**Comment by Parama91** [comment]
Well even if they can (might be possible, also searched for it), it shouldnt matter as they dont have a list of developers from FoE helper which they "whitelist" to allow them using the beta version. So the beta version shouldnt be the problem.

Any other plugins installed in your browser? If you have moderators as friends, maybe they can tell you where the script is coming from as FoE Helper does nothing automated, just showing you more details of the game

**Comment by exstreme** [comment]
Can you tell us which OS you are using?


> Any other plugins installed in your browser? If you have moderators as friends, maybe they can tell you where the script is coming from as FoE Helper does nothing automated, just showing you more details of the game

No, they don't know technical details. 
Some people use an old version of the helper, Innogames, and try to track them down, even though there is no automation whatsoever

**Comment by Parama91** [comment]
Windows 10

Hm, maybe you can send them an introduction on how to activate automated update for the plugin so this case shouldnt occure again. But after some researches in my guilds on different worlds there are no other bans and also Discord is quiet, so it can only be a problem with the outdated version of FoE helper.

**Comment by exstreme** [comment]
Thank you, will wait answer from support
