### ISSUE TITLE
[BUG] GuildBuildings-CSV enthält ZA-Name in Level Spalte bei Ruhmeshallen

### ISSUE THREAD

**Issue by Bozer-der-Barbar** [mainIine/foe-helfer-extension#2224]
Haben Gildies Ruhmeshallen aufgestellt und man exportiert die Daten in eine CSV-Datei, werden in der "level"-Spalte die Namen der Zeitalter ausgegeben.  Beispiel:

![image](https://user-images.githubusercontent.com/79040934/144765148-f08e1b11-3abb-459d-8c2f-e39ffccf0410.png)

**Comment by Bozer-der-Barbar** [comment]
Ich habe den Code nur sehr, sehr oberflächlich angeschaut und vielleicht bin ich an der völlig falschen Stelle, aber in Zeile 314 von /js/web/guildmemberstat/js/guildmemberstat.js habe ich gesehen, dass andere Werte für level und era übergeben werden als sonst üblich.  Hier EntityLevel und Member.era statt EntityEraId und EntityEra wie beispielsweise in Zeile 340 und 354.

![image](https://user-images.githubusercontent.com/79040934/146232186-861c27d5-138a-43ce-9c67-896f142b281e.png)

**Comment by danielvoigt01** [comment]
Jepp, an der Stelle hat sich der Fehler beim letzten Bugfixing eingeschlichen... Wird dann mit dem nächsten Update behoben.

**Comment by Bozer-der-Barbar** [comment]
Danke dir! 👍
