### ISSUE TITLE
Fehler in Ereigniss-Übersicht

### ISSUE THREAD

**Issue by Archeron1977** [mainIine/foe-helfer-extension#2226]
Windows 10 
Browser: Chrome
Version
2.5.10.0
Spieler Id:
3910075
Gilden Id:
16160
Welt:
de18

Bei der Übersicht der Ereignisse auf der Map werden zweispurige Strassen angezeigt, aber ich habe gar keine zweispurigen Stassen in der Stadt :-)

![FoE-Helper](https://user-images.githubusercontent.com/95763425/145234484-36eb6ed3-c5d2-4352-8fb0-e638be62c8db.JPG)

Könnt ja bei Gelegenheit mal schauen.

Ansonsten einfach super und großes Lob

**Comment by Parama91** [comment]
Info an die Entwickler: Derzeit wird hier nur nach dem Zeitalter gefiltert und für Spieler vor ZA Jahrhundertwende diese Einträge gefiltert, jedoch nicht ob in der Stadt überhaupt eine solche Straße vorhanden ist.

prepareData in hidden-rewards.js

**Comment by outoftheline** [comment]
Kein Fehler. Wenn du eine zweispurige Straße baust, erscheinen diese Ereignisse.
