### ISSUE TITLE
GvG Gildenfarben bei gleichem Logo

### ISSUE THREAD

**Issue by Parama91** [mainIine/foe-helfer-extension#2227]
Pro Logo sind derzeit mehrere Farben hinterlegt (speziell bei Premium-Logos), wovon eine Farbe durch eine Formel mit der Gilden-Id ausgewählt wird. Das macht es sehr wahrscheinlich( bei nur 4 Farben sind es 25%), dass eine andere Gilde mit dem gleichen Logo auch die gleiche Hintergrundfarbe erhält, was es auf der Karte (ohne Mouse over, gerade wenn die Gilden direkt nebeneinander sind) nicht möglich macht die zwei Gilden zu unterscheiden.

Lösungsvorschlag: Wir behalten uns pro ZA eine Liste der bereits verwendeten Farben und ordnen einer Gilde mit dem gleichen Logo dann einfach eine andere Farbe zu.

**Comment by outoftheline** [comment]
Manche Logos sind sehr beliebt, zB die mit dem Totenkopf, wofür es auch mehrere Farben gibt. Ich hab die Farben absichtlich anhand der Gilden-ID "berechnet", damit jede Gilde auf allen Karten dieselbe Farbe nutzt. Unterschiedliche Farben pro Gilde je nach Karte fände ich schwierig.
