### ISSUE TITLE
Total on the Current Production Overview is "Not a Number" (NaN)

### ISSUE THREAD

**Issue by Cady36** [mainIine/foe-helfer-extension#2236]
I'm self-guilding for a couple of weeks, so my Townhall doesn't give FPs. It's processing as NaN, so the total is also NaN.

![image](https://user-images.githubusercontent.com/52673062/145655932-b39d7bd8-9ace-4aee-8116-2f679a07c7c3.png)

**Comment by RedIsDead54** [comment]
Same for me,
This bug still here, the last update doesn't solve the problem

**Comment by Gindi4711** [comment]
Fixed in next update
