### ISSUE TITLE
[Idea] - FP investment summary; link to players

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#2247]
Similarly how you can click on player's name which brings you do their profile page on foe.scoredb.io, would be great if it worked similarly in the "Your FP Investments Summary" window, e.g. being able to check the activity for a player more easily, looking at their points and battles in the last few days.

![image](https://user-images.githubusercontent.com/9089026/147859502-8f6a4edd-3ec5-4b6b-810b-f67817d66422.png)

**Comment by danielvoigt01** [comment]
Included in the next update.
