### ISSUE TITLE
Bug: Einige "Keltischer Wald Gebäude" nicht sichtbar bei "Gebäude-/Auswahl-Kits"

### ISSUE THREAD

**Issue by frankmorgner** [mainIine/foe-helfer-extension#2250]
Die Übersicht *Gebäude-/Auswahl-Kits* zeigt bei mir
- Maj. Kitz St. 1
- Maj. Kitz-Kit
- Trauerweide St. 1
- Kelt. Wald-Kit

**nicht** angezeigt werden jedoch:
- Feenringe St. 2
- Mondtor St. 2
- Steinsk. St. 2
- Trauerweide St. 2
- Maj. Hirsch St. 2

**Comment by Gindi4711** [comment]
Sollte mittlerweile gefixed sein

**Comment by frankmorgner** [comment]
Nein, bei mir läuft 2.9.0.0 und folgendes wird nicht angezeigt:
- Hirsch St. 2
- mondtor st. 2
- feenringe st 2
- steinskulptur st 2
- trauerweide st 2

**Comment by Parama91** [comment]
Stufe 2 sollte meines Wissens nach auch nicht angezeigt werden, sondern lediglich die Gebäude auf Stufe 1

**Comment by frankmorgner** [comment]
? ist doch auch teil des sets!

**Comment by Parama91** [comment]
Hab mich gerade ein wenig herumgespielt und im Code nachgesehen, anscheinend sind dort nur die Codes für Stufe 1 eingepflegt. Da diese händisch nachgepflegt werden müssen und nicht von Inno zur Verfügung gestellt werden, müssen wir uns die Codes irgendwo raussuchen, aber wir werden das bei Gelegenheit erweitern :)

**Comment by oesi03** [comment]
Habe mir darüber auch schon Gedanken gemacht unfertige Stufen bis zur vollendeten Stufe mit aufzunehmen. Da mir das von Sammlern unfertiger Teile zugetragen wurde. Jedoch wie schon geschrieben wurde ist alles noch gute alte Handarbeit aufgrund der Komplexität der Daten und zunehmender Sonderregelung (InnoGames hat ja versprochen ständig Neues zu entwickeln😉) ist das Ganze recht tricky😅 
da die daten zu recherchieren was neu ist und wie es zusammen gehört recht aufwendig ist kann ich es verstehen das es anderen Projekten vor allen den vielen tollen neuen Features (danke dafür👍) hinten ansteht. Helfe aber gerne mit es aktuell zu halten😁

**Comment by frankmorgner** [comment]
Wo kommen die IDs her, kann man da helfen?

**Comment by oesi03** [comment]
Chrome entwicklerkonsole "Page"
hier findest du alle Daten: 
https://foede.innogamescdn.com/cache/ForgeHX-3d112ddc.js

und hier findest du alle Bilder z.B.: https://foede.innogamescdn.com/assets/city/buildings/R_SS_MultiAge_ArcheologyBonus22a.png

ist ein Bild noch nicht geladen kannst du dir den Link selbst zusammen friemeln im Browser öffnen und dann wird das Bild nachgeladen!

was neu ist findet man am besten raus indem man nach jedem Update diese Datei: (ForgeHX-3d112ddc.js) mit der vorherigen Version vergleicht zb mit Notepad++ Plugin "compare"

oder du schaust mal hier die sind sehr gut im finden neuer Sachen😅
https://forum.beta.forgeofempires.com/index.php?forums/spoilers.81/
da sie auch die original Bilder von InnoGames verlinken findest du so schnell die neuen "ID's"

wenn du das in der Konsole ausführst kriegst du den Link zur aktuellen Datenbank:
extUrl + "js/web/kits/data/sets.json"

viel Spaß😊
