### ISSUE TITLE
Fehlerhafte Berechnung "LG-Investitionen"

### ISSUE THREAD

**Issue by Muckinator735** [mainIine/foe-helfer-extension#2251]
Es liegen abweichende Berechnungen vor zwischen "LG-Investitionen" und dem "Eigenanteilsrechner".
Daraus resultierend sind dann auch falsche Daten hinsichtlich der Rentabilität der LG's.

Ich räume natürlich auch ein, dass ein Bedienerfehler vorliegt. In diesem Fall bin ich ratlos.

Als zusätzlichen Anstoß möchte ich noch die Berechnung an sich ansprechen. Ursprünglich wurde die Angabe in "FP je FP" skaliert. Heute ist es in "Break even in" skaliert. Ein ROI interessiert mich persönlich wenig jedoch finde ich die Angabe der Investkosten interessant.
Schön wäre (Bitte bitte) eine Auswahlmöglichkeit in den Einstellungen!

![image](https://user-images.githubusercontent.com/66316515/148108399-231670b2-c713-42fb-9964-4767568ed231.png)

P.S. Klasse Job, den Ihr da macht. Trotz der vielen Eingaben bin ich ein begeisterter User und möchte auf keinen Fall wieder auf meine Excel-Tabelle zurückgreifen müssen... Danke!

**Comment by HAL09001** [comment]
Die Kosten in LG-Investitionen rechnen die FP durch den Levelaufstieg herunter, da man die ja zurückbekommt.
1879-89=1790

**Comment by Gindi4711** [comment]
1.) Ja die Doppelernte wird abgezogen.

2.) Bei der Spalte "Break even in" handelt es sich lediglich um eine Umbenennung von "Kosten pro täglichem FP".

Der Grund dafür war, dass die erste Version nun FP unterstützt hat => da war "Kosten pro täglichem FP" die verständlichste Angabe.
Später kamen dann die Güter hinzu. Da war es schon etwas verwirrend, hat sich allerdings noch dadurch erklären lassen, dass man ja Güter in FP handeln kann bzw. umgekehrt (du bist der Meinung 1 FP sind 10 Güter, dann werden 10 Güter am Tag wie 1FP Tagesproduktion gezählt).
Dann kamen die Angriffsboni und spätestens hier musste ein anderer Name her, denn selbst wenn der Spieler eine Gewichtgung festlegt ist kann man Angriffsboni nicht in FP tauschen bzw. umgekehrt.
