### ISSUE TITLE
[REQ] Enhanced GB investment list 

### ISSUE THREAD

**Issue by varazir** [mainIine/foe-helfer-extension#2254]
Hello, 

I know this is not a loved part of the game but sniping-help 

If I snipe a GB of a neighbor I would  love it to be saved in a separat list so I can go back to that player and check again this GB. 
If the GB isn't updated like x days the player are marked as slow player, Green, Yellow and Red. You need ofc check the GB list.  
If I go into a players GB and one or more of the places are already sniped it should be added to the same list as player to check later.

**Comment by GeniePower** [comment]
I came here today with the same goal but a bit better understanding of compliance requirements. I don't think your proposal will survive Inno's scrutiny. All I want is the GB investments list to be downloadable like most lists so I can build it for myself :)

**Comment by varazir** [comment]
> I came here today with the same goal but a bit better understanding of compliance requirements. I don't think your proposal will survive Inno's scrutiny. All I want is the GB investments list to be downloadable like most lists so I can build it for myself :)

Ya asking for that , else you need to have your own notepad. I never remember who I checked last and who I managed to gain som extra FP off.
