### ISSUE TITLE
Track extra FPs from investments

### ISSUE THREAD

**Issue by FlyingPersian** [mainIine/foe-helfer-extension#2258]
Hello,

I have been leveling my Arc past level 80 the past few months. I'd like a feature where you can see how many FP you additionally get back from investing into LBs. It should just add up all extra FPs past 1,9. So if I invest 100FP and get back 105FP, I want it tto track the 5FP. I'm just curious to see how efficient my past 80 Arc is in reference to how much I invest into my Arc and other LBs. 

I'm not sure how exactly this could be achieved, Maybe the Investment Overview page? Maybe it could be integrated there in a seperate tab as an extra setting.

**Comment by Gindi4711** [comment]
The GB investments tool can already do this:
.) Open ingame event log (town hall => News => Event log)
.) Set the filter to "Great buildings" and scroll through all pages
.) Open the GB investments tool and it will suggest FP rewards/day (5519FP/day in this example). This is the average rewards I got in the last 5-6 days.
.) If I upgrade my arc 1 level I will get 2.8FP more per day assuming the current 5519FP rewards per day
.) With the costs of 21914FP for the next level this means it will pay off in 7822 days or more than 20 years which seems not very motivating...

<img width="429" alt="Screen" src="https://user-images.githubusercontent.com/55417498/162574450-e91ec71e-4b87-45d1-97ce-4e0a658fe374.png">

**Comment by FlyingPersian** [comment]
Thanks
