### ISSUE TITLE
Städteplaner

### ISSUE THREAD

**Issue by Rocco89** [mainIine/foe-helfer-extension#2264]
Hallo an die FOE Helper Entwickler, wäre es ggf möglich einen export in den helper einzubauen für fremde Städte ?
Damit man Gildenkollegen helfen kann die Stadt zu verbessern und dann die fertige Stadt auch teilen kann mit dem anderen Gildenkollegen.

Da würden sich sicher viele Spieler drüber freuen über so eine Funktion.

**Comment by mainIine** [comment]
Es gibt bereits 2 funktionen für so etwas.

1. Einmal kannst Du Dir die Daten über das Menü "Stadtplaner > Citymap Daten kopieren"
2. Hast Du eine Stadt zur Webseite foe-helper.com mit dem Button "zeige Übermittlungsbox" geschickt kannst Du dort deine Stadt mit einem Link für jdm anderen freigeben.

Ergo, bauen wir nix weiter ein, ist ja alles schon da.

PS: Die Webseite kann auch komplette Ansichten einer Stadt erstellen falls du so etwas herumzeigen möchtest.
