### ISSUE TITLE
Bug: Eroberungskostenrechner zeigt alle Provinzen als "bereits erobert" an seit dem heutigen Update

### ISSUE THREAD

**Issue by bernhard-kleine** [mainIine/foe-helfer-extension#2268]
Win64
Firefox 96.01 (64 Bit)
de01 avrahall aber der Fehlertritt auch auf de2, de12, de21 auf. Das Löschen des Cache half hier nicht.

![grafik](https://user-images.githubusercontent.com/9216487/150159158-6057791a-7671-4b49-885d-86158fdfb570.png)

**Comment by Sch777560427** [comment]
Ja , das ist überall ein Problem , hier in Ungarn funktioniert es genauso nicht
![Képernyőkép 2022-01-22 135115](https://user-images.githubusercontent.com/98218090/150639268-5ce1a427-1d5f-4941-98dd-3f178bbad186.png)
.
