### ISSUE TITLE
Feature request: Track fp made on investments

### ISSUE THREAD

**Issue by ramijaschek** [mainIine/foe-helfer-extension#2271]
Would be very nice to see how many FP did I make on investments in GB's of friends/neighbors - helps track which friends to keep, etc.

**Comment by Parama91** [comment]
This is not possible because we dont get the data for all of your investments and this would also support sniping which is not allowed from Inno :)

**Comment by SkateScout** [comment]
Hi, i think this is not elated to Snipping.
1) You can already have an overview of the infestments done if you click to GB in the Townhall.
2) For LG Tipps You also fetch from GB events in Townhall what place was made.
So if you add in Information FP made by Invest on day X like collected FP.
This is in no way an help for snipping.

**Comment by ramijaschek** [comment]
So:
A. This is about investments in general. Has nothing to do with the question of which factor they were made in
B. when I go for the list of the GB's I contributed to - you show a window showing all GB's I've invested in and expected profit and whether or not it is secure - so the data can be accumulated even just from there (same as in GbG you take a snapshot of player participation and show difference relative to it).
C. This can also be done even I have FOE-helper open when investing - you can record from there.

It's only about capturing information FOE-helper is already showing and adding them up (same as for event pages and summing up other players contributions, etc.).

Please reconsider. Thx.
