### ISSUE TITLE
Continent Map Overview shows all Provinces as Conquered

### ISSUE THREAD

**Issue by GoodKingChris** [mainIine/foe-helfer-extension#2273]
When using the continent map overview to determine sector resource costs, it returns a message that the sector is already conquered. I have removed and reinstalled the FOE Helper extension, but this made no difference.

![image](https://user-images.githubusercontent.com/98220097/150641007-574a58f1-bf27-45da-b886-fc6e79199c0d.png)

This is for all provinces whether conquered or not. I'm not sure, but I think that this may have started before the last FOE update.

As far as I know, all the other tools are working OK.

**Comment by GeniusTimo** [comment]
@Th3C0D3R already fixed this issue yesterday and the fix will be included in the next update 😊

**Comment by Sparky-2022** [comment]
Unless the update hasn't been released yet, this is still an issue. Reloaded helper and still get "already conquered" message

**Comment by irax68** [comment]
podpinam się pod wątek niestety w dalszym ciągu jest problem

**Comment by bernhard-kleine** [comment]
How can we know that the update has been applied?

**Comment by Franzmannn** [comment]
Would be great if you could release the update soon. This is really a widely missed functionality.
