### ISSUE TITLE
Kosten KdK nicht ermittelt

### ISSUE THREAD

**Issue by Muckinator735** [mainIine/foe-helfer-extension#2274]
Die Kosten einiger offener Sektoren auf der Karte der Kontinente werden nicht berechnet:

![image](https://user-images.githubusercontent.com/66316515/150657677-c0eebe2c-763c-411c-bdac-a3adbe6302bd.png)

**Comment by GeniusTimo** [comment]
Dieser Fehler #2273 wurde bereits gemeldet und wird im nächsten Helfer-Update behoben (0de2816473b07dcb0041a4dafbbeaac26a28c0d5)
