### ISSUE TITLE
[idea]  Incident positions

### ISSUE THREAD

**Issue by stigjoergensen** [mainIine/foe-helfer-extension#2275]
I know you dont take suggestions on this.. as you dont know where it is... however, i think i have a solution...

You clearly know the graphics... can you override the graphics, or change the background on it, so it would be easier to spot... or use some CSS tricks to make it flash or something? i mean, that what it does when playing on mobile, so should be possible to do something simelar here...

fell free to delete this post if you still feel its none productiv.

**Comment by SkateScout** [comment]
CSS Trick s not possible since the game does not use CSS for layout it use canvas and render the GUI.
