### ISSUE TITLE
[Bug] Nicht motivierte Gebäude werden in der Produktionsübersicht nicht mehr angezeigt

### ISSUE THREAD

**Issue by Parama91** [mainIine/foe-helfer-extension#2276]
Anscheinend werden nicht motivierten Gebäude komplett aus der Produktionsübersicht rausgefiltert. Dies betrifft nicht nur den FP sondern auch Güter Übersicht und möglicherweise auch alle anderen Tabs.

**Comment by Gindi4711** [comment]
Anscheinend hat Inno wieder einmal etwas am Datenformat geändert.

Wird mit den nächsten Update gefixed
