### ISSUE TITLE
Nicht Motivierte Gebäude werden in FP Anzeigen nicht mehr erkannt. 

### ISSUE THREAD

**Issue by M3nardi** [mainIine/foe-helfer-extension#2282]
Ich kann leider kein Bild hier einfügen, ich versuche es zu Beschreiben. Wenn man ein Shrine des Wissen Hat und in der Effizienzansicht FP Auswählt erscheint dort 0 wenn der Shrine nicht Motiviert ist. Das selbe Passiert in der Produktionsübersicht dort wird er dann nicht einmal aufgelistete. Also dort gab es ja mal sowas wie 555/786 das gibt es so nicht mehr das ding wird nicht angezeigt. 

Ich Hoffe ich habe mich verständlich ausgedrückt.

![fehler](https://user-images.githubusercontent.com/98600614/151568474-9819c8ee-041b-4ffc-828b-7ac890f36138.PNG)
Bild ging doch noch damit wirt es klarer.

**Comment by mainIine** [comment]
Duplicate of #2276
