### ISSUE TITLE
Min. Qty on Market Filter includes non-matching trades

### ISSUE THREAD

**Issue by Cady36** [mainIine/foe-helfer-extension#2283]
When you set minimum quantity with Neighbors, Guild Members, and Friends all checked, trades are displayed for lower than the minimum, if the trade is by a guild member:

![image](https://user-images.githubusercontent.com/52673062/151882663-d2703afa-8f5e-490d-868e-b4a65476f2af.png)

If you uncheck Guild Members, trades lower than minimum are still displayed on your Market Filter page if that guild member is in your hood or on your friends list:

![image](https://user-images.githubusercontent.com/52673062/151882934-1626d78f-13ff-4dfd-a157-751df93cd54f.png)

**Comment by Gindi4711** [comment]
The use of the min quantity filter is to exclude small quantities that are not worth the fee of 1 FP.
For guild members there is no 1FP fee so the min quantity is disabled for them.

**Comment by Cady36** [comment]
That's unfortunate. I use it to find large trades, so I don't have to page through thousands of trades. I don't care about the FP. It would be nice if it were labeled accordingly, because it's pretty confusing/counterintuitive to have them show up with Guild unchecked AND with a minimum sent.

Thanks. I'll see if I can find another tool for this particular task. :)
