### ISSUE TITLE
Feature Request: Marktübersicht - Bewertung der Angebote

### ISSUE THREAD

**Issue by SwSoC** [mainIine/foe-helfer-extension#2286]
Hallo zusammen,

Es wäre schön, wenn eine Bewertung der Angebote in der Marktübersicht eingeführt wird.
100 EZ : 101 EZ und 100 EZ : 101 Venus sind beides vorteilshafte Angebote, letzteres ist aber natürlich deutlich attraktiver. 
In der Bewertung kann man einen ZA Sprung m.E. mit dem Faktor 2 Bewerten, nachteilige Angebote würde ich als negativen Bewertungsfaktor darstellen. Über die genaue Formel kann ich noch mal nachdenken, wenn das Feature grundsätzlich realisierbar ist. Der nächste Schritt ist dann ein Filter "Zeige Angebote mit Bewertung größer X"

**Comment by Gindi4711** [comment]
Dazu müsste man pro ZA eine eigene Tabelle mit Tauschverhältnissen konfigurieren, die pro Spieler ziemlich individuell ist. Fix einen Faktor 2 annehmen macht wenig Sinn.

**Comment by SwSoC** [comment]
Für den "vorteilshaft" Haken wird ja auch der Faktor 2 angenommen, insofern wäre es konsequent, dies fortzuführen.

Mit ein wenig Abstand betrachtet interessiert die meißten aber gar nicht der "Wechselfaktor" sondern eher, wieviele ZA übersprungen werden. Große Spieler suchen kleine Güter und kleine Spieler suchen "sehr vorteilshafte" Angebote. Eine einfache Differenz der ZA zwischen Angebot und Bedarf wäre m.E. schon ausreichend, den Wechselfaktor (0,5-2) würde ich dann gar nicht mehr in die Berechnung einbeziehen.
