### ISSUE TITLE
Stadt wird nicht übermittelt

### ISSUE THREAD

**Issue by ChrisButt** [mainIine/foe-helfer-extension#2287]
Hallo,
ich kann den Stadtplaner nicht wirklich nutzen, da die Stadt nicht übermittelt wird. Die Stadt die ich bekomme ist eine sehr alter Stand von mir. Ich hab mal in den DevTools von Chrome geschaut, es wird das korrekte JSON übermittelt, auch die SpielerID stimmt.

**Comment by mainIine** [comment]
Dann hat dich der Server geblockt weil Du eine zu alte Version oder nicht den originalen Helfer benutzt hast. Schick mir mal deine Spieler-ID und Welt ID

**Comment by ChrisButt** [comment]
Ich hatte in der Tat eine alte Version, hab dann eine neue installiert. Damals gab es sie nicht direkt bei Chrome, jetzt ist sie direkt aus dem Store. War aber immer die originale! Ich sende dir die Daten, danke!

**Comment by alftimelord** [comment]
hab dasselbe Problem, aber keine alte Version 2.5.10.1 , hab Dir ne Mail gesandt mainline , Gruss Darlee

**Comment by mainIine** [comment]
@alftimelord 
Versuche es noch mal.

**Comment by alftimelord** [comment]
hm jetzt gehts wiederum nicht, bei der Übermttlung bin ich einer endlos Ladeschleife :-(
