### ISSUE TITLE
PRODUCTION Overview - boost calculation error 

### ISSUE THREAD

**Issue by whocares1111** [mainIine/foe-helfer-extension#2290]
I get a different total for both Attk boosts and def boosts when compared to the ingame Town Hall>Boost Overview. I have refreshed the browser a few times already

**Comment by Gindi4711** [comment]
Can you compare the list and tell us which building is missing

**Comment by whocares1111** [comment]
Looks like Castles System %

**Comment by Gindi4711** [comment]
Fixed in next update
