### ISSUE TITLE
Ernte für Ozean-Terminal und Arktischer Hafen wird nicht angezeigt

### ISSUE THREAD

**Issue by Tunsel** [mainIine/foe-helfer-extension#2291]
Wenn Produktionen etc fertig sind, erscheint ein Hinweis  *alle fertigen Produktionen einsammeln*. Dieser Hinweis erscheint jedoch nicht, wenn die Ernten im Arktischen Hafen oder dem Ozean-Terminal möglich sind. 
Es wäre schön, wenn das geändert werden könnte

**Comment by Marcel-Wagner** [comment]
Der Button (alle fertigen Produktionen einsammeln) für 5 Dias kommt von Inno und nicht vom FoE Helfer
