### ISSUE TITLE
Army tab insn't refreshing

### ISSUE THREAD

**Issue by dizzitelli** [mainIine/foe-helfer-extension#2292]
Hi,
the army tab, more exactly the last one on the right (the one that is linked to Alcatraz production) isn't linked to actual production capability of my Alcatraz's building, is still linked and calculating 6 units/day, while my Alcatraz is now producing 11 units/day.
How can I solve the issue ?
Thank you and best regards,
Luca

![image](https://user-images.githubusercontent.com/99487237/153602244-bdb62424-c884-4fa9-8660-708e56b2f10c.png)

**Comment by Gindi4711** [comment]
The tools shows the troops received from the last time you collected your Alcatraz.

The next time you will get 11 units, but we do not know which units that will be.

**Comment by dizzitelli** [comment]
It means that if I collect the troops from my mobile's app then the foe helper isn't refreshing the informations?
Next time I will try to collect them from my pc with the foe helper and I will double check.
Thanks a lot for your reply and have a good day!
