### ISSUE TITLE
Windows 11 & Google Chrome extension issue

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2293]
Hi. 
There is an issue with FoeHelper extension on Windows 11 and Google Chrome, the background does not load:

![FoEHelpesBackgroundIssue](https://user-images.githubusercontent.com/49796453/153705417-585151e9-a760-4dc1-848d-909e8302c87a.png)

For the first time in my life I was forced to use Edge browser (I don't like it), which does not have this effect on extension. 
In Edge browser, I have an issue with tooltip popup, when extension is loaded as "AsBox", and it's location is on the top of the webpage. The tooltip message Y location is negative.

**Comment by Parama91** [comment]
What version of the FoE helper do you use? I remember that this was a problem versions ago and we fixed it

**Comment by valimaties** [comment]
2.5.10.1

**Comment by Gindi4711** [comment]
Did you try removing the extension and installing it again?

Is there anyone else with Windows 11 and Chrome with that problem?

**Comment by valimaties** [comment]
I've done that, with the same issue. 
Right now, as a workaround for me, I'm using Edge browser, without issues.

**Comment by outoftheline** [comment]
does this issue still occur?

**Comment by valimaties** [comment]
I didn't tried anymore, as long as right now I  didn't used Chrome, use Edge browser instead.

**Comment by valimaties** [comment]
Solved for Google Chrome with latest version!
