### ISSUE TITLE
percentuale 

### ISSUE THREAD

**Issue by enricomg** [mainIine/foe-helfer-extension#2300]
hello, since in pvp you see the% attack and defense, could you add the percentage in Guilmemberstat?
we have a chat with% attack but they forget to update.
if it goes against the rules you can close
thank you

**Comment by Gindi4711** [comment]
Innos words on this topic were "Dont show attack/defense for any city except your own".

Personally I do not see why showing attack/defense for friends/guild members are a problem, but as it was a very precise order I dont think adding it would be a good idea.
