### ISSUE TITLE
BUG - Scout Info

### ISSUE THREAD

**Issue by ecthelioni** [mainIine/foe-helfer-extension#2326]
Hello
When I try open map, game frozen and I must restart browser window. When I disable new funkcion Scout Info, map corectly working.

![image](https://user-images.githubusercontent.com/60727513/155172533-4c2d28d4-1a2a-4717-99ca-b0746d4e751e.png)

cz1
Windows 10
Google Chrome 98.0.4758.102
FoE Helper 2.6.0.0

**Comment by mainIine** [comment]
The error is already known. Tonight there will be a small BugFix for it.
