### ISSUE TITLE
Alarm

### ISSUE THREAD

**Issue by kincza1971** [mainIine/foe-helfer-extension#2332]
Hi,

From today upgrade alarm icon does nothing (Chrome:  98.0.4758.102 64bit official, win10).

Regrads,
Laszlo

**Comment by Dlonrab** [comment]
Same experience in some other Chrome based browsers and Opera

**Comment by GeniePower** [comment]
Not working here either, high priority fix please!

**Comment by AlmostAtom** [comment]
Never worked for me. Also no message or anything from the alarm. (Chrome)
