### ISSUE TITLE
Patrick's day window disappears in Firefox

### ISSUE THREAD

**Issue by Dlonrab** [mainIine/foe-helfer-extension#2336]
After closing the Sint Patrick's day event foe helper window (^ button) , the window can not be opened/recalled again anymore in Firefox.
Tried reloading the game, restarting the browser and removing all cookies as wel as opening the game with foe helper in a private window

**Comment by Beelzebob6666** [comment]
seems to be fine on the beta-branch

**Comment by Overkillian** [comment]
It doesn't work at all in Firefox - the add-on version hasn't been updated since 2.5.10.0 in this browser!
According to the page itself: https://addons.mozilla.org/de/firefox/addon/foe-helper/

So the event window never showed in my case.

**Comment by Beelzebob6666** [comment]
Yes it works in Firefox, but only in versions 2.6+
The Mozilla app store has not processed the updates yet. 
Not sure if Dlonrab loaded the Version in developer mode

**Comment by Dlonrab** [comment]
Versie
    2.5.10.1
Speler-ID:
    1908138
Gilde-ID:
    11786
Wereld:
    nl3 
    
 NO developer mode (as far as I know)

**Comment by Beelzebob6666** [comment]
In that case you have seen the st pat box somewhere else - it simply is not available in version 2.5.x
