### ISSUE TITLE
Patrick's Day Info - Quest falsch hinterlegt

### ISSUE THREAD

**Issue by mordillo666** [mainIine/foe-helfer-extension#2339]
Vorneweg...Top, dass ihr für das Event ein Tool gebastelt habt, hilft ungemein, die Zeit besser zu planen. :-)

Die letzte Aufgabe in der 1. Stadt scheint falsch hinterlegt zu sein.
Im Helfer stehen 8,4Q, das Spiel will aber 16Q.

 https://prnt.sc/Sq479OyxMbNW

Die Einheiten verwirren mich auch etwas. Was ist QT?

**Comment by Beelzebob6666** [comment]
Nein, schein alles korrekt 😃 

Tasks die oben in der Leiste stehen tauchen nicht mehr im Info-Fenster auf.
Die Task mit den 16Q hast du oben in der Leiste (dies siehst du also schon)

Die "Nächste Stadt 8.4 Q" ist keine Task an sich - das ist einfach nur die Abschlussbedingung um zum nächsten Durchlauf zu kommen. "Nächste Stadt" im mini-Spiel - dort stehen dann die 8,.4 Q!
