### ISSUE TITLE
Incorrect automatic formatting

### ISSUE THREAD

**Issue by Gegen103** [mainIine/foe-helfer-extension#2345]
![image](https://user-images.githubusercontent.com/100533403/155895257-c4f57895-784c-4ffa-9376-d4468418304e.png)

**Comment by Gegen103** [comment]
The value should be "257" and not "tél. 257".
I'm using Microsoft Edge Version 98.0.1108.56

**Comment by Gegen103** [comment]
Some are well formatted, some not :
![image](https://user-images.githubusercontent.com/100533403/155899584-531fcac2-2071-43bf-9ecf-52d5b0b06a7a.png)
![image](https://user-images.githubusercontent.com/100533403/155899651-da6a1626-ecee-4f7a-8a98-5d2e3d3f0251.png)

**Comment by Beelzebob6666** [comment]
there is nothing in the code that could add such formatting

I would expect some other extension in your browser doing that - or some browser function to "automatically" detect phone numbers...
