### ISSUE TITLE
The infobox of the St. Patrick event is empty

### ISSUE THREAD

**Issue by gyurik** [mainIine/foe-helfer-extension#2346]
Windows 11 with Edge version  98.0.1108.62 (64-bit) most of the time the infobox is empty. There are times when it works okay but it doesn't depend on reload or something other. In two worlds the result is the same.

![image](https://user-images.githubusercontent.com/6838558/155897008-d1db8a43-45c6-41cb-b697-86838bb899ff.png)

**Comment by Beelzebob6666** [comment]
Are there any errors in the debug console (hit F12)?
