### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pdimop** [mainIine/foe-helfer-extension#2347]
When I open the GB calculator, I can hear sound alerts on several occasions, but I dont always know why.
Can I enable some type of text messages combined with the sound alerts?

**Comment by Gindi4711** [comment]
GB calculator sounds goes off when:
At opening: A spot is safe with the current investment factor (for example 90%)
When paying FP: If a reccuring "donate X FP" quest is finished
When aborting quests: If a new "donate X FP" quest is started (so you do not accediently scroll past it).

Sound effects of this box can disabled either with the speaker icon (only for this box) or globally in the settings menu (for all sound effects even those that do not have a box)
