### ISSUE TITLE
White Buttons

### ISSUE THREAD

**Issue by Teberon** [mainIine/foe-helfer-extension#2349]
Good morning, since update 2.6 I have had white buttons. I have already tried uninstalling and deleting the cache/settings, and nothing seems to bring back the colors. I am currently using Brave 1.35.103
![image](https://user-images.githubusercontent.com/25689158/155936940-e6876a74-9df1-4bd8-bb70-9f9452533630.png)
![image](https://user-images.githubusercontent.com/25689158/155936995-95d35251-2326-452c-a069-87facbe98dfc.png)

**Comment by outoftheline** [comment]
looks like the colors are inverted. do you have an extension for that? if so, can you disable it for forge?

**Comment by Teberon** [comment]
@outoftheline Dark Reader was causing it, thanks for reminding me about that addon
