### ISSUE TITLE
Guild member overview not opening properly after guild change

### ISSUE THREAD

**Issue by Beelzebob6666** [mainIine/foe-helfer-extension#2353]
![image](https://user-images.githubusercontent.com/66054355/156551111-b641120f-8c6c-463d-84e7-f874afebefdd.png)
![image](https://user-images.githubusercontent.com/66054355/156551333-a297df48-7564-4527-921f-378599185cff.png)

**Comment by danielvoigt01** [comment]
If you are not a founder or leader of the guild, the overview will not open automatically. Use the menu button for this
![Auswahl_073](https://user-images.githubusercontent.com/46729881/156576869-fdd4f210-d391-45cb-8f84-9babee5b4279.jpg)
.
