### ISSUE TITLE
GE incidents

### ISSUE THREAD

**Issue by WelverinXarann** [mainIine/foe-helfer-extension#2358]
Is there any chance that GE relic "incidents" can get the option to be turned off for the incident finder? When relics are still in the fog and unreachable it throws me off as i automatically start searching the map before realizing that it's showing something currently unreachable. Those are much harder to miss and get an in-game notice to collect them before moving to next stage anyhow.

**Comment by Beelzebob6666** [comment]
This option is already in the current beta
