### ISSUE TITLE
Neue Infobox mit Version 2.8.0.0

### ISSUE THREAD

**Issue by Muckinator735** [mainIine/foe-helfer-extension#2365]
Die Infobox war bei mir bislang ständig geöffnet. 
Bedauerlicherweise wurde mit Änderung 2.8.0.0 die Fenstergröße limitiert und jetzt ist dieser Riesenkasten nur noch störend.

Leider eine sehr schlechte Änderung

**Comment by outoftheline** [comment]
Kannst du einen Screenshot anfügen? Ich kann die Box weiterhin verkleinern. Geht es um die Höhe oder die Breite?

**Comment by Muckinator735** [comment]
Hi!
So sieht das bei mir aus:

![image](https://user-images.githubusercontent.com/66316515/157467583-c32a6da7-0813-40e1-8219-1b412b012d1c.png)

Ich nutzt bislang nur eine Zeile, jedoch die Höhe ist jetzt festgelegt, so dass das Fenster etwa dreimal so groß ist, wie vorher. Habe die Menge an Nachrichten auf 1 reduziert, juckt das Programm jedoch nicht.

**Comment by outoftheline** [comment]
Habs verkleinert!

**Comment by Muckinator735** [comment]
YEY!
Du bist die beste!
