### ISSUE TITLE
Small improvement for copy open positions

### ISSUE THREAD

**Issue by fane1978** [mainIine/foe-helfer-extension#2367]
On the GB Calculator on copy values can we remove the "P" before the position?
There are a lot that are using the format "Name GB 5 4 3 2 1" for easy delete of positions.
It is a small issue but I think that everybody knows that those are positions and do not need the "P"

It will look like 
Name GBName 5 4 3 2 1 
Name GBName 5(10) 4(29) 3(100) 2(450) 1(1700)
which is quite clear.
Thank you!

**Comment by fane1978** [comment]
related to that: 
Can we have the copy option on the main GB Calculator window?
After the selection of the Player/Building/"Include data" all the time will use the copy option. 
It will be nice to not have to go to Copy values additional screen all the time for the actual copy.

**Comment by mainIine** [comment]
Option added

**Comment by fane1978** [comment]
Thank you!
