### ISSUE TITLE
[Beta] - Verhandlungsassistent zeigt falsche Positionen der Grafiken für Güter

### ISSUE THREAD

**Issue by Teberon** [mainIine/foe-helfer-extension#2370]
![image](https://user-images.githubusercontent.com/25689158/157619128-258719fa-638f-4654-8c86-6f24162a2129.png)
Es sieht so aus, als wenn die Positionen verschoben sind um die richtigen Güter anzuzeigen

**Comment by Beelzebob6666** [comment]
this is already fixed in the newest version - you might need to wait a bit for the cached version of the git-code to refresh
