### ISSUE TITLE
Box title higher than top bar

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2380]
In the latest version 2.8.0.0, the box height is greater than FoE's top bar height. Previous version has the height value that fit top bar, now is higher and looks somehow ugly. Please make it as top bar height!

![Box higher than top bar](https://user-images.githubusercontent.com/49796453/158532903-40376fb0-bd4b-4d07-9f1b-a244f281452a.png)

**Comment by Beelzebob6666** [comment]
already fixed on beta
