### ISSUE TITLE
Guild Expedition statistics are wrong

### ISSUE THREAD

**Issue by larfemoon** [mainIine/foe-helfer-extension#2387]
Hello I noticed that guild expedition statistics are wrong since march 14th.

**Comment by Parama91** [comment]
Hey, can you please provide some screenshots with what numbers are not right in your oppinion. Thx

**Comment by larfemoon** [comment]
![Capture d’écran 2022-03-23 085737](https://user-images.githubusercontent.com/102212383/159650721-aa53a4d6-69ac-4c8b-957b-c7281b6f2784.jpg)

All values concerning encounters counts are wrong in the last column.

**Comment by Beelzebob6666** [comment]
are you sure, you visited GE and opened the progress view after the expedition was finished?
If you did not do that, the helper had no chance to get the latest data

**Comment by larfemoon** [comment]
Yes I'm sure it already occured last week. In our guild we reward best performances on guild expedition every week and we use GE statistics to do so. In general we check on wednesdays and extract previous GE statistics. But on wednesday 16th and wednesday 23rd the statistics appeared to be messed up. (For example in the joined screenview we are sure Larfemoon, Claudia39 and Yasmine36 finished GE and should be 64/48... and as you can see they score respectively 52/48, 32/48 and 36/48). Something must have gone wrong.

**Comment by Parama91** [comment]
I just checked my actual list and every single value is right, did you open the member view? As only opening the GE or the season view is not refreshing the data

![2022-03-24_13h35_59](https://user-images.githubusercontent.com/24807959/159917452-598d46d0-b731-4d2a-9b7a-a98e1d902999.png)

**Comment by Beelzebob6666** [comment]
The question was - did you open the ingame (!!!) ranking GE overview on monday (after GE finished)?

**Comment by larfemoon** [comment]
I can't remember if I did so... I 'll check next monday

**Comment by Beelzebob6666** [comment]
Did it work the last two weeks?
