### ISSUE TITLE
Beta: GBG Map - sectors sometimes have the name "undefined"

### ISSUE THREAD

**Issue by outoftheline** [mainIine/foe-helfer-extension#2394]
![image](https://user-images.githubusercontent.com/7482863/160133273-1939b26d-1222-4c54-95bd-41538f59702c.png)

looks like it happens when there is progress being made. happens on reopening the window i think, might be related to having the map open aswell.

**Comment by outoftheline** [comment]
might be more severe
![image](https://user-images.githubusercontent.com/7482863/160133835-4384e8ea-6ea4-44f7-8cfe-00933d03d2ac.png)

**Comment by outoftheline** [comment]
the bug in the second screenshot seems to happen after a province got conquered and you want to reopen the window. all while staying on the map.

**Comment by Beelzebob6666** [comment]
this can be closed?
