### ISSUE TITLE
GvG Marker Markierung einblenden wo Sektor am besten leigt zum Kämpfen

### ISSUE THREAD

**Issue by SkateScout** [mainIine/foe-helfer-extension#2397]
Am Besten wäre es einen Transparenten Roten Punkt einblenden zu können wo der GvG Sektor zum kämpfen am besten Liegt

**Comment by Beelzebob6666** [comment]
ich glaube selbst jemand mit GvG Hintergrundwissen weiß nicht worauf du hinauswillst. Bitte führe etwas klarer aus was du genau meinst.

**Comment by outoftheline** [comment]
Ich weiß was gemeint ist, bin aber dagegen.

**Comment by SkateScout** [comment]
Was spricht dagegen? Es würde nichts automatisieren was ja verboten ist Es wäre nur eine Hilfe die Karte zu positionieren und zu Wissen wo die Maus am Besten ist.

**Comment by outoftheline** [comment]
Und wenn das "alle" machen, geht der Server komplett in die Knie.
