### ISSUE TITLE
GB calculator with % per player.

### ISSUE THREAD

**Issue by SkateScout** [mainIine/foe-helfer-extension#2398]
It would be great if the GB Calculator could be configured with Individual % Rates per player.

**Comment by Gindi4711** [comment]
Do you want to save the full set of percentages per player (for example player1 has 90%, 92% and 93%) or just one value (for example 90% for player1, 92% for player2)?

**Comment by markusb** [comment]
I would like to propose an alternative:
Give us some 'preset' buttons at the to, like we now have the configurable percentage buttons. But the presets save/recall the indivudual values for each level.
Example:
We currently have a 1,9 chain for P1,P2 and P3; a 1,5 chain for P4 and a 1,0 chain for P5.
A preset weher I could save this configuration and recall is with one click would be very useful.
The percentage buttons are not really useful to me as I never have the situation where all percentages are the same.
