### ISSUE TITLE
Recurring quest diamond checklist

### ISSUE THREAD

**Issue by Beelzebob6666** [mainIine/foe-helfer-extension#2399]
Have a list for the recurring quests for checking whether diamonds can still be gotten there or not.

list could be created dynamically:
- reset list when new age is detected
- when a recurring quest is received and is not yet on the list, add it to the list
- when from a recurring quest diamonds or medals (in case diamonds were received on mobile) are won, check the quest as "diamond complete"

**Comment by Gindi4711** [comment]
How should we handle cases when foe helper is installed without changing era or if localstorage is cleared? Also receiving diamonds on other devices could be an issue.

**Comment by Beelzebob6666** [comment]
Nothing can be done against cleared local cache, and in regards to other devices: checkmark will be set also when medals are received - as diamonds replace the first medals occurence, medals can not be received before diamonds have been received

**Comment by outoftheline** [comment]
Just wanted to throw in that I am a bit concerned, because diamonds are a sensitive topic.

**Comment by Beelzebob6666** [comment]
you mean as in "inno might not like that"?

**Comment by outoftheline** [comment]
yep. i think it's better not to implement certain things, because if they revisit the helper and we have to remove stuff again to their liking, we'll just get some user backlash again.
