### ISSUE TITLE
Goldene Felder nicht erfasst

### ISSUE THREAD

**Issue by Muckinator735** [mainIine/foe-helfer-extension#2403]
Die gesammelte Gildenmacht berücksichtigt nicht die "Goldenen Felder"
![image](https://user-images.githubusercontent.com/66316515/161609787-087556a6-95a4-442f-a262-0e7f24ecde97.png)

**Comment by Beelzebob6666** [comment]
Das liegt wahrscheinlich daran, dass die goldenen Felder keine Gildenmacht produzieren - sie produzieren lediglich Gildengüter ;)

**Comment by Muckinator735** [comment]
Mea culpa
Vollkommen richtig!
Gildengüter werde nicht erfasst...
![image](https://user-images.githubusercontent.com/66316515/162269545-9fe76062-32fb-4c2e-90cb-8f760aed73c8.png)

**Comment by Gindi4711** [comment]
Gildengüter werden mit dem nächsten Update gefixed

**Comment by mainIine** [comment]
Duplicate of #2222
