### ISSUE TITLE
Building efficiency rating and Stage of Ages 

### ISSUE THREAD

**Issue by ClausV89** [mainIine/foe-helfer-extension#2405]
The building efficiency rater seems to ignore the attack bonus from Stage of Ages:
![image](https://user-images.githubusercontent.com/103024275/161697364-d53cab1a-e851-4d69-8782-5ac0db726ca4.png)

The building is motivated (red circle. Also the FP and goods bonuses are properly counted), so that's not it. Attack bonuses seemto be counted fine for other buildings (blue circles). Is this a bug or am I missing something?

**Comment by Parama91** [comment]
This might be an issue with the new building, we are going to check this. Maybe a developer has one to check the data from Inno :D

**Comment by Gindi4711** [comment]
Fixed in next update.
The fix applies to buildings effiency as well as the production overview
