### ISSUE TITLE
Goods from previous era marked as current era in production overview

### ISSUE THREAD

**Issue by janinko** [mainIine/foe-helfer-extension#2411]
Buildings like Star Gazer and Stage of Ages which produce goods from previous era show goods from current era instead in the production overview.

**Comment by Gindi4711** [comment]
Can you provide a screenshot

**Comment by janinko** [comment]
![image](https://user-images.githubusercontent.com/644267/162595079-e5c78ea3-64b9-476a-8196-6dbc09e30b63.png)

**Comment by Gindi4711** [comment]
.) If Google translate is correct then Cedic is from the previous age => Should be correct
.) The column "Doba, era" shows the era of the building, not the era of the goods produced. This column exists for every resource like forge points, supplies etc.
