### ISSUE TITLE
The Production Overview is partially off the browser window and won't appear

### ISSUE THREAD

**Issue by Heximus2011** [mainIine/foe-helfer-extension#2414]
Hi, I have a problem now in that the production overview window appears briefly partially off the top of the screen and then disappears. It will not briefly appear again unless I refresh the browser window or start a new session. I am using chrome.

**Comment by outoftheline** [comment]
can you reset the box coordinates in the settings please?

**Comment by Heximus2011** [comment]
Brilliant. I didn't notice that in the settings. Thank you very much!!!
