### ISSUE TITLE
Collected FPs including profit in GBs

### ISSUE THREAD

**Issue by Veru9** [mainIine/foe-helfer-extension#2415]
It'd be great if the collected FPs would tell how many of them I made by sniping or just making profit in the 1.9 thread by having a higher level Arc. It's a couple of hundred/thousand a day and I would really appreciate if I could keep track.

**Comment by Parama91** [comment]
Well, using a 1.9 with a high level arc is like tolerated sniping. How do you differ between them?

**Comment by Veru9** [comment]
Well it definitely isn't sniping. Nor the point. I just wanted to be informed about how many FPs were made as a profit not to discuss whether having a high level Arc someone considers sniping.

**Comment by outoftheline** [comment]
If we were to implement something like this we would need to set a definition of "sniping". Is sniping paying anything below 1.9?

**Comment by ClausV89** [comment]
Yeah veru just wants to know how many of the FPs came from harvesting, battlegrounds or the arc. As of now he can tell which came from battleground, but has no way of seeing which points came from investments (snipes or not).

**Comment by Veru9** [comment]
I mean it already tells you the profit in the GB calculator, I just want it to be added to the statistics of FP income.

**Comment by Gindi4711** [comment]
This idea has already been discussed several times, but it is not easy to solve.
When you make the investment GB cost calculator will show the profit, but it does not know if or when the GB gets leveled or if you will stay on the current spot (if it was not safe).
There is the event log available if you scroll through all pages that tells you which place you got in which GB/level. Based on that and your current arc bonus we can calculate the FP you received but we do not have the information how much you paid for it.

We already track GB investments and resync the GB list is shown in Town hall.

So what we could do is:
.) Let you scroll through events, calculate FP received and subtract FP paid from the saved data from investment tracking.

The problem about that: This will only work if you only play on one device. If you also use mobile (or a second PC) data will get really wrong really fast.
For example you set a bookmark FP in an arc lvl100. Later you snipe P1 on mobile for 2500 and get 2650 back. Your real profit is 150. The tool will see the 2650 will subtract the 1FP and will show you a profit of 2649FP. If this happens once in a list of 50 buildings the whole sum is garbage.
