### ISSUE TITLE
Production overview screen gets 'stuck' at top of game and can't be moved

### ISSUE THREAD

**Issue by Servelan** [mainIine/foe-helfer-extension#2418]
Windows 7 64 Bit
Firefox 99.0.1 (64-bit)
US8 (Houndsmoor)
1.227.0d8c207cd9 (30.03.2022 08:45)- English

No idea how I did this, but I've tried deinstalling/reinstalling, enabling/disabling, nothing works.  Production overview screen can't be moved from its position at the top of the screen.  Yes, there might be a key combo that undoes this, but it shouldn't happen to begin with.
![cant move](https://user-images.githubusercontent.com/8212581/163104161-f47f942e-db47-4ac3-ba6a-5caf0fbcd6e2.png)

**Comment by Parama91** [comment]
You can resize the box in the bottom right corner, then you should see the top of the window again ;)
