### ISSUE TITLE
Eigenteilrechner zwei Mal im Baum von Einstellungen

### ISSUE THREAD

**Issue by thepab** [mainIine/foe-helfer-extension#2421]
![image](https://user-images.githubusercontent.com/61996796/163671013-01c66097-4e2b-4f1c-83be-d0f542c9b2a0.png)
![image](https://user-images.githubusercontent.com/61996796/163671207-8910e890-129c-4d97-bc43-c5332bc16fca.png)

der Eigenteirechner ist zwei Mal in Menubaum.

**Comment by Beelzebob6666** [comment]
Danke! 
ist im nächsten Update gefixt
