### ISSUE TITLE
Potential Production of Buildings In Inventory / In Stock

### ISSUE THREAD

**Issue by SteveTheTechie** [mainIine/foe-helfer-extension#2422]
(Feature Idea)

I really like the Production Overview screen.  I sometimes wish I could see this same type of information for buildings that are in inventory / not yet placed on the grid.   

Reason: It is not always obvious which buildings in inventory are actually worth building vs trading them at the antiques dealer.  Obviously, users could do the calculations themselves, but I am guessing that FOE Helper could calculate the "potential production" of all of them at once so that we could see the results all at once and compare to see which of them are actually worth building.

Thanks for a really great add-on!

**Comment by Gindi4711** [comment]
This could get really complicated with all the upgrade kits, set Items and Chain buildings.

**Comment by oesi03** [comment]
du kannst auch das "Gebäude-Kits" Tool des FoE-Helfers nutzen wenn du die Spieler-Links in den Einstellungen aktiviert hast 
bietet es dir einen Link zu: https://forgeofempires.fandom.com 
dort gibt es alle Informationen was es auf welcher Stufe in welchem Zeitalter produziert und was du beim Antiquitätenhändler dafür bekommst!

You can also use "Sets, Upgrades & Kit" of FoE-Helper! If you have activated the player links in the settings.
It gives you a link to: https://forgeofempires.fandom.com 
There you will find all the information about what it produces at which level in which age and what you can get for it from the antique dealer!

![Screenshot (26)](https://user-images.githubusercontent.com/81358053/165173068-56d52ebe-09ba-4a0e-950d-5e4a2c88ea86.png)
![Screenshot (27)](https://user-images.githubusercontent.com/81358053/165173085-d5ece194-a4db-49ad-8db4-a7de3bc677f8.png)
![Screenshot (28)](https://user-images.githubusercontent.com/81358053/165173098-d7a8ef36-b43c-4bba-bde9-d943acace67a.png)
s

**Comment by Katzepanther** [comment]
Hallo, 
ich wünsche ein gutes neues Jahr und hab gleich mal eine Frage. Ich spiele in drei Welten und in einer (Arvahall) werden die Gebäude-Kits nicht vollständig angezeigt. Ich hab auch schon alle Seiten des Inventars durchgeklickt, aber keine Änderung. Ich spiele alle drei Welten im gleichen Browser Brave. Starte ich Arvhall in Google Chrome werden die Gebäude-Kits vollständig (ich habs nicht verglichen mit dem Inventar, aber schaut so aus) angezeigt. An was liegt das? Habe ich in Brave etwas umgestellt, das nur für Arvahall gilt?

Screenshot Chrome:
![image](https://user-images.githubusercontent.com/121748191/210165907-db64c814-a46d-43cd-81eb-3eb020daae90.png)

Screenshot Brave:
![image](https://user-images.githubusercontent.com/121748191/210165916-099e36a0-e551-4f0f-82ab-fc9129dcbc93.png)
