### ISSUE TITLE
EG issue with icons

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2428]
![EGIssue](https://user-images.githubusercontent.com/49796453/164196295-4d47054a-29b7-4908-ba4e-9c98258adb76.png)

This is the issue I have with last version of FoE Helper in EG.

Browser: Edge, version 100.0.1185.44 (Official build) (64-bit)
OS Windows 11 x64 version 22000.613

**Comment by Parama91** [comment]
Lastest version, are you sure? Which one do you have?

**Comment by outoftheline** [comment]
should be fixed with the next update #2409
