### ISSUE TITLE
Guild battleground helper: Next sectors: copy&paste feature request

### ISSUE THREAD

**Issue by Jimbow45987** [mainIine/foe-helfer-extension#2436]
Hi,
as a gbg coordinator I often use the FOE helper to announce upcoming sectors. In an active guild there are often a lot of sectors to announce - especially with the new map.

1. Would it be possible to intregrate a copy&paste feature into the next sector overview to have them more easily available?

2. More advanced idea (but maybe not possible): In a perfect would the helper would be also able to include the available amount of siege camps for the respective sector. But I´m not sure if the helper can track this information? 

Best

**Comment by outoftheline** [comment]
the copy function already exists, just click on the lines you want to copy
<img width="399" alt="Bildschirmfoto 2022-04-30 um 12 07 04" src="https://user-images.githubusercontent.com/7482863/166101187-c441bb12-7f4f-4e4a-9887-05463fdb8230.png">

unfortunately we cannot track the available siege camps.

**Comment by Jimbow45987** [comment]
Wonderful! I wasn´t aware of this!!! Thanks a lot!
