### ISSUE TITLE
Guild Overview - Guild Buildings - A.I. Core Undercounted

### ISSUE THREAD

**Issue by skinlessantidragons** [mainIine/foe-helfer-extension#2438]
The A.I. Core appears to be undercounted, currently, in the Guild Buildings tab of the Guild Member Overview widget. It is being counted correctly in the Great Buildings tab, however. FoE Helper version 
2.9.0.0. Chrome version: Version 100.0.4896.127 (Official Build) (64-bit) Screens:
![AI Core Bug - Guild Buildings Tab](https://user-images.githubusercontent.com/104733778/166160287-0fac6e6b-191e-46c2-b491-99b6389b8434.png)
![AI Core Bug - GB Tab](https://user-images.githubusercontent.com/104733778/166160379-958eb838-b5d6-4c98-a20e-79a1353c4c9b.png)

**Comment by Gindi4711** [comment]
Can you try vising those 3 players again with current version (2.9.0.0) and see if anything changes.

**Comment by skinlessantidragons** [comment]
Done! Results:
![AI Core Bug - Guild Buildings Tab - Take 2](https://user-images.githubusercontent.com/104733778/166185072-a1457790-47c8-4906-b4af-6e9f8f526847.png)
![AI Core Bug - GB Tab - Take 2](https://user-images.githubusercontent.com/104733778/166185079-2131ba57-4e0f-4d6c-8b8d-25e8c6fd07e2.png)

**Comment by skinlessantidragons** [comment]
I think I can see the issue now: One of the players with the A.I. Core has disconnected it from their roads, so it is not currently producing guild goods, although it is still technically a GB.  This behavior makes sense to me, so I will mark this as closed. Thank you!
