### ISSUE TITLE
Panoramica degli edifici

### ISSUE THREAD

**Issue by PAT-BEL** [mainIine/foe-helfer-extension#2439]
Buonasera, l'icona della panoramica degli edifici non mi funziona più....quando clicco la prima volta mi apre la maschera (oltretutto molto grande) ma dopo una frazione di secondo si chiude e non si apre più :(

**Comment by PAT-BEL** [comment]
Good evening, the icon of the overview of the buildings does not work for me anymore .... when I click the first time it opens the mask (also very large) but after a fraction of a second it closes and does not open anymore :(

**Comment by outoftheline** [comment]
hope this was fixed in the meantime :D
