### ISSUE TITLE
Gebäude-Effizienzberechnung: Fehlende Werte

### ISSUE THREAD

**Issue by frankmorgner** [mainIine/foe-helfer-extension#2440]
Der Wert für die Verteidigung für die angreifende Armee scheint beim Goldenen Orrery aktuell nicht hinterlegt zu sein...

**Comment by frankmorgner** [comment]
Außerdem fehlt bei der Bühne der Zeitalter der Wert für den Angriff für die angreifende Armee...

**Comment by Beelzebob6666** [comment]
was fixed some time ago...
