### ISSUE TITLE
Idea - Backup - Cloudsync

### ISSUE THREAD

**Issue by ninokotur** [mainIine/foe-helfer-extension#2441]
Hi,

I was thinking it would be great idea to have sync when playing on different computers / laptops to be able to sync historical data between them as if we pickup anything on different device we dont have it in track on computer where any player mainly plays on.

Maybe some google drive integration and icloud integration for ios users would be great as opt in option for backing up data so every time something is loaded into extension it would upload to cloud, and on page reload, compare data local and cloud and load most recent or something like that.

Kind regards,

Nino

**Comment by decommentator** [comment]
sounds nice!

Or an auto backup to a local folder as a start would be nice as well

**Comment by mainIine** [comment]
I browser extension has no access to the file system from the os. They always work in a sandbox environment.
One option is a action like download a file as the export function. 
The other one a sync via Google Drive or something similar.
