### ISSUE TITLE
Production Overview not working

### ISSUE THREAD

**Issue by itango27** [mainIine/foe-helfer-extension#2449]
Haver 3 cities on International sever, and on Dinegu city the Production Overview does not appear, but does on the other 2

**Comment by Parama91** [comment]
Try reset the box coordinates in the settings

**Comment by itango27** [comment]
Did that -- all box co-ordinates deleted -- but still does not appear

**Comment by Parama91** [comment]
Can you check the console pls? F12 -> console and check on red messages, if you have one pls screenshot and add here :)

**Comment by itango27** [comment]
Here you go...

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/50616534/167624135-6da2d59c-2f9a-4e2f-9725-0a97b52ad4ca.png">

**Comment by Parama91** [comment]
Thanks, we will have a look at it! ;)

**Comment by itango27** [comment]
I've uploaded my city data, if that is any help :)

**Comment by Gindi4711** [comment]
Do you have a Golden Orrery lvl6 or lower
or golden fields level 5 or lower?
If yes then I think I have found the problem.

Unrelated to this problem:
I strongly suggest removing the extension "foe powertools". This extension has classified as illegal by Inno and there have already been bans because of it.

**Comment by itango27** [comment]
Hi - I have golden fields lv 3; golden orrery is in inventory; and will remove foe-powertools - did not know about ban

**Comment by itango27** [comment]
Correction not golden fields - i have golden crops lv 3 - not sure if that is the same thing :)

**Comment by itango27** [comment]
BTW foe-helper was working perfectly :) thank you :) before today - I think there was an update this morning as it wanted me to login again
