### ISSUE TITLE
Foe Helper error

### ISSUE THREAD

**Issue by ToxicRebel** [mainIine/foe-helfer-extension#2451]
Hi,

There's an error, where when people aren't investing what's expected, the Helper is off.
https://ibb.co/ygZw19m
This is from today, the player is Rusty-Chev22 so you can check the info yourself.
You only need to invest 88 FP's to be safe, if I calculated it correctly.
And that's my investment target for tomorrow, so please don't take it :)

Als je wil dat ik in de toekomst nog bugs meld (in de veronderstelling dat deze klopt), zou ik dat liever doen via e-mail, dat is wel zo makkelijk.

Vriendelijke groeten,
Jürgen alka Toxic Rebel

**Comment by outoftheline** [comment]
This is working as intended, as this calculator is mainly for your own GBs. 
If you use the other one (calculator symbol and FPs), you should see the correct amounts.
