### ISSUE TITLE
Produktionsübersicht lässt sich nicht aufrufen.

### ISSUE THREAD

**Issue by Osoberni** [mainIine/foe-helfer-extension#2452]
Windows 11 Home 64 bit, Version 21H2
Chrome Version 101.0.4951.54 (Offizieller Build) (64-Bit)
de14
2.9.1.0

Hallo, leider kann ich auf dieser Welt die Produktionsübersicht nicht mehr aufrufen. Es passiert nichts, wenn ich auf das entsprechende Icon drücke.

Ich habe noch eine Welt auf de9. Dort funktioniert es einwandfrei.

Beste Grüße
Osoberni

**Comment by Parama91** [comment]
Die Box Koordinaten über das Einstellungsmenü löschen, dann müsste das Fenster wieder sichtbar sein ;)

**Comment by Osoberni** [comment]
Hi Roman,

 

Danke für Deine schnelle Antwort. Leider hat das nichts gebracht. Habe auch versucht, die Erweiterung neu zu  installieren. Macht leider auch keinen Unterschied.

Hast Du noch eine Idee?

 

Grüße

Tobias

 

Von: Roman Pawel ***@***.***> 
Gesendet: Mittwoch, 11. Mai 2022 19:02
An: mainIine/foe-helfer-extension ***@***.***>
Cc: Osoberni ***@***.***>; Author ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Produktionsübersicht lässt sich nicht aufrufen. (Issue #2452)

 

Die Box Koordinaten über das Einstellungsmenü löschen, dann müsste das Fenster wieder sichtbar sein ;)

**Comment by Florian-L** [comment]
Moin! Ich habe das selbe Problem.

MacOS Monterey 12.0.1 (21A559)
Chrome Version 101.0.4951.64 (Offizieller Build) (arm64) auf Macbook Air M1

Viele Grüße!
