### ISSUE TITLE
Statistics Overview - Unknown DNA (special goods) missing

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#2453]
In the Statistics Overview window when selecting the "special" category, the SAJM special goods (Unknown DNA) doesn't show up:

![image](https://user-images.githubusercontent.com/9089026/168475748-31cd221d-c628-4bc8-b785-0b96bd6a6620.png)

Windows 10 64 Bit
Chrome 101.0.4951.54
us1 (Arvahall)
2.9.1.0 - English

**Comment by Gindi4711** [comment]
Fixed with next update
