### ISSUE TITLE
GB investment overview - persist 'Hide GB not built'

### ISSUE THREAD

**Issue by GeniePower** [mainIine/foe-helfer-extension#2457]
All selections in this screen are persisted except the first checkbox for 'Hide GBs not built'
<img width="503" alt="image" src="https://user-images.githubusercontent.com/97710104/168671223-c36db2cf-de69-4383-b88b-eec9ecd11604.png">

**Comment by Gindi4711** [comment]
That is by design. Players should always check if building a new GB gives more rewards than upgrading existing ones.
