### ISSUE TITLE
Blue Galaxy Helper: Consider Diamond Output

### ISSUE THREAD

**Issue by pmamat** [mainIine/foe-helfer-extension#2458]
Hello, thanks for the great tool.
[The Crow's Nest](https://forgeofempires.fandom.com/wiki/The_Crow%27s_Nest) has a chance to produce diamonds. I think this is a worthy output to be doubled. But the building is not pushed to the top of the Blue Galaxy Helper list.

**Comment by Arklur** [comment]
This "does not work" on purpose. It used work like that, but was removed because it's a bit risky for the extension to help players regarding gaining diamonds.

**Comment by NickRing** [comment]
I asked about the same thing in #1792 and got a "Will Not Implement"

**Comment by outoftheline** [comment]
yeah, it's actually on our "do not suggest" list, sorry -> #860
