### ISSUE TITLE
Other worlds does not appear

### ISSUE THREAD

**Issue by JoiaGames** [mainIine/foe-helfer-extension#2459]
Foe-Helper doesn't detect other worlds that I have on my account, I have 3 worlds, Fel Dranghyr (my main world), Greifental and Langendorn (only this one appears).

**Comment by Gindi4711** [comment]
Did you enable transfer of data to foe-helper.com in the settings menu?

**Comment by Neal446** [comment]
I have the same issue and I do have transfer of data enabled in settings.
