### ISSUE TITLE
Eigenteilsrechner ließt keine fremden LGs

### ISSUE THREAD

**Issue by hslupo** [mainIine/foe-helfer-extension#2462]
Beispiel
Windows 11 64 Bit
Chrome 102.0.5005.63
de17 (R)
2.9.1.0 - Deutsch

Moin 
seit heute ließt der Eigenteilsrechner keine fremden LGs, bzw. zeigt sie nicht mehr an

Ciao hslupo

**Comment by outoftheline** [comment]
Schau mal bitte in die Einstellungen, ob das noch aktiviert ist.

**Comment by hslupo** [comment]
> Schau mal bitte in die Einstellungen, ob das noch aktiviert ist.

🙈🙈🙈 danke, sorry
Aber guter Support von dir/euch
