### ISSUE TITLE
Stadtübersicht zeigt Dekorationen nicht an

### ISSUE THREAD

**Issue by Elmax9** [mainIine/foe-helfer-extension#2465]
Hallo, 

die Stadtübersicht zeigt in einem bestimmten Bereich des Rasters (rote Markierung) keine Dekorationen an, sondern gibt die Fläche als frei an. In dem Bereich ist kein Feld frei. Es stehen da Piraten Wachposten und antike Gesichter. Ein größeres Gebäude, was man in diesen Bereich ragen lässt, wird vollständig dargestellt.
Im Stadtplaner auf foe-helper werden alle Gebäude angezeigt. Neuinstallation des Foe Helpers hat nicht geholfen.
![Stadtübersicht 1](https://user-images.githubusercontent.com/107049363/172388669-1e2a10ff-3799-4dc7-964e-cfb8e4a95367.jpg)

**Comment by oesi03** [comment]
das selbe Problem wie #2470 und gefixt

**Comment by Elmax9** [comment]
Muss bzw. kann ich den fix selber installieren oder kommt der mit einem zukünftigen Update?
