### ISSUE TITLE
FP-Einsammlungen zeigt Blaue Galaxie nicht mehr mit an

### ISSUE THREAD

**Issue by Winter1976** [mainIine/foe-helfer-extension#2469]
Seit 09.06.2022 wird in den FP-Einsammlungen leider nicht mehr die Verdoppelung der blauen Galaxie mit angezeigt. Wäre schön wenn das wieder implementiert werden könnte.

**Comment by Gindi4711** [comment]
Anscheinend gibt es da einen Bug bei Inno:
https://forum.beta.forgeofempires.com/index.php?threads/daily-changelog-w-c-06th-june.15611/post-135826

Ich denke wir werden erst einmal abwarten was Inno an Fixes bringt und dann erneut testen

**Comment by oesi03** [comment]
Inno ist der Meinung es behoben zu haben😅
https://forum.beta.forgeofempires.com/index.php?threads/daily-changelog-w-c-13th-june.15616/#post-135941
na mal schauen was das nächste Update sagt

**Comment by sirphoenix** [comment]
Irgendwas stand dazu in den letzten Patch-Notes, leider wird die doppelte Einsammlung vom Helper immer noch nicht erkannt.
