### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by FastRip564** [mainIine/foe-helfer-extension#2470]
Hello.
Not all buildings located in the city are displayed on the Helper map.
Please fix it.
FastRi
![Скриншот 2022-06-14 12 38 28-1](https://user-images.githubusercontent.com/107458468/173506990-e1e24119-5abf-4f65-a414-17a08c199168.jpg)
p

**Comment by Cady36** [comment]
Related to this, in the city planner itself, when things are imported on the city I am working on, the right-most expansions - probably the new expansions added a few months back - aren't imported, though the buildings are. I added the expansions, but once I moved the buildings (trying to rearrange a set) I can't move buildings BACK onto those expansions, except for the first cell:
![image](https://user-images.githubusercontent.com/52673062/174496174-04d52fdf-5d0b-47b4-ade3-4009f3cf7bf1.png)

**Comment by TheRealKingFlush** [comment]
I too am experiencing both of these issues

**Comment by KostasToutouzis** [comment]
Αnd me too

**Comment by KostasToutouzis** [comment]
And me too.
