### ISSUE TITLE
Blue Galaxy collection.  

### ISSUE THREAD

**Issue by SeanMCC2** [mainIine/foe-helfer-extension#2471]
When you collect on the Blue Galaxy you get a window suggesting what to collect.  After collection can that window show what was collected with the BG bonus?    I collect the little thing manually before I activate the BG and then use the collect all button (5 diamonds)  so I am able to collect over 100 FPs on my bar.  
Thank you for the consideration.
Sean

**Comment by oesi03** [comment]
already exists😊

but has a few small problems at the moment I'm on it�

![Screenshot (32)](https://user-images.githubusercontent.com/81358053/173995246-4e9538ce-b558-45b1-bc83-af50aa28fc9f.png)
�

**Comment by SeanMCC2** [comment]
![image](https://user-images.githubusercontent.com/107558342/174690148-86edac31-fd8a-409d-a3f0-efa3177d980b.png)

After collection the suggested collection box is empty.  So the box is already open and would align with the BG collection.

**Comment by SeanMCC2** [comment]
![bg](https://user-images.githubusercontent.com/107558342/174690297-65a66bea-6658-4923-ab16-3b7cd6ac5944.png)
After collection the BG suggestion box is still open and would align with what you just collected without having to open an additional box.  Just seems logical to fill that box with what was collected or have it automatically close.  
Thanks for a fantastic tool BTW!
