### ISSUE TITLE
GB Calculator: Saving the donation factor per Conversation

### ISSUE THREAD

**Issue by Gindi4711** [mainIine/foe-helfer-extension#2472]
In the next update GB calculator has a new option "Save Donation Factor per Conversation".
.) Calculator will now detect if the great building has been open via the context menu in an open conversation (for example a 1.95 group).
.) When selecting a different donation factor (1.9, 1.92, 1.95 etc.) this value will per stored per conversation.

So after some time:
.) If you open a GB in the 1.9 group it will preselect 90% when opening the GB
.) If you open a GB in the 1.95 group it will preselect 95% when opening the GB

**Comment by Gindi4711** [comment]
For Own part calculator this does not work because you usually open your own GB first, create the copy string and then open the conversation (1.9 group) to post values.

For GB calculator it works if you:
.) Open the conversation first
.) Then open the GB via attachment or context menu of the player

**Comment by Beelzebob6666** [comment]
OK - bummer... I only use the own part for all GB ;)
