### ISSUE TITLE
"Fehler beim Parsen eines Datums" - Beta Version not loading properly

### ISSUE THREAD

**Issue by Teberon** [mainIine/foe-helfer-extension#2481]
Betriebssystem: Win 11 + Win 10
Verwendeter Browser inkl. Versionsnummer: Brave 1.40
Forge of Empires Server: DE13 + DE5
Extension Version und Sprache der Extension: Beta Tester, dasselbe hatte ich damals bei der normalen Version
Fehler in der Konsole falls vorhanden: "DevTools failed to load source map: Could not load content for https://foede.innogamescdn.com/cache/rewriteframes.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"
Sind andere Extensions installiert: LastPass, Dark Reader, Keepa

Beim Laden des Spiels wird die Erweiterung nicht angezeigt, unten rechts erscheint das Beta deaktivieren, aber die Leise wird nicht geladen. Dafür erscheint eine Meldung das es ein Fehler beim Parsen des Datums gab 
![image](https://user-images.githubusercontent.com/25689158/176108266-1013923d-e39f-4097-8a6f-e32a6f02e7dd.png)

Nach mehrmaligen Refresh der Seite wird irgendwann die Erweiterung angezeigt

**Comment by Gindi4711** [comment]
Kannst du in den Extension Einstellungen des Browsers schauen, ob 2 Versionen von Foe Helfer gleichzeit8g aktiviert sind?

**Comment by Beelzebob6666** [comment]
OK, das ist dann vielleicht doch etwas anders gelagert...

tägliche Updates kann es geben, aber das ist immer etwas aktivitätsabhängig - kommt manchmal vor, dass mehrere Updates an einem Tag gemacht werden und andererseits kommt es vor, dass ein/zwei Wochen gar nix geändert wird...

Dutzende Male Neuladen passt auch nicht so recht - wenn es nur am Cache liegt, sollte einmal Neuladen reichen, solange man etwas wartet vor dem Neuladen - damit der Browser Zeit hat im Hintergrund die Daten zu beschaffen.

kommt der Fehler mit der Normalversion auch oft oder ist das sporadisch?

Sprache kann eine Ursache sein halte ich aber eher für unwahrscheinlich - ich kann bei mir die Sprache der Erweiterung problemlos auf Englisch umstellen und es funktioniert - die Sprache fürs Datums-Parsing wird basierend auf der Spielserveradresse festgelegt - dem sind Systemsprache und Broswerspracheinstellungen egal.

Wenn das nochmal auftritt, wäre es sinnvoll, wenn du mal in der Konsole (F12/dev tools) gucken könntest, ob Fehler verzeichnet wurden

**Comment by Teberon** [comment]
![image](https://user-images.githubusercontent.com/25689158/176356835-214ae7ea-447a-4d91-9a03-01f5ba83b4dc.png)
Leider gibt es keinen wirklichen Eintrag in der Console. Es tritt auch den Tag über auch, wenn zum Beispiel das Tool ein Ereignis anzeigt, das Spiel aber nicht. Wenn ich neulade sehe ich das Ereignis, aber das Tool bleibt aus.

Die rote Nachricht vom ersten Post kommt auch nicht mit jedem neuen Laden, oft kann ich Neuladen und es kommt keine Nachricht wegen dem Parsen, aber das Tool bleibt auch aus.

**Comment by Beelzebob6666** [comment]
Heute hat das Laden der Beta-Version bei mir auch etwas länger gedauert - kam erst nach zweimal Neuladen. Einmal habe ich die "konnte nicht geparsed werden" Meldung bekommen. 

Die Meldung kommt vermutlich deshalb, weil noch irgendwas nicht richtig geladen ist. Warum diese Meldung genau kommt kann ich aber leider nicht nachvollziehen.

Wenn das bei dir sehr häufig vorkommt, liegt das vermutlich an einer nicht so günstigen Verbindung zum Verteilerserver.  Wenn es zu störend ist, kann ich an dieser Stelle nur empfehlen, auf die klassische Extension umzusteigen. Beta-Modus deaktivieren reicht da unter umständen nicht, da in der Beta-Extension auch die "Release-Version" via Github bezogen wird - es ist allerdings wahrscheinlicher, dass die im Cache liegt, da die nicht so oft geändert wird.

**Comment by Beelzebob6666** [comment]
Das Problem mit der Parser-Fehlermeldung ist behoben.

Dass der Beta-Loader nicht mehr geladen wird liegt scheinbar daran, dass die Extension zu langsam ist, und eine wichtige Spieldatei nicht abgefangen wird, so dass der Helper nicht starten kann. Wir untersuchen das...

**Comment by Beelzebob6666** [comment]
please load the newest extension version from github for the beta-loader - should work now
