### ISSUE TITLE
city overview

### ISSUE THREAD

**Issue by davecholly** [mainIine/foe-helfer-extension#2488]
the bottom section of the overview only shows blank yellow squares no the buildings on them how do i solve this thank you

**Comment by Beelzebob6666** [comment]
what version of the helper do you use?
The latest version (2.9.3.0) should have fixed that issue

**Comment by davecholly** [comment]
thank you for the reply i am not on that version will try and find it and
download mine is following
Version2.9.2.0Player ID:851581084Guild ID:23233World:en6

**Comment by Beelzebob6666** [comment]
chrome and firefox should update automatically as soon as the new version is available
