### ISSUE TITLE
Aztec mini helper does not show up any more

### ISSUE THREAD

**Issue by champli** [mainIine/foe-helfer-extension#2489]
With the latest update (two days ago), the aztec mini game helper does not work anymore on MS Edge browser.

**Comment by LainFuchs** [comment]
I have the same issue with Chrome on Windows. The Aztec mini helper does not pop up anymore at all. Tested on 2 different notebooks.

**Comment by Soulprayer79** [comment]
just joining because I've encountering the error on firefox and brave as well

**Comment by sravazdurga** [comment]
Yes, the same issue. After the last update, the Aztec minigame helper is not showing up.

**Comment by Beelzebob6666** [comment]
this is fixed on beta
