### ISSUE TITLE
Military advisor

### ISSUE THREAD

**Issue by Beelzebob6666** [mainIine/foe-helfer-extension#2492]
Currently thinking of the concept...

When opening the "Army Organisation"
- helper gets the Att/Def of the player, gets the Att/Def of the defending army
- helper gets the players current army
- helper gets the opposing army
- the worse the players win quota is with the current setup, the redder a border around the army gets 
- the more often a player encountered a certain setup, the thicker the border gets
- maybe the advisor could present the configuration that has the highest success rate

What counts as a "same setup":
- units identical
- unit's LP are ignored
- a bonus quotient of `the players attack stats (att+def+1) / the defenders attack stats (att+def+1)` is used for reference
- the bonus quotient should be of a discrete spectrum (e.g. 0-3 in 0.1 steps)

Possible trouble:
- big dataset? most players like to use a single configuration and only seldom switch it up, that should prevent the data set from getting too big.

Open questions:
- what about AO? Should it be included in the bonus quotient as a simple factor maybe? e.g. AO with 50% --> (att * 1.5 +def) / (att+def)
- clean up of data set??? the data points should include a "last encountered" time stamp - when that is older than X month then the data point is removed?
- differentiate between auto/manual battle?

**Comment by oesi03** [comment]
Habe mir darüber auch schon Gedanken gemacht.
Zu beachten sind weiter: Kraken / Virgo-Projekt.
Weiteres Problem, dass die Höhe der Datensätze ausarten lässt sind temporäre Boni (Taverne/Trank/Ads)
und Zeitalterwechsel

Größtes Problem überhaupt InnoGames da die dann wieder Bedenken bezüglich des "Balancings" (oder wie man das auch nennt "Angst um die eigenen Einnahmen") anmelden werden!
Wie bei allem was das kämpfen oder verhandeln angeht und das tracking dieser Daten oder Hilfen dabei!
Die würden das dann maximal für die gex vielleicht sogar noch für die kulturelle Siedlung(Ägypter) zulassen
Das steht in keinem Aufwand/Nutzen Verhältnis.

_____________________________________________________________________________________________________________________________________

I've been thinking about that too.
Also to be considered are: Kraken / Virgo project.
Another problem that increases the amount of data records are temporary bonuses (tavern/potion/ads)
and age change

Biggest problem ever is InnoGames, as they will then report concerns about "balancing" (or as it is also called "fear of their own income")!
As with anything that involves fighting or negotiating and tracking that data or helping with it!
They would then allow that for the GE at most, maybe even for the cultural settlement (Egyptians).
This has no cost/benefit ratio.

**Comment by Beelzebob6666** [comment]
Currently leaning towards a "warn me about this opposing army when bonus > XXX%" scheme - that way the player can actively add/remove/modify specific warnings. e.g.:

- "use 2+6rogues!"
- "use 8 gliders!"

there could be an "add this army" Button generated after every battle in a not too intrusive position
the button could automatically vanish after X seconds

Menu-Module to modify settings/remove armies from list...
module could have button "add last opponent"

possible settings:
- always show add button
- only show add button when units lost
- only show add button when all non-rogues lost in first wave or when battle lost
- only show add button when module window is open
- never show add button
