### ISSUE TITLE
[IDEA] Tavern helper

### ISSUE THREAD

**Issue by exxaminer** [mainIine/foe-helfer-extension#2494]
Hi, is it possible to implement "Tavern helper" maybe within the current Motivate/Polish helper or on its own? It would - within one screen - display all my friends and these would be sorted/filtered by their tavern status (Full, Waiting, read for a visit) or visually highlighted. Scrolling through the Friends list by 5 and trying to distinguish based on very low-contrast icons is annoying. It's not automation, the mobile version does it natively - sort of (News feed - filter Friends events and just scroll, the most recent friends to visit you are most likely to have collected their silver).

**Comment by jupiler** [comment]
The news feed is available in the browser version as well. (click on your townhall - news - history - filter on friends)
Would be nice if it was added like the motivation feature but that's something for inno i guess

**Comment by Beelzebob6666** [comment]
I also thought about implementing something like this. The main problem is updating the states and having proper data - the game only pulls the newest data for a specific friend when the social bar is updated and they appear in the social bar. Other than that the helper only has the data from first login in.

So, after login, a list can be made:
- can sit
- full
- still sitting (no cooldown)
- await cooldown

When the cooldown for a player is up, we could change the state to "maybe can sit", but the real tavern state is ultimately unknown and the list is not accurate. 

As the first 3 states listed above are dependent on other players actions, those states can change at any point in time  and therefore effectively are "maybe can sit" as well. So not really helpful
