### ISSUE TITLE
Production Overview window closes/crashes immediatley

### ISSUE THREAD

**Issue by jerrytwinam** [mainIine/foe-helfer-extension#2498]
Windows 10 Home
Chrome - Version 103.0.5060.134 (Official Build) (64-bit)
Server - US Zorskog
foe Helper version - 2.9.3.0  English
Errors:  (1) Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
(4) Page layout may be unexpected due to Quirks Mode

All other tabs work perfectly when selected.  The Production Overview flashes open and immediately closes.   I have had this issue for about 2 months.   I have removed and reinstalled Chrome and the foe helper extension but the issue persists.

**Comment by jerrytwinam** [comment]
How is this completed?   Nobody ever responded?  The issue still persists.

**Comment by mainIine** [comment]
Not with the actually version. Also not reproducible. Show me your console error log.

**Comment by jerrytwinam** [comment]
really not sure how to do that.  What is the best way?

**Comment by mainIine** [comment]
Pls update your version up to 2.10.0.0 and your problems are gone....

**Comment by jerrytwinam** [comment]
That was the version I had.  The new version updated this morning and the problem persists.  Production Overview crashes immediately after opening.  
![FoeHelper console](https://user-images.githubusercontent.com/110453773/187374222-6ba0db77-e6f3-49af-b35a-185d1f1ca114.JPG)

**Comment by Beelzebob6666** [comment]
this error likely is unrelated to the production overview - as explained in your other post
