### ISSUE TITLE
[Festure Request] Kopierfunktion der aktuellen Einheiten

### ISSUE THREAD

**Issue by Th3C0D3R** [mainIine/foe-helfer-extension#250]
Siehe [Kopierfunktion](https://forum.foe-rechner.de/d/37-kopier-funktion-in-der-armee-ubersicht)

**Comment by Selene443Foe** [comment]
... die Funktion ist in der Beta enthalten. Funktioniert zwar noch nicht ganz, aber der Wille ist da :D
