### ISSUE TITLE
Recurring quest

### ISSUE THREAD

**Issue by jomste** [mainIine/foe-helfer-extension#2500]
How do I access the new recurring quest information

**Comment by Gegen103** [comment]
Same problem

**Comment by Beelzebob6666** [comment]
the menu entry is missing - will be visible in the next version 

you can run the following commands in the console to manually activate the menu item:
```
_menu.Items.push('recurringQuests');
localStorage.setItem('MenuSort', JSON.stringify(_menu.Items))
```
