### ISSUE TITLE
Recurring Quests

### ISSUE THREAD

**Issue by Gegen103** [mainIine/foe-helfer-extension#2502]
I don't find a new module wit title "Recurring quest".
And the recurring quest themselves have no mark with a check or a question mark (as describe i, Changelog 2.10.0.0

**Comment by Beelzebob6666** [comment]
the menu entry is missing - will be visible in the next version 

you can run the following commands in the console to manually activate the menu item:
```
_menu.Items.push('recurringQuests');
localStorage.setItem('MenuSort', JSON.stringify(_menu.Items))
```

**Comment by Gegen103** [comment]
Your workaround doesn't work.
I didn't find the console for FoE assistant so I used the one from my browser Chrome.
>_menu.Items.push('recurringQuests');
<18
>localStorage.setItem('MenuSort', JSON.stringify(_menu.Items))
<undefined

**Comment by Gegen103** [comment]
Ah, I got it. I needed to hide/show the button

**Comment by Beelzebob6666** [comment]
yeah - forgot to mention the need for a reload
