### ISSUE TITLE
Invisible Incidents

### ISSUE THREAD

**Issue by TomServo92** [mainIine/foe-helfer-extension#2507]
FoE Helper shows that I have three road incidents but I can't find them.  I have put all buildings into temporary storage so that 100% of the roads are visible and there are no incidents.  I don't even see traffic stoppages on the roads (in case the incident is there but not visible).  Other incidents (forests, water) seem to be working OK.

**Comment by TomServo92** [comment]
Windows 11 64 Bit
Edge Version 104.0.1293.54
us22
2.10.0.0 - English

**Comment by TomServo92** [comment]
Cancel this.  It turns out it's an issue within FoE.

**Comment by mainIine** [comment]
The helper only passes on this information. Whether something is on a road or not is Inno's problem.
