### ISSUE TITLE
Production Overview window closes/crashes immediatley #2498 - 

### ISSUE THREAD

**Issue by jerrytwinam** [mainIine/foe-helfer-extension#2511]
![FoeHelper 3](https://user-images.githubusercontent.com/110453773/187381661-baf0f136-a787-41a6-a73e-834397fa5367.JPG)
![FoeHelper 2](https://user-images.githubusercontent.com/110453773/187381663-6b383a51-138b-41d6-9d67-333864c7e0b8.JPG)
![FoeHelper console](https://user-images.githubusercontent.com/110453773/187381664-f1dc555d-1975-4eeb-88a8-a8952e06e93d.JPG)

**Comment by Beelzebob6666** [comment]
this likely has nothing to do with the production overview per se - but still is an unwelcomed issue

please have the console open when reloading the game and let me know what you did in the game (not the helper) just before the error appeared the very first time

I highly suspect that you are using an other extension (which has the clarity.js) - what is that extension? this seems to trigger the error.

I will try to implement an error handling to hopefully mediate such issues - until the next update you should deactivate the third party extension on FoE

**Comment by jerrytwinam** [comment]
Reloaded with the console open and the errors start appearing as the game is loading, before I have done anything at all.

I only had two other extensions installed in Chrome and they were a Capital One shopping extension and Google Docs Offline extension.  Uninstalled them both but the errors still occur as the game is loading.

Not tech savy, obviously but here is a screen shot of the folder structure described above.   Not sure if this helps.
![FoeHelper 5](https://user-images.githubusercontent.com/110453773/187412206-a3c6f754-1642-4435-adfb-c83e299817c3.JPG)

**Comment by Beelzebob6666** [comment]
well... told you to click the "clarity.js" one... 
but obviously there are a ton of other scripts loaded currently:
![image](https://user-images.githubusercontent.com/66054355/187413152-99ddd8b7-181f-457e-abc3-55ebbf8c6841.png)
one of them is sending data to "clarity.ms" - apparently a Microsoft application
I suspect that the culprit for the error message - but that likely has nothing to do with the production window not showing.
just a sign that MS is spying on you, as they send out data...

**Comment by jerrytwinam** [comment]
This is the only clarity.js I could find...  given I'm not entirely sure what I'm looking for.   I'm a truck driver.  lol
![FoeHelper 6](https://user-images.githubusercontent.com/110453773/187416293-a859ae94-7533-4fa2-811b-cae6ca13f736.JPG)

**Comment by Beelzebob6666** [comment]
jupp - as suspected - that has to be some kind of plugin that is running in the background - As I do not know that tool, I can not really say where you could possibly deactivate it...

but you should also look into all those other things: bing, google, facebook... those might be in the form of "toolbars" maybe?

**Comment by jerrytwinam** [comment]
Thank you for all of your time and help.  I installed a toolbar once in 1996, never again!  Deleted my Facebook account a couple years ago.   No idea how to get rid of any of those other things.   I run something called Spybot Search and Destroy but all it seems to do is find tracking cookies to delete.   Thank you again, I'll just live without the production overview tab working.  It really was very useful.

**Comment by Beelzebob6666** [comment]
as there are no error messages in regards of the production overview - did you already try to reset the box positions?
Settings - extension - box coordinates - delete... maybe that helps...
alternatively zoom out with the browser zoom (CTRL + mouse wheel)

**Comment by jerrytwinam** [comment]
You're a genius, lol   That worked!!!  Thank you
