### ISSUE TITLE
External Great Monuments not always included in OwnPartBox ?

### ISSUE THREAD

**Issue by lnplnp** [mainIine/foe-helfer-extension#2512]
Hello,

It happens that the "OwnPartBox" window does not take into account the external Great Monuments.
I am unable to determine in which cases external monuments are taken into account and in which cases they are not taken into account.
I know this window is for our own monuments but it's a plus when external monuments are taken into account.

Thank you for this great extension.

**Comment by Beelzebob6666** [comment]
there is a setting in the extension settings that activates this

**Comment by lnplnp** [comment]
Do you mean that it is a setting by Great Monument ? Could you reminde me what is this setting/parameter ?
