### ISSUE TITLE
Constant error in dev log

### ISSUE THREAD

**Issue by gsxruk** [mainIine/foe-helfer-extension#2515]
Hi,

I have noticed that the following error appears constantly in the Google Chrome dev console (at least on my system):

index:1 Uncaught (in promise) SyntaxError: Unexpected token '', "�\00\00\00\00\00\00"... is not valid JSON
    at JSON.parse (<anonymous>)
    at xhrOnSend (foeproxy.js:539:21)
    at XHR.send (foeproxy.js:549:4)
    at Oa (clarity.js:2:39126)
    at clarity.js:2:38633
    at clarity.js:2:5988
    at Object.next (clarity.js:2:6093)
    at o (clarity.js:2:4832)

Is this something you are aware of?

**Comment by Beelzebob6666** [comment]
yeah - that is a conflict with another extension you are using - will be fixed in the next version and only is cosmetic
