### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by enricomg** [mainIine/foe-helfer-extension#2516]
hey guys but what have you done? both in the beta and in the master same problem removed in the setting douplefp back to normal, I don't have time to check
![setting](https://user-images.githubusercontent.com/61316507/189200658-3fdac9d1-ccee-474e-99b0-ffa280d774e8.png)

**Comment by Beelzebob6666** [comment]
there was an issue in the beginning, but that was patched before it went to the live version....
not sure if it helps, but try in the console (F12):
`localStorage.setItem('doubleFPtimeout', '0')`

if that does not work, please check the console for error messages and post them here

**Comment by enricomg** [comment]
perfect it worked , thx
