### ISSUE TITLE
Stadtplaner kann Teile der Karte nicht besetzen

### ISSUE THREAD

**Issue by Trimires** [mainIine/foe-helfer-extension#2519]
OS: Windows 10
Browser: Chrome 64bit ver: 105.0.5195.127
Im Stadtplaner der Webseite ist es mir nicht möglich ein Gebäude an bestimmten Stellen der Karte zu platzieren.
Die Gebäude, die man importiert, werden zwar angezeigt, aber wenn man versucht andre Gebäude dahin zu verschieben, geht dies nicht.
Dies hat möglicherweise mit der Kartenerweiterung in FoE vor einigen Monaten zu tun, denn es betrifft in meinen Fall einen Bereich, den es vorher nicht gab. Bei mir sind es die Kartenerweiterungen ganz rechts unten(bzw. nur rechts in der 2D-Ansicht)
Indem Bild kann ich die Orangerie nicht weiter rechts verschieben, als das.
![bug](https://user-images.githubusercontent.com/26199522/191327741-0e0fe521-0453-4c9b-96ce-c53386894dca.jpg)

**Comment by mainIine** [comment]
Ich habe versucht das nachzustellen, aber bei mir geht alles.
Es gibt theoretisch auch keine Begrenzung in den Bereichen, da diese mit der mitgelieferten Fläche automatisch gesetzt werden.
Schaue mir das aber noch Mal an.

**Comment by Warema-von-Lueneburg** [comment]
Hallo, ich habe genau das selbe Problem, was Trimires schreibt. Ich habe es mit Google Chrome, Firefox und auch Edge als Browser versucht: es bleibt gleich - bei mir beginnt es sogar noch eine Kästchenreihe vorher, da ich dich Ausbuchtung noch nicht frei geschaltet habe. Sehr schade, nutze den Stadtplaner schon sehr lange zum Umbauen, komme nun leider nicht weiter.

**Comment by ChaosLord76** [comment]
Hallo unter Opera auf Mc-OS habe ich weiterhin genau das beschrieben Problem. Sobald man versucht ein Gehbäude auf die angezeigte flache zu schieben, bleibt diese davor stehen und mann kann es nur halb ablegen. Interessant ist, das wenn man das entsprechende Gebäude in der unteren Ecke festhält, kann man es etwas weiter schieben aber nicht ganz normal wie bei den anderen Flächen.

Grüße

Steve
