### ISSUE TITLE
Guild Battlegrounds statistics

### ISSUE THREAD

**Issue by adryang78** [mainIine/foe-helfer-extension#2520]
Hi!
It would be a great improvement if a leader that use foe-helper could see in real time who is fighting/negotiating in GbG and, most important, on WHICH sector.
Is there a chance to add this feature to the extension?
Thanks!

**Comment by Beelzebob6666** [comment]
no - we do not access to that kind of info/data - if you want to know who is currently performing actions you have to repeatedly open the point/league overview
