### ISSUE TITLE
GG: Angabe der Anzahl der Min/Max-möglichen BLs in der NextUpTab

### ISSUE THREAD

**Issue by gitinh0** [mainIine/foe-helfer-extension#2521]
Hallo zusammen,
aktuell wird in der Tabelle der nächsten Gefechte die Informationen "Provinz", "um" (also die Uhrzeit, wann der Sektor aufgeht) und "in" (verbleibende Zeit bis zur Öffnung) ausgegeben.
Es wäre m.E.n. hilfreich, wenn noch die Anzahl der Mindest- und Maximal-möglichen BLs, die sich aus den Bauslots der umgebenden Sektoren ergeben, ausgegeben werden.

Beispiel: Sektor B5B ist von zwei Sektoren B4A und B4B umgeben. B4A hat einen Bauslot, B4B hat 2 Bauslots.
In einer zusätzlichen Spalte in der NextUp-Tabelle würde dann "1-3BL" stehen.

VG aus Parkog!

**Comment by Beelzebob6666** [comment]
hierüber hatten wir schon mehrfach nachgedacht - die Anzahl der möglichen Lager anzugeben ist zwar grundsätzlich möglich, könnte aber für viele Spieler verwirrend sein - und beim Ausschreiben ist ein von-bis auch nicht sonderlich hilfreich
