### ISSUE TITLE
Löschung von Chats im Gildenbereich 

### ISSUE THREAD

**Issue by mordillo666** [mainIine/foe-helfer-extension#2523]
Wir haben zZ auf zwei Welten das Problem, dass immer mal wieder Chats im Gildenbereich verschwinden.
Wenn es kein Fehler im Spiel selbst ist, muss ja ein Spieler mit entsprechenden Rechten diese gelöscht haben.
Besteht da die Möglichkeit das irgendwie anzeigen zu lassen?

**Comment by Beelzebob6666** [comment]
vielleicht wenn du zum Zeitpunkt der Löschung gerade online bist, aber ich glaube nicht...
