### ISSUE TITLE
Incorrect guild goods shown for BA building

### ISSUE THREAD

**Issue by sandratiffin** [mainIine/foe-helfer-extension#2525]
The FoE helper is showing my Golden Crops will contribute 10 BA guild goods. Inno support confirmed to me today that my BA GC will actually contribute IA goods, given BA goods can't be donated to the guild treasury. (I don't know that this is true for all BA guild good-producing buildings, but must assume it is true as I have seen someone say it is true for the Statue of Honor also).

![Screenshot 2022-10-12 at 02 24 31](https://user-images.githubusercontent.com/2490111/195227840-ce3b0a5f-ee52-4451-9fce-565b23810b2b.png)

From the support email:
"Thank you for contacting the Forge of Empires Support Team.
Yes, the Bronze Age Golden Crops building will provide Iron Age goods."

**Comment by outoftheline** [comment]
Yes, any BA building put IA goods in the treasury
