### ISSUE TITLE
[CRITICAL] GvG Map - Special characters (e.g. <>) in guilds' name

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#2526]
It seems if the name of a guild includes the `<>` characters, the name is not shown, likely because the special characters are not escaped, become the part of the HTML itself:

![image](https://user-images.githubusercontent.com/9089026/195377460-fd3a78bf-61e6-4740-a416-0afa17586e47.png)

Windows 10 64 Bit
Chrome 106.0.5249.119 (64 bit)
us1 (Arvahall)
2.11.0.0 - English

**Comment by Th3C0D3R** [comment]
This is really critical as it could enable XSS!

**Comment by teageek** [comment]
Whatever you did within the last update:
It made it worse:
![2022-10-24 13_58_25-Window](https://user-images.githubusercontent.com/26075267/197521468-4b045dbf-01f0-4c33-906c-850a4e25ba89.png)
