### ISSUE TITLE
cityplanner with zoom and move pieces together.

### ISSUE THREAD

**Issue by Etevaldo1190** [mainIine/foe-helfer-extension#2528]
May I have a sugestion to foehelper? To use cityplaner, is it possible to move many pieces together?  Ex: To move a road, instead moving each brick, I can select and move entire path. Another sugestion is to zoom in and out  the city map. It makes easy to group buildings around the extensions and move them to  rebuild. Thanks.

**Comment by mainIine** [comment]
Sounds easy but it is really tricky to program.
