### ISSUE TITLE
GBG box is gone. 

### ISSUE THREAD

**Issue by KokoPuddin** [mainIine/foe-helfer-extension#2529]
FOEhelper Guild Battle Ground box is gone. 
The second box (FOEhelper box) that use to pop up along with the 
Battleground League box when you clicked on the Battleground League box.
Now I can't tell who had what hits in GBG.
How do I get it back?
Is there an update or do I have to uninstall and reinstall FOEhelper?

**Comment by outoftheline** [comment]
try resetting the box coordianates in the settings, please

**Comment by KokoPuddin** [comment]
Didn't work. I deactivated it and check it to activate again and nothing. 
Still not working.

**Comment by Th3C0D3R** [comment]
the box coordinates are resetting then

**Comment by KokoPuddin** [comment]
Okay, so, you are saying that if I press the button that says "Delete",
then it will reset all of the boxes and I will have to reset them manually?

**Comment by KokoPuddin** [comment]
Nobody really knows, do ya?
Well, just say you don't know or don't respond to this message if you don't know.
Thanks for nothing. 
I will not be using this unhelpful site again.
