### ISSUE TITLE
Recurring Quest Bug

### ISSUE THREAD

**Issue by Pictonboy** [mainIine/foe-helfer-extension#2531]
After the update that installed the Recurring Quest, clicking on its icon fails to show any information. Instead, the Recurring Quest window opens and then immediately closes when the icon is clicked. I waited for the next update (October 24/22) thinking it may correct the issue. It did not. Thoughts?

**Comment by Beelzebob6666** [comment]
please try to reset box coordinates in the settings
Settings (cogwheel in menu) - General - Box coordinates - Delete

**Comment by Beelzebob6666** [comment]
![image](https://user-images.githubusercontent.com/66054355/197842958-8658a3e5-fb18-4d4b-8d7c-34c086300e2c.png)

**Comment by Pictonboy** [comment]
Followed the directions as requested, still same results. I repeated and included closing my browser and restarting it as well. No success.

Am using Opera Browser, fyi.

Tony Gentile
613-969-0612

**Comment by Pictonboy** [comment]
Is it possible to remove my signature and number please?

**Comment by mainIine** [comment]
You can edit posts by yourself.

If you have no recurring quest the box close immediately.

**Comment by Pictonboy** [comment]
Thank you, I will try again.

Tony Gentile
343-367-2150
________________________________

**Comment by Beelzebob6666** [comment]
sorry for the late reply - is the problem still occuring?

**Comment by Pictonboy** [comment]
Yes it does. I have to think that a file was corrupt or corrupted during install / upate.

Tony Gentile
613-969-0612

**Comment by Beelzebob6666** [comment]
are there any error messages in the console?
open dev tools (F12 typically) - there select "console"

**Comment by Pictonboy** [comment]
***@***.***

Tony G

**Comment by Beelzebob6666** [comment]
btw: do you currently have any active recurring quests? Or did you age up recently and you have not reached the recurring quests?

**Comment by Pictonboy** [comment]
Yes, I do on one of my worlds. I have one world on the Beta Server with an active recurring quest. I have one active one in one of five other worlds on the EN server.

**Comment by Pictonboy** [comment]
*Two of my worlds.

**Comment by Pictonboy** [comment]
* Clarification:  I have two recurring quests that I can proceed with. I have others that require me to age up. The last age up was approx 2 - 3 months ago.

**Comment by Beelzebob6666** [comment]
please provide a screenshot - and the data requested above

**Comment by Pictonboy** [comment]
From Console
![screen grab](https://user-images.githubusercontent.com/116567550/204161137-6e24b6e2-5e51-4a09-a6a5-921acf030ed7.jpg)

Recurring Quest - Beta Server
![image](https://user-images.githubusercontent.com/116567550/204161380-7dd5e50e-aae0-4e50-a4db-a7068ae62932.png)

Recurring Quest - EN Server - Langendorn - There are still four technologies that I can complete for this age (Colonial)

![image](https://user-images.githubusercontent.com/116567550/204161727-04c65e46-24f4-487b-85e2-8f4a7a4b1976.png)

I trust this is what you are looking for.

**Comment by Beelzebob6666** [comment]
As expected - none of the quests you show are recurring quests - those are side quests and story quests. It says it in the brackets!

You will only get the recurring quests after finishing or canceling all the side quests of the current age.
