### ISSUE TITLE
Produktionsübersicht

### ISSUE THREAD

**Issue by Kampfdruide** [mainIine/foe-helfer-extension#2537]
Bei mir funktioniert die Produktionsübersicht nicht , entweder gehts kurz auf und ist sofort weg oder sie geht gar nicht
Nach Neustart geht es zwar sehe aber nur die untere Hälfte 
Kann mir wer helfen ?

**Comment by Beelzebob6666** [comment]
1) bitte mal die Box Koordinaten zurücksetzen ![image](https://user-images.githubusercontent.com/66054355/203337386-0e545ac1-449a-4506-a637-449694c0d96f.png)
2) bitte mal die Entwicklertools öffnen (F12) und in die Console schauen - werden hier Fehler angezeigt?
3) bitte mal einen screenshot machen, wenn nur die untere hälfte zu sehen ist

**Comment by Gindi4711** [comment]
Und bitte die Bug Report Vorlage hier verwenden:
https://github.com/mainIine/foe-helfer-extension/issues/620

Das spart uns die ganzen Rückfragen nach Browser, Betriebssystem usw.

**Comment by Kampfdruide** [comment]
Danke , ich kann auf jeden Fall die komplette Produktionsübersicht wieder verwenden auch wenn ich nach F12 öffnen Fehler habe wo ich nicht weiss was die bedeuten,da ich kein Programmierer bin und ich mir da schwer tue

**Comment by Beelzebob6666** [comment]
Du musst die Fehlermeldungen ja nicht verstehen, aber wenn du sie uns wiedergibst (kopierst/screenshot), dann können wir damit vielleicht was anfangen ;)
