### ISSUE TITLE
Event DS switch log

### ISSUE THREAD

**Issue by Valutin** [mainIine/foe-helfer-extension#2538]
Hello, 
Is it possible for FoeHelper to keep track of the Daily Special switch that has appeared by specific world? For example, on one of my main fighting world, I forgot if I had the House of Horror as a daily special switch already or not. I can refer to the wiki for the main Daily Special, but switches are random.
Would be nice to keep track of it if possible.
Thanks

**Comment by Beelzebob6666** [comment]
Why do you need that?
The switch DS is randomly selected from all DS of the event - it is not as if you could get a DS switched in only once per event. You can thoretically switch to a certain prize 10 times or not at all.

**Comment by Valutin** [comment]
Oh, I was not aware of that. If it's random out of a list, then, just forget it. I thought it would work like th emain DS, meaning that once you have switch to an item, the same item won't appear again (unless it was there multiple times to begin with).
Thanks for the feedback :)
