### ISSUE TITLE
Übersetzungsfehler

### ISSUE THREAD

**Issue by Shadoria-max** [mainIine/foe-helfer-extension#2545]
Hallo, der Foe-Helper übersetzt in dem  Moppelassistenten und in der Spielerübersicht in den GG leider die Spielernamen. Spieler können somit kaum noch zugeordnet werden und ich muss ständig nach meinen Freunden suchen. Könnt ihr das bitte ändern? Namen übersetzt man nicht, das ist ein no go! So wurde aus Matches Streichhölzer der Gesegnete, aus Hetake Er nimmt. Iguana sterben Tapfere, Schmiede 21 und Willenskraft sind echt eine Zumutung! Bitte sorgt hier für Abhilfe!

**Comment by mainIine** [comment]
Hi @Shadoria-max 

Der Helfer übersetzt keine Namen. Hat also überhaupt nichts mit ihm zu tun.

Deaktiviere in deinem Browser die automatische Übersetzung, dann sollte alles stimmen. Meist ist das ein Zeichen am Ende der URL Leiste.

**Comment by Shadoria-max** [comment]
Herzlichen Dank für die rasche Antwort.

 

Ich habe seit 3 Tagen einen neuen Lapi und irgenwie die automatische Übersetzung eingeschaltet gehabt. Wäre ich ohne eure Antwort eher nie drauf gekommen.

 

Danke und LG

Shadoria-max

 
 

Gesendet: Samstag, 26. November 2022 um 13:17 Uhr
Von: "Daniel Siekiera" ***@***.***>
An: "mainIine/foe-helfer-extension" ***@***.***>
Cc: "Shadoria-max" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Übersetzungsfehler (Issue #2545)


 

Hi @Shadoria-max

Der Helfer übersetzt keine Namen. Hat also überhaupt nichts mit ihm zu tun.

Deaktiviere in deinem Browser die automatische Übersetzung, dann sollte alles stimmen. Meist ist das ein Zeichen am Ende der URL Leiste.
