### ISSUE TITLE
Icons bei Gebäude-Kits fehlen

### ISSUE THREAD

**Issue by thodem** [mainIine/foe-helfer-extension#2548]
Bei der Anzeige der Gebäude-Kits fehlen die Icons/Previews. Dadurch wird die Anzeige der Kits "etwas durcheinander".
Im Netzwerk-analysator werden bei Aufruf des foe-helper Menüpunktes "Gebäude-Kits" 404-Fehler angezeigt.

Eventuelle Ursache: Umstellung auf cdn??? 
anstelle von "https://de6.forgeofempires.com/..." müsste evtl. "https://foede.innogamescdn.com/assets/" verwendet werden.

z.B. Adresse: _https://de6.forgeofempires.com/shared/icons/reward_icons/reward_icon_upgrade_kit_heroes_tavern.png_
gibt 404!
Im Spiel wird aber Adresse _https://foede.innogamescdn.com/assets/shared/icons/reward_icons/reward_icon_selection_kit_heroes_tavern-b03da9228.png_ verwendet.
Ein Test von Aufruf 
_https://foede.innogamescdn.com/assets/shared/icons/reward_icons/reward_icon_upgrade_kit_heroes_tavern.png_
zeigte ebenfalls das Bild des Kit an.

// verwendete Konfiguration
Mac OS 10.15.7
Firefox Developer 108.0b9 / auch in Firefox 107.0.1 !
de6.forgeofempires.com, auch auf anderen de[XX].forgeofempires.com!!!
foe-helper 2.12.1.1 deutsch
![Gebaeude-kits-Fehler](https://user-images.githubusercontent.com/23363064/205963792-4ea8adce-bf4d-488d-9467-b8d1824d1f88.png)
![Netzwerkfehler-bei-Klick-auf-Gebauede-kits](https://user-images.githubusercontent.com/23363064/205965507-17782a97-2cc0-4f9d-9ea2-218efae273da.png)
.
.

**Comment by thodem** [comment]
Problem bestand heute nicht mehr!

**Comment by Beelzebob6666** [comment]
Either you still had an old version running, or you did not wait long enough after loading the game before opening that module.

**Comment by thodem** [comment]
> Either you still had an old version running, or you did not wait long enough after loading the game before opening that module.
I suspect that both causes do not apply. On the one hand, I used the current version of the extension (2.12.1.1), on the other hand, the error also occurred when I was already logged into the game for more than 30 minutes. The problem did not occur once but reproducibly over many days every time. Here I was then partly very long already logged into the game.

In my opinion, it was either due to the use of a wrong base URL from the game or the extension, or the corresponding resolution was not implemented locally for me. 
For the last cause, of course, could be that one of the "third-party" scripts was outdated. However, I clear the browser cache at least daily.
