### ISSUE TITLE
[Bug] Bounties from Privateer's Boathouse are not considered in Building Efficiency Rating

### ISSUE THREAD

**Issue by Squazz** [mainIine/foe-helfer-extension#2555]
Bounties from Privateer's Boathouse are calculated in Building Efficiency Rating

Buccaneer's bounty gives 8FP and Deadmans Bounty gives 6FP
Deadmans Bounty also contains 25 Guild Treasury Goods
But those are not part of the calculation of how efficient a building is.

**Comment by Beelzebob6666** [comment]
I guess we will need a special table for cases like this and for the buildings with random productions

**Comment by Squazz** [comment]
Yeah, we are getting more and more buildings with cases like this. And unfortunately I guess it will be some kind of hard-coding for every case, as Buccaneer's bounty & Deadmans Bounty gives goods and forgepoints, that you can easily give a value. Where other buildings gives fragtments that's hard to put a value on, and unfeasable to give a value to every kind of fragment in the game.

The buildings with random productions should be averaged out. I've seen thoughts about this already, so no need to elaborate further on that.
