### ISSUE TITLE
[Bug] Statue of Honor building are shown as Road to Victory in Building Efficiency

### ISSUE THREAD

**Issue by Squazz** [mainIine/foe-helfer-extension#2556]
All of my Statue of Honor building are shown as Road to Victory in Building Efficiency

Took me some time to figure out why I couldn't see any Statue of Honor buildings.
I guess this happens when one has at least one Road to Victory placed. But I'm unable to verify that

**Comment by Gindi4711** [comment]
This is the name of the set "road to victory" which consists of:
.) Statue of honor
.) Road to victory (the building name)

Those set names are read from the game so it was Inno who did the bad naming, but as set names are not directly visible in the game I think they will not care if you complain about it.

**Comment by Squazz** [comment]
Oh, so there's no way to seperate the information of Statue of Honor buildings that have Road to Victory connected, and those who doesn't?
