### ISSUE TITLE
[Feature request] Inclusion of St. Mark's Basilica in GB Investment Overview - based on coin boost

### ISSUE THREAD

**Issue by Squazz** [mainIine/foe-helfer-extension#2558]
As the St. Mark's Basilica gives a percentage boost to coin production, and coins can be used to buy Forge Points, investments into St. Mark's Basilica can in some scenarios be a better investment than many other FP producing buildings.

I know that St. Mark's Basilica is already shown due to goods production. So I'm advocating for some way to take coin boost into consideration.

How to illustrate this in the GB Investment Overview, I don't know, sorry :)

**Comment by Gindi4711** [comment]
The problem about this is that the coin cost of buying FP increases with every FP bought so the FP/day will be going down pretty fast and I dont know how I should compare a fixed FP production like Cape with one that goes down over time.

**Comment by Squazz** [comment]
Hmm, you can't I guess :)
It would be a here and now representation.

But, I would guess that even though the price increases for every coin you buy. Then the increase of 50 gold per coin, really isn't much when a coin costs 1 or 2M coins.
When a coin costs 1M, the price increases with 0.005% for every coin bought.

Or, said in another way.
Let's assume a coin costs 1M.
If an increase of coin-production of 5% is giving you the possibility to buy, say, 10FP every day. When the price increases to 2M, that's still 5FP a day.
But, in order for the price to go from 1M to 2M, you would have to buy 20 000FP. Resulting in a cost of 29 999 500 000 gold.

Whay I'm trying to say.
When the price for FP gets high enough, my guesstimate is that it's semi ok to compare a fixed production with increased buying bower. 

Right now, the ROI for my Cape is above 3500 days. The ROI for St. Mark is about 350. Even though the price for FP will steadily climb, I will also get into a new era within that timeframe, gaining new buildings that produces more gold.

It's impossible to calculate 100% correct.
But it can give you an idea of if 10 levels in St. Mark is a sensible trafeoff compared to a lvl more in Cape ;)
