### ISSUE TITLE
Cant Signup for FOE-Helper

### ISSUE THREAD

**Issue by SCHLUMPFSCHRAMMEL** [mainIine/foe-helfer-extension#2561]
Hello
My Infos:
Megan Rapinoe (849783648), de18
I play FOE on Firefox

When I trie to signup under [https://foe-helper.com/register/player](url) I always get the same reply: "We couldnt find your Players-ID. Is it the right Number? Have you used the Extension ingame" Ill add the german Screenshot.

While I`m playing Foe on Firefox, the FOE-Helper recognizes me and I can use the basic Features for peoples having the FOE-Helper-Addon installed on Firefox.

SO... i don`t get it ... The Addon obviously recognizes me, but it doesn`allow me to signup.

Look... I`M not the greatest Technerd but i useally don`t have problems to signup for something. Meaning .... never

![Warnhinweis FOE Signup 301222](https://user-images.githubusercontent.com/121660745/210045276-ab8b7b5f-fe7f-42fa-8960-fda29f99a2ad.png)

Greetings
PS
If this is not the right place for my problem could you tell me where to look?

**Comment by loops** [comment]
Me too.

Trying on International  "enxx" server, have triple checked my player ID, and still the website refuses to recognize and register me.   Am still waiting for a reply about the issue on the Discord server, but thought I'd post it here as well in case anyone can offer a solution.

Cheers.

**Comment by loops** [comment]
For anyone stumbling on this in the future, you must use the extension in the browser first:

Open "Town Overview",  "Show submit box" and then submit to website.

After that, the registration window on the website will know your player ID and allow you to sign up with a username and password of your choosing.
