### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by TacomaGray** [mainIine/foe-helfer-extension#2562]
The menu bar (bottom of page) shows a different number of icons on each city, ranging from 4 to 7.  I can't find a place to change this.  Help please.

![FoE Helper](https://user-images.githubusercontent.com/121702471/210122535-41a97414-2d1e-4487-873f-a073b0f9b5f1.jpg)

**Comment by outoftheline** [comment]
You can change the amount of icons in the settings
