### ISSUE TITLE
motivate/polish activity doesn't work

### ISSUE THREAD

**Issue by gamer6984** [mainIine/foe-helfer-extension#2567]
motivate/polish activity doesn't work anymore
the activity is not shown correctly

Windows 10 64 bit
Chrome 108.0.5359.125
IT 5
3.1.0.0 - Italian

**Comment by outoftheline** [comment]
can you give a bit more detail? I just went through my townhall and everything updated in the helper.

**Comment by gamer6984** [comment]
if I switch the language from italian to english the issue disappear
https://prnt.sc/rJ_Ebd_XdzwO    (english)
https://prnt.sc/3cypslnb86rj      (italian)

**Comment by outoftheline** [comment]
thanks, someone translated too much, will be fixed in the next version

**Comment by gamer6984** [comment]
thanks for your help
