### ISSUE TITLE
Leiste verschwunden

### ISSUE THREAD

**Issue by Rosengaertner60** [mainIine/foe-helfer-extension#2568]
Seit dem letzten Update von Firefox, ist die FoE-Leiste verschwunden. Laut "Extensions" ist der FoE-Helper installiert. Firefox 108.02 (64 bit) auf einem Linux Ubuntu System

**Comment by Beelzebob6666** [comment]
sorry for the late reply - is this issue still persisiting

**Comment by Rosengaertner60** [comment]
Thank you for your answer - this issue is still persisting
Greetings
Jürgen Pohl

Am Mo., 20. März 2023 um 18:55 Uhr schrieb Beelzebob6666 <
***@***.***>:

**Comment by Rosengaertner60** [comment]
Tut mir leid, so viel weiß ich nicht. Ich kann das Terminal öffnen, aber
wie ich einen screenshot von der Console machen kann, weiß ich leider nicht

Am Di., 21. März 2023 um 15:38 Uhr schrieb Beelzebob6666 <
***@***.***>:

**Comment by Beelzebob6666** [comment]
Dann können wir dir leider nicht helfen.

Ich kann bestenfalls noch raten, dass die Erweiterung nicht aktiv ist, weil die von irgendwas blockiert wird
