### ISSUE TITLE
Idee: GvG Spieler Übersicht 

### ISSUE THREAD

**Issue by FoEHero** [mainIine/foe-helfer-extension#2570]
Wäre es den möglich auch im GvG, ähnlich wie im GG die Kämpfe / BA und das VA setzen der eigenen Gildis aufzuzeichnen und in einer Liste darzustellen?

Would it also be possible in GvG, similar to GG, to record the fights / BA and VA set of your own guildis and display them in a list?

**Comment by outoftheline** [comment]
Ja, könnte ich hinzufügen. 
Es wird aber nur mitgezählt, was auf der Karte, auf der man sich gerade befindet, passiert. Spielt parallel ein Gildenkollege auf einer anderen Karte, können wir das nicht erfassen.

**Comment by FoEHero** [comment]
Schade, aber besser wie nichts :P
