### ISSUE TITLE
Event Window does not load

### ISSUE THREAD

**Issue by DieRabin** [mainIine/foe-helfer-extension#2585]
![event](https://user-images.githubusercontent.com/126161116/220888427-2feb4c2a-4f2d-49ee-8502-a9c0a7878550.jpg)

The Foe Helper Event Window doesn´t load.
I have restarted the browser (chrome newest version), I have uninstalled Foe Helper but it doesn´t help.
What can I do?

Thanks for your help.

**Comment by outoftheline** [comment]
Look in the settings for "event chest" please
