### ISSUE TITLE
inconsistent event window

### ISSUE THREAD

**Issue by esirca1** [mainIine/foe-helfer-extension#2587]
I am using version 3.2.0.0 on chrome on windows.
I play in 3 worlds (same user id) and the St Patricks Day window appears in 2 of the worlds only.
It appears in Brisgard and Odhrovar and works fine but it does not appear at all in Rugnir and I can't see any way to "enable" it

**Comment by outoftheline** [comment]
There is a setting called event chest, this needs to be active

**Comment by esirca1** [comment]
excellent thanks - that fixed it for me

**Comment by esirca1** [comment]
excellent thanks - that fixed it for me
