### ISSUE TITLE
Unable to enter Discord Webhook URL into FoE Helper's Webhook module

### ISSUE THREAD

**Issue by aRena620** [mainIine/foe-helfer-extension#2588]
Hello,
I am trying to connect to my guild's Discord server via the new Webhook integration in FoE Helper.  I was able to create a Webhook URL from Discord, but I am unable to paste it into FoE Helper's Discord module.  Where do I do this?  Is this ability currently only for people doing Beta testing?  Am I unable to enter my Discord webhooks URL into FoE because I need some kind of authorization?  We set up our guild Discord server specifically to use Webhooks via FoE Helper, so any advice on how to get it to link to our server would be appreciated.  Thank you.

![Discord Webhook Issue](https://user-images.githubusercontent.com/11948003/221364416-96ba5e7b-383e-4d32-bf8f-d2406333231e.png)

**Comment by mainIine** [comment]
Look at the top box on your screenshot. There you will find a button "Webhock URLs" in the upper right corner. There you store all the ones you need, then you can always select them in the lower boxes.

**Comment by RWGupta** [comment]
Thanks for replying mainline.  However, that does not work.  When I click the Webhook URLs box, a box opens titled Boxes.Discord.WebhookUrls.  But I am unable to enter anything there.  The only thing that works is the x button, which, of course, deletes the box.
![Webhook response](https://user-images.githubusercontent.com/11948003/221386793-0f04830d-b86c-4713-a182-88c34c4a980f.png)

**Comment by torben-w** [comment]
That is the error message after saving a discord webhook url. The box afterwards looks like the top image in https://github.com/mainIine/foe-helfer-extension/issues/2588#issuecomment-1457864750

![2024 01 05_14h01m06s_012_](https://github.com/mainIine/foe-helfer-extension/assets/23728620/6308b3c0-6cf2-4186-bcd3-e47f549be4a5)
