### ISSUE TITLE
Berechnung Stündliche Produktion St. Patricks Day

### ISSUE THREAD

**Issue by Muckinator735** [mainIine/foe-helfer-extension#2592]
Die Berechnung der stündlichen Produktion stimmt nicht.
Wenn Captain Iglo etwas mehr liefert als durch den Fest-Manager abgebaut wird, sollte sich eigentlich etwas anhäufen.
Tatsächlich aber wird der Haufen zwischen den beiden abgebaut.

![image](https://user-images.githubusercontent.com/66316515/223206178-e9c8a304-796f-42e4-8648-0a413ac50728.png)

In diesem Beispiel nimmt der Betrag ab. Fest-Manager baut mehr ab, als der Schifffahrts-Onkel liefert.

**Comment by Beelzebob6666** [comment]
Ich bin mir sehr sicher, dass die Berechnungen stimmen. Was vorkommen kann, ist dass durch Verzögerung der Datenübertragung die Berechnung nicht aktuell ist (spätestens 20 Sekunden nach der letzten Änderung sollte des aber geschehen sein). Was wahrscheinlicher ist, dass du einfach eine falsche Beobachtung gemacht hast. Da die beiden in einem recht ähnlichen aber nicht gleichen Zyklus arbeiten, ist es oft so, dass der Bestand sich über kurzem Zeitraum in eine Richtung ändert, aber über lange Zeit in die andere.

Auch bringt es reichlich wenig einen Screenshot vom Spiel zu schicken, und nicht einen vom Helfermodul.

**Comment by Beelzebob6666** [comment]
Ich bin immer noch der Meinung, dass die Berechnung korrekt war - aber evtl. hatte er einfach falsche Basisdaten auf denen die Berechnung durchgeführt wurden. Was mir aufgefallen war, war das der Helfer manchmal nicht korrekt aktualisiert wurde (Produktionswerte haben nicht gestimmt oder Tasks die schon in der Leiste waren waren noch in der "kommende Aufgaben" Liste). Vielleicht war das bei dir auch passiert. 

Die Ursache hierfür wurde vermutlich behoben.
