### ISSUE TITLE
Cape Canaveral FP-Calculater transfers false name

### ISSUE THREAD

**Issue by ChaosLord76** [mainIine/foe-helfer-extension#2595]
Hi,

I just noticed, that when i use the LG-Helper with Cape Canaveral to transfer the costs to the chat it add Tower of Babel as name and not Cape Canaveral

Docmage Turm von Babel 3->4 P2(29) P1(57).  <- this comes for Cape Canaveral

Thaks

Doc

**Comment by Beelzebob6666** [comment]
Could you please check the GB settings (arrow top left corner) maybe you overwrote the name there?
