### ISSUE TITLE
Sets, Upgrades, & Kits

### ISSUE THREAD

**Issue by AnthonyBahl** [mainIine/foe-helfer-extension#2596]
Hey!
First and foremost thank you for putting this together, I love your tool.

 I'm reaching out to report a small bug in the "Sets, Upgrades, & Kits" tool. 
When I search "Celtic Forest" using the "Filter Sets" search box, the [Celtic Alters Selection Kit](https://forgeofempires.fandom.com/wiki/Selection_Kit#Celtic_Altars_Selection_Kit) does not show up currently.

**Comment by Beelzebob6666** [comment]
yeah, that was a new addition and need to get added to the config

**Comment by Beelzebob6666** [comment]
on that note... a lot of things were missing from the config - is now up to date again
