### ISSUE TITLE
Request: Export der aktuell vorhandenen Güter

### ISSUE THREAD

**Issue by ChaosLord76** [mainIine/foe-helfer-extension#2597]
Hallo,

gibt es eine möglich oder ist diese in Planung, dass man seine aktuell vorhandenen Güter exportieren kann? Wäre für die Planung des Vorangehend sehr praktisch.

Grüße

Steve

**Comment by Beelzebob6666** [comment]
du solltest nach dem ersten Einloogen am Tag im Statistik Menu einfach alle Güter und den aktuellen Tag als Filterkriterium auswählen können. das Ergebnis kannst du dann exportieren
