### ISSUE TITLE
[Feature Request] Motivated Building Tracker

### ISSUE THREAD

**Issue by OsulivanAB** [mainIine/foe-helfer-extension#2601]
Dear FOE Helper developers,

I wanted to take a moment to express my gratitude for the incredible tool you have created. It has made playing this game so much more enjoyable and smooth, and I really appreciate your hard work.

I do have a feature request that I would like to submit - could you please consider adding a function that tracks buildings that are not motivated? With the recent addition of buildings that require motivation to receive full rewards, it's becoming increasingly difficult to keep track of which buildings have been motivated and which have not. This is especially challenging during events when there are many short-duration productions absorbing extra motivations as well. Furthermore, with the new trees of patience and vitality, which quickly use up motivations given their small size, it can be hard to ensure that all the important buildings have been motivated before collection.

Having a feature that tracks unmotivated buildings would allow us to use manual motivate them with items more effectively, ensuring that all the important buildings are being motivated and we are getting the full rewards. While I understand that this may not be an issue for everyone, having the ability to gather data on our own motivation usage would be very helpful.

Thank you for considering my feature request and for creating such an amazing extension.

Best regards,
Anthony

**Comment by Donce-Aza** [comment]
Yes.
I also would like this feature.
It is now hard find important buildings to motivate as here are too many not motivated and unimportant buldings. Today I removed many 1x1 and 2x2 buildings as they don't really give much, but are first to be motivated/polished. My Mass Self/Aid Kits also going down little by little.
It would be nice to be able to see list of all not motivated/polished buildings who can be motivated/polished. And to see reward diffirence if it where motivated (FP, goods, guild goods, fragments).
I am left with only 16 Mass SelfiAid Kits, but I get some Mass Self-Aid Kits fragments each time I harvest. 
But I have 817 Self-Aid Kits. I use them to Aid buildings with fragments to harvest them using BG and Finish Special Production.
If here was list of not motivated buildings with shown rewards if where motivated, I could use Self-Aid Kits only on selected few buildings.
