### ISSUE TITLE
Geburtstagsevent-Helper "Merger Game" zeigt keine Kristall Icons, Darstellungsfehler / no Gem icons

### ISSUE THREAD

**Issue by irgendwer001** [mainIine/foe-helfer-extension#2606]
Im Helfer für das FoE Geburtstags Event (Merger Game)  fehlen die Icons für die Kristalle komplett.
Die Liste etc. arbeitet vollständig ist aber ohne Icon Darstellung nicht den passenden Kristallen mit Typus (Bart/Schlüssel) zuzuordnen.
An der Stelle allerKristall-Icons wird ein durchgebrochenes Ersatzsymbol dargestellt. Bei Klick auf das Symbol wird ein Link angezeigt der auf eine fehlende Symboldatei verweist. Z.B. dies ist eine davon:
https://de7.forgeofempires.com/shared/seasonalevents/anniversary/event/anniversay_icon_key_bottom_white.png 
eine weitere:
https://de7.forgeofempires.com/shared/seasonalevents/anniversary/event/anniversary_gem_yellow_2.png

Ich vermute der verwendete Server für die Icons hat die Datei-/Pfadstruktur geändert. Warum werden die Symbole nicht einfach direkt in die Bitmap-Hintergrunddatei aufgenommen/integriert, dann gibts das Risiko nicht? Den Grund da dynamische Links verwenden zu müssen sehe ich bei diesem Spiel nicht.
Liebe Grüße
irgendwer

Umgebung:
Windows 7 64 Bit profess.
Firefox 111.0.1 (64-Bit)
FoE-Helper 3.2.2.0 - Deutsch

**Comment by Beelzebob6666** [comment]
Das liegt primär daran, dass die Spieldatei nicht korrekt gelesen wurde - das scheint vor allem dann zu passieren, wenn die Spieldatei nicht im Cache vorliegt.

Mit der nächsten Version sollte das nicht mehr passieren. Bis dahin vielleicht nicht mehr ganz so oft den Cache leeren.

Warum ich das nicht in irgendeine interne Bitmap integriere? Das ist noch mehr extra-Arbeit - wieso sollte ich mir die machen, wenn das Spiel mir die Bildchen auch so zur Verfügung stellt.

**Comment by irgendwer001** [comment]
Wow, vielen Dank, das nenne ich mal eine schnelle und korrekte Antwort!
Ich habe wirklich 1-2Mal die Icons gesehen und 95% nicht. Deine Einschätzung passt genau, da ich den Cache aus Sicherheitsgründen mit jedem Beenden des Browsers automatisch leere. Werde geduldig auf das nächste Update warten. ;)
Übrigens ein richtig geiles Tool was Ihr da entwickelt habt und auch noch tut! Weiter so, ist jede Codezeile wert.
Gruß irgendwer

**Comment by aviogit** [comment]
I think I never cleared the cache in my whole life (well, not really, but I do it in super rare moments of rage) and I can't see the icons anyway. They aren't there for real I think! https://en1.forgeofempires.com/shared/seasonalevents/anniversary/event/anniversay_icon_key_bottom_white.png

**Comment by 4ndr3aR** [comment]
Ha! I fired up the inspector to see what was going on... and at the second refresh the URLs changed! https://foeen.innogamescdn.com/assets/shared/seasonalevents/anniversary/event/anniversay_icon_key_bottom_white-958db9592.png

Now I see the icons -.-

**Comment by aviogit** [comment]
Ha! I fired up the inspector to see what was going on... and at the second refresh the URLs changed! https://foeen.innogamescdn.com/assets/shared/seasonalevents/anniversary/event/anniversay_icon_key_bottom_white-958db9592.png

Now I see the icons -.-

**Comment by irgendwer001** [comment]
Top! Update funktioniert einwandfrei. It works!
Thanks a lot.
