### ISSUE TITLE
[Bug] Efficiency Rating not taking "Attacker Boost" into account

### ISSUE THREAD

**Issue by DavidMoritz** [mainIine/foe-helfer-extension#2619]
Several new buildings have an "Attacker Boost" and/or "Defender Boost". These values are seen in the Feathered Serpent, Forgotten Temple, Greater Ritual Flame, and Devine Sky Watch to name a few. 

However, Efficiency Rating is ignoring these values.

The simplest approach, in my mind, would be to equate "Attacker Boost" to both attack AND defense for attacking army and similar to "Defender Boost". But I could see value in setting it as a new metric to evaluate.

Forgotten Temple also has "Forge Point Collection" percentage bonus, which may not be worth making it's own metric, but worth a thought.

Lastly, several new buildings give fragments and items. I am not sure how to measure that either.

I'd be happy to just have "Attacker Boost" added to the mix.

Thank you!

**Comment by Beelzebob6666** [comment]
that is already corrected in the beta version ;)
