### ISSUE TITLE
Copy values of GB calculator missing values when pasting

### ISSUE THREAD

**Issue by Phq-art** [mainIine/foe-helfer-extension#2638]
Hello, I have the following problem that when I click copy values from BG calc I would expect that the values would be in the format:
Name Alcatraz P2(value)
what I am getting when pasting is:
![2023-07-07 14_23_53-Forge of Empires - Brave](https://github.com/mainIine/foe-helfer-extension/assets/78696198/79636520-81b7-4076-8373-2a3c220a89f9)
basically just missing the values in the parentheses.
![2023-07-07 14_23_06-Forge of Empires - Brave](https://github.com/mainIine/foe-helfer-extension/assets/78696198/bee20aa8-9435-4e43-862c-d9cbd571eeea)
this is the situation where I click copy values and expect to paste:
Forgegodx Alcatraz P2(276)

Let me know if you need any more information.

OS: Windows 11 64 bit
Brave [Version 1.52.129 Chromium: 114.0.5735.198 (Official Build) (64-bit)]
Xyr
Extension Version: 3.2.6.0, english
no error msg in dev tools console
no other extensions installed

**Comment by outoftheline** [comment]
try to adjust the settings with the arrow on the left (it is cut off in your screenshot)

**Comment by Phq-art** [comment]
Oh right! Was a matter of settings then... consider this done! thanks for the help :)
