### ISSUE TITLE
#Idea : Add the "connection state" to the GM external window

### ISSUE THREAD

**Issue by Zepiii** [mainIine/foe-helfer-extension#2643]
![image](https://github.com/mainIine/foe-helfer-extension/assets/139322751/dae07331-3539-4890-a78a-b43b7bcf4672)

As discussed on discord, thank you :)

**Comment by Zepiii** [comment]
Any chance to see this one getting developped :) ? I don't think it's a huge work normally and would be kind of helpful :)) Thank you!

**Comment by Zepiii** [comment]
Hello, any chance to see this developped ;) ? Would be useful daily for me, so I believe for others also ;)

**Comment by Arklur** [comment]
Should be available in the Beta version soon:

![image](https://github.com/mainIine/foe-helfer-extension/assets/9089026/6fddc81d-f6e7-4f62-b0b7-74ea9f2eca14)

**Comment by Zepiii** [comment]
Saw it was implemented in the final version, thank youuuuuuuuuuuuuuuuuuuuuuuuuuuu :))
