### ISSUE TITLE
Auto open and some data missing.

### ISSUE THREAD

**Issue by NarghileEnjoy** [mainIine/foe-helfer-extension#2647]
I had to clean cookies and cache. Ever since then Helper is not working properly.

FP Investments is blank (See image)
GBG does not auto open
Statistic Overview just say "Loading"
FP Collector is blank
Motivate/Polish Helper is blank
GE Statistics just has a swirly thing in the middle

I have un-installed and re-installed, no luck.

Everything else seems to be working.

Regards
Narg

[https://ibb.co/fSSJ3nR](url)

**Comment by Beelzebob6666** [comment]
might be a database issue - could you please check the console for any errors?
