### ISSUE TITLE
Grilling Grove produces FP packages but they are not included in the building efficiency calculation

### ISSUE THREAD

**Issue by HansBrende** [mainIine/foe-helfer-extension#2653]
The new Grilling Grove building for the fellowship event produces FP packages, but they don't seem to be included in the building efficiency calculation.

1 forge point +
50% chance for a small forge point package +
25% chance for a medium forge point package +
25% chance for a large forge point package

= 5.75 total forge points per grilling grove (on average).

**Comment by janinko** [comment]
bump
