### ISSUE TITLE
GvG Overview showing incorrect data

### ISSUE THREAD

**Issue by kronikpillow** [mainIine/foe-helfer-extension#2654]
Greetings,

I am the developer for FoE-Info. I've noticed a discrepancy between our apps regarding the GvG Overview data presented in FoE Helper. Specifically, it appears that the criteria for Guild Rankings on FoE Helper are based on the number of sectors. However, the actual rankings should be determined by the total amount of power.

I've analyzed over several days and consistently found that a guild with the most sectors is displayed as top-ranking on FoE Helper. Yet, when the reset occurs, this guild does not maintain its position. For your reference, we've had our GvG Overview feature on FoE-Info for approximately 4.5 years, our ranking representation is accurate, however, FoE-Info does not account for GBG Guild Power in the overview, unlike FoE Helper.

Here are the relevant screenshots for comparison:

FoE-Helper:
![wrong info](https://i.imgur.com/Wi5AYKF.png)

FoE-Info:
![correct info](https://i.imgur.com/5G9BYd9.png) 

I hope this information aids in refining the accuracy of FoE Helper. I am available for further discussion if needed.

Best regards,
KronikPillow [Lords of War] (en7)

**Comment by outoftheline** [comment]
Thank you. 

The feature is a bit rough around the edges still. Sorting is one issue I noticed myself, but it's not depended on the amount of sectors, it must be something else. Didn't investigate much further yet:
![image](https://github.com/mainIine/foe-helfer-extension/assets/7482863/f62086dc-d9fd-4400-a094-be172ef746e9)

Not sure where the difference in power comes from. Maybe rounding when adding the power from 1st to 3rd place on each map?

**Comment by kronikpillow** [comment]
my tool should use the 15% 10% and 5% boost on top of total power when P1/2/3 on a map, and should account for that as far as I'm aware, but it's not me personally who made this feature, so I will need to check in my codebase, but I believe that is why there is a difference in power as well between our tools, and ofc, my tool doesn't add the GBG Prestige to the count, it just counts GvG Guild power ... looks like you have a sorting issue which can easily be fixed, just make it sort by guild power and you should be fine ... maybe also account for the 5%, 10% and 15% power boost

**Comment by kronikpillow** [comment]
verified ... my tool does account for 15% 10% and 5% boost on total power when P1/2/3 on a map ... which explains the difference in power as well

**Comment by outoftheline** [comment]
i also add the power % of the maps, but some small amount is missing.

**Comment by kronikpillow** [comment]
yeah ... seems so, unfortunately, I barely have time to work on my tool atm, and my own also has a couple of bugs that I need to find time to fix, so the best I could assist you was to report these issues

**Comment by outoftheline** [comment]
thank you anyways, i hope i can get around to fixing it

**Comment by outoftheline** [comment]
sigh, this is now a wont-fix for obvious reasons. :(
