### ISSUE TITLE
Donkey Enclosure does not reflect unit production

### ISSUE THREAD

**Issue by e2m2** [mainIine/foe-helfer-extension#2662]
Donkey Enclosure produces one random unit, but FoE Helper Efficiency and Production Overview tabs don't recognize it.

![FoE_Efficiency](https://github.com/mainIine/foe-helfer-extension/assets/143840673/47f78a5c-808d-437e-994c-77adedaa8179)

**Comment by G-Bigo** [comment]
Some other affected buildings :

• Royal Bathhouse (stage 1 and up now)
• Cider Garden
