### ISSUE TITLE
Suggestion: Neighborhood combat memory

### ISSUE THREAD

**Issue by arlininger** [mainIine/foe-helfer-extension#2666]
Include a window for combat with a neighbor that will show you the results of your previous battle with that neighbor. This would essentially be the equivalent of taking meticulous notes on each combat engagement and recalling those notes when you are about to attack a neighbor again. No predictions, no auto-combat.

Minimum viable product:
Was the previous combat a win or a loss.

Goal:
What army did the neighbor have defending last time?

Ideal:
What army did I bring?
What army did they bring?
Which units were killed?
Was it auto-combat?

**Comment by outoftheline** [comment]
We used to have a feature called PvP Activity a few years back, but had to remove it as per InnoGames request

**Comment by arlininger** [comment]
I don't know what that features entailed, but I recall reading something about a feature that made combat suggestions. I'm thinking something that would be equivalent to taking really good notes. If even that is going to far for InnoGames, no worries.

**Comment by outoftheline** [comment]
Sorry, we will not bring back features that can give an "unfair advantage" to some. Saving neighbours armies will most likely be considered unfair.
