### ISSUE TITLE
ability to export data

### ISSUE THREAD

**Issue by vdcaldwell** [mainIine/foe-helfer-extension#2669]
it would be great if i could export the statistics/treasury data for guild / self management to excel

**Comment by illie0** [comment]
You can. Open the treasury log and click through every page, then click the 'export' button to make a csv that Excel can read

**Comment by vdcaldwell** [comment]
Thank you, I forgot I added this comment and found the function.  Thank-you!

Sent from mobile.  Please forgive typos.
________________________________
