### ISSUE TITLE
LG Investitionen: Helfende Hände (Saatgut-Tresor)

### ISSUE THREAD

**Issue by frankmorgner** [mainIine/foe-helfer-extension#2670]
LG Investitionen bietet bereits die Möglichkeit, Güter in die Bewertung mit einzubeziehen. Leider fehlt hier die Berücksichtigung der[ Helfenden Hände vom Saatgut-Tresor](https://forgeofempires.fandom.com/wiki/Seed_Vault). Die Berechnung der erhaltenen Güter ließe sich reicht leicht durchführen, wenn man annimt, dass allen Freunden/Gildies/Nachbarn geholfen wird oder wenn man die Zahl der Motivationen/Polierungen durch den Nutzer festlegen lässt.

Der ST ist tatsächlich [einer der besten Güter-Lieferanten im ganzen Spiel](https://youtu.be/wkBxbbUy_Go?t=341&feature=shared)...

**Comment by outoftheline** [comment]
mittlerweile ist der saatgut-tresor nicht mehr so gut. sollte inno mal das versprochene LG update rausbringen und der tresor angepasst werden, kann man nochmal drüber nachdenken.

**Comment by frankmorgner** [comment]
Sorry, aber die Bewertung ist einfach falsch. Eine aktuelle Einordnung findet sich z.B. [bei Linnun](https://www.youtube.com/watch?v=EZku5Q2tBgs). ST ist auch hier weiterhin unter den Top 6 der LG, die keine extra Güter benötigen.

**Comment by outoftheline** [comment]
dann sthast du ja alle nötigen infos und kannst ihn selbst leveln, weil er so gut ist.

**Comment by frankmorgner** [comment]
Hmm, ich benutze ja den Helfer, um eine Gewichtung der Faktoren zu erreichen.

Egal, ich komme auf jeden fall weiterhin klar. Danke für euren Einsatz!
