### ISSUE TITLE
Ägäisches Marina Resort

### ISSUE THREAD

**Issue by SkateScout** [mainIine/foe-helfer-extension#2672]
Hi, die FP's aus dem neuen Gebäude werden bei der Blauen Galaxie nicht berücksichtigt.

**Comment by G-Bigo** [comment]
Bestätigt. Hat mich heute richtig FPs gekostet.

**Comment by G-Bigo** [comment]
Edit: Auch die anderen Ägäischen Resorts werden im BG-Helfer nicht berücksichtigt.
