### ISSUE TITLE
GB Investment overview showing wrong data for PEGASUS and CENTAURUS

### ISSUE THREAD

**Issue by GeniePower** [mainIine/foe-helfer-extension#2674]
GB Investment overview is showing PEGASUS for attack boosts even tho that is blue attack and not red. It's not showing CENTAURUS even tho that is red attack.

![image](https://github.com/mainIine/foe-helfer-extension/assets/97710104/75c2cb35-4746-45ef-b613-2ff9e86d0d7f)

**Comment by AnthonyBahl** [comment]
I would like to up-vote this issue.
There are two issues here that I see, 

1. PEGASUS is showing % Attack value, when it actually provides % Defense (see first image below.
2. CENTAURUS is not included in the list at all, even though it does provide % Attack boost

![image](https://github.com/mainIine/foe-helfer-extension/assets/95724635/c08123d8-5dac-4fec-82ef-cd3732f52b31)

![image](https://github.com/mainIine/foe-helfer-extension/assets/95724635/f6028cc9-6626-40ac-962c-260eb3c4c80a)

**Comment by hashpatel** [comment]
Upvoting this. Changes needed to:
https://github.com/mainIine/foe-helfer-extension/blob/master/js/web/greatbuildings/js/greatbuildings.js

AttackProductions & AttackIncrease need to be moved from line 71 to line 69
