### ISSUE TITLE
Suggestion: Show remaining charges in BG Helper

### ISSUE THREAD

**Issue by GeniePower** [mainIine/foe-helfer-extension#2675]
With the UI changes that no longer show the remaining BG charges while collecting, it would be nice if the BG Helper could show the counter since it already knows it
![image](https://github.com/mainIine/foe-helfer-extension/assets/97710104/b3ea1f87-0c50-47b8-a434-113d4c0854e8)

**Comment by Beelzebob6666** [comment]
The remaining charges are given in the menu bar already. Is that not enough?

**Comment by GeniePower** [comment]
Well, with the new HUD, you have to open it up to see it. It seems to always be GT tower that's visible. I created the ticket, but there were several people on discord talking about it.

**Comment by Beelzebob6666** [comment]
I spoke of the helpers menu bar

**Comment by GeniePower** [comment]
Oh, yea. I guess that could work. It's on page 2 for me, so I'd have to decide which one to demote to 2nd page. It's on page 2 because it's not actually used as a button
