### ISSUE TITLE
Neuere Eventgebäude lassen sich im Stadtplaner nicht platzieren 

### ISSUE THREAD

**Issue by greenmind23** [mainIine/foe-helfer-extension#2679]
Mac OS Ventura 13.5.2
Chrome 116.0.5845.187
DE12 Mount Killmore
3.2.8.0 Deutsch
CityMap 1.7.4

Ich kann leider keine neueren Eventgebäude (z.B. Seeräuberbucht, Handelsposten oder Pergola) im Stadtplaner platzieren. In der Suche sehe ich sie, aber nach der Auswahl passiert nichts. Andere Gebäude lassen sich aber platzieren.

**Comment by outoftheline** [comment]
Mainline, der der einzige ist, der sich um den Stadtplaner kümmern kann, hat leider aktuell wenig Zeit
