### ISSUE TITLE
GbG Attrition

### ISSUE THREAD

**Issue by MFS-of-Redemption** [mainIine/foe-helfer-extension#2680]
Hello FoE Helper Team,

Is there a plan to add GbG Member Activity "Attrition" column in FoE Helper "GBG Overview" ?

![GbG Attrition](https://github.com/mainIine/foe-helfer-extension/assets/146681016/233adc19-f1d6-4266-aef8-87db399fceea)

**Comment by outoftheline** [comment]
attrition was added and will be added to the exports in the next update
