### ISSUE TITLE
Finding ID Number

### ISSUE THREAD

**Issue by CaelusSky22** [mainIine/foe-helfer-extension#2681]
I can't find my in game ID number anywhere. I need this to sign up on FoE Helper.

**Comment by ElenaEm73** [comment]
Если с компа смотрите свой профиль, учетную запись вкладка о нас, там есть, но у меня почему то был не виден полностью, поэтому чуть ниже кнопка скопировать в буфер, далее я тупо вставила в word и все видно полностью.Сегодня этим занималась, но зарегистрироваться не получилось, при регистрации не находит ID, о чем здесь и написала.Если у вас получится зарегистрироваться, напишите как, номер проблемы #2683.
