### ISSUE TITLE
[BUG]"Zestaw ulepszeń i zestawy" PL name not refresh 

### ISSUE THREAD

**Issue by tpaciorek** [mainIine/foe-helfer-extension#2687]
Enhancement Sets and sets. This part does not work, it does not refresh. What needs to be done to refresh it?
I go into the inventory and click through everything and there is no refresh effect, the data I have is from August 4, 2023. Please help.

**Comment by Arklur** [comment]
Quite late with a response, but...hey, better later than never?

Joke aside, could you write a more detailed message what is not happening and what should happen? I think you are referring to the "Sets, Upgrade & Kits" window, so this one:

![image](https://github.com/mainIine/foe-helfer-extension/assets/9089026/a9fc88c0-b742-447a-bcbd-ec69761b365b)

Which needs to be updated manually on "our" side, and I think it was updated recently, so...your problem might be solved already?
