### ISSUE TITLE
I dont see "card list" in Halloween event

### ISSUE THREAD

**Issue by marek48medved** [mainIine/foe-helfer-extension#2691]
Hi, 
I dont see any card list in current Halloween event.

![image](https://github.com/mainIine/foe-helfer-extension/assets/96011936/9792c2ec-7b66-4fdc-9296-9d2962f57a30)

I should see something like in this moment in video: https://www.youtube.com/watch?t=510&v=BrnscETw8vY&feature=youtu.be

I am using Chrome, and I have FoE Helper version 3.2.9.0

**Comment by rdorsi** [comment]
same. i also checked for extension updates and tried both chrome and firefox. No card game list.

**Comment by chr1sters** [comment]
Same for me.

**Comment by JonSaffron** [comment]
The code for this looks to be only in the beta branch. I've managed to get it working in Firefox.

**Comment by MythosFortuna** [comment]
The same here.
![Ashampoo_Snap_2023 10 27_11h28m36s_001_](https://github.com/mainIine/foe-helfer-extension/assets/62996357/cef327a4-be0c-48de-9461-bc4ad664c2e2)
![Ashampoo_Snap_2023 10 27_11h29m08s_002_](https://github.com/mainIine/foe-helfer-extension/assets/62996357/08f30ca2-e8f3-4491-85f6-d76bcb4028cc)
 Update is 3.3.0.0
in the browser only 3.2.9.0
All AdBlocker deleted!

Greets Mythos

**Comment by marek48medved** [comment]
Ok, it looks working in version 3.3.0. Can someone confirm? If so, I will close this issue.

**Comment by Phq-art** [comment]
Yes, I see the card list now. I think you can close it

**Comment by marek48medved** [comment]
fixed in 3.3.0

**Comment by mainIine** [comment]
> The same here. ![Ashampoo_Snap_2023 10 27_11h28m36s_001_](https://user-images.githubusercontent.com/62996357/278600907-cef327a4-be0c-48de-9461-bc4ad664c2e2.png) ![Ashampoo_Snap_2023 10 27_11h29m08s_002_](https://user-images.githubusercontent.com/62996357/278600934-08f30ca2-e8f3-4491-85f6-d76bcb4028cc.png) Update is 3.3.0.0 in the browser only 3.2.9.0 All AdBlocker deleted!
> 
> Greets Mythos

I cleared the cache. Thx for this info.

**Comment by MythosFortuna** [comment]
Does this require a deck of cards to be active? I've got everyone ready for today!
The card list doesn't start for me.
