### ISSUE TITLE
Version 3.3.0.0 not released for Firefox ("card list" in Halloween event)

### ISSUE THREAD

**Issue by MaTribu** [mainIine/foe-helfer-extension#2693]
Hi
Version 3.3.0.0 has been release 4 days ago as mentionned in Github, but still no updated, even if update if well configured into Firefox.
![image](https://github.com/mainIine/foe-helfer-extension/assets/48768551/ffba60e5-a153-4650-8bc6-4a2b2a8d6f5c)
![image-1](https://github.com/mainIine/foe-helfer-extension/assets/48768551/01d76e07-7c97-45cf-b67f-537a3c9657b9)
Maybe because the wrong version has been uploaded into Firefox store
![image](https://github.com/mainIine/foe-helfer-extension/assets/48768551/40d0de61-9613-49da-9dcd-8ae8802e2c9b)

**Comment by mainIine** [comment]
The new version is uploaded but not released by mozilla...

![image](https://github.com/mainIine/foe-helfer-extension/assets/834814/360a2325-232e-410a-97a1-d6e76db5ffbb)

Please  be patient.

Chrome has already released the version although both were submitted almost simultaneously. In an emergency, you can use Chrome for a few days.

**Comment by Beelzebob6666** [comment]
3.3.0.0 was released for FF
