### ISSUE TITLE
Suggestion:  Equity Calculator // Vorschlag: EA-Rechner

### ISSUE THREAD

**Issue by andihome** [mainIine/foe-helfer-extension#2696]
There are three buttons in the upper part that are preset with 80%/85%/90%.
Would it be possible to add another button there with a configurable personal value?
Or would it be easier if the three existing buttons were configurable via the FOE settings?
Thank you for reading :-)

Hier gibt es im oberen Teil drei Knöpfe, die mit 80%/85%/90% vorbelegt sind.
Wäre es möglich, dort einen weiteren Knopf mit einem persönlichen Wert konfigurierbar einzubauen?
Oder wäre es einfacher, wenn die drei bestehenden Knöpfe über die FOE-Einstellungen konfigurierbar wären?
Danke für's lesen :-)

**Comment by AlfonZ42** [comment]
_GB (Cost) Calculator's_ arc bonuses can already be customized - click the cog wheel in the title bar of the window.
![FH_GBCalcCustomValues](https://github.com/mainIine/foe-helfer-extension/assets/1955593/af1ac743-553c-43d0-a9e5-27a67c76d927)

**Comment by andihome** [comment]
👍
