### ISSUE TITLE
Suggestion: ❤️ Lives and Levels for Halloween Card Helper

### ISSUE THREAD

**Issue by rogerdrummond** [mainIine/foe-helfer-extension#2699]
Would it be easy to add Lives and Levels on the Card game helper. It would be very useful during Card selection?

![Screenshot 2023-11-14 at 6 03 02 PM](https://github.com/mainIine/foe-helfer-extension/assets/322118/6e2269af-cc98-47e9-9664-401adabb24b6)

![Screenshot 2023-11-14 at 6 27 44 PM](https://github.com/mainIine/foe-helfer-extension/assets/322118/7b22535b-0d44-460b-8e71-320db20831ca)

**Comment by Beelzebob6666** [comment]
Was already in Beta - will be in the net version - thus in the game when the same mechanic is used again
