### ISSUE TITLE
Suggestion/Idee: Ergänzung der Produktionsübersicht durch zusammengefasste Kategorien

### ISSUE THREAD

**Issue by Falconheavy1** [mainIine/foe-helfer-extension#2700]
Die Produktionsübersicht kann man bisher nach den verschiedenen Werten (FP, Güter, Angriff, Verteidigung usw.) filtern und dabei nach Effizienz sortieren lassen. Mittlerweile sind die Gebäude ja nicht mehr nur rein Angriff bzw. rein Verteidigung sondern haben eigentlich von allem etwas. Da ich (wie wahrscheinlich die meisten) meine Stadt hauptsächlich nach der Effizienz (also bspw. Angriff pro Tile) plane, komme ich mit der "Produktionsübersicht" im FoE-Helper nicht mehr so gut zurecht und mache das meiste händisch.

Deshalb der Wunsch bzw. die Idee, zusätzlich zu den bisherigen Filterkategorien auch die Kombination aus "Angriff/Verteidigung der Angreifenden Armee" hinzuzufügen um mit der dort sortierten Effizienz besser planen zu können.

Als ergänzenden Wunsch hätte ich noch, dass es eine zusätzliche Kategorie in der Produktionsübersicht gibt, in der man die angezeigte Effizienz nach eigenen Parametern bzw. Prioritätsfaktoren berechnen lassen kann.  Beispielsweise ist für mich Angriff 1,3x so wichtig wie Verteidigung, FP sind 1,5x so wichtig wie Verteidigung, und CityDeff ist 0,7x so wichtig wie Verteidigung. Wäre einfach super, wenn man die Faktoren für alle möglichen Produktionskategorien selber eingeben könnte und dann die Gesamtformel als Effizienz pro Gebäude Filtern/Sortieren könnte. 

Gruß und danke für das tolle Tool! :-)

**Comment by Beelzebob6666** [comment]
Für die Effizienz gibt es bereits ein eigenes Modul:
![image](https://github.com/mainIine/foe-helfer-extension/assets/66054355/dfbece65-cd5a-4ccc-bf71-0b229c91a93e)
Man könnte es auch in die Produktionsübersicht integrieren, aber ich denke, dort wo es ist, ist es ganz gut aufgehoben.

Bin mir nicht ganz sicher, was du mit "Kombination 'Angriff/Verteidigung'" meinst - würde aber vermuten, dass das mit dem Effizienzmodul bereits erledigt wird.

**Comment by outoftheline** [comment]
Ich würde auch sagen, dass die Effizienzbewertung alles gewünschte abdeckt.
