### ISSUE TITLE
GG - Übersicht öffnet sich beim falschen Event

### ISSUE THREAD

**Issue by mainIine** [mainIine/foe-helfer-extension#2701]
Öffnet man die Spielerübersicht der gespielten Welt (Ehrenkranz oben links), dann öffnet sich auch die GG-Rangliste.

Offenbar hat Inno den Eventnamen doppelt vergeben. Eine kombination aus geöffneter Karte + Eventname sollte das schon lösen.

**Comment by Beelzebob6666** [comment]
Already fixed in Beta
