### ISSUE TITLE
Windows with transparent background

### ISSUE THREAD

**Issue by fwagner314** [mainIine/foe-helfer-extension#2702]
<img width="374" alt="image" src="https://github.com/mainIine/foe-helfer-extension/assets/12300896/fa2ba0d1-5817-48cc-a943-1f525c715f92">

Does anyone know how to solve it? I'm using the chrome extension in Opera GX

**Comment by mainIine** [comment]
Mayby a other Extension? Have you tried to clear The cache?

**Comment by fwagner314** [comment]
> Mayby a other Extension? Have you tried to clear The cache?

You're right! This was caused by another extension called Dark Reader that edits html. Thank you.
