### ISSUE TITLE
Foe helper

### ISSUE THREAD

**Issue by Michaelj15** [mainIine/foe-helfer-extension#2704]
Hello all, thanks for all great work with the Foe helper!
Already asked by other users i think (but i can't find it), is the Foe helper in the future available for mobile overlay?
I hear a lot of users who didn't use the helper because it's only for pc.

Thanks!

**Comment by Beelzebob6666** [comment]
unfortunately it is not possible (for us) to do something like that. Especially as the data-streams/server-communication can not be listened in.
