### ISSUE TITLE
Daily Guild Battleground fights per player

### ISSUE THREAD

**Issue by G-Bigo** [mainIine/foe-helfer-extension#2705]
Could it be the calculation of the daily guild battleground fights is not based on the corresponding server time?

Observation: Directly after midnight (MEZ, German servers) it shows I've already done dozens of fights.

I have done some fights between 11 and 12 pm as far as attrition allowed me. But none directly after midnight.

**Comment by Arklur** [comment]
Based on some quick investigation, it looks like your local date/time is used, not the server time, yes.

**Comment by GeniePower** [comment]
I have no timezone problems with GBG fights, as long as I refresh right before midnight server time. Helper doesn't know when the fights happen, it only knows the current time and the difference between the current snapshot and the previous snapshot
