### ISSUE TITLE
Blue Galaxy suggestion: Collect new building giving fragments

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2711]
The fragments for newly added buildings from the events are starting to be more important things that goods or FPs. It will be better to choose if we want to collect those building first.
For example those buildings which gives fragments of boost attack/defense for attacking army, or stocking fragments, or Sunhaven building fragments, and so on. 
FoE starting add a lot of fragments for important buildings, which add more attack/defense boost for attacking army. It is better to have something to see those buildings if we want that!

Thanks

**Comment by IgorKaisa594** [comment]
or collect diamonds)

**Comment by valimaties** [comment]
> or collect diamonds)

This one you can easily do using production tab. There you can see which building generate diamonds. We know that production tab shows including fragments, but is hard to choose from that entire screen, so is better to choose from attack/defense building fragments, or storage fragments. So I see it as a choosing box, what is the interest of. Right now is goods or forge points depending of what percent of change you choose. Is deprecated IMO, based on what is new in the game right now.

**Comment by outoftheline** [comment]
> or collect diamonds)

Won't happen.


We're currently looking into including fragments.

**Comment by valimaties** [comment]
Ok, you have included fragments, but now the window has some problems. #2731 say it
