### ISSUE TITLE
Microsoft Edge extension latest is version 3.2.9.0 

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2712]
Microsoft Edge extension latest is version 3.2.9.0 , and a lot of the updates information comes, but no update was installed since 3.2.9.0. Why?

**Comment by mainIine** [comment]
Hi,

Microsoft need much more time to publish a new version.

Google and Firefox are much faster.

Regards,
Daniel

Vali Matieș ***@***.***> schrieb am So. 10. Dez. 2023 um
19:37:

**Comment by valimaties** [comment]
So, is there any way to compile and install myself the latest version for extension?

**Comment by mainIine** [comment]
This not nessessary.
Look in your current version. Browse to the settings tab and look for the
“Beta” tab. There you find the informations you’re looking for.

Regards,
Daniel

Vali Matieș ***@***.***> schrieb am So. 10. Dez. 2023 um
19:44:

**Comment by valimaties** [comment]
![FoeHelperExtensionScreen](https://github.com/mainIine/foe-helfer-extension/assets/49796453/ad8f7b97-e6ea-43dc-abcc-2a701de2334e)


Sorry, but I don't see any Beta tab in Microsoft Edge screen of the extension!

**Comment by valimaties** [comment]
Ok.. I found a way to install the latest version.
I've accessed the Chrome Web Store from MEdge and I've install it from there, it is working now. In edge I have the latest 3.4.0.0

![image](https://github.com/mainIine/foe-helfer-extension/assets/49796453/acfa29b3-1260-45e6-bf75-f74ad52839c8)
