### ISSUE TITLE
Guild Member Overview Not Fully Updating

### ISSUE THREAD

**Issue by Sweetini** [mainIine/foe-helfer-extension#2724]
In the guild member overview, specifically the daily guild goods donations do not appear to be fully updating for all members within the guild.  Some build members data is 6+ months old, some guild members do not have any data at all.  Is there a workaround to get updated information?  This is very helpful for our guild and it would be amazing if we could get up-to-date information on all guild members.

**Comment by AlfonZ42** [comment]
To get updated data for the _Guild member overview_ window, you have to do the actions that fetches them from the server:

- Open the guild window.
- Switch to the guild treasury tab.
- Visit all members' towns.

It reminds you to do so at the top of most _Guild member overview_ tabs.

To check how old the members' data is, in the first _Guild Members_ tab click on the one you are interested in. You'll get a summary of their data, including the last update date - 
![FH-guildmember-updatestatus](https://github.com/mainIine/foe-helfer-extension/assets/1955593/d7d790aa-267c-4e88-bdca-7e96b2892e2a "Last update date before and after.")
(No date listed means you haven't visited their city ever.)

**Comment by Sweetini** [comment]
Confirmed - really appreciate your guidance!
