### ISSUE TITLE
Attrition save to snapshot log, too

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2728]
Righ now, the attrition is showing in the main window of GbG Overview. Snapshot Log window, however, shows only the negotiations, fights and total, attrition is missing. Could this be implemented?

**Comment by outoftheline** [comment]
the snapshot is incorrect if you do not track exactly at reset.

here is an example:
let's say you log out 3 hours before reset and log back in 5hours after.
someone with 0 attrition that day does 500 fights before reset and 500 more after it. they have 100-ish attrition when you log in again. 
if we add sttrition the data would make it look like they gained only 100 attrition from 1000 fights, which is incorrect. 

we won't add numbers that will be incorrect for 95% of players most of the time. it will just lead to confusion.

**Comment by outoftheline** [comment]
if you do want to track attrition, you can use the export function at recalc, the attrition is included there.
![image](https://github.com/mainIine/foe-helfer-extension/assets/7482863/a2197221-a999-4535-94f1-83d5c8f448b0)

**Comment by valimaties** [comment]
> the snapshot is incorrect if you do not track exactly at reset.
> 
> here is an example: let's say you log out 3 hours before reset and log back in 5hours after. someone with 0 attrition that day does 500 fights before reset and 500 more after it. they have 100-ish attrition when you log in again. if we add sttrition the data would make it look like they gained only 100 attrition from 1000 fights, which is incorrect.
> 
> we won't add numbers that will be incorrect for 95% of players most of the time. it will just lead to confusion.

If I log in after reset, the action of GbG overview calculates all the fights, negotiations and attrition from the last instance, yes? If so, it will be simple to calculate even in your example, because you will know the fights, negociations and attrition for current day (after reset) and the rest of those are from the last login. So, if the action of snapshot log is triggered first time after reset there could be two snapshots created, one till the reset, and one for current day, which will automatically generate a good snapshot for current day starting day, from the reset. I think it will be a great idea then to store attrition also, because for example I could trigger the snapshot log before starting fights for a sector and trigger it again after it finnished, and I can see for one important sector what attrition was gained for that sector. I know that creating those two snapshots we will don't know what was the attrition at reset, but this could be set as NaN value, as long as the snapshot was done after reset, it is the user's choice to trigger snapshot exactly before reset to know the attrition at reset time. 
I don't think snapshot will be trully affected by this approach.

**Comment by valimaties** [comment]
I see... unknowing fights and negotiations for each day is somehow hard to know how many fights and negotiations were done in current day round... We know attrition for each day, but we don't know the other values. However, I see the limitation but IMO is good to view it in snapshot than export it into a csv/Excel file... I know that first snapshot is inaccurate, but the rest of the day are good.

**Comment by Arklur** [comment]
> We know attrition for each day

You do not. If you don't login for 3 days, you have no idea about others' attrition for those 3 days. Fights and negs are different, as the server do send that total amount of fights/negs, it's not calculated by FH. Even if you miss 3 days, the total for those attributes will be correct.

As outoftheline said, although that number **_could be_** correct if the player checks the neg count seconds before reset, for the majority of the users it would be incorrect. So, unless Inno decides to send the cumulated attrition for players too similarly how it's done with negs and battles, this won't be implemented, or at least very-very-very unlikely. 

It's better to have 1 out of 100 user to miss this feature than 99 out of 100 complain about the number being off.

**Comment by valimaties** [comment]
Sad. Thanks.
