### ISSUE TITLE
Blue Galaxy helper is no longer ranked high to low

### ISSUE THREAD

**Issue by draghor1** [mainIine/foe-helfer-extension#2731]
Today my BG helper is no longer showing BG targets in order of the benefit. It also has an additional column, showing fragments of buildings. It is also no longer removing the items already used. 

These are not helpful changes and I haven't found an option to change the parameters to the original view. Rebooting the game has not resolved these issues.

**Comment by valimaties** [comment]
More than that, the popup cannot be resized, as long as it does not fit the available screen area, it grows to much and the right-down corner cannot be placed in the view. It is awkward.

**Comment by hutch924** [comment]
It also has removed my Sunflower Oil Presses and Lab of Monstrosities from the list entirely. The star added is nice though to verify the building is motivated.

**Comment by valimaties** [comment]
I understand now the star, but in this state is useless, till next update I will deactivate the window for starting when the building is accessed. Wrong step, IMO

**Comment by AlfonZ42** [comment]
As a workaround in the mean time for the overly large default BG window size, close the BG window and run in the dev console (_F12_ or _Ctrl+Shift+I_): `localStorage.setItem('bluegalaxySize','500|400')`. This should set the window to a small enough size.

**Comment by jamesrpx** [comment]
Latest update has completely wrecked BG helper. No longer shows buildings in order of benefits. No longer removes buildings when collected - either shows them as done or as ready in 24 hours. Please revert to old version until you can fix the problems with the update.

**Comment by hutch924** [comment]
> Latest update has completely wrecked BG helper. No longer shows buildings in order of benefits. No longer removes buildings when collected - either shows them as done or as ready in 24 hours. Please revert to old version until you can fix the problems with the update.

I had to refresh the game after collecting for them to remove. The problem is it completely removed 2 buildings from the next collection that is showing. I will not be surprised if they show up tomorrow when I collect my BG though. I also had to change the number at the top from .2 to .1 to get my buildings back in the normal order. I don't recall ever having to adjust that.

**Comment by SmartCologne** [comment]
Window is way too large now. please make the fragment column otional

**Comment by BoboGargle** [comment]
As per jamesrpx, has been borked.

**Comment by valimaties** [comment]
> As a workaround in the mean time for the overly large default BG window size, close the BG window and run in the dev console (_F12_ or _Ctrl+Shift+I_): `localStorage.setItem('bluegalaxySize','500|400')`. This should set the window to a small enough size.

Yes, this workaround is good till next update.

However, why the buildings remains in the window? Why they don't dissapear? Which is the logic?

**Comment by draghor1** [comment]
Update: Please remove the fragments column or enable it to be hidden. The terms are so long they cause the text to wrap which stretches the bottom of the box below the frame of my screen.  I can no longer size the screen.
Also not all buildings are displayed and most continue to show as available to collect after they've been collected. This helper has lost about 90% of it's value to the my game.

**Comment by valimaties** [comment]
> Update: Please remove the fragments column or enable it to be hidden. The terms are so long they cause the text to wrap which stretches the bottom of the box below the frame of my screen. I can no longer size the screen. ...

The popup window must resize itself if the size is greater than 100% of viewport height. Let's say to 90%. This can be done in bluegalaxy css file, by setting the max-height property to 90% of viewport's height, or using calc function in css value of max-height. It is so simple.

**Comment by outoftheline** [comment]
We just rolled out a new update and every concern should be addressed.
