### ISSUE TITLE
Guild Members won battles overview

### ISSUE THREAD

**Issue by e12harry** [mainIine/foe-helfer-extension#2732]
Could you add another window showing won battles count after visiting any guild profile (and progress when you visit profile next time with possibility to compare few recent snapshots) . 
I know this is being sent when viewing guild's profile, but unfortunately, the game itself does not show members fights in guild profile.
Would this kind of feature be legal?

**Comment by outoftheline** [comment]
what for would you need that? to see if others are too fast and report them?

**Comment by e12harry** [comment]
Exactly. We suspect some players are using script for fighting. When we are fighting in Guild vs Guild or Guild Battle Grounds and we have to fight fast I don't want to go to leader board, find every player and remember their fights.

**Comment by outoftheline** [comment]
Sorry, i don't think we should add this as a feature.
