### ISSUE TITLE
BlueGalaxy table thead sticky and sorting must be three-states option

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2735]
Hi.
It is better that in every table the thead to be stiky, it is a better visibility to each of the data, to see the column's names. Adding this css in boxes.css file seems to do the job:

```css
thead {
    position: sticky;
    top: 0px;
    z-index: 1;
}
```
and removing the `background-color: transparent;` from `.foe-table, table.foe-table` classes.

![image](https://github.com/mainIine/foe-helfer-extension/assets/49796453/3ef8639d-0e79-4fb2-a434-cea7d816bd83)

![TableHeaderSticky](https://github.com/mainIine/foe-helfer-extension/assets/49796453/6da3d1db-8762-4d2e-9d55-5f3078075e47)

However, the issue I see here is with sorting options which must be a three-states soting option (ascending, descending and not-sorted). So, as I see, there is an event which changes the th class of the table, which will add the `ascending` `descending` classes to the th clicked. I suggest to remove the class name `descending` if exists without adding the `ascending`. This will do the three-states sorting. When you first click on the header will add `ascending`. If `ascending` is present, then will remove `ascending` and add `descending`. If `descending` is present, remove `descending` without adding `ascending`.

**Comment by outoftheline** [comment]
the foe-table class is used for so many things. would need to check if it breaks on any module.
