### ISSUE TITLE
Blue Galaxy Helper no longer removing used buildings

### ISSUE THREAD

**Issue by SuRFDownUnder** [mainIine/foe-helfer-extension#2736]
Since the Fragments were added to the Blue Galaxy Helper it has become a lot less useful because buildings that have been used are not removed from the list and as the list does not scroll you cannot even see what buildings should be used, nor can you resize the window as the resizer is off the bottom of the screen and there is no way to get to it. (Browser is Edge OS is Windows 11).  On top of this it is no longer taking into account the Forgotten Template (Panda Shrine in below picture actually gives 207 FPs)

![Screenshot 2024-01-21 211601](https://github.com/mainIine/foe-helfer-extension/assets/6124047/83f3ee81-d51a-481f-8857-6fa0091b2b2b)

**Comment by outoftheline** [comment]
please wait for the latest update, it includes some bugfixes. thank you!

**Comment by valimaties** [comment]
with the latest version, buildings collected still remains in the list... 

![image](https://github.com/mainIine/foe-helfer-extension/assets/49796453/e1423def-01fc-4ec6-87c7-20dfc7d0eed2)

**Comment by outoftheline** [comment]
@valimaties whats your latest version?

**Comment by valimaties** [comment]
Seems working now.

**Comment by SuRFDownUnder** [comment]
I am using version 3.5.0.0.  This is the error that is posted in the console when I click on my Panda Shrine, which does not vanish from the list:

merged-3rd-party-109b844c.js:16  TypeError: Cannot read properties of undefined (reading 'required_population')
    at Object.getPopulation (_main.js:878:37)
    at Object.createNewCityMapEntity (_main.js:1372:27)
    at _main.js:407:36
    at Array.forEach (<anonymous>)
    at _main.js:403:14
    at _proxyAction (foeproxy.js:390:5)
    at proxyAction (foeproxy.js:405:3)
    at XMLHttpRequest.xhrOnLoadHandler (foeproxy.js:525:7)

**Comment by valimaties** [comment]
The latest version is 3.5.0.2, which works fine... so update your extension

**Comment by SuRFDownUnder** [comment]
The current version in the store is 3.5.0.0.  How can I update the extension to 3.5.0.2?

**Comment by valimaties** [comment]
what browser do you use?

**Comment by SuRFDownUnder** [comment]
Microsoft Edge.

**Comment by valimaties** [comment]
For microsoft Edge, do like this:

1. open extensions from menu
2. search and uninstall your current extension
3. enable "Allow extensions from other stores" (in the left part of the screen)
4. install the extension from chrome store [(FoE-Helper)](https://chromewebstore.google.com/detail/foe-helper/bkagcmloachflbbkfmfiggipaelfamdf), which is 3.5.0.2

**Comment by SuRFDownUnder** [comment]
That got me to 3.5.0.2.  Thank you.
