### ISSUE TITLE
After the Jan. 27th update .. Infobox changed -- Infobox doesn't show GBG elements outside the GBG battlefield

### ISSUE THREAD

**Issue by producermark11** [mainIine/foe-helfer-extension#2740]
Yesterday and for a long time before that,  me and my guild mates could play anywhere in the game, be it, GE, map, in my city, in an event ....
and the infobox showed the GBG elements as I did other things.
Now
We  have to be in the GBG battlefield or it doesn't show GBG elements.

I use Chrome, but also tried Firefox  - same issue.

FOE HELPER Extention Developers -----    __ CHANGE IT BACK PLEASE !  -----

It worked as above stated for years --  now it doesn't 

There was an update on Jan 27th from FOE Helper Extensions.  ever since then,
Infobox doesn't work the same way.

For those that don't use Infobox- please refrain from being an opiner.

If you look at the link below
https://prnt.sc/D6AK8XT8NUiz

It states "While this window remains open, it will display background events."
There are no caveats.

**Comment by AlfonZ42** [comment]
As far as I know, that is how it's supposed to work.

When you enter GBG, your game sends a "subscribe to GBG events" request to the server.
When you leave GBG, your game sends an "unsubscribe from GBG events" request to the server.

If the server doesn't send any GBG events, the *Infobox* can't show them.

**Comment by producermark11** [comment]
Yesterday, it worked.

**Comment by producermark11** [comment]
Even the Infobox 'window'  says it should 

see link 
https://prnt.sc/Ft7dtPPjB7Kt

**Comment by AlfonZ42** [comment]
Indeed it does show them, while you're on the *GBG map*.
Here is an example of what I see:
![FH-Infobox_GBGevents](https://github.com/mainIine/foe-helfer-extension/assets/1955593/5eb21be5-a95f-47b3-ad04-2ab31bf0935f)

I entered the *GBG map*, events start appearing in the *Infobox*.  
I left *GBG map*, events stop appearing.
I entered the *GBG map* again, events resume. Notice the skip from 130 to 138 while I was in the main town. No events received during that time.

I'm not sure what happened with your game yesterday, maybe there was some internet hiccup that garbled the "unsubscribe" request and you kept receiving GBG events even while in the main town. I just have never encountered it.

**Comment by producermark11** [comment]
It wasn’t just yesterday
It was working as explained above
For  YEARs

Omg.

**Comment by producermark11** [comment]
Can someone who actually knows what I am talking about
And actually has used Infobox
Respond to this
Please

My guild mates
Said the same thing

**Comment by producermark11** [comment]
I thought this thread was for the creators of the extension
Not
For some dudes opinion

**Comment by outoftheline** [comment]
I don't know why the GBG information seemed to be working for you while not on the map, but it's true that the information does not update when you're not in GBG.

**Comment by producermark11** [comment]
NOT JUST ME !  ! !  -- my guild   

HOLY   CRAP ! ! !

**Comment by AlfonZ42** [comment]
Which world is/was this on?
If you're playing on more worlds, did this happen on them as well, or was this just one world?

**Comment by producermark11** [comment]
Alfon  are you a developer of FOE Helper?

**Comment by producermark11** [comment]
People who don't fight in GBG, wouldn't notice a difference. 
Only those that do noticed a difference after the Jan. 27th update.

**Comment by producermark11** [comment]
This thread is really going nowhere with people who can't change it back to the way it was before the update.

People who probably never used Infobox before seem to be commenting on 'How it should work'.
I never asked for your opinion.  I want it changed back to the way it was before the Jan. 27th update.

Developers ONLY please.

**Comment by AlfonZ42** [comment]
You are right. I am not a *FoE Helper* developer. I have only read the source code, contributed couple of changes and used *Infobox* with *GBG* for years.

What we (*outoftheline* above **is** a developer) are trying to explain to you, *Infobox* only shows information that is sent from the server to you. If it's sent, it will be shown. If it's not sent, it will not be shown.

I see no recent change in *FoE Helper* in *Infobox* that touched it (the last one was in April 2023), so there is nothing to change back.

This seems like a change was made on the game server itself.

I would recommend you go to forums and/or official Discord and look whether other players of your world/language version noticed the change as well.

**Comment by producermark11** [comment]
I should have known this thread was not going to be so useful when I saw that it says
helfer not helper 
in the link.

**Comment by AlfonZ42** [comment]
@producermark11 Which world are playing on? So I personally can look at relevant forums and discord, as you seem to not want to do it?

**Comment by outoftheline** [comment]
How can a person be so freaking ignorant.
Helfer ist the German word for helper and the extension was initated by a German guy. 
Whatever, there is no bug here.
