### ISSUE TITLE
BG Helper - Make sort order persistent

### ISSUE THREAD

**Issue by coderwolf2015** [mainIine/foe-helfer-extension#2742]
In the new BG helper, if you set a sort order then collect a building. The sort order will reset back to default.  It would be nice if the tool respects the selected sort order and maintains that setting.  Having to resort after each building collect is quite annoying.
If this approach is not broadly an accepted practice a tool setting could be implemented allowing the user to select the preferred behavior

**Comment by outoftheline** [comment]
Implemented
