### ISSUE TITLE
Lag in Battlefields

### ISSUE THREAD

**Issue by Jesuantonio79** [mainIine/foe-helfer-extension#2749]
The lag is the same in Chrome and Opera, I've tried both browsers and the problems is there.
You can't fight with forges in the bar.

Regards.

**Comment by G-Bigo** [comment]
Confirmed.

The latest version of the helper causes an immense delay loading and executing fights. Something about 15-20 seconds compared to 1-2 w/o helper.

Only chance to reasonably contribute to guild battleground races right now is to deactivate the helper.

**Comment by G-Bigo** [comment]
Issues #2747 and #2748 address the same topic. Conflate?

**Comment by outoftheline** [comment]
Fixed, please update
