### ISSUE TITLE
Issue with Blue Galaxy helper

### ISSUE THREAD

**Issue by ingbabic** [mainIine/foe-helfer-extension#2752]
Hi,
Recently Blue Galaxy helper does not work. It does not hide the special building production that I already take and also does not showing me what to take next (the best option for me). I cleaned cookies and also installed newer version, but bug stay. Any other have similar experience?

**Comment by valimaties** [comment]
With the latest version, no. Are you sure you don't have another version, not the latest? Could you post a screenshot with the version from the settings page of the extension?

**Comment by outoftheline** [comment]
The MS edge store is super slow at releasing new versions. i'd suggest installing from the google chrome store instead.
