### ISSUE TITLE
Units from Winter Wonderland Pyramid not in Production Overview

### ISSUE THREAD

**Issue by EdwardBlack** [mainIine/foe-helfer-extension#2755]
Because this bug is not related to my browser but to the in game content, I skipped the bug-report template.

With the winter event, we got the Majestic Winter Wonderland Pyramid. It produces +12 Random Units when motivated. 

Unfortunately, these units are not displayed at the Production Overview. Is that a deliberate decision, because one gets them only when the building is motivated? If so, maybe it is reasonable to always include things from motivated buildings (especially event-buildings), because in reality they are always motivated...

**Comment by outoftheline** [comment]
the building data structure is all over the place and it's hard to catch all these exceptions.

the bug is known. we are working on getting things in order, because this is just one of the problems. 
the bugfix is part of a bigger project.

same issue as #2662
