### ISSUE TITLE
Strategy Edit Window for St Patrick does not open / pop up

### ISSUE THREAD

**Issue by txwikinger** [mainIine/foe-helfer-extension#2757]
Linux kernel 6.1.68-1-MANJARO
FOE Helper version 3.6.2.0 started. ID: bkagcmloachflbbkfmfiggipaelfamdf (No other extension in the profile)
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Error when St Patrick Event is started:

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.checkStrat (idleGame.js?v=3.6.2.0:697:88)
    at Object.idleGameUpdateDialog (idleGame.js?v=3.6.2.0:507:12)
    at idleGame.js?v=3.6.2.0:81:11
    at _proxyAction (foeproxy.js:390:5)
    at proxyAction (foeproxy.js:403:3)
    at XMLHttpRequest.xhrOnLoadHandler (foeproxy.js:525:7)
(anonymous) @ merged-3rd-party-109b844c.js:16
_proxyAction @ foeproxy.js:392
proxyAction @ foeproxy.js:403
xhrOnLoadHandler @ foeproxy.js:525
load (async)
XHR.send @ foeproxy.js:582
load @ ForgeHX-2d2e0f48.js:34263
__loadText @ ForgeHX-2d2e0f48.js:34266
loadText @ ForgeHX-2d2e0f48.js:34264
loadString @ ForgeHX-2d2e0f48.js:34425
load @ ForgeHX-2d2e0f48.js:35145
_loadUrlRequest @ ForgeHX-2d2e0f48.js:659
_send @ ForgeHX-2d2e0f48.js:657
_sendNextBatch @ ForgeHX-2d2e0f48.js:657
_pushBatch @ ForgeHX-2d2e0f48.js:657
_sendAllBufferedRequests @ ForgeHX-2d2e0f48.js:657
send @ ForgeHX-2d2e0f48.js:655
call @ ForgeHX-2d2e0f48.js:638
_callWithNoiseFuture @ ForgeHX-2d2e0f48.js:631
initMainComponentsData @ ForgeHX-2d2e0f48.js:6254
execute @ ForgeHX-2d2e0f48.js:28882
execute @ ForgeHX-2d2e0f48.js:35225
routeEventToCommand @ ForgeHX-2d2e0f48.js:35226
m @ ForgeHX-2d2e0f48.js:35223
__dispatchEvent @ ForgeHX-2d2e0f48.js:25
dispatchEvent @ ForgeHX-2d2e0f48.js:22
dispatch @ ForgeHX-2d2e0f48.js:617
_onUnlockedHudClicked @ ForgeHX-2d2e0f48.js:13884
_onHudClicked @ ForgeHX-2d2e0f48.js:6341
routeEventToListener @ ForgeHX-2d2e0f48.js:35230
u @ ForgeHX-2d2e0f48.js:35229
__dispatchEvent @ ForgeHX-2d2e0f48.js:25
__dispatch @ ForgeHX-2d2e0f48.js:51
__dispatchStack @ ForgeHX-2d2e0f48.js:34942
__onMouse @ ForgeHX-2d2e0f48.js:34954
onMouseUp @ ForgeHX-2d2e0f48.js:34935
dispatch @ ForgeHX-2d2e0f48.js:34311
handleMouseEvent @ ForgeHX-2d2e0f48.js:34282

Error when Edit for strategy is clicked: 

merged-3rd-party-109b844c.js:16 TypeError: Cannot read properties of undefined (reading 'map')
    at Object.modifyStrategy (idleGame.js?v=3.6.2.0:770:75)
    at HTMLTableCellElement.onclick (index:1:10)
(anonymous) @ merged-3rd-party-109b844c.js:16
(anonymous) @ _main.js:222

**Comment by AlfonZ42** [comment]
Indeed.

A fix for it has been committed into beta version so far. A released update might be tomorrow/in upcoming days.

In the meantime, you could try a workaround for it.

Open the event window. Then in the dev console (*F12* or *Ctrl+Shift+I*) run `idleGame.settings.Strategy.CurrentVariant = 0`. Close the event window and reopen it again. The Strategy edit window should work now.

Alternatively, removing the old settings should work as well - run `localStorage.removeItem('idleGameSettings')` in the dev console, then reload the game page.

**Comment by valimaties** [comment]
I think this one can be closed, as long as no issue was found anymore, and the event is almost finished,
