### ISSUE TITLE
Saint Patrick's Idle Game Info

### ISSUE THREAD

**Issue by Vicarius23** [mainIine/foe-helfer-extension#2760]
For the event, at the very bottom you give a "Next Town 8.4Q: 18h:39m" right below this would be ideal to have what time the following day that city will finish. Which for me would be 5:43am tomorrow. Just using a calculator on another website to determine that but it would be nice to have it right there and seems like it might be easy to do.

Another idea for it would be to add a checkbox for the the Swift-Sham Savings.

Thanks

**Comment by AlfonZ42** [comment]
A line calculating the time with discounted amount has been recently added.

Using your example, it will look like:
```
Next Town 8.4 Q: 18h:39m
     6.3 Q: 14h:00m
```

**Comment by Vicarius23** [comment]
Is it live? I don't have that and Chrome doesn't show an update for the extension.

**Comment by AlfonZ42** [comment]
It's in the beta version so far. It's not in the regular update yet.
