### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by wruenzler** [mainIine/foe-helfer-extension#2764]
It is impossible to open the city planer.
I've tried it in the game and with the web page.

The error message ERR_TOO_MANY_REDIRECTS is generated on several browsers and on several devices.
Deleting the cookies does not solve the problem.

**Comment by mainIine** [comment]
There was a problem with the server. It is now available again.

**Comment by wruenzler** [comment]
Thanks

**Comment by wruenzler** [comment]
It seem to be broken again. Not possible to do saves, .....
