### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by matti476** [mainIine/foe-helfer-extension#2768]
there is still same problem with sending city data. i click it and nothing happens
in city palnner when I start new city there is my old city. and i can't save the city - when i try it - nothing happens
no matter which browser i'm using - i tried firefox and chrome. i also cleaned cookies

**Comment by JonSaffron** [comment]
Error from server:
<head/><br/>
<b>Fatal error</b>:  Uncaught Error: Call to undefined function each() in /usr/www/users/foecre/api.foe-rechner.de/_inc/vendor/adodb/adodb.inc.php:839
Stack trace:
#0 /usr/www/users/foecre/api.foe-rechner.de/_inc/classes/db.php(74): ADOConnection-&gt;Execute()
#1 /usr/www/users/foecre/api.foe-rechner.de/_inc/classes/db.php(54): db-&gt;db_connect()
#2 /usr/www/users/foecre/api.foe-rechner.de/CityPlanner/index.php(42): db-&gt;__construct()
#3 {main}
  thrown in <b>/usr/www/users/foecre/api.foe-rechner.de/_inc/vendor/adodb/adodb.inc.php</b> on line <b>839</b><br/>

**Comment by protprot-it** [comment]
same problem....

**Comment by palWorx** [comment]
Same here!

**Comment by palWorx** [comment]
All systems go! Login and planner functional again!

**Comment by mainIine** [comment]
Yes. I fixed all problems.

**Comment by protprot-it** [comment]
Warning: Undefined array key "tech_id" in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 558
