### ISSUE TITLE
City Planner isn't recognizing my submission

### ISSUE THREAD

**Issue by Lucky-Delilah** [mainIine/foe-helfer-extension#2769]
I've tried to submit my city to the planner several times, and it always says I haven't done it. I used to be able to do this just fine but not today. It says in the little window that it's transmitted and to come here, but ut keeps telling me I have no city on file. I've logged in and out of both my FoE and FoE Helper accounts and restarted the browser multiple times. I don't know what else to try. Any suggestions?  Thank you!

**Comment by palWorx** [comment]
Seems to be the same or related error here. I can't login, does not recognize my Userdata. Password-Forgotten-Function sends a password, but the same error, when i try to login. A new registration fails, the server cant find my userid (yes the right one, checked your help page).

**Comment by Muddyfox6** [comment]
Same here. Submitted data is not recognised.

**Comment by Efm2004** [comment]
The same to me. No data.

**Comment by StephenCT333** [comment]
Similar here. I'm submitting the City, I'm getting the Transmitted response. BUT when I go to the City Planner in Chrome and attempt to open it, I only ever get a old city. The latest is not getting in there. I've tried clearing the cache and using Alt-F5. I even deleted all the old Cities , supposedly I have no saved cities right now. BUt still comes up with the old one each time I open New City.

**Comment by steventjoen** [comment]
I have the same problem.  Can submit the city, but no city data is found.

**Comment by steventjoen** [comment]
> I have the same problem. Can submit the city, but no city data is found.

Just now, it works again.

**Comment by palWorx** [comment]
Same here, login and city planner work again.

**Comment by Dlonrab** [comment]
Same here. Submitting city in foe helper produces an error message. 

Get a weird city after opening the city overview which disappears for a short period into my real city map until I clear my browser cache. But this cycle repeats itself again and again.
