### ISSUE TITLE
overview city of quantum incursion ?

### ISSUE THREAD

**Issue by Mowglik** [mainIine/foe-helfer-extension#2772]
hello, I would like to know if the Quantum Incursion City will be avalaible to see, in overview of the city, like the main city,
thanks.

**Comment by outoftheline** [comment]
will be included in the next update

**Comment by Mowglik** [comment]
thank you 🥂

**Comment by Malagenia55** [comment]
witam mam problem chce wysłać dane miasta na serwer i wyskakuje mi błąd nie wiem co mam zrobić proszę o pomoc
