### ISSUE TITLE
Data lost for no reason

### ISSUE THREAD

**Issue by exxaminer** [mainIine/foe-helfer-extension#2780]
Hey, today I just lost all my data, when I . I Haven't reinstalled or updated my system nor the browser. It just happened out of the blue. Is it possible I crossed some boundary for file size or so? Is it possible that historical data is somewhere in there? I love my data and there is a lot of statistics I'd like to keep :-( 

Interestingly - helper configuration remained intact...

![image](https://github.com/mainIine/foe-helfer-extension/assets/48965178/629b4fff-2292-4853-9621-fbbe8991c3da)

**Comment by outoftheline** [comment]
Do you maybe have very little disk space left on your computer? If so, this happens automatically.
The data cannot be restored.
