### ISSUE TITLE
Error occurred Your city data could not be sent to the server. Please report this error directly to Github

### ISSUE THREAD

**Issue by roguebk021** [mainIine/foe-helfer-extension#2782]
I get the error below when trying to submit my settlement to City Planner 
Error occurred
Your city data could not be sent to the server. Please report this error directly to
[Github](https://github.com/mainIine/foe-helfer-extension/issues)

**Comment by chrisdiy** [comment]
same here

**Comment by tedkirby** [comment]
Ditto.  Just noticed typo in project name helfer vs. helper.  Probably can't change that now.

**Comment by geochatzi** [comment]
same here

**Comment by Buggsy2k** [comment]
Same.  Before this started happening, when I did try to open a city in the city planner it was either the wrong data (when I looked at a settlement I got the right dimensions but buildings from a different settlement (very wonky looking), and my Main city was the right dimensions but no buildings just a big empty grid)

**Comment by Gerechto62** [comment]
same for me

**Comment by fousty71** [comment]
same for me

**Comment by AgnieszkaAnn** [comment]
same here

**Comment by 1312020515** [comment]
Same here. Never had this problem before

**Comment by korol086** [comment]
Планувальник не працює на офіцйному сайті https://foe-helper.com/citymap/maintained
Ця сторінка знаходиться в режимі обслуговування
Завдяки деяким ідіотам, які думають, що вони сценарні діти, які руйнують безкоштовний проект, структура повністю переглядається.

Під час цього процесу вся база даних буде очищена та скинута.

магістраль

**Comment by totinaster** [comment]
the same to me

**Comment by thodem** [comment]
same here,
additional if I log in the website  https://foe-helper.com, got to city planer I get message
"Du haste deine Stadtdaten noch nicht hier her geschickt oder bist in der falschen Welt. Gehe zu deinen Einstellungen in der Erweiterung im Spiel und sende deine Stadtdaten zur Webseite."
though ther must be many data from older submit and planing.

**Comment by thodem** [comment]
zusätzliche Info:
POST-Anfrage bei Übermittlung der Stadt-Daten an api.foe-rechner.de /CityPlanner/ gibt Fehler-Antwort des Servers:
(HTTP-Status 200)

**{"status":"ERROR","msg":"Api-token is missing! Create an API token first on foe-helper.com!"}**

Fehler auf foe-helper.com - eventuell gleiche Fehlerursache wie "error showing marketplace #2784 "

**Comment by mainIine** [comment]
Wollt ich mich alle veralbern? Seit wann ist ein Wartungsmodus ein Fehler?!!
Es wurde schon auf so vielen Wegen kommuniziert das ich die Datenbank umgebaut habe und es deshalb nicht möglich war Daten zu verschicken.

Am I kidding everyone? Since when is a maintenance mode an error?!!!
It has already been communicated in so many ways that I have rebuilt the database and therefore it was not possible to send data.

DE: [https://docs.foe-helper.com/deutsch/api-token](https://docs.foe-helper.com/deutsch/api-token)
EN: [https://docs.foe-helper.com/english/api-token](https://docs.foe-helper.com/english/api-token)

**Comment by tedkirby** [comment]
I am a user of FoE Helper.  I had the reported problem.  I just tried again, and I still have the problem.  I hope the problem will be fixed.  Or, have you removed this function from FoE Helper?  It is a very useful function, and I would be quite sorry to see it go!  Thanks.

**Comment by thodem** [comment]
Sorry wenn ich dich genervt habe,
aber:
Ich habe nirgends etwas über Wartungsmodus/maintenance gelesen. Auf der Homepage der Extension hatte ich nichts gesehen.
Das Forum ist nicht erreichbar um dort nachzuschauen. - nur Fehlermeldung
und das mit dem API-key ist irgendwie untergegangen, da es den bei Firefox anscheinend (noch) nicht gibt.

In meiner Extension Version 3.6.3.0 für Firefox (Update geprüft am 11.4.2024) gibt es keine Eingabe für den API-key: 
![Bildschirmfoto 2024-04-12 um 14 36 39](https://github.com/mainIine/foe-helfer-extension/assets/23363064/55f3f13d-f558-438e-9353-7c412fcf3152)
Wenn man auf der offiziellen Webseite von Firefox-Extensions nachschaut, steht da als aktuelle Version dieser Extension die 3.6.0! 

Ich habe es auf Chrome auch noch einmal geprüft und festgestellt, dass es dort funktioniert da es eine neue Version der Extension gibt (3.6.4).
