### ISSUE TITLE
CIty Planner won't send new data and old cities lost. 

### ISSUE THREAD

**Issue by rabbitofredemption** [mainIine/foe-helfer-extension#2787]
Was just settling in for a morning playing with City Planner and I couldn't copy my data to the server, it directed me here to report the error. Also all my old cities in City Planner were no longer there. Relogs and reboots didn't help. Thanks!

**Comment by AnthorAsl** [comment]
Can confirm this issue for all 6 worlds where I'm active: A, B, D, F, G & H :(

**Comment by JanineElH** [comment]
I got the same issue since yesterday on Z/us25 server. Just tried again and it's not working

**Comment by mainIine** [comment]
You need the Helper Version 3.6.4.0. 
This Version has a field for a api token.

Pls read here for further informations [https://docs.foe-helper.com/english/api-token](https://docs.foe-helper.com/english/api-token)

**Comment by mainIine** [comment]
The update was rolled out by Chrome immediately. But Firefox takes his time up to one week.

**Comment by Demiorgg** [comment]
Поле Api-Token пустое, версия foe-helper 3.6.4.0  Какими значениями надо заполнить данное поле и от куда их брать?
