### ISSUE TITLE
Building attack ratings are incorrect in "Building Efficiency Rating"

### ISSUE THREAD

**Issue by AradynGaming** [mainIine/foe-helfer-extension#2789]
Brief intro: Inno's new buff icons are messing up the formula "Building Efficiency Rating" uses to calculate.

Example: (DAA = Defense for Attacking Army) Building: Sun Temple Level 9. Produces: 126 DAA + 63 GBG DAA + 63 GE DAA + 50 QI DAA. When broken down, this is 189 GBG DAA + 189 GE DAA + 50 QI DAA or 189 Overall DAA + 50 QI DAA. A maximum of 239 points. Building efficiency will count this as 302.

Detailed explanation of issue: The overall or combined buff provides both GE & GBG benefit, while the specific GE or GBG tags only provide to that event category. This is leading buildings with split symbols (GE & GBG) to rank higher than they should & hurting the rating of buildings that has use the combined symbol. Example: A building with 3 combined would count as "3" efficiency and provides 3 to GBG & 3 to GE. While a building with 2 GBG & 2 GE would count as "4" efficiency, even though it is actually worse than the combined 3 building.

Suggestion: Overall buffs should still count as full value, while event specific buffs only count as half. Additionally, give QI buffs their own category, since they are isolated from overall & providing any support to GBG or GE.

**Comment by outoftheline** [comment]
![image](https://github.com/mainIine/foe-helfer-extension/assets/7482863/bb2ab32e-2fed-46b8-835b-fca021dfd370)
![image](https://github.com/mainIine/foe-helfer-extension/assets/7482863/1f1adcb9-389a-4f58-86a1-10b89e54e1d4)

this is how the rework looks like thus far

**Comment by AradynGaming** [comment]
Sorry for late response. I saw this the other day & couldn't log in to comment. It looks AMAZING! I've let it leak in my guild that this is getting repaired and people went nuts with excitement.  I know this is beyond the scope of this request, but in the future, it would be nice to analyze buildings that could be completed that are in the inventory. One thing at a time though. Thank you so much for fixing this issue, it's been driving a bunch of us insane. =)
