### ISSUE TITLE
User ID not recognized - cannot register

### ISSUE THREAD

**Issue by MarcellusDeOude** [mainIine/foe-helfer-extension#2790]
Okay, here's the thing:
I lost my notes. If I click on my notes icon, I get a notification I need a token. 
If I want to get a token, I need to register.
If I register, I need to fill in my user ID.
But my user ID is not recognized. If I reinstall the app, my user ID stays the same.

Can anyone help me out here?

Cheers

**Comment by peppermil** [comment]
I have a similar problem. My notes are empty (no longer available) with the note “First create a group…”
It works, but nothing happens after confirming!

Thanks

**Comment by Ricky6938** [comment]
Impossible de créer un compte sur Helper, ID non reconnue.
J'ai tout essayé et rien ne marche.

Si quelqu'un aurait une idée !!!!!
Merci.

**Comment by Mbj242** [comment]
I too am having the same problem with the user code.

**Comment by SunnyAnechka** [comment]
I have the same problem.
I am using Google Extention v. 3.6.4.0
player ID: 852050387
guild ID: 4568
world: ru8

After trying to Register (via https://foe-helper.com/register/player)
I get this error message:

"I couldn't find anything about this Player-Id.
Is this Id correct?.  
Have you already been in the game with the extension?
If not, install it now:"
