### ISSUE TITLE
can not send city map to foe helper 

### ISSUE THREAD

**Issue by saebuck80** [mainIine/foe-helfer-extension#2796]
My saved city maps are gone. I cannot upload thru the FOE Helper submit box. An error message occurs telling me to send a message to GitHub.  Can you fix this so I can upload my city ad modify it using the foe helper city planner tool?

**Comment by Pawel545** [comment]
Mam to samo :/
"Twoje dane miasta nie mogły zostać przesłane na serwer, zgłoś błąd bezpośredni do Github".

**Comment by mainIine** [comment]
@saebuck80 
Have you added a token to the helper extension to send data to the server?

[https://docs.foe-helper.com/english/api-token](https://docs.foe-helper.com/english/api-token)
