### ISSUE TITLE
Stadtplaner-trotz Api-Token und Update keine Daten in der Stadt

### ISSUE THREAD

**Issue by Wittgenstein299** [mainIine/foe-helfer-extension#2799]
Hallo zusammen,

ich nutze den FOE-Helper mit Firefox, habe die Version auf 3.6.4.0 In der Anwendung habe ich das API-Token hinterlegt. Trotzdem bekommen ich beim übermitteln der Stadtdaten, egal ob Hauptstadt oder Siedlung (aktuell Japaner) keine Daten. Wenn ich die Stadt öffne (egal welche) bekomme ich eine leere Hauptstadt ohne Gebäude angezeigt. Habe inzwischen überall nachgelesen, ich finde keine Lösung. Was kann ich noch tun...

Liebe Grüße
Markus

**Comment by TheJRH** [comment]
Ich habe das gleiche Problem. Benutze Chrome

**Comment by mainIine** [comment]
Das war ein Cache Problem und trat schon seit Wochen nicht mehr auf.

**Comment by Wittgenstein299** [comment]
Ich habe jetzt zur Sicherheit den kompletten Browsercache gelöscht, dann das Api-Token neu eingegeben und dann versucht aus der Siedlung die Daten zu übertragen..das Ergebnis sieht so aus...das bedeutet für mich ich kann den Stadtplaner nicht mehr nutzen....
![Stadtplaner_02](https://github.com/user-attachments/assets/54d4b618-d81d-4da5-9647-d2672864cf15)
![Stadtplaner](https://github.com/user-attachments/assets/0d359580-1a90-49a6-a1bf-6a85ed534051)

**Comment by mainIine** [comment]
Prinzipiell stimmen die Ansichten so. Über "Neu > Hauptstadt" werden aus der vorher übermittelten Stadt gesäuberte Daten mit denen Du dann eine Stadt bearbeiten kannst.

Gib mir doch mal Deine Spieler-Id und dein Weltenkürzel damit ich mir mal deinen Account anschauen kann. Ggf hängt da was quer.

**Comment by Wittgenstein299** [comment]
Gerne …hier die Infos: 

Spieler Id:

851788367

Gilden Id:

14466

Welt:

de14

 

 

Viele Grüße,

 

 

Markus Rath

Freier Redakteur

 

Redaktion – Grafik – Druck 

 

Phone: 09498 7228031

Mobile: 0176 62678739

Email:  ***@***.*** ***@***.***> 

Kirchplatz 15, 93164 Laaber

 

 

Von: Daniel Siekiera ***@***.***> 
Gesendet: Sonntag, 21. Juli 2024 16:56
An: mainIine/foe-helfer-extension ***@***.***>
Cc: Wittgenstein299 ***@***.***>; Author ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Stadtplaner-trotz Api-Token und Update keine Daten in der Stadt (Issue #2799)

 

Prinzipiell stimmen die Ansichten so. Über "Neu > Hauptstadt" werden aus der vorher übermittelten Stadt gesäuberte Daten mit denen Du dann eine Stadt bearbeiten kannst.

Gib mir doch mal Deine Spieler-Id und dein Weltenkürzel damit ich mir mal deinen Account anschauen kann. Ggf hängt da was quer.

**Comment by mainIine** [comment]
Alles stimmt. Ich kann keinen Fehler entdecken.

**Comment by Wittgenstein299** [comment]
…ein mirakel … denn trotzdem funzt es nicht Ich kann die Hauptstadt übertragen aber nicht die Siedlung Von meinem iPhone gesendetAm 22.07.2024 um 20:33 schrieb Daniel Siekiera ***@***.***>:﻿
Alles stimmt. Ich kann keinen Fehler entdecken.

**Comment by mainIine** [comment]
Habe ich die Abfrage bei den Siedlungen vergessen?
Kann sein, dass ich die Extension noch fix anpassen muss.

Lass mich das noch prüfen.

Mit freundlichem Gruß,
Daniel Siekiera


Am Mo., 22. Juli 2024 um 21:15 Uhr schrieb Wittgenstein299 <
***@***.***>:
