### ISSUE TITLE
Website - warnings for link copy

### ISSUE THREAD

**Issue by exxaminer** [mainIine/foe-helfer-extension#2800]
Hi,
When I copy link for the own part calculator and paste it to the url bar, I get error:

Co-payment calculator for
Warning: Undefined array key "LG_DATA" in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/bc7e3c448bf82c550075b89ac67f917d6ae83f55_0.file.index.tpl.php on line 67

Warning: Attempt to read property "value" on null in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/bc7e3c448bf82c550075b89ac67f917d6ae83f55_0.file.index.tpl.php on line 67

Warning: Trying to access array offset on value of type null in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/bc7e3c448bf82c550075b89ac67f917d6ae83f55_0.file.index.tpl.php on line 67

Link used: https://foe-helper.com/ownpart/index?lg=X_OceanicFuture_Landmark3&step=68&p1=93&p2=93&p3=90&p4=90&p5=90&own=0

It doesn't happen when working with drop downs, only when link is used.

All the best!
ex
![Screenshot_20240425_135757](https://github.com/mainIine/foe-helfer-extension/assets/48965178/7bbda308-4109-4b76-b672-20dc59497dd6)

**Comment by mainIine** [comment]
Is fixed.
