### ISSUE TITLE
Owner contribution tool with Arch above level 130

### ISSUE THREAD

**Issue by FuerstFugger89** [mainIine/foe-helfer-extension#2801]
As you may know, many guilds, as does ours, has a thread to sponsor Legendary Buildings, which contribute to the Guild, such as the Arch, the Observatory, Atomium, etc. with 95% Arch bonus. Many players, including myself, have an Arch on or above level 130, so they accept these sponsor places, paying FP into the buildings with 95% boost, without losing FP.

However, the Cost Calculator tool only shows a 80%, 85%, 90% button and one with the boost ratio of the own Arch. Whenever I want to verify whether a 95% sponsor place is safe, I have to type in the 95 into the tool by hand.

Ergo, could you please, with your next update, add a 95% button to the two Investment Calculator tools in the Helper?

This would be much appreciated.

![Screenshot 2024-04-26 181736](https://github.com/mainIine/foe-helfer-extension/assets/168214455/d89c37f7-5418-4954-ad27-bacefdc091d3)
![Screenshot 2024-04-26 181759](https://github.com/mainIine/foe-helfer-extension/assets/168214455/2db323c5-d8e1-464f-85a2-35b95d26894a)

Thank you!

**Comment by outoftheline** [comment]
Gibts schon lange! 
Bitte einmal den Button hier drücken:
![image](https://github.com/mainIine/foe-helfer-extension/assets/7482863/e733f918-0992-47d7-b979-f5bc0b561585)

**Comment by FuerstFugger89** [comment]
Wow - hab ich bis jetzt nicht geschnallt! Vielen Dank! 😅😂
