### ISSUE TITLE
Stadtplaner

### ISSUE THREAD

**Issue by Ricco73** [mainIine/foe-helfer-extension#2802]
Windows 10 64 Bit
124.0.2478.51 (Offizielles Build) (64-Bit)

Spielername : Ricco (4616267)
Welten :
Houndsmoor,
Arvahall,
Uceria,
Odrovar
Sineria
2.4.2.2 - Deutsch

auf all diesen welten ist es mir nicht mehr möglich meine daten an den Foe Helfer zu senden

vielen dank für eure Hilfe schonmal im voraus

Ricco

**Comment by Crazy-Winni** [comment]
Welche ist die Aktuellste?

**Comment by outoftheline** [comment]
das ist die version vom spiel.. die helfer version bekommst du je nachdem welchen du nutzt im firefox oder im chrome store
