### ISSUE TITLE
jeton api

### ISSUE THREAD

**Issue by Bernie-Raspa** [mainIine/foe-helfer-extension#2806]
Le jeton d'api ne fonctionne pas : 
018ec9b4-b6c8-766d-9165-9efd3b98a289

Une erreur est survenue
Il n’y a pas de joueur avec cet identifiant sur ce monde. S’il vous plaît créer un compte sur foe-helper.com d’abord !

**Comment by outoftheline** [comment]
english, thank you

**Comment by Bernie-Raspa** [comment]
Comment avez vous eu cette adresse mail ???? cc : Bernie-Raspa ***@***.***>, Author ***@***.***>envoyé : 29 avril 2024 à 17:59de : Yvi ***@***.***>à : mainIine/foe-helfer-extension ***@***.***>cc : Bernie-Raspa ***@***.***>, Author ***@***.***>objet : Re: [mainIine/foe-helfer-extension] jeton api (Issue #2806) english, thank you—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by azertyuiop20** [comment]
rien ne fonctionne
