### ISSUE TITLE
city planner ne marche pas

### ISSUE THREAD

**Issue by azertyuiop20** [mainIine/foe-helfer-extension#2809]
le token reste vide vous faite quoi ???

**Comment by mainIine** [comment]
English or german.

**Comment by azertyuiop20** [comment]
Frenchenvoyé : 12 juillet 2024 à 11:48de : Daniel Siekiera ***@***.***>à : mainIine/foe-helfer-extension ***@***.***>cc : azertyuiop20 ***@***.***>, Author ***@***.***>objet : Re: [mainIine/foe-helfer-extension] city planner ne marche pas (Issue #2809) English or german.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
