### ISSUE TITLE
Card list in Historic event Helper have wrong colors in some browsers

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#2815]
Chromium (v105.0.5154.0)
![2405081510](https://github.com/mainIine/foe-helfer-extension/assets/35531243/b4a29c09-5ca3-4c77-a722-7b4ebc1e66ba)

Maxthon (v7.1.8.6001)
![2405081518](https://github.com/mainIine/foe-helfer-extension/assets/35531243/e4cca86a-328f-430a-b20e-2e0088f29940)

Brave, Яндекс and Vivaldi are OK.

**Comment by outoftheline** [comment]
do you use any other extensions like a dark reader or similar? it's fine for me on chrome

**Comment by belikoviv** [comment]
> do you use any other extensions like a dark reader or similar?

Only AdBlock Plus (but it is disabled on FoE domain)

> it's fine for me on chrome

Chrome and Chromium are different browsers.
