### ISSUE TITLE
Stadtplaner

### ISSUE THREAD

**Issue by anoscr** [mainIine/foe-helfer-extension#2818]
Servus zam,
seit einigen Tagen ist es nicht mehr möglich, den Stadtplaner zu nutzen.
Ich weiss, das ist hier schon häufiger aufgeschlagen, jedoch bisher noch nichts passiert.
Ablauf: wenn ich meine Stadt an den FOE-Helper senden möchte, ploppt ne Info im Game auf, dass ich den Fehler direkt in Github melden soll. Fehlermeldung: "Deine Stadtdaten konnten nicht an den Server gesendet werden. Bitte melden Sie diesen Fehler direkt an
[Github]" - API-Key ist hinterlegt und hat auch bis vor gut 1.5 Wochen funktioniert.

Helper-Version: 3.6.2.0
Chrome-Version: Version 124.0.6367.156
Welt(en): Korch
Spielername: Momo der Unsagbare

Wenn ihr weitere Infos benötigt, gerne melden.

Danke euch im Voraus!

Cheers!

**Comment by outoftheline** [comment]
website probleme kann nur mainline beheben. er scheint aktuell sehr beschäftigt zu sein, länger nichts von ihm gehört. deshalb können wir nur um geduld bitten.
