### ISSUE TITLE
Ätherisches Luftschiff - Einheitenproduktion wird nicht angezeigt.

### ISSUE THREAD

**Issue by G-Bigo** [mainIine/foe-helfer-extension#2819]
Für einige der neueren Eventgebäude wird die Produktion von Einheiten vom Helfer anscheinend nicht erfasst.

Sicher bestätigen kann ich diese z.B. für das ätherische Luftschiff.
![luftschiff](https://github.com/mainIine/foe-helfer-extension/assets/37943206/83ecf1af-bc5c-4e21-b2b1-0432718ae8c4)

**Comment by G-Bigo** [comment]
Winterwunderland-Pyramide ebenso.
![pyramide](https://github.com/mainIine/foe-helfer-extension/assets/37943206/885f83d1-632f-4830-917a-9bed63ae92a1)

**Comment by G-Bigo** [comment]
![buehne](https://github.com/mainIine/foe-helfer-extension/assets/37943206/1e6645b1-fc1b-4ca2-b591-8b00ab1f5256)

**Comment by outoftheline** [comment]
siehe #2662 
da innos datenstruktur über 12 jahre gewachsen ist und unser code deshalb wie ein flickenteppich aussieht, mache ich gerade eine grundsätzliche anpassung. bin fast fertig, aber der restliche kleinkram dauert noch ein bisschen.

**Comment by G-Bigo** [comment]
Nachempfindbar. Mit den immer tolleren Event-Haupt- und Nebengewinnen in den letzten 1½ Jahren kommt kaum noch jemand hinterher.
