### ISSUE TITLE
Building efficiency rating

### ISSUE THREAD

**Issue by dawid19921** [mainIine/foe-helfer-extension#2822]
Hello, I would like to suggest adding bonuses for GBG and GE to Building efficiency rating

**Comment by outoftheline** [comment]
i am already working on it

**Comment by dawid19921** [comment]
I love you :D

**Comment by AradynGaming** [comment]
@outoftheline Oh you're my hero, can't wait to see it. Came to see if anyone ever commented on my post and saw this one as a duplicate https://github.com/mainIine/foe-helfer-extension/issues/2789 (can group that into this one/whichever one is primary for this topic).
