### ISSUE TITLE
foe helper website wont let me register so I cant get a token

### ISSUE THREAD

**Issue by SunnyOneVa** [mainIine/foe-helfer-extension#2829]
it just keeps saying my user ID is incorrect even tho I am copying and pasting directing from the extension on my game, which matches my game as well.   I have triple checked to make sure all my info I am putting in is correct. 

Help, please.  New update requires a token for info about my city to be transmitted.

**Comment by SunnyOneVa** [comment]
bump

**Comment by p1d3c** [comment]
same trouble

**Comment by tbasnoopy** [comment]
same here

**Comment by mainIine** [comment]
Is there a brave player who can test the new registration / login?

Please try to create a new account.

Please report any errors here immediately so that I can fix them.

**Comment by stekkedecat** [comment]
I tried, it just keeps on loading

**Comment by mainIine** [comment]
I don’t know what you mean by that. Can you describe this in more detail?

**Comment by JIJ01** [comment]
I’m having the same problem with the person above. When I go to make the account for FOE helper, I fill in all the required information but once I click register it get stuck in an endless loading cycle so it won’t allow me to make the account

**Comment by mainIine** [comment]
Oh, ok. I’ll take a look at that again. Please wait for my feedback.

**Comment by tbasnoopy** [comment]
If it helps:

https://foe-helper.com/register/_ajax?ajax=native&file=find-player&pID=<BLABLA>&pw=<BLABLA>=<BLABLA>&server=de
Request Method:
GET
Status Code:
404 Not Found

**Comment by stekkedecat** [comment]
what i see if i look at that url is that there is no key-value pair for the world nr in there, is that intended?

**Comment by tbasnoopy** [comment]
sorry, my fault. I wrote "<>" around them so it wasn't shown correctly. Fixed now ^^

**Comment by tbasnoopy** [comment]
But (I think) the more relevant info is, that the site isn't present (Error 404)

**Comment by stekkedecat** [comment]
@tbasnoopy I'm not an ajax expert, but cant it be that the endpoint cannot be found because of the missing parameter?

**Comment by mainIine** [comment]
That was probably an old JS cache. I have refreshed it.

**Comment by p1d3c** [comment]
> That was probably an old JS cache. I have refreshed it.
> 
> The file "find-player" doesnt exists any more.

so we can try to register now?

**Comment by mainIine** [comment]
Yes pls.

**Comment by p1d3c** [comment]
request for
> https://foe-helper.com/register/_ajax?ajax=native&file=register-player&w=ru&wNr=4&pID=myID&pw=myPassword&em=myEmail
returns 200 OK
But after that i see infinity loading. 
So if request for register returns 200, I can login now? No. Login form shows me that password is wrong :/

**Comment by p1d3c** [comment]
Hah, I just get a new password by "Forgot password?" function. And successfully logged in

**Comment by p1d3c** [comment]
Now when I'm trying to check my profile on foe-helper.com I get an error 
`Warning: Undefined array key "current_world" in /usr/www/users/foecre/foe-helper.com/core/modul/user/pages/profile.php on line 112

Warning: Undefined array key "all_worlds" in /usr/www/users/foecre/foe-helper.com/core/modul/user/pages/profile.php on line 114

Fatal error: Uncaught TypeError: array_column(): Argument #1 ($array) must be of type array, null given in /usr/www/users/foecre/foe-helper.com/core/modul/user/pages/profile.php:114 Stack trace: #0 /usr/www/users/foecre/foe-helper.com/core/modul/user/pages/profile.php(114): array_column() #1 /usr/www/users/foecre/foe-helper.com/core/modul/user/user.php(34): include('/usr/www/users/...') #2 /usr/www/users/foecre/foe-helper.com/core/classes/class.layout.php(341): user->getTPL() #3 /usr/www/users/foecre/foe-helper.com/core/modul/user/user.php(28): layout->__construct() #4 /usr/www/users/foecre/foe-helper.com/index.php(50): user->__construct() #5 {main} thrown in /usr/www/users/foecre/foe-helper.com/core/modul/user/pages/profile.php on line 114`

**Comment by p1d3c** [comment]
Looks like my data in database is undefined or null. And register middleware didnt saved it.

**Comment by p1d3c** [comment]
ID: 852547561
world: ru4

**Comment by tbasnoopy** [comment]
ID: 852814468
world: de11

**Comment by mainIine** [comment]
Pls let's discuss here: https://github.com/mainIine/foe-helfer-extension/discussions/2836

**Comment by norbet6566626** [comment]
850389886 
PL11
