### ISSUE TITLE
Spieler/Gildenranking in QI

### ISSUE THREAD

**Issue by rkotulla** [mainIine/foe-helfer-extension#2831]
Ist denn was in Arbeit oder geplant fuer eine QI Spieler Uebersicht, parallel zur Uebersicht in GG? Dann koennte man als Gildenleitung besser aufpassen wer aktiv ist und wer nix macht. In der Betaversion ists scheinbar noch nicht. 

Wenn noch nix konkretes geplant ist wuerde ich mich da dran mal versuchen, die entsprechenden Infos vom Server gibts auf jeden Fall. Wenn ihr da schon dran seid kann ich mir die Muehe natuerlich sparen.

**Comment by outoftheline** [comment]
nein, ist im Moment mit Absicht noch nicht in Arbeit, weil Inno die Daten nach QI Ende nicht mehr auswirft. Dadurch entstehen unterschiedliche Speicherstände bei verschiedenen Spielern.. und die Leute verstehen das dann leider nicht.

**Comment by rkotulla** [comment]
Ok, dann bastel ich das erstmal fuer mich weiter, besser ein beinahe-Endstand als gar keine Infos. Uns gehts in der Gilde hauptsaechlich eh um die QI-Nuller, die werden auf den letzten Druecker dann nicht noch anfangen. GG-Tool ist ja ne super Vorlage, und wenn sich Inno dann dazu durchringt die Daten nach Ende doch noch zu schicken ware zumindest ein Anfang mal gemacht

**Comment by outoftheline** [comment]
@rkotulla hast du da schon was gebastelt? inno will das ranking mit einem zeitnahen update auch nach QI ende verfügbar machen. auf dem beta-server ists schon so.

**Comment by outoftheline** [comment]
nvm, habs soweit fertig :)

**Comment by outoftheline** [comment]
#2778
