### ISSUE TITLE
Sortierung

### ISSUE THREAD

**Issue by rauschm** [mainIine/foe-helfer-extension#2834]
Wieso kommt es, dass, wenn ich die Produktions Übersicht nach Name sortiere, das Ätherische Luftschiff zwischen Tapir-Pade und Traubenstampfen-Festival?

![grafik](https://github.com/mainIine/foe-helfer-extension/assets/1425585/f9e13af6-6104-4579-b076-02c40c76a2f8)

**Comment by Beelzebob6666** [comment]
ich vermute, dass das Ä ignoriert wird - was den sortieralgorithmus angeht, ist der name "therische Luftschiff"... Ä ist halt leider ein "sonderzeichen"...
