### ISSUE TITLE
Production Overview: units missing

### ISSUE THREAD

**Issue by kleopatra** [mainIine/foe-helfer-extension#2838]
they appear neither in the units tab nor the productions per building, happens for some buildings only, f.i.:
- dragon gong (too new?)
- cider garden
- marauder
- royal bathhouse

others (gov's villa, oilpress, panda shrine) are correctly shown

Version
    3.6.4.0
Spieler Id:
    172231
Gilden Id:
    7459
Welt: doesn't seem to matter, same in all (de and beta) worlds

**Comment by outoftheline** [comment]
it is being worked on, see also #2662

**Comment by kleopatra** [comment]
darn .. didnt scroll so far back 😎 sry

**Comment by GeniePower** [comment]
building efficiency != production overview


imo of course
