### ISSUE TITLE
A new static for seedvault

### ISSUE THREAD

**Issue by ThomasX321** [mainIine/foe-helfer-extension#2841]
We already have statics for the GB: HC,SC and flying island so i was wondering what if you could make a new static for the reward from SVbecause seedvault often gives dia,good,supplies,coins or medals. it would be the same like the GB HC and SC and flying island only now for SV because we don't have one yet

**Comment by outoftheline** [comment]
the rewards ar a bit hard to extract and also: we cannot know how many people could successfully be aided. makes adding stats a small headache.
