### ISSUE TITLE
add world to my profile

### ISSUE THREAD

**Issue by stekkedecat** [mainIine/foe-helfer-extension#2844]
I tried to add a new world to my profile, but i cannot get it to work right...
I've been doing some digging and in the form i found 2 errors:
`<form class="form-inline" action="user/profile"> <span class="input-group-text">
					nl
				</span> <input type="number" min="1" step="1" class="form-control" name="world_number" required=""> <button class="btn btn-primary btn-sm waves-effect waves-light" role="button" type="button">
                    Save
				</button> <input type="hidden" name="action" value="save-new-world"> </form>`
issue one: it should be `action="/user/profile"`
issue two: it should be `<button class="btn btn-primary btn-sm waves-effect waves-light" role="button" type="submit">`
when solving these 2 settings, I manage to get the round trip to server working again, however, the data does not get saved yet
needs more debugging as to why the data doesn't get added

**Comment by stekkedecat** [comment]
Happy to report this has been fixed!

**Comment by mainIine** [comment]
Yes, I found some time beside my family and fixed it 😊
