### ISSUE TITLE
Unable to send city data from foe helper

### ISSUE THREAD

**Issue by BergReal** [mainIine/foe-helfer-extension#2847]

**Comment by mainIine** [comment]
??

**Comment by BergReal** [comment]
Unable to send data to server

Sent via the Samsung Galaxy, powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mainIine** [comment]
Any message or hint for this action?

**Comment by geoffbon** [comment]
I see the same problem; steps to reproduce are

1. Ensure API key is set correctly, and right world is selected in the city builder
2. In FOE, open the town overview and hit the City Planner button, then Submit
3. In the city planner, refresh the page, then New City > Main city
4. The correct city footprint appears, but with no buildings

**Comment by RealWheelman** [comment]
This is exactly the same problem I have. If you click remove buildings, they will appear in the pane on the left side. Except now, which ever city I load, it's all buildings from my last Aztec settlement.

**Comment by mainIine** [comment]
I cannot reproduce this error. I asked a few players who tested the planner yesterday and there were no problems.
