### ISSUE TITLE
City import von https://foe-city-builder.web.app/#/

### ISSUE THREAD

**Issue by darylam** [mainIine/foe-helfer-extension#2853]
Hi, ich finde euren City Planner super genial zum vorbereiten und dann im Spiel umzusetzten, weil ihr eine sehr gute Darstellung habt mit den Gebäudetypen Farben etc. ... https://foe-city-builder.web.app/#/ bietet eine verbesserung an und immer wieder schafft der es, mein layout zu "optimieren" - aber die Darstellung ist schrecklich - und ich würde das gerne in eurem Planner manuell fertig machen :) ... Seht ihr eine Möglichkeit die gespeicherten Städte bei euch einzuladen? Man importiert dort ja auch euren Export? VG Aldaron

**Comment by manumnc** [comment]
Hi, why did I receive the message "Your city data could not be sent to the server" when I tried to send it to Helper?

**Comment by mainIine** [comment]
Ich wüsste nicht das das derzeit möglich ist.
