### ISSUE TITLE
Unable to login anymore 

### ISSUE THREAD

**Issue by w052** [mainIine/foe-helfer-extension#2854]
I have used the city planner multiple times in the past 2 years.  now i cant login to my account anymore.  This is the screen i get after I login:

"Warning: Undefined array key "worldShort" in /usr/www/users/foecre/foe-helper.com/core/modul/login/pages/index.php on line 113

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/foecre/foe-helper.com/core/modul/login/pages/index.php:113) in /usr/www/users/foecre/foe-helper.com/core/functions/general.php on line 24

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/foecre/foe-helper.com/core/modul/login/pages/index.php:113) in /usr/www/users/foecre/foe-helper.com/core/functions/general.php on line 25

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/foecre/foe-helper.com/core/modul/login/pages/index.php:113) in /usr/www/users/foecre/foe-helper.com/core/functions/general.php on line 43"

Thank you

 Syl

**Comment by mz-ed** [comment]
Check compatibility between your general.php info and your db info because I think it's not accessing the db to login

**Comment by w052** [comment]
Thanks but how do I do that?

Syl

On Jun 25, 2024, at 10:45, mz-ed ***@***.***> wrote:

﻿

Check compatibility between your general.php info and your db info because I think it's not accessing the db to login

**Comment by mz-ed** [comment]
go to the header file or the file that hold the db connection info and check if it's compatibale with apache configuration on the browser like bd name and user info etc...
check also for corruption in bd files maybe that is the problem too
look on youtube you will find a solution 
"sorry for bad english"

**Comment by ToughK1** [comment]
I have exact same problem.
![image](https://github.com/mainIine/foe-helfer-extension/assets/175161272/f1c79e6f-f1d7-4f27-94f2-fdd1108fdc96)
I've been using this program for years. The problem arose a week or two ago ... 
NB! First time I saw these error messages, it showed me like I had logged in to someone's M-world account ...

**Comment by mainIine** [comment]
I fixed a cuple of errors. Give it a new try.

**Comment by ToughK1** [comment]
Thank you for your support.
Those Warnings are gone.
But now there are other issues.
Instead my name it shows my player ID.
And API token is not correct.

![image](https://github.com/user-attachments/assets/0f6eb251-60f4-4e9d-b33c-f35c3f1d3af0)

**Comment by mainIine** [comment]
Pls re-login.

**Comment by mainIine** [comment]
@ToughK1 
You can set your name at the right bottom. Take a look at the complete page.

![image](https://github.com/user-attachments/assets/1b329c2d-4676-4272-ac1d-342267c20516)

**Comment by ToughK1** [comment]
Thank you very-very much!
It's working again!

**Comment by mainIine** [comment]
Wunderful.
