### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by bernie79160** [mainIine/foe-helfer-extension#2855]
Good morning,
I don't understand,
can you send me the link for deleting your server thank you.

**Comment by outoftheline** [comment]
write an email https://foe-helper.com/info/impressum

**Comment by bernie79160** [comment]
Bonjour Yvi,Comme vous ne respectez pas le RGPD j'ai déposé plainte à la CNIL, et à la Gendarmerie.Bonjour Raspapopoulos,Même si FoE Helper a un nom qui se rapproche de notre jeu, FoE Helper ne nous appartient donc on ne peut pas leur ordonner quelque chose. En revanche, une règlementation européenne appelle “RGPD” (Règlement général sur la protection des données) vous donne le droit de demander à n'importe quel site de supprimer vos données. Le nom respect de ce règlement expose un site à des sanctions financières :)Cordialement,YushiCo-Community Manager Forge of EmpiresForum | Page Facebookenvoyé : 24 juin 2024 à 15:27de : Yvi ***@***.***>à : mainIine/foe-helfer-extension ***@***.***>cc : bernie79160 ***@***.***>, Author ***@***.***>objet : Re: [mainIine/foe-helfer-extension] Ask for help (Issue #2855) write an email https://foe-helper.com/info/impressum—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by outoftheline** [comment]
i will not bother translating this.

write an email to mainline, because it is his website and his resposibility only. not mine.
