### ISSUE TITLE
Login auf den falschen Account

### ISSUE THREAD

**Issue by Andi47** [mainIine/foe-helfer-extension#2858]
Ich habe mich vor ein paar Wochen, als die API-Tokens eingeführt wurden, mit meiner Mailadresse als Andi47 registriert, konnte mich damals aber nicht einloggen.
Gestern habe ich es wieder versucht, scheint geklappt zu haben (ich habe aber nicht auf den angezeigten Usernamen geachtet). Mir ist aber dann etwas dazwischen gekommen, sodass ich das API-Token dann heute Vormittag testen wollte - beim Versuch, auf https://foe-helper.com/ meine Spielwelt Houndsmoor (de8) auszuwählen, kam eine Fehlermeldung, die die Kopfzeile der Seite überdeckt hatte. (leider habe ich keinen Screenshot, war irgendwas mit unknown id)

Das Problem mit obiger Fehlermeldung scheint wieder behoben, aber der nach dem Login nun angeführte Username - shiotabc - nein, das bin nicht ich. (wenn ich ins Profil gehe, steht dort meine Mailadresse drin, Problem besteht nach logout und erneutem Login weiterhin, ich hab mich daraufhin wieder ausgeloggt, ohne einen API-Token einzutragen oder sonst etwas zu ändern)

Edit: Browser: Google Chrome, Version 126.0.6478.63 (Offizieller Build) (64-Bit), 

Werden die Usernamen beim Registrieren mit der Mailadresse zufällig vergeben, oder hat's die User-Datenbank zerschossen?

**Comment by mainIine** [comment]
@Andi47 
Kannst Du mir via Discord PM oder Mail Deine Spieler-Id + Welten-Kürzel zukommen lassen?

**Comment by Andi47** [comment]
Meinst du meine Spieler-ID in FoE? Mail ist unterwegs.
