### ISSUE TITLE
Mistake API-TOKEN

### ISSUE THREAD

**Issue by norbet6566626** [mainIine/foe-helfer-extension#2880]
![aaa](https://github.com/mainIine/foe-helfer-extension/assets/174933244/ed47693e-d82f-4ea7-9e5c-930198d34cad)
![Screenshot_6](https://github.com/mainIine/foe-helfer-extension/assets/174933244/2246d7c2-1684-4ac4-b8af-31247e890127)
![Screenshot_7](https://github.com/mainIine/foe-helfer-extension/assets/174933244/aee167fe-2495-4a61-9d8f-1da367fd434f)
![Screenshot_8](https://github.com/mainIine/foe-helfer-extension/assets/174933244/f7e0113f-53ac-4794-a374-fdd38aeff03e)

**Comment by mainIine** [comment]
Sounds like you deposited the token in the wrong world of the game.
