### ISSUE TITLE
Music issues

### ISSUE THREAD

**Issue by Yamihm** [mainIine/foe-helfer-extension#2881]
Hello
I don't want to listen to music while playing and I have to enter the FoE helper settings every time I enter the game to mute the music, I haven't selected music, it's not even one of the items I have selected in the menu content, something is wrong .
Please help me to permanently eliminate this problem.
Thank you

**Comment by outoftheline** [comment]
i guess you are always clearing browser information? 
mute the browser tab or the website then. most browsers can do so by right clucking on the browser tab and selecting
