### ISSUE TITLE
Problems to start the Helper

### ISSUE THREAD

**Issue by Trahorn** [mainIine/foe-helfer-extension#2882]
Hello
When I start the helper, my User-Name is not written, only a number. When I try to build my city Iget this error message:

Warning: Undefined array key "player" in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 69

Warning: Trying to access array offset on value of type null in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 69

Fatal error: Uncaught TypeError: Cannot assign null to property citymap::$player_world of type string in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php:69 Stack trace: #0 /usr/www/users/foecre/foe-helper.com/core/classes/class.layout.php(341): citymap->getTPL() #1 /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php(56): layout->__construct() #2 /usr/www/users/foecre/foe-helper.com/index.php(50): citymap->__construct() #3 {main} thrown in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 69

**Comment by Trahorn** [comment]
Nach der Anmeldung kommt folgender Bildschirm
![anmeldung-tools](https://github.com/user-attachments/assets/f93d1dcb-00fb-4f1e-be11-7cdc5083fc06)

**Comment by mainIine** [comment]
Can you give me your player-id and your main world-shurtcut?

**Comment by Trahorn** [comment]
Meine Spieler ID lautet: 
10048233
Ich spiele auf Noarsil
https://foe.scoredb.io/DE13/Player/10048233
Ich hoffe, das hilft

**Comment by Trahorn** [comment]
Mein Profil unter foe-Helper
Statt meinem Spielername Trahorn steht meine Spieler-ID
![profil](https://github.com/user-attachments/assets/ff41c916-797f-4692-805b-d0f10c613992)

**Comment by matti476** [comment]
i have the same problem

**Comment by Trahorn** [comment]
It is not good but i am tranquilize. It is no problem only with my game. Thank you for your answer

**Comment by mainIine** [comment]
> Meine Spieler ID lautet: 
> 
> 10048233
> 
> Ich spiele auf Noarsil

Versuch es bitte einmal.

**Comment by mainIine** [comment]
> i have the same problem

Send me your player id and the world shortcut.

**Comment by Trahorn** [comment]
An Mainline: VIELEN DANK !!!! Es funktioniert wieder alles so wie immer. Ein schönes Wochenende wünsche ich

**Comment by Innovindiel** [comment]
Ich habe das gleiche Problem wie oben beschrieben.
Ich spiele auf Arvahall und Vingrid. 
Meine Spieler ID 1030451
Ich kann keine Welt auswählen. Der Token wird nicht akzeptiert.

**Comment by mainIine** [comment]
@Innovindiel 

Hilf mir mal aufs Pferd und gib mir die Welten-Kürzel. Also die Nummern die in der URL stehen.
Ich kenne die nicht alle auswendig.

**Comment by matti476** [comment]
> @matti476
> 
> > i have the same problem
> 
> Send me your player id and the world shortcut.

player ID: 2437241
world: pl7

**Comment by mainIine** [comment]
@matti476 
Pls re-login.

**Comment by matti476** [comment]
OK, it helps. Thank you!👍

**Comment by Innovindiel** [comment]
@mainIine
Meine Welten sind de1 und de21 meine Spieler ID 1030451

**Comment by mainIine** [comment]
@Innovindiel 
Bitte logge Dich noch mal neu ein. Ich habe das gerichtet.

**Comment by Innovindiel** [comment]
@mainIine
Jetzt bekomme ich im Helper wieder nur meine Spieler ID angezeigt und wenn ich auf den Stadtplaner gehe erscheint folgende Meldung:

Warning: Undefined array key "world" in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 69

Fatal error: Uncaught TypeError: Cannot assign null to property citymap::$player_world of type string in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php:69 Stack trace: #0 /usr/www/users/foecre/foe-helper.com/core/classes/class.layout.php(341): citymap->getTPL() #1 /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php(56): layout->__construct() #2 /usr/www/users/foecre/foe-helper.com/index.php(50): citymap->__construct() #3 {main} thrown in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 69

Dein Profil
Add a new world to your player-Id
de
1

gebe ich da die Spielewelt ein, siehe oben, erscheint folgende Meldung:
You have already registered this world number
Dein Profil
Add a new world to your player-Id
de

Was mach ich falsch ????

**Comment by mainIine** [comment]
Oben am Rand sollte ein Dropdown mit seinen Welten sein.
Ist das zu klein?

**Comment by Innovindiel** [comment]
![image](https://github.com/user-attachments/assets/6a7e08e8-910f-424f-8a20-1d6a57ad0c42)
da erscheint KEINE Weltauswahlt siehe Imge

**Comment by Innovindiel** [comment]
Hat nicht funktioniert ...gleiches Problem

**Comment by Innovindiel** [comment]
@mainIine, ist mein Problem noch in Arbeit oder muss ich ein neues Ticket für das Problem aufmachen ??? Wenn das mit dem Stadtplaner nicht funktioniert brauch ich den Helper nicht und werde die Erweiterung deinstallieren. Mit der Bitte um Info.

**Comment by mainIine** [comment]
@Innovindiel 
Auf welchen Welten spielst Du noch? Ich sehe hier noch mehr.

**Comment by Innovindiel** [comment]
@mainIine 
Ich spiele auf de1 und de21. Spieler ID 1030451. Sollten andere Welten angezeigt werden die werden NICHT bespielt.

**Comment by mainIine** [comment]
@Innovindiel 
Fehler gefunden, bitte einfach noch mal einloggen.

**Comment by Innovindiel** [comment]
@mainIine,
geht alles wieder super. Vielen Dank !!!!!
