### ISSUE TITLE
Suggestion for Military Units 

### ISSUE THREAD

**Issue by SirDragonKnight** [mainIine/foe-helfer-extension#2883]
Hi there, 

Would it be possible to have a tab that shows the army units you gain from other buildings like the Bullion Garrison for example like you do with Alcatraz?

**Comment by GeniePower** [comment]
This should be part of the military units tab in the production overview, but no newer buildings are showing up there

**Comment by outoftheline** [comment]
> This should be part of the military units tab in the production overview, but no newer buildings are showing up there

this. it is being reworked now.
