### ISSUE TITLE
Vorschlag: Wiederkehrende Quests scrollbar machen

### ISSUE THREAD

**Issue by Andi47** [mainIine/foe-helfer-extension#2887]
Im Zeitalter Raumfahrt: Venus gibt es einige wiederkehrende Quests mit UND- sowie ODER-Verknüpfungen, wodurch die Liste über den unteren Bildschirmrand hinausgeht, zusätzlich trägt noch der lange Text in der Kopfzeile der Tabelle zur Länge der Tabelle bei, sodass die untersten Einträge bereits unter dem unteren Bildschirmrand verschwinden. Im "normalen" Browsermodus ist es so gar nicht möglich, die Tabelle breiter zu machen - erst im Vollbildmodus ist das möglich, indem man die Tabelle möglichst weit nach oben schiebt.
Allerdings hat das auch nur begrenzten Nutzen - auch im Vollbildmodus wird der Platz nach unten schon knapp,, und die Einträge enden mitten im Wort mit "...", obwohl nach der Verbreiterung der Tabelle ausreichend Platz wäre.

Vorschlag:
1.) Die Länge der Tabelle auf die Höhe des Browserfensters begrenzen, sodass man auch ohne Tricks an die "Fenstergröße ändern"-Schaltfläche in der unteren rechten Ecke herankommt (oder diese Schaltfläche (auch) oben rechts platzieren)
2.) Beim Verbreitern des Fensters die maximale Textlänge vergrößern.

Screenshot :
![240715_Helper_FoE_Wiederkehrende_Quests](https://github.com/user-attachments/assets/74ae316b-c20a-4ee5-a8f4-1fd25cd92906)

**Comment by outoftheline** [comment]
eigentlich müsstest du an der ecke ziehen können und dann bleibt das fenster in der gewünschten größe.
ich hab aber mal eine höhe hinzugefügt. kommt mit ins nächste update.

**Comment by Andi47** [comment]
Super, danke.

In den meisten Zeitaltern ist es kein Problem, aber in Raumfahrt
Asteroidengürtel sind SO VIELE Schleifenquests, dass man schon ordentlich
tricksen muss, um an die Ecke überhaupt ranzukommen (Browser im
Vollbildmodus, Windows-Taskleiste verschwinden lassen, und hoffen, dass die
Bildschirmauflösung ausreicht, dass sich das Fenster ausgeht. Und dann das
Fenster auf die gesamte Bildschirmbreite verbreitern, damit man den Roman
in der Kopfzeile von gefühlten 15 Zeilen auf 3 Zeilen "verdünnen" kann, und
die letzten paar Quests noch ohne Vollbildmodus sieht.)

P.S.: Noch ein Vorschlag: Da Inno jetzt das "Krankenhaus" eingeführt hat,
wo man im Rathaus bis zu 100 Einheiten mit Dias wiederbeleben kann, könnte
man im Kampf die Box "Stop, du hast Einheiten eines zukünftigen Zeitalters
verloren" eigentlich rausnehmen? Oder zumindest separat abschaltbar machen
(also nicht an die Box "Stop, die Armee besteht nur noch aus Agenten"
binden).

lg
Andi

Am Fr., 30. Aug. 2024 um 09:40 Uhr schrieb Yvi ***@***.***>:

**Comment by outoftheline** [comment]
zoom hätte vermutlich auch geholfen :D

ja, die einstellung wollten wir ändern oder entfernen
