### ISSUE TITLE
API Token

### ISSUE THREAD

**Issue by GerarDelissen** [mainIine/foe-helfer-extension#2888]
Alles geprobeerd om mijn stadsplanner te kunnen activeren maar geen enkel resultaat. aik moet het API Token invoeren maar wat ik ook doe, ik krijg deze niet gevonden. Kan iemand muj helpen daarmee?

Please use deppl.com or translate.google.com.

[EN] Tried everything to be able to activate my city planner but no result. aI have to enter the API Token but no matter what I do, I can't find it. Can anyone help muj with that?

**Comment by mainIine** [comment]
Please send me your player-id and your main-world short cut.

**Comment by GerarDelissen** [comment]
This is my player ID: 849473591 and the world is Cirgard

**Comment by mainIine** [comment]
And Cirgard has the number?

**Comment by GerarDelissen** [comment]
Where can I find that?

**Comment by GerarDelissen** [comment]
Versie
3.6.5.0
Speler-ID:
849473591
Gilde-ID:
25866
Wereld:
nl3

**Comment by mainIine** [comment]
I only found nl31 and changed this to 3. Pls try it again.
