### ISSUE TITLE
Fehler bei Stadtplaner / Anmeldung

### ISSUE THREAD

**Issue by Wilfried111-w** [mainIine/foe-helfer-extension#2889]
Bei Anmeldung Stadtplaner wird diese Fehlermeldung ausgegeben:

Warnung : Undefinierter Array-Schlüssel „player“ in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php in Zeile 69.
Warnung : Versuch, auf Array-Offset auf Wert vom Typ null in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php in Zeile 69 zuzugreifen.
Schwerwiegender Fehler : Nicht abgefangener TypeError: Kann der Eigenschaft citymap::$player_world vom Typ String in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php:69 keinen Nullwert zuweisen. Stacktrace: #0 /usr/www/users/foecre/foe-helper.com/core/classes/class.layout.php(341): citymap->getTPL() #1 /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php(56): layout->__construct() #2 /usr/www/users/foecre/foe-helper.com/index.php(50): citymap->__construct() #3 {main} geworfen in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php in Zeile 69

Und anstelle Profil eine Ziffernfolge
Spieler Id:  4861639
Gilden Id:  11330
Welt:          de2

Ich sag schon mal Danke im voraus
Wilfried111-w

**Comment by mainIine** [comment]
Versuch dich bitte noch mal komplett neu einzuloggen.

**Comment by Wilfried111-w** [comment]
Dankeschön für die Mühe;

Funktioniert wieder 

Wilfried
