### ISSUE TITLE
Problem bei Aufruf des Stadtplaners

### ISSUE THREAD

**Issue by Spuelwurm** [mainIine/foe-helfer-extension#2890]
Hallo

Beim Start der Tools wird immer folgende Fehlermeldung  ausgegeben:

Warning: Undefined array key 3 in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/32e8f97d9014f3500921e1b26565b58f299c990b_0.file.profile.tpl.php on line 98

 
Der im Profil angezeigte API-Token
0190b886-4e59-7732-9564-a762a18aef8b
Wird als falsch erkannt

Spieler ID: Spülwurm (6222207)
Spielwelt: de3

Besteht eine Möglichkeit dieses Problem zu beheben?

Mit freundlichen Grüßen

**Comment by mainIine** [comment]
Hi @Spuelwurm ,

Bitte logge Dich einfach mal neu ein. Dir wird dann bestimmt ein passender Token angezeigt.

**Comment by Spuelwurm** [comment]
Leider schon mehrfach probiert. Selbst ein Broserwechsel auf Firefox mit  Installation der Erweiterung brachte nicht den gewünschten Erfolg!

**Comment by Spuelwurm** [comment]
Überdies habe ich direkt nach dem Einloggen die o.g. Fehlermeldung:
Warnung: Undefined……….

**Comment by mainIine** [comment]
Der Token ist auch falsch.

Schaue ich in dein Konto sehe ich drei andere.

**Comment by gerry4444** [comment]
same Problem:

Api-Token -
Warning: Undefined array key 16 in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/32e8f97d9014f3500921e1b26565b58f299c990b_0.file.profile.tpl.php on line 98

the token doesnt work

**Comment by gerry4444** [comment]
Api-Token -
Warning: Undefined array key 16 in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/32e8f97d9014f3500921e1b26565b58f299c990b_0.file.profile.tpl.php on line 98

Bei mir funzt es auch nicht
ID : gersha
DE16
