### ISSUE TITLE
API token error

### ISSUE THREAD

**Issue by smail6233** [mainIine/foe-helfer-extension#2892]
![id](https://github.com/user-attachments/assets/a4c60fa0-d2ec-448d-8318-c63f47e97b7b)
ID: 7846656
world:  RU11
langendorn

api token does not arrive.
there is no designation in the profile world Langendorn
only id

help!!!

**Comment by mainIine** [comment]
On how many worlds u play?

**Comment by smail6233** [comment]
> On how many worlds u play?

16
all ru servers

**Comment by mainIine** [comment]
Ok. I linked the worlds to your account. Pls re-Login.

**Comment by smail6233** [comment]
> Ok. I linked the worlds to your account. Pls re-Login.

could not log in error
This data is incorrect!

I'm trying to reset the password also an error
Error! We do not know this email address
((

**Comment by mainIine** [comment]
The mail-address ends with @yandex.ru

**Comment by smail6233** [comment]
> The mail-address ends with @yandex.ru

hmm, true Yandex mail
it worked!
thank you)
respect

![city](https://github.com/user-attachments/assets/beb1e7f7-0889-4b64-941c-10ec13c41a4e)

**Comment by mainIine** [comment]
Your appricated
