### ISSUE TITLE
API-Token

### ISSUE THREAD

**Issue by byteviper1** [mainIine/foe-helfer-extension#2894]
Getting the following error on the API Token page:

Warning: Undefined array key 25 in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/32e8f97d9014f3500921e1b26565b58f299c990b_0.file.profile.tpl.php on line 98

There is a code, but when added to the extension I get an error that it is not the correct API-Token.
Is there a way to fix this issue?

**Comment by mainIine** [comment]
Pls send me your player id and the world-short cut from your main world.

**Comment by byteviper1** [comment]
Player ID:  21395808

Not sure what the world short cut is but maybe this is it:  us25

**Comment by byteviper1** [comment]
Player ID: 21395808

Not sure what the world short cut is but maybe this is it: us25

    On Friday, July 19, 2024 at 02:51:42 AM EDT, Daniel Siekiera ***@***.***> wrote:  
 
 


Pls send me your player id and the world-short cut from your main world.

**Comment by mainIine** [comment]
@byteviper1 
Fixed your account. Your e-mail-address starts with chuckd...@....com for the right account. Pls try to re-login.

**Comment by byteviper1** [comment]
Excellent, thank you so much!
