### ISSUE TITLE
City invisible when moving from Space Age Mars to Asteroid

### ISSUE THREAD

**Issue by g15713** [mainIine/foe-helfer-extension#2895]
Can you delete my account and let me start all over again?

email: g15713@yahoo.com
Player ID: 852230995
Guild: 1271
World: us25

City planner is a great tool! Was working great but now when transferring city data becomes blank in city planner.

**Comment by mainIine** [comment]
I fixed your data. Please re-login to your account.

**Comment by g15713** [comment]
Unfortunately it did not bring up my current city in Space Age Asteroid. I don't mind losing data just delete the account so one can start fresh. Thank you for your consideration.

**Comment by mainIine** [comment]
The old city no longer appears. We had to redo this and a lot has been lost. 
1. transfer the data from the extension to the page 
3. create a new city there via "New > Capital"

**Comment by g15713** [comment]
Transferred the city data to the page of foe-helper  login
created a new city there - Capital, worked today and showing Space Age Asteroid buildings !!

Was going to donate but it only accepts Eur - needs to accept US dollars!!
