### ISSUE TITLE
Link in "Nicht Vorschlagen"-Liste, Punkt 1, wirft Fehlermeldung

### ISSUE THREAD

**Issue by Andi47** [mainIine/foe-helfer-extension#2896]
In der "Nicht Vorschlagen"-Liste (https://github.com/mainIine/foe-helfer-extension/issues/860) in Punkt 1 wirft der Link https://forum.foe-rechner.de/d/355-anderungen-am-foe-helfer-changes-to-the-foe-helper folgende Fehlermeldung:

Warning: Undefined array key "data" in /usr/www/users/foecre/discuss.foe-helper.com/forum/vendor/flarum/core/src/Frontend/Content/CorePayload.php on line 74

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Unable to emit response; headers already sent in /usr/www/users/foecre/discuss.foe-helper.com/forum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:19 Stack trace: #0 /usr/www/users/foecre/discuss.foe-helper.com/forum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(36): Laminas\HttpHandlerRunner\Exception\EmitterException::forHeadersSent() #1 /usr/www/users/foecre/discuss.foe-helper.com/forum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /usr/www/users/foecre/discuss.foe-helper.com/forum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit() #3 /usr/www/users/foecre/discuss.foe-helper.com/forum/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 /usr/www/users/foecre/discuss.foe-helper.com/forum/index.php(22): Flarum\Http\Server->listen() #5 {main} thrown in /usr/www/users/foecre/discuss.foe-helper.com/forum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 19

**Comment by mainIine** [comment]
Das Forum sollte eigentlich nicht mehr erreichbar sein. Ich leite das mal sauber um. Danke für die Info!
