### ISSUE TITLE
PY-R8 Marauder Military Unit production not reflected in Building Efficiency Rating

### ISSUE THREAD

**Issue by Gerardo-Quinones** [mainIine/foe-helfer-extension#2897]
The PY-R8 Marauder building generates one artillery unit per day, but in the Efficiency Rating it is shown as none, giving an incorrect efficiency rating for the building when military unit generation is selected as an efficiency criterion.
![Screenshot 2024-07-21 at 11 09 42 AM](https://github.com/user-attachments/assets/07d6667f-5f55-4846-bdf5-c3cce411318f)
![Screenshot 2024-07-21 at 11 11 31 AM](https://github.com/user-attachments/assets/c2a18c3a-bd5c-4253-a1fb-613e5d0d8850)

**Comment by outoftheline** [comment]
will be implemented in a bigger rework that is almost done
