### ISSUE TITLE
Export SnapshotLog as csv or json

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#2899]
Hi.
Could you please implement exporting Snapshot Log as csv or json?

Because, right now, there is only the save button in GBG Overview, but not for snapshot log. 
This could be helpful!

Thank you.

**Comment by valimaties** [comment]
any news? no comment, could be done or not ...

**Comment by Beelzebob6666** [comment]
almost everything can be done... it simply has no high priority as of now
