### ISSUE TITLE
Vorschlag/Suggestion - produzierende abgelaufene Gebäude bei Push-Nachrichten ignorieren - ignore producing expired buildings in push messages

### ISSUE THREAD

**Issue by Andi47** [mainIine/foe-helfer-extension#2901]
Deutsch:
Vorschlag: abgelaufene begrenzte Gebäude, die dennoch produzieren (also nicht nur Zufriedenheit, z.B. Goldener Drachengong Stufe 2, Zhengs Goldene Glocke Stufe 2 sollten in Push-Nachrichten für abgelaufene Gebäude ignoriert werden - diese Ignorier-Funktion sollte in den Optionen ein- und ausgeschaltet werden können.
Begründung: ich spiele auf 4 Servern (eine Hauptwelt, 3 Nebenwelten), und habe in allen vier Städten jeweils mehrere (teils bereits abgelaufene, d.h. auf Stufe 2 zurückgestufte) Goldene Drachengongs und Goldene Glocken stehen - diese produzieren aber auf Stufe 2 immer noch brav Einheiten bzw. Güter des nächsten Zeitalters, sodass ich diese nicht abreißen möchte. Es nervt, wenn bei JEDEM neu Laden des Spiels die Push-Nachrichten kommen - gleichzeitig übersieht man dann leicht, wenn einmal ein wichtiges Gebäude, z.B. Vergessener Tempel oder Turniergelände) abläuft und dadurch wertlos wird.

Englisch:
Suggestion: Expired time-limited buildings, which are still producing (more than happiness, e.g. Golden Dragon Gong level 2 or Zheng's Golden Bell level 2) should be ignored in "expired buildings"-push messages. This ignore function should be able to be switched on or of in the FoE helper options.
Reason: When playing on more than one server it is annoying to get the push messages for expired, but still producing time-limited building such as Golden Dragon Gongs or Golden Bells, which are (on level 2) still producing units or goods for the next era, and therefore most players will not want to remove these buildings. Furthermore, when getting this messages EVERY time when reloading the game, it is likely to overlook / miss it when an important time-limited building, such as the Forgotten temple or a Tourney Ground (which turn to a worthless decoration on expiration) is expired.

**Comment by outoftheline** [comment]
ist schon eingebaut 
![image](https://github.com/user-attachments/assets/62d13180-de04-47f3-8cfb-c96fb4333e27)

**Comment by Andi47** [comment]
Ah, danke, dann werde ich das bei mir gleich anklicken.
