### ISSUE TITLE
Habe das gleiche Problem das ich nach dem Anmelden keine Stadt auswählen kann

### ISSUE THREAD

**Issue by Karsch83** [mainIine/foe-helfer-extension#2903]
Player ID 849594230 
Spiele in Tuulech
Vingrid und Arvahal

**Comment by mainIine** [comment]
Bitte noch mal neu einloggen.

**Comment by Karsch83** [comment]
Hallo Herr Siekiera,

das Problem besteht weiterhin in der beschriebenen Form.
 

Mit freundlichen Grüßen

Borchert Klaus-Dieter

-----BEGIN RSA PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCO8M3+kVXD7Sw9zKJXAZ2dT4Zy
AUMjn4hWrSYfldh0oYs98bf7j979w0lQ/uxmJg+ayFqoEbRUlxvmAVtyhnXcbaCw
7sWjpkblnr1habOqmb3SVRKgG2jd9JljILkvskkGZjT+UZ58FvzcH4r3w4OwzANN
4nEahYhET5Zx/KPBiQIDAQAB
-----END RSA PUBLIC KEY-----

 
 

Gesendet: Mittwoch, 28. August 2024 um 10:46 Uhr
Von: "Daniel Siekiera" ***@***.***>
An: "mainIine/foe-helfer-extension" ***@***.***>
Cc: "Karsch83" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Habe das gleiche Problem das ich nach dem Anmelden keine Stadt auswählen kann (Issue #2903)


 

Bitte noch mal neu einloggen.

**Comment by mainIine** [comment]
Wenn keine Stadt in der Liste ist, wurde keine gespeichert?
Das Du erstmal eine anlegen musst über "Neue Stadt" weißt Du aber?

**Comment by Karsch83** [comment]
Habe eine andere Welt ausgewählt wo ich NICHT Spiele danach konnte ich meine Städte auswählen.

Problem gelöst.
 

Mit freundlichen Grüßen

Borchert Klaus-Dieter

-----BEGIN RSA PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCO8M3+kVXD7Sw9zKJXAZ2dT4Zy
AUMjn4hWrSYfldh0oYs98bf7j979w0lQ/uxmJg+ayFqoEbRUlxvmAVtyhnXcbaCw
7sWjpkblnr1habOqmb3SVRKgG2jd9JljILkvskkGZjT+UZ58FvzcH4r3w4OwzANN
4nEahYhET5Zx/KPBiQIDAQAB
-----END RSA PUBLIC KEY-----

 
 

Gesendet: Mittwoch, 28. August 2024 um 14:05 Uhr
Von: "Daniel Siekiera" ***@***.***>
An: "mainIine/foe-helfer-extension" ***@***.***>
Cc: "Karsch83" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] Habe das gleiche Problem das ich nach dem Anmelden keine Stadt auswählen kann (Issue #2903)


 

Wenn keine Stadt in der Liste ist, wurde keine gespeichert?
Das Du erstmal eine anlegen musst über "Neue Stadt" weißt Du aber?
