### ISSUE TITLE
Fehler bei der Übertragung zum FOE Helper

### ISSUE THREAD

**Issue by R3Guru** [mainIine/foe-helfer-extension#2906]
Moin,
versuche ich meine Stadtdaten zum FOE Helper zu übertragen, erhalte ich folgende Meldung:
"Ein Fehler ist aufgetreten. Deine Stadtdaten konnten nicht an den Server übertragen werden".
Bitte um Hilfe

Gruß R3Guru

**Comment by goch71** [comment]
Hallo,
habe das gleiche Problem. Hat jemand eine Lösung?

Gruß goch71

**Comment by mainIine** [comment]
Hab ihr denn den API-Token für die korrekte Welt hinterlegt?

[https://docs.foe-helper.com/deutsch/api-token](https://docs.foe-helper.com/deutsch/api-token)

**Comment by R3Guru** [comment]
Moin Daniel, danke für deinen Tipp. Leider ist bei mir über Einstellungen -
Übermittlung der Eintrag "API-Token" nicht vorhanden.
Gruß R3Guru

Daniel Siekiera ***@***.***> schrieb am Mi., 28. Aug. 2024,
10:45:

**Comment by mainIine** [comment]
Auf der Webseite unter Profil und in der Extension unter "Übermittlung > Api-Token".

Wenn der Punkt in der Extension fehlt, solltest du mal ein Update ziehen.

**Comment by R3Guru** [comment]
It is working now.

github-actions[bot] ***@***.***> schrieb am So., 29. Sept.
2024, 04:07:
