### ISSUE TITLE
Delete Account for re-register

### ISSUE THREAD

**Issue by epoxef** [mainIine/foe-helfer-extension#2908]
When I open the City Planner I get an error message. Chrome and also Firefox. Can you delete my account so I can re-register? Then I hope the problem can be solved.
Thanks
epoxef

Version 3.7.0.0
Spieler Id: 8246730
Gilden Id: 21626
Welt: de5

**Comment by Glenfiddish2011** [comment]
Gleiches Problem bei mir, bitte Konto löschen für neue Registrierung.
Relog hat leider nichts gebracht.
Funktioniert weder in Chrome, noch in Opera GX noch in Firefox

Vielen lieben Dank 

Version
3.7.0.0
Spieler-ID:
4118403
Gilden-ID:
15156
Quaddel:
de4
![FoE-Helper Screenshot 2024-08-13 ](https://github.com/user-attachments/assets/ed7c83d7-d871-4f2d-8534-6f19442a7ecd)

**Comment by mainIine** [comment]
Try the login again if something is missing you get advised.

**Comment by damoojeje** [comment]
I signed up for foe helper using the wrong world. Please delete all associated accounts to start afresh.

Version: 3.8.0.0
Player ID: 22374706
Guild ID: 19197
World: us12

Email 1: damoojeje@gmail.com
Email 2: orclpdb@gmail.com

Thank you.
