### ISSUE TITLE
account auf der Website funktioniert nicht mehr

### ISSUE THREAD

**Issue by BABI6598** [mainIine/foe-helfer-extension#2912]
ich kann die Daten für den Stadtplaner nicht senden, meine Welten

Version 3.7.0.0
Spieler Id: 9347613
Gilden Id: 1479
Welt: de10

 und 

de Walstrand

werden nicht mehr angezeigt 

![helfer](https://github.com/user-attachments/assets/2fa208f5-c69b-4bb0-be8b-9c120b220c95)

bitte reparieren oder löschen, dass ich neu registrieren kann

**Comment by BABI6598** [comment]
Warning: Undefined array key 1 in /usr/www/users/foecre/foe-helper.com/core/modul/docs/docs.php on line 30

Warning: Undefined array key 1 in /usr/www/users/foecre/foe-helper.com/core/modul/docs/docs.php on line 30

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/foecre/foe-helper.com/core/modul/docs/docs.php:30) in /usr/www/users/foecre/foe-helper.com/core/functions/general.php on line 24

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/foecre/foe-helper.com/core/modul/docs/docs.php:30) in /usr/www/users/foecre/foe-helper.com/core/functions/general.php on line 25

Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/foecre/foe-helper.com/core/modul/docs/docs.php:30) in /usr/www/users/foecre/foe-helper.com/core/functions/general.php on line 43

**Comment by Grinsebaer** [comment]
Mir geht das genauso. Egal an welchem Rechner und in welchem Browser...

**Comment by mainIine** [comment]
Versucht es bitte noch einmal. Ich habe einiges angepasst.

**Comment by Grinsebaer** [comment]
Der Fehler bleibt. Direkt nach dem Login steht dort:
Api-Token -
Warning: Undefined array key 6556 in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/32e8f97d9014f3500921e1b26565b58f299c990b_0.file.profile.tpl.php on line 98

Scheinbar ist mein Konto mit keiner Welt verknüpft. Ich kann aber auch keine hinzufügen. Nach Klick auf "save" passiert nichts.
In meinem Account sehe ich auch meinen In-Game Namen nicht.
Vielleicht bringt es was, wenn mein Account gelöscht wird und ich mich wieder neu registrieren kann 🤔

**Comment by mainIine** [comment]
Schick mir deine Spieler-id und dein Weltenkürzel.

Ich schau mir das an.

LG, mainline

Mit freundlichem Gruß,
Daniel Siekiera


Grinsebaer ***@***.***> schrieb am Mi. 28. Aug. 2024 um 20:24:

**Comment by Grinsebaer** [comment]
Hallo,

 

mittlerweile bin ich mir gar nicht mehr sicher wie ich mich da registriert habe. Ich glaube ich habe da irgendeine Umstellung auf Email verpasst. Bei mir im Kopf ist nämlich immer eine Anmeldung mit meinem Nik „Grinsebär“…

 

Version 3.7.0.0

Spieler Id: 9859938

Gilden Id: 23245

Welt: de9

 

Hoffentlich gutes Gelingen. Müsste nämlich langsam mal umbauen und den Frachter irgendwie unterbringen, damit ich mal die ZA Leiter weiter klettere… 😉 und ohne den Helper ist das schon ein Graus 😜

 

Ciao,

                Grinsebär

 

 

Von: Daniel Siekiera ***@***.***> 
Gesendet: Mittwoch, 28. August 2024 20:26
An: mainIine/foe-helfer-extension ***@***.***>
Cc: Grinsebaer ***@***.***>; Comment ***@***.***>
Betreff: Re: [mainIine/foe-helfer-extension] account auf der Website funktioniert nicht mehr (Issue #2912)

 

Schick mir deine Spieler-id und dein Weltenkürzel. 

Ich schau mir das an. 

LG, mainline 

Mit freundlichem Gruß, 
Daniel Siekiera 


Grinsebaer ***@***.***> schrieb am Mi. 28. Aug. 2024 um 20:24:

**Comment by mainIine** [comment]
Nutze er bitte die E-Mail Adresse hohlkopf@*****zi.de

**Comment by Grinsebaer** [comment]
yippidie, was habt ihr gemacht? Es geht wieder. Oder war ich wirklich zu dämlich mit dem Token? 😇
Keine Fehlermeldungen mehr, vielen dank! 😊

**Comment by mainIine** [comment]
Ich habe zwei überflüssige kaputte Weltverlinkungen entfernt.

That's all.

**Comment by mainIine** [comment]
@BABI6598 
Versuche es bitte noch einmal

**Comment by BABI6598** [comment]
![image](https://github.com/user-attachments/assets/8cd84d01-2726-4092-98c5-d7c52f52747e)

**Comment by BABI6598** [comment]
ich hatte versucht, bei Add a new world etwas einzugeben, der token ist weder von Korch noch von Walstrand

**Comment by mainIine** [comment]
Welche Städte stehen denn rechts oben bei Klick auf die Nummer?

**Comment by BABI6598** [comment]
wenn ich auf die Spieler-ID klicke? da kommt nichts

**Comment by BABI6598** [comment]
![image](https://github.com/user-attachments/assets/64662794-57d3-43b1-8328-bfb3af4fa088)

**Comment by BABI6598** [comment]
![image](https://github.com/user-attachments/assets/d07097fe-703b-4583-88af-6909a8044a2c)
und das kommt beim Stadtplaner

**Comment by mainIine** [comment]
Du hattest zwei Konten. Logge dich bitte noch mal neu ein Büro-Tiger 😊

**Comment by BABI6598** [comment]
sieht sehr viel besser aus - ich probier gleich, ob ich die Stadt exportieren kann

**Comment by BABI6598** [comment]
fantastisch - ich danke Dir sehr - und das zu so später Stunde - wünsche Dir eine gute Nacht

**Comment by BABI6598** [comment]
❤️

**Comment by mainIine** [comment]
Ich habe gedient. Ich will zu Diensten stehen. 😎
