### ISSUE TITLE
FoE Global guild helper

### ISSUE THREAD

**Issue by papadan1943** [mainIine/foe-helfer-extension#2915]
When I click 'Global' then 'your guild' then foe helper tries to load its summary but locks up and can only be reset by reloading FOE. This blocks access to my guild actions such as making donations.

**Comment by outoftheline** [comment]
you can disable the automatic guild overview pop up in the helper settings

**Comment by papadan1943** [comment]
Thank you for your reply. Unfortunately I don’t see the auto guild overview
in settings/ Boxes or General.
Can you give any more information?
