### ISSUE TITLE
City Planner

### ISSUE THREAD

**Issue by QueenTheresa57** [mainIine/foe-helfer-extension#2917]
I'm unable to enter my world (Sinerania) so that I can get the Api-token. It keeps jumping to an error on line 69. I play on US18. 

Warning: Undefined array key "world" in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 69

Fatal error: Uncaught TypeError: Cannot assign null to property citymap::$player_world of type string in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php:69 Stack trace: #0 /usr/www/users/foecre/foe-helper.com/core/classes/class.layout.php(341): citymap->getTPL() #1 /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php(56): layout->__construct() #2 /usr/www/users/foecre/foe-helper.com/index.php(50): citymap->__construct() #3 {main} thrown in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 69

**Comment by mainIine** [comment]
I have revised everything again. Everything works for me, even the outposts.
