### ISSUE TITLE
Api Token

### ISSUE THREAD

**Issue by alexmas2** [mainIine/foe-helfer-extension#2918]
Как получить Api Token
![Screenshot_1](https://github.com/user-attachments/assets/59cba27b-544a-431e-ac22-89c0a1355566)

**Comment by mainIine** [comment]
Add a world?

**Comment by alexmas2** [comment]
ru7

**Comment by mainIine** [comment]
Try it again to the input field. Enter 7 after the ru mark.

**Comment by RManPT** [comment]
I have the same issue. That screen is all I see. When I try to enter the world number I got an annotation stating I have already registered that world ... so I am stuck. How to proceed? Thank you

**Comment by outoftheline** [comment]
> I have the same issue. That screen is all I see. When I try to enter the world number I got an annotation stating I have already registered that world ... so I am stuck. How to proceed? Thank you

for this bug try this for troubleshooting:

**copy this URL** to your browser while logged in
``https://foe-helper.com/user/profile?remove=``

add your **world shortcode** to the end, e.g. ``de3``
*full url is ``https://foe-helper.com/user/profile?remove=de3`` in this example*

**hit enter**

(for multiple worlds, repeat this multiple times)

then try to add your world(s) again

**Comment by RManPT** [comment]
Thank. Although there were multiple warnings like the one bellow, both on remove and adding the world, it worked.

"Warning: Cannot modify header information - headers already sent by..."

sorry I didn't get a print screen.

**Comment by Ocicathero** [comment]
Bin seit Wochen hier auf der Suche, um Probleme wie: Übertragen der Daten zum Stadtplaner funktioniert nicht, ein mir unbekanntes API Token wird im Profil angezeigt, verbunden mit den Warnungen, die schon von mehren gepostet wurden, endlich zu beheben.
![Bildschirmfoto_13-9-2024_31847_foe-helper com](https://github.com/user-attachments/assets/371eefb7-4abd-48fd-af03-8c8962dbdda3)

Leider funktionierte der Tipp von outoftheline bei mir nicht. Zusätzlich sind nach der Aktion auch die Notizen im Nirvana verschwunden und der Helfer im Spiel erklärt mir, lege erstmal einen Account an. Den ich habe ich. Zusätzlich kommen ein paar Warnungen mehr:
![Bildschirmfoto_13-9-2024_34643_foe-helper com](https://github.com/user-attachments/assets/4ebd15c1-1836-4664-95ee-77d03d1009d2)

Wäre für eine funktionierende Aktion sehr dankbar. Hat jemand andere Ideen und gibt es eine Möglichkeit meine Spieler ID wieder mit den fehlenden Daten zu verbinden? Das ursprüngliche API Token habe ich noch.
