### ISSUE TITLE
Cannot bring up city planner

### ISSUE THREAD

**Issue by g15713** [mainIine/foe-helfer-extension#2919]
Cannot bring up city planner

**Comment by g15713** [comment]
email: [g15713@yahoo.com](mailto:g15713@yahoo.com)
Player ID: 852230995
Guild: 1271
World: us25

**Comment by chrisdiy** [comment]
same here Cannot bring up city planner everything else OK including APi token etc.

**Comment by chrisdiy** [comment]
Having to use 
https://foe-city-builder.web.app/#/ instead (more complicated)

**Comment by mainIine** [comment]
U cannot send data to the website?

**Comment by bakkouz** [comment]
> U cannot send data to the website?

city planner just brings up a blank page. nothing shows up on the website.

**Comment by mainIine** [comment]
This is an security check. If the page is blank, a world selection is missing.

**Comment by chrisdiy** [comment]
Tried with different worlds selected still get  a blank page

**Comment by arcadius1487** [comment]
Same problem here.

**Comment by Gerechto62** [comment]
Das gleiche Problem hier. 2 Server beide zeigen weiße Seite.
Alles andere funktioniert. Nur der Stadtplaner trotz richtiger Token und Welt Nummer

**Comment by Mowglik** [comment]
same problem here; last week all was OK...

**Comment by Mowglik** [comment]
Could the site managers or designers please answer?

**Comment by Gerechto62** [comment]
Gibt es eine Lösung das man den Stadtplaner endlich wieder verwenden kann ?

**Comment by Gerlinde18** [comment]
Unfortunately I am having the same issue. I am using Firefox.

**Comment by LordJinx** [comment]
> This is an security check. If the page is blank, a world selection is missing.

I did check all possible world selection, even submit data all over again.. still blank

**Comment by mainIine** [comment]
Pls try it again.

**Comment by g15713** [comment]
City Planner working again !!

**Comment by Mowglik** [comment]
big thank you!

**Comment by Gerlinde18** [comment]
Thank you very much! It's working again.

**Comment by chrisdiy** [comment]
working again but all previous data gone.

**Comment by arcadius1487** [comment]
Thank you.
