### ISSUE TITLE
Warning: Undefined array key 1 in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/32e8f97d9014f3500921e1b26565b58f299c990b_0.file.profile.tpl.php on line 98

### ISSUE THREAD

**Issue by Nadine0815** [mainIine/foe-helfer-extension#2921]
Leider kann ich nicht mehr mit dem Stadtplaner arbeiten.
Ich hab schon diverse neue (nicht vorhandene) Welten hinzugefügt. Das hat es leider nicht besser gemacht :-(
Besteht die Möglichkeit, den Account komplett zu löschen?
Spieler ID ist 849054519, ich spiele auf DE5 und DE7.

Das Abschicken der Daten in der Erweiterung klappt einwandfrei, aber beim Login auf der Helper-Seite kann ich weder eine Welt auswählen, noch zeigt er mir die gesendeten Stadtdaten an.

**Comment by mainIine** [comment]
Warum fügt man Welten hinzu die nicht existieren? Klar das dann Fehler kommen.

Überflüssige Welten können auch wieder entfernt werden.
Ich habe das mal für dich gemacht.

Schau bitte noch mal rein.

**Comment by Nadine0815** [comment]
Gute Frage 🙈
Vielen Dank, geht wieder🥰
