### ISSUE TITLE
Warning: Undefined array

### ISSUE THREAD

**Issue by Vladka1717** [mainIine/foe-helfer-extension#2922]
Hello!
Problem only in ru16 world. No way to delete token and generate new one. Plz fix if possible
id: 852347562
login: vladimir1707 (dog) inbox (dot) ru

Warning: Undefined array key "ru16" in /usr/www/users/foecre/foe-helper.com/cache/smarty/templates_c/32e8f97d9014f3500921e1b26565b58f299c990b_0.file.profile.tpl.php on line 98

**Comment by mainIine** [comment]
I dont know the name from world ru16. 
Can you send me?

**Comment by Vladka1717** [comment]
in Russian will be Кунрир
Kunrir or Kunreer mb

**Comment by mainIine** [comment]
Ok, thanks. I added the world to my list.

Pls try again.

**Comment by Vladka1717** [comment]
Now work correctry. Thanks!!!
