### ISSUE TITLE
Moving Alerts exception button to Alerts menu

### ISSUE THREAD

**Issue by FoE-Budha** [mainIine/foe-helfer-extension#2927]
Currently "Do not create alerts for selected buildings" button is positioned in the settings menu. It would feel more user friendly if it would be located in regular "Alerts" menu.   

![image](https://github.com/user-attachments/assets/87a634c6-51ad-4b21-a25c-84cdc430f88d)

**Comment by Beelzebob6666** [comment]
Personally I feel it is a different feature, as it is about automatically created alerts. The alerts module feature is only for
