### ISSUE TITLE
Unable to add cities to profile

### ISSUE THREAD

**Issue by hippityhyp** [mainIine/foe-helfer-extension#2930]
Was getting API-token error when trying to use city planner and notes. Have tried the solution here about using the "https://foe-helper.com/user/profile?remove=" + world. This did remove the cities from my profile but I'm not able to add them back now. It's defaulting to "de"... there's no way for me to change this or even type "en". I'm on EN8. 

![2024-09-07_12-58-34](https://github.com/user-attachments/assets/35deaeaf-b939-4ce1-bd22-9455e1b2af8c)

**Comment by tntturtl** [comment]
I can confirm that adding new cities to city planner does not work.

**Comment by Dimwitted1** [comment]
Same here, Still getting all kind of "Array Erros" Wrong API token etc. etc.
