### ISSUE TITLE
Inventory sorted by x/y size

### ISSUE THREAD

**Issue by G-Bigo** [mainIine/foe-helfer-extension#2935]
For the reconstruction of the city, it would be helpful if there was a list of the existing buildings that could be sorted according to their x and y dimensions.

The two sorting options should logically be:
First x, then y.
First y, then x.

**Comment by Beelzebob6666** [comment]
For the website or the extension?

**Comment by G-Bigo** [comment]
For the helper extension. Export option would be great.

I don't believe Inno will implement this anytime in the future as a standard feature.
