### ISSUE TITLE
Icons missing in negotiation helper

### ISSUE THREAD

**Issue by erik-1772** [mainIine/foe-helfer-extension#3054]
quando utilizza auto negoziazione dell'app foe-helper sul pc questa non mostra più i beni per effettuare la negoziazione ma solo degli spazi vuoti allego immagine da foto scattata dal cellulare

![20241001_144734](https://github.com/user-attachments/assets/1e8de51a-7740-4f55-957e-35f3d063d14f)

potete risolvere il problema

**Comment by Beelzebob6666** [comment]
you probably need to clear browser cache (CTRL+F5 when on foe)

**Comment by erik-1772** [comment]
salve ho fatto come suggerito ma il problema persiste potrebbe essere dovuto al vostro ultimo aggiornamento delle funzioni dell'applicazione visto che oltre a ciò compaiono dei rettangoli nelle schermate di al postò delle vocali accentate è-à-ì etc compaiono i rettangoli?

**Comment by Beelzebob6666** [comment]
could you please check how the research overview looks?

The negotiation module was not really touched in the update, only goods images were added.

Not sure what you are talking about in regards to accents.

**Comment by erik-1772** [comment]
la panoramica della ricerca è come sempre, si vede tutto e chiaro, per
quanto riguarda il modulo negoziazione ho fatto l'accesso su altri due pc e
c'è sempre lo stesso problema come nella foto che vi avevo allegato in
precedenza

Il giorno mer 2 ott 2024 alle ore 13:53 Beelzebob6666 <
***@***.***> ha scritto:

**Comment by Beelzebob6666** [comment]
is there any error message in the console (F12)? if so, make a screenshot
are you using any other extensions? if so, deactivate them

**Comment by Beelzebob6666** [comment]
also please write in english, google translate is not really friendly

**Comment by erik-1772** [comment]
unfortunately I can't write in English, and no there are no other
extensions I use google translate sorry

Il giorno mer 2 ott 2024 alle ore 16:21 Beelzebob6666 <
***@***.***> ha scritto:

**Comment by Beelzebob6666** [comment]
please try reinstalling the extension

**Comment by erik-1772** [comment]
hi, as you can see in the screenshot I attach I did not find any writing ::before, I opened all the nodes with the black arrows but that writing was not there, now I have a doubt I have a PC with Windows 8 that cannot be updated to any later version, could this create a problem?

kind regards erik17
![nodo negoziazione](https://github.com/user-attachments/assets/6bccb358-e413-449b-9324-f40133e140cd)

**Comment by BoboGargle** [comment]
I get this, also cannot see any ::before parameter
![Uploading foe.png…]()

**Comment by BoboGargle** [comment]
I get this, also cannot see any ::before parameter
![foe](https://github.com/user-attachments/assets/36c4abae-52bd-4ef0-b024-f460bb0ac4e6)

**Comment by BoboGargle** [comment]
![foe2](https://github.com/user-attachments/assets/ff1c4603-9637-4bac-a549-7cad34b2682d)

**Comment by Beelzebob6666** [comment]
my guess is you are running a very outdated chrome version - please update

**Comment by BoboGargle** [comment]
I'm running Opera 85 on Windows 7, which might stymie any attempts to get later versions, I will have to see what the situation is. Meanwhile, I've just gone back to v3.7.

Thanks for looking into it.

**Comment by Beelzebob6666** [comment]
Opera is on version 115 currently - for the extension to work properly you likely would want at least V106

**Comment by erik-1772** [comment]
hello I understood where the problem comes from, I bought a new pc with windows 10 and everything is fine there you can see the icons for the negotiations, the old pc on which I played is with windows 8 and chrome that can no longer be updated and this is what the problem is due to, thanks for the understanding I had from you in these days

kind regards erik17

**Comment by Beelzebob6666** [comment]
Firefox seems to still be supported for Win8 or even Win7 btw.

**Comment by BoboGargle** [comment]
Next question: Is it possible to stop it auto-updating?

**Comment by Beelzebob6666** [comment]
you can download a specific version from github and manually install it in chrome extensions - this will never update
alternatively, just live with the icons not showing up and rely on the number key indicators to type in the goods

**Comment by erik-1772** [comment]
I solved it by switching to a PC with Win10 and this problem does not exist, thank you very much

you can close the intervention

**Comment by BoboGargle** [comment]
Ha, turns out using the number values and keyboard is much simpler and easier than using the mouse. Four years of needless clicking!
