### ISSUE TITLE
Boosts for wishing wells

### ISSUE THREAD

**Issue by Goku702** [mainIine/foe-helfer-extension#3057]
Hello,

In the production overview again, the wishing wells (as well as fontain of youth) takes the % supply boost in consideration while in the game, it is unafected by this boost. So the supply production number is false.

Thanks for your help, and your great addon.

Edit : Not 2 but 1 problem. The other was my mistake.

**Comment by BoboGargle** [comment]
Also, the icons in the negotiation dialogue have disappeared

**Comment by Beelzebob6666** [comment]
1) random production results are still provided:
![image](https://github.com/user-attachments/assets/7f3c9d92-bc87-4cae-bdf5-956701b12a46)
the building has to be motivated though - and had to be in the previous version as well !!!

2) should be considered a bug - maybe @outoftheline can take a look

3) negotiation icons are not showing for some other players as well - there are no hints yet as to why that happens

**Comment by Goku702** [comment]
OMG you're right. My apologies. I'll edit my first message to leave just the supplies bug.

**Comment by Beelzebob6666** [comment]
@BoboGargle 

please refer to this #3054
