### ISSUE TITLE
GB Calculator Addition

### ISSUE THREAD

**Issue by MonkoBro** [mainIine/foe-helfer-extension#3058]
New to GitHub so please forgive me if this is the wrong way to submit ideas.  Wanted to ask if FOE Helper could add buttons for 92%, 95%, 97% and 100% to the GB Calculator and GB Cost Calculator like you have 80%, 85% and 90%.  Many players have Arcs leveled past 80 and it would make an already good extension even better.

**Comment by Beelzebob6666** [comment]
you already can do that - just click the cog wheel in the top bar
