### ISSUE TITLE
Einstellungen werden in MS Edge nicht gespeichert

### ISSUE THREAD

**Issue by ihavenonick** [mainIine/foe-helfer-extension#3059]
Bei jedem Neustart des Spiel, sind die Einstellungen des Helper wieder auf default. Was kann ich dagegen tun?

**Comment by Beelzebob6666** [comment]
nicht den Inkognito Modus benutzen oder andere Einstellungen/Tools deaktivieren, die regelmäßig lokale Daten löschen.

**Comment by ihavenonick** [comment]
Inkognito Modus wäre ein privates Fenster und das nutze ich nicht, bin aber für jeden weiteren Vorschlag dankbar.

**Comment by Beelzebob6666** [comment]
Wir können nicht raten - das was ich dir geschrieben habe sind die wahrscheinlichsten Ursachen - das einzige was noch sein könnte, ist dass du zu wenig Festplattenspeicher übrig hast und der Browser selbständig lokale Daten löscht.
