### ISSUE TITLE
Produktionsübersicht

### ISSUE THREAD

**Issue by Alex72-foe** [mainIine/foe-helfer-extension#3060]
Hallo, ich hätte gerne in der Produktionsübersicht bei den Gütern den oberen Teil mit den Summen der einzelnen Güter der einzelnen ZA zurück. Das fand ich eine prima Sache.
Danke und LG
Alex

**Comment by Beelzebob6666** [comment]
Im Tabellenkopf werden doch die Summen angezeigt:
![image](https://github.com/user-attachments/assets/e782dd28-5cb0-4aaa-9432-0315e2b63c1b)
die sind nur nicht mehr nach Gut aufgeschlüsselt - da die aber sowieso fast immer zufällig sind (wenn nicht gerade ein Gütergebäude verwendet wird) hat dies für uns keinen Sinn mehr ergeben

**Comment by outoftheline** [comment]
die summen hab ich nachträglich eingefügt, das is noch nicht live :D
