### ISSUE TITLE
Production overview

### ISSUE THREAD

**Issue by Moto57** [mainIine/foe-helfer-extension#3061]
Production overview  completion column empty
Version 3.8.0.0

**Comment by Beelzebob6666** [comment]
the column will be merged with the "finished at" column in the next version

**Comment by Moto57** [comment]
Hi,

you just show completion time, no "completed" in green. The old version was
much more convenient and user friendly.

Best regards, Moto

Am Fr., 25. Okt. 2024 um 08:01 Uhr schrieb Yvi ***@***.***>:

**Comment by outoftheline** [comment]
you might want to wait for the update, but this is done now:
![image](https://github.com/user-attachments/assets/015cc99a-5443-48d9-bea3-a369af7565fb)
