### ISSUE TITLE
Fehler im User-Account, Stadtplaner kann nicht genutzt werden

### ISSUE THREAD

**Issue by SchwarzeWitwe77** [mainIine/foe-helfer-extension#3064]
Wenn ich mich auf der Helper-Seite einlogge, werde ich zuerst aufgefordert, in meinen Profil  eine Welt anzulegen "Add a new world to your player-Id"
Wähle ich dann die de15 aus (Hauptwelt), kommt folgende Meldung: "You have already registered this world number"

Wähle ich den Stadtplaner aus, kriege ich folgende Fehlermeldung: Fatal error: Uncaught Error: Typed property citymap::$players_citydata must not be accessed before initialization in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php:254 Stack trace: #0 /usr/www/users/foecre/foe-helper.com/core/modul/citymap/pages/overview.php(87): citymap->GetCityEntities() #1 /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php(122): include('/usr/www/users/...') #2 /usr/www/users/foecre/foe-helper.com/core/classes/class.layout.php(346): citymap->getTPL() #3 /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php(56): layout->__construct() #4 /usr/www/users/foecre/foe-helper.com/index.php(50): citymap->__construct() #5 {main} thrown in /usr/www/users/foecre/foe-helper.com/core/modul/citymap/citymap.php on line 254

Logge ich mich aus, kommt eine lange Liste von Meldungen, angefangen mit:
Warning: Undefined array key "player_id" in /usr/www/users/foecre/foe-helper.com/core/modul/logout/pages/index.php on line 19

Im Spiel ist mein API-Token weg. Ich kann nicht genau sagen, seit wann das Problem besteht, weil ich den Stadtplaner einige Monate nicht genutzt habe, davor hat aber alles reibungslos und regelmäßig funktioniert. Kann man den User einfach löschen und ich registriere mich neu? Mein Spieler-ID

Version 3.8.0.0
Spieler Id: 4495836
Gilden Id: 2730
Welt: de15

**Comment by cs37sc** [comment]
Ich habe das gleiche Problem. Habe mich heute registriert um den Stadtplaner zu probieren, kann aber nicht die Stadt verknüpfen. Es kommt immer die Meldung dass die Stadt schon verknüpft ist mit den anderen Fehlermeldungen

**Comment by cs37sc** [comment]
Zusatz: ich habe jetzt in einem anderen Post eine Lösung gefunden. Stadt im foe-helper entfernen und nochmal neu einbinden:

add your world shortcode to the end, e.g. de3
full url is https://foe-helper.com/user/profile?remove=de3 in this example

**Comment by SchwarzeWitwe77** [comment]
Das hat funktioniert, vielen Dank
