### ISSUE TITLE
Negotiation assistant: pictures of goods are no more shown

### ISSUE THREAD

**Issue by Thergana** [mainIine/foe-helfer-extension#3069]
![Bug_Verhandlungsassistent](https://github.com/user-attachments/assets/1c67908e-07dc-4588-8046-706c7641c0cb)

Since today, the pictures has been lost at the negotiation window in FoE Helper Addon. See screenshot.

I use Firefox 115.16.1esr (64-Bit) as browser (latest update: today installed) in combination with addon FoE Helper (latest update: today installed).

Closing and new start of browser didnt help to fix it.

If you need more info, pls dont hesitate to ask.

**Comment by outoftheline** [comment]
you'll need at least firefox 117, because we'll be switching to more modern technologies in the future and more issues like this will arise eventually.

(for reference)
https://caniuse.com/?search=css%20nesting

**Comment by RoboReCop** [comment]
I've seen the same issues. I updated my Firefox 116... but couldn't fix the problem. It feels like in a few months, I'll have to buy a new computer to just access the internet.

**Comment by RoboReCop** [comment]
> you'll need at least firefox 117, because we'll be switching to more modern technologies in the future and more issues like this will arise eventually.
> 
> (for reference) https://caniuse.com/?search=css%20nesting

Do you, or anyone else, know of a browser that is compatible that we may use? I'm currently running a MacPro 11.13.6; Most browsers have started to "upgrade", however, they are incompatible with my older machine.

**Comment by Beelzebob6666** [comment]
I thought that (almost) every mac machine can update to the latest OS version? That should also fix the issue with browsers not supporting your outdated OS

**Comment by Beelzebob6666** [comment]
you could just live with the icon not showing - and just use the number indicators to type in the needed good

**Comment by Beelzebob6666** [comment]
also: #3054
