### ISSUE TITLE
Castle system doesn't show any information

### ISSUE THREAD

**Issue by LeMyst** [mainIine/foe-helfer-extension#3070]
Hello,

The Castle system ("Système de château" in French) doesn't show any information:

![image](https://github.com/user-attachments/assets/a09614b4-e5aa-4025-8ae2-a671d1148bfc)

BR,

M

**Comment by Beelzebob6666** [comment]
Inno changed, how certain data is transmitted... a workaround is needed.

**Comment by Beelzebob6666** [comment]
Thanks for the report - will be fixed in the next version
