### ISSUE TITLE
FoE Helper Notes - resize

### ISSUE THREAD

**Issue by rbrucemccarthy** [mainIine/foe-helfer-extension#3072]
I am unable to resize the Notes window since the bottom is lower than the bottom edge of my screen. Would it be possible to have the top and left to be resizable? Thanks in advance.
![notes too large](https://github.com/user-attachments/assets/a3545757-52b5-4d2b-8ded-99b0af640cc8)

**Comment by outoftheline** [comment]
zoom out, grab the window, zoom back in
