### ISSUE TITLE
Disparition infos système chateau

### ISSUE THREAD

**Issue by Cinnamon84** [mainIine/foe-helfer-extension#3074]
Bonjour,
Avant, le système de château était très pratique. En un coup d'œil, on savait si on avait fait nos 15 négos et combats, si on avait récolté le château et si la quête du jour était validée.
Vos nouvelles infos ne sont pas pratiques du tout et ne donnent pas envie d'y aller
Merci de remettre l'ancienne version
Cordialement

**Comment by outoftheline** [comment]
We did not change anything with the castle system, InnoGames did. Next update will fix that.
