### ISSUE TITLE
Goods Icons are missing in GE

### ISSUE THREAD

**Issue by kimzonline** [mainIine/foe-helfer-extension#3080]
Hi
The goods icons in FOE Guild Expedition (GE) have been missing for about a week

I play on FireFox. and all updates are up to date.
Have windows 11
and everything ran perfectly until abt a week or so ago.

**There was a microsoft update last week -not sure if that broke the extension or not.**

I cleared my cache
I deleted the extension and ReInstalled it

I then REcleared my cache
I closed my browser 
REopened my browser and IT still does not work

![Screenshot (1676)](https://github.com/user-attachments/assets/9032f526-1a3f-4a46-b663-b113dcc1502b)

**Comment by ouvea-83** [comment]
hello
i have the same problem

**Comment by ouvea-83** [comment]
but under windows 7
and
firefox

**Comment by kimzonline** [comment]
Here is a screenshot of my firefox browser
115.16.1esr

![Screenshot (1679)](https://github.com/user-attachments/assets/c9e4c8e8-f2dd-4b72-9d27-3721fe03014b)

**Comment by Beelzebob6666** [comment]
and here is a link to the [official release website](https://www.mozilla.org/en-US/firefox/releases/) - the latest release is version 131

as is stated in your screenshot you are using the "esr update channel"
![image](https://github.com/user-attachments/assets/0f04c436-2a4f-4abe-9462-8b354e29ffff)

It should only be used on machines with outdated OS - like Win7, no clue why you (@kimzonline) have it installed in the first place - did you maybe migrate to win11 from win7 recently (not sure that is even possible)?

**Comment by KingKlutz** [comment]
I still use windows 7 with Chrome and mine is missing also :(
I love the way things get updated to force you to buy new tec to help keep the rich richer and you poor. That way you have to work your life away and do not have time to see that you are just a mouse stuck on a wheel.

**Comment by Beelzebob6666** [comment]
Pretty sure the upgrade to win 10 was/is free for users of win 7 at least for some time when it just was released

**Comment by ouvea-83** [comment]
hello, indeed I am poor, if you come back for this option as before the
update as it seems to me that you said it works. no the update to go to W10
is not free, and I am 71 years old, and going to W10 is not too complicated
for me, and I think I am not the only one in this case. sorry for my
English, but I go through google translator. have a good day

Le mar. 22 oct. 2024 à 15:05, Beelzebob6666 ***@***.***> a
écrit :
