### ISSUE TITLE
next GM suggestion : empty panel

### ISSUE THREAD

**Issue by Pekiglou** [mainIine/foe-helfer-extension#3082]
Hello,
First, excuse me if the problem has already been described. I looked at the previous questions, but my translation is a bit laborious and I may have missed the topic!

So, since (I think) the last update, the "next GM suggestion" panel does not give any information anymore (empty panel of text).
Do you know the problem and do you know if it should be fixed?

**Comment by Beelzebob6666** [comment]
#2984
