### ISSUE TITLE
Since Space Hub update can't see the goods by Guild Expedition

### ISSUE THREAD

**Issue by zarsys** [mainIine/foe-helfer-extension#3084]
Everything else work fine.
Windows 8.1 Pro, Firefox 115.16 (last update)

![Firefox_Screenshot_2024-10-17T17-49-03 408Z](https://github.com/user-attachments/assets/5ba6bb11-3efd-43bd-b17f-dad559ec729d)

**Comment by Beelzebob6666** [comment]
See #3054
