### ISSUE TITLE
Update for Fellowship event idle game

### ISSUE THREAD

**Issue by valimaties** [mainIine/foe-helfer-extension#3087]
Now, it's about to finnish, but for the next fellowship event you must made some updates:

![image](https://github.com/user-attachments/assets/d97bbd67-efa9-47b7-b7a9-ef6e6c2d3875)

Using those stones it reduce the costs for next town to 50%, so that 6.3Q must be 4.2Q

**Comment by outoftheline** [comment]
next update will use game data, so this will hopefully never be a problem again.
