### ISSUE TITLE
Production overview is blank

### ISSUE THREAD

**Issue by FGk24** [mainIine/foe-helfer-extension#3089]
I play on 6 worlds in the international server.
Only on 1 of the 6 worlds is there something populating in the production overview - the other 5 show blank overview screens.
I have tried this on Edge and Chrome with a newly installed extension - the result is the same.

Is there something that needs to be reset, or cleared - or is this being fixed in next update?

**Comment by recordfair** [comment]
Yes same problem here production overview page blank

**Comment by outoftheline** [comment]
we do not know what might be causing this. can you think of any building you recently built?

**Comment by FGk24** [comment]
I have been trying to think what it could be. but nothing seems consistent - royal shroom throne was a suspect - but one of the towns where it doesnt work doesnt have one of those

how do i obtain the error message from the console?

**Comment by FGk24** [comment]
figured out how to find the console error:

merged-3rd-party-109b844c.js:16  TypeError: Cannot read properties of undefined (reading 'clan_power')
    at productions.js?v=3.8.0.0:218:32
    at Array.forEach (<anonymous>)
    at productions.js?v=3.8.0.0:214:25
    at Array.forEach (<anonymous>)
    at Object.CalcBody (productions.js?v=3.8.0.0:198:28)
    at Object.showBox (productions.js?v=3.8.0.0:181:15)
    at Object.ReadData (productions.js?v=3.8.0.0:155:15)
    at Object.init (productions.js?v=3.8.0.0:122:15)
    at HTMLSpanElement.<anonymous> (_menu.js?v=3.8.0.0:426:16)
    at HTMLSpanElement.dispatch (merged-3rd-party-109b844c.js:3:43064)
    at v.handle (merged-3rd-party-109b844c.js:3:41048)

**Comment by outoftheline** [comment]
thank you. i found and - hopefully - fixed the issue. it was caused by the game update that happened yesterday on the EN servers. all other servers will break tomorrow :D fuuuun.

we will update the extention as soon as we can.

**Comment by outoftheline** [comment]
by the way: the culprit is the sleigh builder. inno changed it to prepare for winter event, where it will get an upgrade. 
if you don't need sleigh builders right now, you could store them until our update happened.
