### ISSUE TITLE
Guild Expedition - Limited Reward notification

### ISSUE THREAD

**Issue by SirWesleyofSnipes** [mainIine/foe-helfer-extension#3098]
Hi, playing through GE and have noticed that the reward notification in some cases does not reveal the awarded reward; the system indicates that you have won a reward, but it is non-specific, it does not tell you which reward from those available. please advise.

**Comment by outoftheline** [comment]
this is a game change, not sure what it has to do with foe helper? is the reward not tracked in the statistics?
you can see what you received by clicking the box just like with city collection
![image](https://github.com/user-attachments/assets/91eef49a-dac2-49e4-8caf-a9780f44d080)

**Comment by SirWesleyofSnipes** [comment]
Hi Yvi

Actually, I believe you are right in that this looks like a game change and, therefore, should be an INNO query. 

Thanks for coming back to me.

regards

SirWesleyofSnipes
