### ISSUE TITLE
Favoritenliste? / Notizfeld

### ISSUE THREAD

**Issue by Selene443Foe** [mainIine/foe-helfer-extension#31]
Hallo,

hatte ich schon mal erwähnt das ich dieses kleine, wundervolle Helferlein liebe? 
Ein absoluter Traum!

Ich hab nun noch eine Idee was toll wäre:
Kann man vielleicht sowas wie eine Favoritenliste für Nachbarn oder Freunde einfügen?
Am besten mit einem Notizfeld dazu?
Sodass man sich zu den entsprechenden Spielern Notizen zu deren oder den eigenen Aktionen machen kann.
Am liebsten würde ich die komplette originale untere Leiste neu gestalten mit den entsprechenden Optionen. So dass man die Spieler in Gruppen (Favoriten) sortieren kann.

Schön wäre auch eine Historienanzeige wen man wann oder wie oft wie oft angegriffen hat und am besten noch mit welchem Erfolg.
Und auch eine History bei wem man wann in welches LB mit welchem Verlust oder Gewinn investiert hat. 
Dies beides wiederum würde dann ausschlaggebend für die Einsortierung der Favoriten sein :)

**Comment by Selene443Foe** [comment]
... ach noch was vergessen...
idealerweise hier gleich noch die Moppelauswertung mit einfügen. 
Also so, dass man in dieser Ansicht die Aktivitäten des anderen noch sehen kann - was dann wieder Ausschlag für Angriff, Ausbeutung oder Schonung gibt und damit wieder ein Faktor für die Einsortierung in der Favoritenreihenfolge :)

**Comment by JHCD** [comment]
Die Regeln von Inno erlauben keinen Eingriff ins Spielgeschehen. 
In weit die Veränderung der GUI erlaubt wäre, ist fraglich. Historische Daten mit aktuellen Daten zu mischen ist auf jeden eine Veränderung der angezeigten Daten und in dem Fall verboten.

**Comment by Selene443Foe** [comment]
Hi, das ist freilich etwas "unschön"...
Könnte man denn auf der Webseite sowas einrichten? Dahin werden die Daten ja eh transferiert. Vielleicht kann man dort sowas stricken?
Das wäre dann nicht ganz so komfortabel, aber immernoch besser als die (meine) derzeitige Zettelvariante... 
Oder darf man das dort auch nicht?

**Comment by JHCD** [comment]
Für die HP sind mir keine entsprechenden  Einschränkungen bekannt.
