### ISSUE TITLE
Error Occured: this is not the correct api-token. 

### ISSUE THREAD

**Issue by Arsura-Havenglow** [mainIine/foe-helfer-extension#3104]
I'm trying to get an api token to send my city data to the planner, but no matter what token I use it always says it's not the correct one.
I've tried deleting the world on the website and add it again but it does not work.

**Comment by Arsura-Havenglow** [comment]
Delete these 2 accounts on the website please, I will make new one and try...

petru.d.dumi@gmail.com
pddnobel@gmail.com

I've realized where the issue was probably with old account using an old player id... idk please help delete the account I'll try make new one

**Comment by Arsura-Havenglow** [comment]
Is there any update?

**Comment by Arsura-Havenglow** [comment]
It cannot be that hard to delete an account

**Comment by LeniRoCZ** [comment]
Hi, I want to try the city planner. I entered the token into the helper according to the instructions, but when I click on the planner in the helper and confirm sending the data, it tells me this: This is not the correct api-token!. I copied the token from the profile 100% correctly. How do I solve this?
