### ISSUE TITLE
production overview still now working despite clearing cache

### ISSUE THREAD

**Issue by Nursie777** [mainIine/foe-helfer-extension#3106]
production overview still now working despite clearing cache

**Comment by outoftheline** [comment]
what version are you using? you need 3.8.1.0

**Comment by Nursie777** [comment]
yes downloaded the new version from chrome store. unsure how to check that it is the correct version tho.

**Comment by Nursie777** [comment]
actually its not production overview its the building efficiency results rating button that does not work

**Comment by outoftheline** [comment]
same issue like this then #3097
