### ISSUE TITLE
Bug about translation in Italy

### ISSUE THREAD

**Issue by GiuseppeTalpa** [mainIine/foe-helfer-extension#3108]
Into file js\web\_i18n\it.json 
the String 
"Boxes.Infobox.Messages.LevelUp": 
has an error.
The macro __building__ was traslated into __costruzione__
The macro should be not converted. 
The result of this bug is the show __costruzione__ instead of the correct build.

Thanks for your job anyway.
Best regards
Giuseppe

**Comment by outoftheline** [comment]
translations can be managed by anyone willing to help here: http://i18n.foe-helper.com/
feel free to change it
