### ISSUE TITLE
Show ascendeable buildings

### ISSUE THREAD

**Issue by varazir** [mainIine/foe-helfer-extension#3119]
Hello, 
I would like to be able to show buildings that can be activated or are inactive in the city overview. 
Or in some other fashion. 

![image](https://github.com/user-attachments/assets/1e491783-611c-487a-9e95-b57fa835ca32)

Something like this 
![image](https://github.com/user-attachments/assets/1ed8cdca-e066-4a60-85d7-199ef49a9c70)

**Comment by outoftheline** [comment]
![image](https://github.com/user-attachments/assets/3818beeb-f8bf-498d-a6df-368240c13202)

**Comment by varazir** [comment]
Cool
