### ISSUE TITLE
Possible account ban 

### ISSUE THREAD

**Issue by SANSKARI1310** [mainIine/foe-helfer-extension#3127]
Hey devs, i recently got a warning regarding usage of a prohibited software and as far as my knowledge i am not using anything else apart from foe-helper extension on chrome downloaded the chrome web extension store. Currently its just a 1d ban asking me to stop using the prohibited software/ script.
I am planning to stop using my browser to avoid this kind of situation but would like if u can check if that error is getting caused due to the extension or not.

**Comment by SANSKARI1310** [comment]
![Screenshot from 2024-12-04 09-33-09](https://github.com/user-attachments/assets/4cf616dc-28fb-4b40-a3c0-99dd03ebe3b8)
heres what the devs replied

**Comment by outoftheline** [comment]
we'd have more reports on this, if this were true. 
we'd also be warned beforehand. none of this has happened, so you might have had something else installed at some point.
another possibility might be: you gave your account to someone to rebuild your city or sth and they had something against the game rules installed on their browser.

**Comment by SANSKARI1310** [comment]
I haven't shared the account with anyone else so it might just be a fault from my end , i will re install the browser and try it again , thx for the reply that helps a lot.
