### ISSUE TITLE
Chrome Crashes with foe helper

### ISSUE THREAD

**Issue by Connan1962** [mainIine/foe-helfer-extension#3134]
Hi, my chrome crashes / freezes with FOE,   using Helper.

Can you help? enclosed image.. 

Any version for Edge? of Foehelper?

![Screenshot_1](https://github.com/user-attachments/assets/66866f6e-0334-4dfb-ba75-956c91ed2923)
![Screenshot_1](https://github.com/user-attachments/assets/67b46ee6-eec7-44eb-97e8-ec435ceb10c9)

**Comment by Beelzebob6666** [comment]
This is a memory overflow issue that also happens without the helper present afaik.

In edge you can just install the helper from the chrome webstore - as edge also is chromium based, I doubt that will change anything though.
