### ISSUE TITLE
Alarms are emptied and no one can be added

### ISSUE THREAD

**Issue by andihome** [mainIine/foe-helfer-extension#3143]
From Yesterday on, the Alarmlist is empty.
No new Alarms can be added.

I'm using WIN11 & WIN10 (three Computers) with Chrome Version 131.0.6778.205 (Offizieller Build) (64-Bit)
I tried to use FF, but there is the same phenomenon with FOE-Helper.

Is there a known workaround to run alarms?

**Comment by Beelzebob6666** [comment]
#3140
