### ISSUE TITLE
Alarm Pop-Up funktioniert nicht mehr

### ISSUE THREAD

**Issue by crossi69** [mainIine/foe-helfer-extension#3148]
Schönen guten Tag!
Seit dem letztem Updated funktionieren die Alarme bei mir nicht mehr. 
Ich habe bereits die Einstellungen im Browser sowie den API-Token überprüft.
Auszug aus der Entwickler Konsole:

Uncaught (in promise) Error: invalid response from Extension-API call
    at Object.sendExtMessage (_main.js:1050:10)
sendExtMessage @ _main.js:1050
await in sendExtMessage (async)
preview @ alerts.js?v=3.10.0.1:278
preview @ alerts.js?v=3.10.0.1:1092
(anonymous) @ alerts.js?v=3.10.0.1:892
Promise.then (async)
(anonymous) @ alerts.js?v=3.10.0.1:889
dispatch @ merged-3rd-party-109b844c.js:3
v.handle @ merged-3rd-party-109b844c.js:3

**Comment by outoftheline** [comment]
#3140
