### ISSUE TITLE
Güter der Gex tracken und ausgeben

### ISSUE THREAD

**Issue by mainIine** [mainIine/foe-helfer-extension#381]
In einer laufenden Gex soll ermittelt werden welches Gut gewählt und wie viel davon in jeder Verhandlung genutzt wurde.

Das kann jeder Zeit in einer Box ausgegeben werden.

**Comment by Arminius52** [comment]
Es wären sicher nicht nur die Güter interessant, auch bei Kämpfen sollten die verlorenen Truppen angezeigt und in Vergleich zu den in Kasernen und vom Alcatraz produzierten gezeigt werden um den Bestand seiner Truppen überwachen zu können und rechtzeitig aufhören sie zu verbraten...
