### ISSUE TITLE
City Overview of other players

### ISSUE THREAD

**Issue by kronikpillow** [mainIine/foe-helfer-extension#449]
I noticed that the Plunder helper, when you click on the eye icon opens up a players city layout and shows you his current layout and where the building is exactly ...

but the city overview, can only see your own city overview, it would be good to be able to see other players city overview as well, for example I found a sick 16 maharaja combo, and I can't see properly how it's layed out and connected, but the player is in my friends list, not in my hood, so i cant attack him to see his layout ...

or is this function already implemented and im just not noticing it?

love the project btw, I'v seen similar projects but not as close to what this project is regarding details and functions

**Comment by honza111** [comment]
and city overview for cultural settlements would be great
and also make all buildings draggable on grid
![xA3E](https://user-images.githubusercontent.com/60223602/73101112-48efc380-3eef-11ea-9b8f-38d6cab30257.png)

**Comment by honza111** [comment]
and also saving to file and loading from file would be perfect

**Comment by kronikpillow** [comment]
don't quite understand the point of making it draggable, then they would need to make it possible to apply the new layout ... maybe have a function to export it to a spreadsheet so that you can play with the design

**Comment by honza111** [comment]
makin it draggable is very easy. I have done it and i am using it. Just the 3d thing and the zoom recalcs need to be fixed.  But it doesnt matter to me. I am using just the 2d when planning changes in my city. Its really very usefull

**Comment by outoftheline** [comment]
Has been implemented
