### ISSUE TITLE
1. Trade / Market helper - 2. "Activity check"

### ISSUE THREAD

**Issue by TPSeer** [mainIine/foe-helfer-extension#485]
1 - Ability to screen trades ... there are often sneaky people who try to give bad trades, a simple 2:1 1:1 1:2 check on the trades and flag ones that aren't ? 

2 - GB Investment - it is _VERY_ easy when investing in friends/hood (mostly) to invest in cities that are inactive - I usually use scoredb.io ... so for example top guild on EN4 (Dinegu) would be https://foe.scoredb.io/EN4/Guild/5040 ... as your able to display the guild in the FP window ... could you possibly include a link to https://foe.scoredb.io/<server>/Guild/<guildID>/Activity which gives a simple preview of all guild members, and when they last did anything (green or red = active, grey = inactive)

**Comment by ljettinger** [comment]
These are great ideas, though probably need a little spit shine to make easy to use... lol.. 
👍🏼👍🏼

**Comment by fwright0408** [comment]
I love the idea of having the ability to know how recent a person was active. Nothing worse than contributing to (sniping) a hoodie's GB to only realize they aren't active.
