### ISSUE TITLE
Prestige im GvG

### ISSUE THREAD

**Issue by Barbar65** [mainIine/foe-helfer-extension#513]
Hallo,
wäre es möglich, aus dem GvG die tagesaktuellen Machtpunkte / Prestigepunkte zu erhalten bzw. anzuzeigen?

**Comment by Timee79** [comment]
Schön wäre hier auch eine Übersicht nach ZA und was sich zum Vortag so getan hat, sprich, wie viele Sektoren +/- und was diese Änderung an Prestige aus macht.
