### ISSUE TITLE
Inventarübersicht / Inventory overview

### ISSUE THREAD

**Issue by andy71** [mainIine/foe-helfer-extension#546]
Ich hätte gern eine sortier- und filterbare Übersicht des Inventars. Es wäre sehr nützlich wenn man z.B. nach Gebäuden sucht die Zufriedenheit bringen oder Eventgebäude mit Gütern aus bestimmten Zeitaltern, oder ...

**Comment by dsiekiera** [comment]
Ich hätte das gerne um Gebäude Sets + UpgradeKits auf einmal sehen zu können. Das muss man sich immer müselig zusammen suchen.

**Comment by ljettinger** [comment]
Both of these suggestions combined would be a great new feature!! Or v2.0 of an existing one...
It would fit in very nicely with the existing "Building Efficiency Rating" tool... I'm not sure what it would require to get access to the Inventory data, whether it's already there like the current Building Efficiency info, or if the user would have to prime it like the Tech Tree or Military Units overviews...
Either way, it would greatly increase the usefulness of the current "Building Efficiency Rating" tool... And it could be easily integrated into the current interface by: 

1. Adding a dropdown/toggle to filter displayed buildings with 3 options: 
   a. Option1 - by "Current City Only" (this already exists)
  b. Option2 - "Inventory Only" (this would only show buildings in inventory exactly like the current info/layout is done)
  c. Option3 - "Both Current City & Inventory"... The "Both" option would easily allow a user to benefit by seeing what 
    options are available for adding to partial or customized Building Sets as well as what Upgrades they could apply (built 
     Lvl1 buildings with Lvl2 Upgrades in Inventory)...

2. Add in a “List/Group Building Sets” option
  a. This could work like an upgraded version of the “List/Group” currently found in the “Production Overview” tool by 
     offering 3 options:
    i. “List” - Lists all the buildings individually (already exists in Production Overview)
    ii. “Group” - Groups all the individual buildings (already exists in Production Overview and Building Efficiency Rating, but 
        is done slightly different in each one)
    iii.“Connected Group Sets” - This would Group each of the currently Connected Group Sets in a nested manner like 
        Connected Group->Individual Buildings
  b. Then put columns showing age and level here

3. Add in a “Availible Updates” or “Group Updates” option
  a. When "Both Current City & Inventory" is selected, this would first group together built buildings with inventoried 
    upgrades, then inventoried buildings with inventoried upgrades

4. The displayed lists should be color coded so the user could easily tell if one item was built or in the city as well as if a 
connected group has miss matched level buildings in it

5. An option to export a the list of buildings from all three options from bullet 1 above to CSV would be useful too

  Hopefully that makes total sense, if not, let me know and I can clarify... 
thanks
