### ISSUE TITLE
Stadtübersicht

### ISSUE THREAD

**Issue by hhpc1957** [mainIine/foe-helfer-extension#559]
Ist es vielleicht möglich die Stadtübersicht auch für den Umbau Modus zu machen da wäre er sinnvoll

**Comment by andrgin** [comment]
Das Problem daran ist, dass die Extension Verschiebeoperationen nicht mitbekommt. Gerade im Umbaumodus würde dann etwas ganz anderes angezeigt werden.

**Comment by honza111** [comment]
i am using this just on the fly:
open the city overview. enable 2D mode and 100% zoom. press F12 and type this code into console:
$('#grid-outer .street').css({left: 100 + 'em'});
$('#grid-outer .entity').css({opacity: 0.8});
$('#grid-outer .entity').draggable({
  grid: [ 14.4, 14.4 ]
});  

press enter and now you can prepare some changes
i would love to have this in the cultural settlements mini towns:(
