### ISSUE TITLE
MoPo Vergleich mit der FL

### ISSUE THREAD

**Issue by spacy673** [mainIine/foe-helfer-extension#560]
Gibt es die Möglichkeit die MoPo auszulesen und mit der FL zu vergleichen?
Jeden Namen einzeln im Rathaus einzugeben um MoPo zu vergleichen und evtl. Schläfer zu kicken ist echt mühsam.

**Comment by frank42hh** [comment]
Hmmm, das ist doch so ziemlich das, wofür https://foe-rechner.de/stats/events/social-player gedacht ist... da hast du - wenn du die Ereignis-Inhalte aus dem Rathaus gescannt hast - eine riesige Liste zum auswerten.

**Comment by outoftheline** [comment]
Mit dem Moppelhelfer gibt es mittlerweile diese Möglichkeit
