### ISSUE TITLE
Timer mit Alarm für Auktionen

### ISSUE THREAD

**Issue by frank42hh** [mainIine/foe-helfer-extension#562]
Moin,

da mir das nun mehrmals passiert ist, dass ich eine interessante Auktion beim Antiquitätenhändler verpasst habe, dachte ich mir, ich schlage mal folgendes vor:

Einen Timer, ähnlich wie den für den 4. Zug aus der Taverne, der aufploppt, wenn man den Antiquitätenhändler öffnet oder alternativ einen Button in die Leiste. Optimal wäre es, wenn dieser Timer in vorgegebenen und/oder konfigurierbaren Zeitabständen (z.B. 10m, 5m, 1m) irgendwie eine visuelle und/oder akustische Benachrichtigung produzieren könnte.

**Comment by outoftheline** [comment]
Mit dem Alarm-Modul ist der Wunsch nun abgedeckt :)
