### ISSUE TITLE
Technologie calculate per age

### ISSUE THREAD

**Issue by ikdoemee** [mainIine/foe-helfer-extension#586]
In the tech section, you can see how many goods you need to complete until an age.
But if you look a few ages further it calculates the total to get there.

It would be nice if I can see two columns. One with the amount I need for that era only, and also a column total until the era you search for..

**Comment by dsiekiera** [comment]
Fehlt eigentlich nur eine weitere Spalte.

**Comment by ikdoemee** [comment]
What is the status of this?

**Comment by ikdoemee** [comment]
Hello, is there a status update?
Just wondering because this was assigned over 4 months ago

**Comment by andrgin** [comment]
No status update. I think I can remove the assignment.
To be honest I dont see a use for this column. I cant think of a situation where this information could be useful.

**Comment by ikdoemee** [comment]
It's useful because I would like to calculate per age how many goods I need.
If it's too much of a deal to write, close the request.
