### ISSUE TITLE
Kostenrechner Warnung, wenn bereits im LG eingezahlt

### ISSUE THREAD

**Issue by Mugen888** [mainIine/foe-helfer-extension#598]
Hallo,

wäre es möglich die Ansicht des Kostenrechners zu verändern, wenn man bereits einen Platz in einem LG sicher belegt hat, analog zu der Ansicht, wenn das LG nicht mit einer Straße verbunden ist?
Das wäre sicherlich sehr praktisch.
Vielen Dank,

Gruß

**Comment by andrgin** [comment]
Nur weil du bereits einen Platz belegt hastbist doch nicht sicher, dass du nicht weiter einzahlen willst. Du könntest z.B. einen Platz darüber nehmen, wenn der noch frei ist. Eventuell willst du auch kontrollieren, ob du bei Fördergruppen die vollen 90% gezahlt hast oder willst einen Freund noch etwas drauf legen.

**Comment by Mugen888** [comment]
Das wäre ja alles trotzdem weiterhin möglich, aber es wäre eine visuelle Unterstützung, die einem den Zustand des "bereits Platz sicher belegt" besser anzeigen würde.

**Comment by andrgin** [comment]
Das macht doch schon die blaue Farbe der Zeile (Platz belegt) bzw. wenn der Platz nicht sicher ist wird die Spalte Einsatz rot und zeigt dir an wieviel du einzahlen musst. Im Tooltip steht dann auch wieviel noch fehlt.
Dasselbe gibt es auch bei der "Fördern" Einsatz Spalte, wo angezeigt wird, ob man genug bzw. zu viele FP eingezahlt hat.

**Comment by Mugen888** [comment]
Genau diese blaue Farbe hat mich heute irritiert, deswegen dieser Thread.
P3 eines Gildenkollegen stand zur Förderung aus und ich wollte den Platz belegen. (Zugegebenermaßen war das noch während dem ersten Kaffee) Als ich das LG geöffnet habe, haben mich die FP für P1 abgeleuchtet und ich habe treudoof diesen Betrag eingezahlt und damit das LG ungewollt gelvlt und einige hundert FP verloren. (Natürlich könnte man das mit einem genaueren Hinschauen auch vermeiden, aber genau das sehe ich persönlich momentan als großen Vorteil des FoE-Helfers...man kann gemütlich nebenher spielen und wird dabei unterstützt)
Wenn in diesem Fall (bereits P1 belegt, bzw. allgemein bereits einen Platz belegt und ein höherer Platz kann nicht mehr belegt werden) das ganze in einer markanteren Aufmachung erschienen wäre, hätte es mich wohl vor diesem Zwischenfall behütet.
