### ISSUE TITLE
Inaktiver Freundesucher

### ISSUE THREAD

**Issue by BDRMega** [mainIine/foe-helfer-extension#605]
Inaktiver Freundesucher. Das System sollte Ihnen mitteilen, welche Freunde Sie nicht motiviert oder aufpoliert haben (Ihnen geholfen haben). Auf diese Weise kann ein Spieler einen Freund leicht wegen Inaktivität treten.

**Comment by andrgin** [comment]
Dieses Feature ist derzeit außer Betrieb, da wir gerade einige wichtige Änderungen durchführen.
