### ISSUE TITLE
Bug report Vorlage / Bug report template

### ISSUE THREAD

**Issue by Gindi4711** [mainIine/foe-helfer-extension#620]
Bitte bei bug reports folgende Informationen angeben / Please include following information in your bug reports:

Betriebssystem / Operating System
Verwendeter Browser inkl. Versionsnummer / Used Browser including version
Forge of Empires Server
Extension Version und Sprache der Extension. Falls ihr Betatester seid unbedingt dazuschreiben!!! / Extension version and language of the extension. If you are beta tester include that as well!!!
Fehler in der Konsole falls vorhanden (F12 drücken und in den Tab "Konsole" wechseln) / Errors in the console (press F12 and switch to console tab)
Sind andere Extensions installiert / Are other extensions installed?

Beispiel / Example:
Windows 10 64 Bit
Chrome 80.0.3987.122
de16 (Qunir)
2.4.2.2 - Deutsch

**Comment by Cyber-Raptor** [comment]
hi 
the new feature dont show all the kits and ups i have ...

**Comment by outoftheline** [comment]
Benutzt ja leider niemand
