### ISSUE TITLE
Vorteile Gebäude auf ein anderes ZA bringen

### ISSUE THREAD

**Issue by modGTB** [mainIine/foe-helfer-extension#634]
Ich wünsche mir eine Möglich um sehen zu können, welche Vorteile ich habe wenn ein Gebäude auf ein anderes ZA gehoben wird. zB bessere Kampfwerte oder höhere Münzproduktion.

**Comment by dsiekiera** [comment]
Die Idee ist an sich super, nur leider müsste man dann für alle Gebäude + sämtliche Zeitalter + der mögliche Status (motiviert) vorhalten. Aber so eine Liste gibt es nicht.

Wir arbeiten in sämtlichen Modulen mit den Infos die zu diesem Gebäude in der aktuellen Zeit. Und das sind schon eine ganze Menge. Mehr schickt Inno auch nicht zum Spieler.

Sorry.

**Comment by dsiekiera** [comment]
Ich habe noch mal in die Daten geschaut. Es gibt eine Liste für die Eventgebäude. Entweder hab ich die nie gesehen oder die ist neu.

Auf jeden Faoll sollte es damit gehen.

**Comment by modGTB** [comment]
Top !
