### ISSUE TITLE
Freunde/Gildenmitglieder nach Zeitalter auflisten

### ISSUE THREAD

**Issue by mordillo666** [mainIine/foe-helfer-extension#646]
Moije :-)

Ich habe seit Kurzem einen Dynamischen Turm in meiner Stadt und stand jetzt vor dem Problem die Spieler in meiner Liste nach Zeitaltern aufzulisten.
 Ich habe keine andere Möglichkeit gefunden als in jede Stadt zu gehen und nach dem Rathaus zu suchen...

Wäre es möglich die Zeitalter der Spieler in meinen Listen auszulesen und tabellarisch darzustellen?

Gruß Mordillo666

**Comment by Th3C0D3R** [comment]
Der Dynamische Turm gibt die ein Gut von dem Gebäude das du motivierst/pollierst. Es hat nichts mit dem Zeitalter des Spielers zu tun (hab selbst ein Turm) also musst du sogar selbstständig ein gebäude suchen und das polieren.

**Comment by andrgin** [comment]
Das ZA eines Spielers wird meines Wissens nicht in der Übersicht übertragen und wäre deshalb frühestens beim Besuchen der Stadt anzeigbar.

**Comment by mordillo666** [comment]
@Th3C0D3R 
Das ist richtig, allerdings brauche ich in einer Stadt der Gegenwart kein Gebäude aus der Raumfahrt Mars zu suchen. ;-)
