### ISSUE TITLE
GG- Spielerliste

### ISSUE THREAD

**Issue by sbehnsen** [mainIine/foe-helfer-extension#677]
Die Liste ist oben etwas zu lang/zu hoch. Sie sollte unterhalb des Titelbalkens anfangen scrollt aber dahinter...
Eventuell könnte man den Table head von GuildPlayersBody loslösen und einzeln machen, wenn sich das nicht im CSS lösen lässt.

**Comment by outoftheline** [comment]
Mittlerweile ist die Liste resizeable :)
