### ISSUE TITLE
Feature Request - Forge Points

### ISSUE THREAD

**Issue by tlunglhofer** [mainIine/foe-helfer-extension#690]
It would be nice to have an easier way to access the FP stats that come up when you go to Town Hall-> Great Buildings.  Wither a button on the side that gives you a dedicated window that updates as you play would be fantastic to see FP on other buildings and profit constantly.

**Comment by scibuff** [comment]
The data is not available until you open the Great Building screen (from Town Hall) to list all your GB contributions. After that, it is possible to keep track of your new contributions, but you can see that in the calculator (for each building)
