### ISSUE TITLE
Feature Request - CSV export

### ISSUE THREAD

**Issue by arsqldba** [mainIine/foe-helfer-extension#692]
It would be great if the data in many of the windows could be exported into a .csv format so that it could be brought into a personal spreadsheet for tracking.

**Comment by jgwells1** [comment]
The next level would be to peek into BG to gather costs per building

**Comment by parascubasailor** [comment]
In the same line of reasoning, but maybe even simpler to implement, I would love to have a button on the PvP Activity screen that creates a text string for the selected neighbour containing the relevant information: PlayerName /tab/ Def% /tab/ Att% /tab/ ArmyUnit1 /tab/ ArmyUnit2 ... ArmyUnit8 /tab/ Date /tab/ GoodsPlundered /tab/ PlunderDateTime
It would then be easy to paste that information into the spreadsheet I currently use and fill "by hand"...
Great extension BTW !

**Comment by andrgin** [comment]
The tables for "Market", "Technologies" and "MoppelHelper" can now be exported to csv. Others will be added in future udpates
