### ISSUE TITLE
Feature Request - Friends, Guild, Neighborhood section

### ISSUE THREAD

**Issue by arsqldba** [mainIine/foe-helfer-extension#693]
I'm not sure of the possibilities here but it would be great if there could be a section (e.g. People) that including details or stats about the three social aspects of the game. Whether their tavern is open for a visit, what guild they are in, what are their great buildings, and possibly other things could be gathered.

Great tool!

**Comment by outoftheline** [comment]
We removed most features from the homepage and transferred them into the extension. Therefore, we will not implement this.
