### ISSUE TITLE
FP - investor

### ISSUE THREAD

**Issue by Tigertjheu** [mainIine/foe-helfer-extension#698]
Hi there!
I think it is a good idea to have the possibility to exclude some Great buildings from the list.
I have some that are in there for years, and it always say i lost a lot of fps, while im having a profit.

**Comment by dsiekiera** [comment]
Are you talking about the website version?

**Comment by scibuff** [comment]
I believe this refers to the Investment box (Boxes.Investment) where it shows the invested FP and Current profit. The issue (as I understand it) is that the current profit calculation includes buildings that have been on the list for several years and whose owners have probably stopped playing the game (or at least leveling that particular building).

**Comment by Tigertjheu** [comment]
Thnx scibuff, that is exactly what i meant!
