### ISSUE TITLE
Gildengüter in Produktionsübersicht

### ISSUE THREAD

**Issue by smarto65** [mainIine/foe-helfer-extension#708]
In der Produktionsübersicht hätte ich gerne eine Liste der von mir produzierten Gildengüter  mit Art und Anzahl pro Gebäude (Arche, Obsi, Atomium, Ehrenstatue, andere?) pro Tag und einer Gesamtsumme . Im letzten Tab der Produktionsübersicht als neue Auswahl "Gildengüter" wäre ein guter Platz.

**Comment by outoftheline** [comment]
Müsste mittlerweile implementiert worden sein
