### ISSUE TITLE
Antiques dealer - Auctions

### ISSUE THREAD

**Issue by MaikyGeerman** [mainIine/foe-helfer-extension#736]
Hello there, today at the antique dealer I bought something for not too much coins and I realized when I would exchange it, I would even make a small profit (if gems are take into consideration too). I bought the Lord's manor for 3503 coins on the auction, and it is exchangable for 3240 coins and 2-5 gems. Maybe you could make a button that when you open the antiques dealer, the extension would show if the current object for sale is worth/not worth to snipe based on the exchange value. Just an small idea, I'm loving the extension so far, I helps me a lot, thanks!

**Comment by dsiekiera** [comment]
This is a nice idea.
