### ISSUE TITLE
Can someone please respond?

### ISSUE THREAD

**Issue by syjytg** [mainIine/foe-helfer-extension#755]
https://prnt.sc/rv2xyp

**Comment by syjytg** [comment]
https://prnt.sc/rv54gh

What does KW 15 and KW 14 mean?

**Comment by Th3C0D3R** [comment]
Its Germen for Kehrwoche LUL
Just Kidding
It means Kalenderwoche which says which Week its is after the Year Change

**Comment by dsiekiera** [comment]
This Webpage Modul needs to be translated
