### ISSUE TITLE
Not activity and help alert

### ISSUE THREAD

**Issue by Franciko** [mainIine/foe-helfer-extension#770]
I would like to suggest you 2 things:
1) an new tab where we can find a summary of our friends and guild mates on a day basis about the helping and the entries in the tavern. An simple thing, 7 columns (one to each day) and 2 lines to each friend checking the help and entrance in tavern.
2) when we open the sniping tool to the Great Buildings, the windows of the Neighbour summary snipping great buildings can have another information, can tell if the neighbour its active or inactive in the last days (analysing the growing up of the individual power and battles  in the last 24 or 48 hours for example)

**Comment by outoftheline** [comment]
We removed most features from the homepage and transferred them into the extension by now. Therefore, we will not implement this.
