### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by DianeKomo** [mainIine/foe-helfer-extension#785]
This is just a suggestion.  I love the add on it really enhances game play.  One piece of information that would really help decision making in the game for events like the Spring Event 2020 would be the number of steps remaining.  If you're trying to maximise the number of steps you can make for your lanterns you need to know that to take the best decision on the final jumps.  Don't know if that's possible.

Diane

**Comment by andrgin** [comment]
Why do you need to know the steps remaining? All additional steps you make will be transfered to the next round.

**Comment by DianeKomo** [comment]
They're not.  The game only offers enough steps to finish the pond so if
you have only a single step left to finish the pond you end up using 50
lanterns whereas if you had managed it better you could have used two 80
lantern moves which would have averaged 40 points per step.  This isn't
like the football games where they are carried over.  This makes you finish
each pond with the precise number of steps.

**Comment by andrgin** [comment]
1.) This event tool was not written for spring evnt only. It was designed to work with all events with this pattern like football, soccer etc.

2.) Well even if the game does not offer you more steps than you need for the current there is not a real difference.
Lets say you are 4 steps away from the finish line:
You can take 4 steps at 150
You can take 3 steps at 100 and 1 at 50
You can take 2x2 steps at 75+75

All 3 choices have about the same costs.

**Comment by DianeKomo** [comment]
I'm sorry you misunderstand me. This isn't a criticism or a bug I'm
complaining about it was a gentle suggestion as to how to make a really
good tool ever so slightly better. I wasn't expecting an argument about it.
It's entirely up to you if you wish to take my suggestion on board.

However if there are five steps remaining it's always better to take a two
and a three than a four and one and if the only options offered for the
penultimate jump are a 2 or a 4 you need to know there are five steps left
and not 6 or 7. It's hard to work out visually which is where the problem
comes.

But please don't worry about it I won't trouble you again with any thoughts

**Comment by andrgin** [comment]
Hhm in case you get offered 2 and 4 it could really make sense to take the 4 if there are 4 left.

**Comment by DianeKomo** [comment]
But not if there are five steps left
