### ISSUE TITLE
Idea: Antique dealer

### ISSUE THREAD

**Issue by Kellasone** [mainIine/foe-helfer-extension#788]
Hello there, i have an idea which could be fun and useful:

On antic dealer, whenever is a deal in progress and i want to snipe a cheap item to sell it back to him for profit, i have to check wikipedia to see how much it is worth. I think a panel with this info could be useful.

Best Regards

**Comment by andrgin** [comment]
The problem is that Inno does not transfer the resale value until you already own that item and open the sell menu in the dealer.

**Comment by Kellasone** [comment]
Data can be scrapped from foe wiki. There it is available all the time

**Comment by Kellasone** [comment]
after a bit of research, it seems that only for a few items. u can find the resale prices on wiki. Previous, i found the data for some buildings and i assumed there is data for every building. That being said, my idea is indeed unimplementable, or a database could be used and every player could contribute to upload the prace for an item
