### ISSUE TITLE
Internal GM calculator : How does "Level" works ?

### ISSUE THREAD

**Issue by lnplnp** [mainIine/foe-helfer-extension#808]
![image](https://user-images.githubusercontent.com/934004/79208114-eea53580-7e41-11ea-9b46-e7e7bfd7a628.png)

Hi,

How the option "Level" ("Niveaux" in french, my language) works ?
Is it possible to include the Monument level in the message to copy-paste ?

Thanks.

**Comment by scibuff** [comment]
It adds a note "to level the building", e.g. Arc P3 P4 P5 please level (when you don't mind that the building is leveled)

**Comment by lnplnp** [comment]
Ah ok !

Is it possible to add patern that include the current and the next level of the building ?
So I can copy-paste this message "%MYNAME% %BUILDING% %CURRENT_LEVEL% -> %NEXT LEVEL% P1 (fp) P2 (fp) P3 (fp) P4 (fp) P5 (fp)"

For example : "MyName L'arche 10->11 P1(100) P2(40) P3(20) P4(10) P5(5)"

**Comment by scibuff** [comment]
It seems that there are too many formats/schemes to include them all. Probably the best would be the ability to add/save/edit/delete user defined formats/schemes.

**Comment by andrgin** [comment]
I will take at it.
