### ISSUE TITLE
In "investments", is it possible de add fp received ?

### ISSUE THREAD

**Issue by lnplnp** [mainIine/foe-helfer-extension#811]
Hi,

In "investments" popin (see capture under), is it possible to consider the forge points invested in my own Grands Monuments? So I will know if I have given more than what I have been given.
Indeed, in the "Endless Chains", when I give 5 forge points, I am supposed to receive 5 forge points. So I don't lose these 5 forge points.

![image](https://user-images.githubusercontent.com/934004/79236052-b5ce8600-7e6c-11ea-97ec-981fe736356b.png)

**Comment by andrgin** [comment]
This statistic only shows your investment into great buildings that have not been leveled yet. So if you compare FP paid by your guild mates into your great buildings and investments you made into your guild mates great buildings this will never be equal. It will only be equal if nobodylevels his great building.
