### ISSUE TITLE
Date of last login // last investment in GB

### ISSUE THREAD

**Issue by fxmozart** [mainIine/foe-helfer-extension#823]
Would it be possible to add  : 
-either the last login date of a player (when we visit him or his GB).
-Last date when someone invested in a GB of the visited player or visited GB.

This would help when we want to invest in a GB of a "friend" or neighbour, as if they havent logged in for some time it might be better not to invest.

Best.

**Comment by scibuff** [comment]
The only data that's available about a player is the `is_active` field, which i assume is login in the last 30 days.

**Comment by Th3C0D3R** [comment]
I think its actually the same if the player is red in a guild which is 7 days or so.

**Comment by andrgin** [comment]
If you have already visited this GB and there was no investment since then (green line in overview) we could show the "first seen" date.
