### ISSUE TITLE
Außenposten: Der Tooltip bei den Diplomatiekosten funktioniert nicht

### ISSUE THREAD

**Issue by Gindi4711** [mainIine/foe-helfer-extension#849]
Die Tooltip wenn man mit der Maus auf das Fragezeichen in der Diplomatiespalte geht funktioniert nicht.

**Comment by andrgin** [comment]
Kleiner Zusatz: Es funktioniert nur dann nicht, wenn man noch kein Diplomatiegebäude freigeschaltet hat.
