### ISSUE TITLE
New feature: Antiek timer

### ISSUE THREAD

**Issue by ghost** [mainIine/foe-helfer-extension#850]
Hi, can you implement a timer that we can start with a variable duration to help up with the antiek dealer ? 

Greets,

**Comment by scibuff** [comment]
I'm already working on that ... should be ready for beta this week

**Comment by dsiekiera** [comment]
Nice to hear

**Comment by giumi438** [comment]
Excellent ! Keep up the good work !!!

**Comment by scibuff** [comment]
Please see #900
