### ISSUE TITLE
Homepage: Investitionsübersicht zeigt falsche investierte FP

### ISSUE THREAD

**Issue by Gindi4711** [mainIine/foe-helfer-extension#877]
Wenn man die Einzahlung in ein LG aufstockt (Wert in der Spalte "Investierte FP" wird mit + angezeigt), so wird nur der alte kleinere Wert gezählt.

Beispiel:
Investierte FP 1758 (+1501).
Gezählter Wert: 1758 - 1501 = 257

**Comment by Camulos-it** [comment]
I'd like you change the code to limit the calculation to the "sure" positions, i.e. if i took a position with 100 PF but someone could still overtake me, the calculation should take in count only the minimum amount sure i'll have back.

**Comment by andrgin** [comment]
Unfortunately we dont have that information available. We dont know how many FP the next place is and if it will be safe, because there is no ranking information in the overview.
We cant even tell if a place is safe. All we can do is mark GB that have more FP peft than your investment.
