### ISSUE TITLE
Highlight Guild vs Non Guild Member donations

### ISSUE THREAD

**Issue by Tinman4** [mainIine/foe-helfer-extension#891]
In larger guilds with 20+ users, it becomes difficult to keep track of new members. Is it possible to alter the color of those contributing from guild vs non guild? 
This also ensures other guild members aren't sniping one another.

**Comment by scibuff** [comment]
I'm not sure I understand what you mean? Highlight what where ? Could you make a screenshot? 

I don't understand really how you'd snipe another guild member?

1) Remove all your guildies from your friend list (there's no point of keeping players on two lists)
2) When you *snipe* you lock the slot, so no one (not a guildie nor a non-guildie) can snipe

**Comment by Tinman4** [comment]
[image: image.png]

**Comment by osv** [comment]
you need reply using github, screenshot is not visible

**Comment by Tinman4** [comment]
![Snag_162aa3f2](https://user-images.githubusercontent.com/55988770/80505186-000e3780-8942-11ea-98e7-fa1696b3fffb.png)

**Comment by scibuff** [comment]
I guess, in theory, the Cost Calculator could show this info for each taken slot but there are a few complications, for example, the rankings (contributions) list of players does not provide the guild details (only the player id). If I'm not mistaken, there list of players (player ids) in a guild is available only after loading the guild info in the game (for example, either going through the guild players in the bottom panel, or viewing the guild info etc).

**Comment by Tinman4** [comment]
Thank you for taking a look. You can close

**Comment by Th3C0D3R** [comment]
The list with all guildmembers is loaded on startup. So if this list is saved its possible to highlight the  guildmembers is the cost calculator
