### ISSUE TITLE
Suggestion GE scoreboard

### ISSUE THREAD

**Issue by strugure-merlot** [mainIine/foe-helfer-extension#904]
Stats are an amazing feature , thank you, can the GE be added to export the GE scoreboard?

**Comment by osv** [comment]
I'm not sure about a good example of use case of GE scoreboard.. why it might be good to know when user played GE? Most of guild just require from member to finish it, that all :)

**Comment by scibuff** [comment]
I guess the export would help you to keep track of GE completion over time

**Comment by osv** [comment]
You dont need per-day statistic but per week (GE season)? Just to have ability exporting it as far I understand

**Comment by scibuff** [comment]
I'm not sure whether the OP meant to track changes in GE completion or just the ability to export the current GE completion stats (e.g. into a spreadsheet). The former could work in the same as the battlegrounds does. The later would be just a simple export (of the current data to import into a spreadsheet for example).

**Comment by strugure-merlot** [comment]
Most guilds require a minimum in GE and they keep  track of the end results ( number of encounters resolved), so yes the ability to export at the end of the GE season would make life so much easier :-)
