### ISSUE TITLE
Quest lists in Cultural settlement

### ISSUE THREAD

**Issue by jollii** [mainIine/foe-helfer-extension#906]
Hi,

I've been using FOE-helper for a month and I find it great!
My suggestion is that I find it will be very handy to show the quest list in the Cultural settlement, especially in the Egyptian.
When I do some construction I always check the next five following quest, however sometimes it can be time-consuming to open the thread in Fandom.
I hope my suggestion would be helpful.

Best regard,
J.

**Comment by Cory847** [comment]
+1

**Comment by ammaar1267** [comment]
+1

**Comment by PeacefulWrestler** [comment]
+1
