### ISSUE TITLE
Score Increase Per Day / Per week

### ISSUE THREAD

**Issue by ammaar1267** [mainIine/foe-helfer-extension#910]
Hello 
I really like your work. Can you please add score details like battle points(How many fights you fought and you generate such score), Collection score up like Arc GB Treasury goods score. I mean everything which increase scores like fight, Guild treasury and GB level up. And display in per day, per week and per month. 
Thank you

**Comment by kwhelan1** [comment]
Agree with this.  Nice job on this app.

**Comment by osv** [comment]
btw, you can use thirdparty sites that collect score: e.g https://foe.scoredb.io/ru1/Player/442767
