### ISSUE TITLE
Useraccount erstellen / Daten PC übergreifend nutzen

### ISSUE THREAD

**Issue by marcomo09** [mainIine/foe-helfer-extension#912]
Hi,
aktuell ist es ja nicht möglich das Tool mit einen Useraccout zu verknüpfen und so auf die gesammelten Daten an verschiedenen PCs zu zugreifen.
Sprich, wenn ich FOE an verschiedenen PCs spiele werden meine Daten, wie Statisken, PVP Übersicht, LG Sniper Kostenrechner nicht von PC 1 auf PC 2 übertragen etc.
Dafür müssten die Daten halt auf einen Server gespeichert werden und man müsste per Useraccount drauf zugreifen können so das man überall die gleichen Daten hat.
Hoffe ihr versteht was ich meine, und vielleicht ist das ja irgendwann möglich? 

Ansonsten kann ich nur sagen, super Tool, danke dafür :)

mfg
marcomo

**Comment by andrgin** [comment]
Ja das Problem mit mehreren PCs ist uns bewusst. Leider haben wir dafür derzeit keine einfache Lösung. Eine ständige Client/Server Kommunikation wäre zwar technisch machbar, jedoch würde das bei ca. 50K Nutzern schon einiges an zusätzlichen Ressourcen am Server benötigen, was dann eher ein finanzielles Problem ist.

**Comment by scibuff** [comment]
It could possibly be a paid feature or financed through Patreon but that would take this endeavor to a whole new level ...

**Comment by Polyfly** [comment]
Kann man dies nicht mit einem storage.sync lösen? Sowohl unter Firefox als auch Chrome könnte man ein json mit Hilfe eines Accounts (z.B. Google Account) speichern und mit jedem angemeldeten Browser synchronisieren. Wäre aber meines Wissens nach auf eine bestimmte Anzahl von Einträgen limitiert. Ob dies reichen könnte, müsst ihr entscheiden.

**Comment by scibuff** [comment]
storage.sync cannot be used due to its limits on data storage and # of writes/reads
