### ISSUE TITLE
Chrome, Synchronize Extension Data

### ISSUE THREAD

**Issue by kwhelan1** [mainIine/foe-helfer-extension#913]
If you use multiple chrome browsers on different devices,  data in the new history function is not updated between browsers.   It appears from the link below that you can use storage.sync rather than storage.local and it will sync between browsers if you are logged in to the browser.

https://developer.chrome.com/extensions/storage

**Comment by scibuff** [comment]
Yes, unfortunately, using Chrome Sync places very strict restrictions on the amount of data that can be stored. It is questionable to use this feature for a data heavy application such as this one.

**Comment by kwhelan1** [comment]
Thanks for the quick response. . .

**Comment by osv** [comment]
Need to have server to sync it, but it super increase complexity

**Comment by andrgin** [comment]
Do not forget we need to support Firefox as well.

And yes quota limits are an issue. It could be enough for settings, but not for data like the GBG stats etc. Also the stats are saved in indexedDB.
