### ISSUE TITLE
Statistik GEX Relikt Seltenheit

### ISSUE THREAD

**Issue by TachTach** [mainIine/foe-helfer-extension#916]
Ist es irgendwie möglich die Seltenheit der Reklikte mit in die Statisik aufzunehmen?
Vieleicht so: 
![Z80AtL1](https://user-images.githubusercontent.com/12811212/80577963-0f57b880-8a08-11ea-8522-cca3aa6f76ec.png)
statt: 
![l8ezpSM](https://user-images.githubusercontent.com/12811212/80577978-167ec680-8a08-11ea-8577-edfa5c33778d.png)
oder als ganz eigenen Menü Punkt.

**Comment by osv** [comment]
Hi, grouping by silver, gold, jade is not done because there were  no much time to test it and because of developer have low level of temple of relic to collect necessary amount of rewards. Maybe later it will support grouping. I'm also interesting on it

**Comment by scibuff** [comment]
I have level 58 TOR (30%) so I'll taking some stats

**Comment by osv** [comment]
@scibuff in dev console you can run  `copy(await IndexDB.db.statsRewardTypes.toArray())`
and paste somewhere

**Comment by scibuff** [comment]
Cool, I see I can use that to track rewards from HC and the Space Carrier as well ;)
