### ISSUE TITLE
List of ideas

### ISSUE THREAD

**Issue by szurabura** [mainIine/foe-helfer-extension#932]
First of all, I'd like to thank you for amazing work, your tools are very useful (while sometimes too powerful, if you ask me, but whatever :)). Anyway, since I've started using the tool I had many ideas and finaly joined GitHub so I can share. They're in no particular order:

- overlay to select preferred units to attacking army (like rogues and one or two other favourites instead of having to search them in menu) - not sure if possible, but would be super useful. Also number of those units.
- better inventory menu - original one is annoying with only 8 items per page. Also goods could be Era colour coded to easier distinguish them, like on mobile version.
- building kits should include proper upgrade items as well. I.e. Spring Set doesn't include the upgrades, which are in fact also buildings. Without it renders the menu useless for me.
- negotiation helper isn't actually helping in easy tasks, i.e. only 3 goods to choose from. It should ALWAYS ask for 5x gold, 5x tools then finish with whatever there is, instead of probing with a mix of goods and gold/tools.
- city overview to display grid also on placed buildings, it would help with planning
- be able to set global profile for every world, including menu order and all settings instead of having the settings separate for each world
- self-check of great buildings against sniping below 1,9 (or set higher)
- be able to set manufactured goods for negotiation helper as preferred, regardless of their amount
- option to remove rogue only warning
- option to remove estimated attack / defense value of neighbour
- change the PvP activity icon please. I keep thinking I got robbed :)
- [English] Forum button has mistakes: "You have a question? **You annoying something? Or just to talk ...**". Needs to be corrected :)

**Comment by osv** [comment]
> overlay to select preferred units to attacking army (like rogues and one or two other favourites instead of having to search them in menu) - not sure if possible, but would be super useful. Also number of those units.

impossible

> better inventory menu - original one is annoying with only 8 items per page. Also goods could be Era colour coded to easier distinguish them, like on mobile version.

Even if we create alternative inventory menu, all what you able to do is **view** only, you will not be able to deploy buildings from FOE helper. 

> building kits should include proper upgrade items as well. I.e. Spring Set doesn't include the upgrades, which are in fact also buildings. Without it renders the menu useless for me.

known bug..

> negotiation helper isn't actually helping in easy tasks, i.e. only 3 goods to choose from. It should ALWAYS ask for 5x gold, 5x tools then finish with whatever there is, instead of probing with a mix of goods and gold/tools.

yes, this is special case, good to have.

> city overview to display grid also on placed buildings, it would help with planning


> be able to set global profile for every world, including menu order and all settings instead of having the settings separate for each world

Not possible I guess, settings are saved per domain (url before "/")

> self-check of great buildings against sniping below 1,9 (or set higher)

> be able to set manufactured goods for negotiation helper as preferred, regardless of their amount

Hey, maybe I'm not first one, but you should focus on Chateau Frontenac and forget about manufactures!

> option to remove rogue only warning

already reported, probably will be in next release 

> option to remove estimated attack / defense value of neighbour

Agree

> change the PvP activity icon please. I keep thinking I got robbed :)

pls save our life and give your suggestion :) But I like current icon 

> [English] Forum button has mistakes: "You have a question? You annoying something? Or just to talk ...". Needs to be corrected :)

pls give suggestion for change

**Comment by szurabura** [comment]
> 
> 
> > overlay to select preferred units to attacking army (like rogues and one or two other favourites instead of having to search them in menu) - not sure if possible, but would be super useful. Also number of those units.
> 
> impossible

Well, expected that, still was curious ;)

> > better inventory menu - original one is annoying with only 8 items per page. Also goods could be Era colour coded to easier distinguish them, like on mobile version.
> 
> Even if we create alternative inventory menu, all what you able to do is **view** only, you will not be able to deploy buildings from FOE helper.

No point then I guess.


> 
> > building kits should include proper upgrade items as well. I.e. Spring Set doesn't include the upgrades, which are in fact also buildings. Without it renders the menu useless for me.
> 
> known bug..

Sorry.

> 
> > negotiation helper isn't actually helping in easy tasks, i.e. only 3 goods to choose from. It should ALWAYS ask for 5x gold, 5x tools then finish with whatever there is, instead of probing with a mix of goods and gold/tools.
> 
> yes, this is special case, good to have.
> 
> > city overview to display grid also on placed buildings, it would help with planning
> 

![image](https://user-images.githubusercontent.com/64558520/80724576-4ca07100-8b02-11ea-8980-b98149d6bf93.png)
That's what I meant :)

> > be able to set global profile for every world, including menu order and all settings instead of having the settings separate for each world
> 
> Not possible I guess, settings are saved per domain (url before "/")
> 

Fine.

> > self-check of great buildings against sniping below 1,9 (or set higher)
> 
> > be able to set manufactured goods for negotiation helper as preferred, regardless of their amount
> 
> Hey, maybe I'm not first one, but you should focus on Chateau Frontenac and forget about manufactures!

Well, it depends on the realm. Let me elaborate my point. On my main realm, I have thousands of goods and couldn't care less which are being used first. So this part of helper isn't of any use for me. I also have no use of negotiation helper at all. But I also play on relatively new realm (6 months old), where I use this part of helper a lot. And on the realm there's still huge shortage of everything and ChF is a luxury only few have. Everybody is using manufactures.

![ilosc](https://user-images.githubusercontent.com/64558520/80723839-67261a80-8b01-11ea-8a16-76f49f5b8ffe.JPG)

Please see above screenshot from that realm. It's not rearranged yet. Helper favours a good I have no constant supply (130 Fertilizer) and I don't have a lot of it. It's pita to get for me so I always move to be least used. On the other hand, Tinplate, which is abundant for me (366) is not favoured. I'd love keep it favoured, since I have 3 plants producing it daily and I do not risk running out of it. I' ope you understand.



> 
> > option to remove rogue only warning
> 
> already reported, probably will be in next release
> 
> > option to remove estimated attack / defense value of neighbour
> 
> Agree
> 
> > change the PvP activity icon please. I keep thinking I got robbed :)
> 
> pls save our life and give your suggestion :) But I like current icon
> 

Anything but an icon of being plundered. But might as well drop this topic, it's not important really. I just moved the icon to second row.

> > [English] Forum button has mistakes: "You have a question? You annoying something? Or just to talk ...". Needs to be corrected :)
> 
> pls give suggestion for change

"You have a question? Are you annoyed by something? Or just want to talk?"

**Comment by andrgin** [comment]
Fertilizer is from industrial age, tinplates is from progressive era. You have selected "save current goods" so it will save goods of progressive era. If you disable this option it will use tinplates first because of higher stock.
