### ISSUE TITLE
cost calculation of my own Great buildings

### ISSUE THREAD

**Issue by shodbyed** [mainIine/foe-helfer-extension#935]
i love the cost calculator for profit loss lock amount etc.  when i open my own building i would like to see what it would cost someone so i could see if it is profitable or at a loss etc.

**Comment by andrgin** [comment]
If someone can snipe a place in your great building and the damage to you is more than 5 FP there is a label "danger X FP" while X is the amount of FP you could be loosing.
This also applies to situations where P2 is in danger after P1 has been paid.

**Comment by shodbyed** [comment]
Well truthfully I am not worried too much about sniping as I don't self
donate and all my buildings are over level 60.   My reasoning is I want to
see how much people will lose if they do want a spot (my guild takes
positions with the loss and owner pays the difference) or to be able to
help my friends easier

**Comment by andrgin** [comment]
Bwfore the investment: Loss when overpaying is 50% of the own part that is listed above this place.
Example: P1 is 200 FP, your own part before that is 100 FP.
If someone needs to lock the place without your own part he needs to invest 250 FP (200 + 100/2).

After the investment:
You can see how much each player over/underpaid.
Example: "250" in blue, "(+50)“ in green

If you are not sure you can also simulate an investment by putting the 250FP in the Ext column.
