### ISSUE TITLE
2 ideas

### ISSUE THREAD

**Issue by FreedamnDE** [mainIine/foe-helfer-extension#940]
Hi,

I got 2 ideas:
- it would be pretty helpful, if the new statistic hub remembers my settings. I like the line diagram way more than the stream and it'd be good if it can remember my preferences. Same with goods- goods daily and so on. Maybe checkboxes would be good here. Just like the new negotiation-add on, which is great btw. Anyway I really like the new statistic feature! :)
- In the city-overview tab, it's currently displayed, how much total space and how much freespace there is, but there is so much free space in this bar. I'd like some %-values for 1. Useful space (everything that is not free space and streets, cause you want to minimize it (would be very nice for comparison)) 2. legendary buildings, 3. eventbuildings 4. etc. We already got a differentiation with the colours, why not point it out in numbers? :)

**Comment by osv** [comment]
there were plan to save settings for statistic, like chart type for chart source, I think make sense add it to reduce number of clicks
