### ISSUE TITLE
Idea: friends list and friends activity

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#953]
Hi.

First idea (simple): export friends nicknames in txt format.

Second idea (more complex): expord friends list + friends activity (Tavern and buff) from event log from Town hall (sorry if I mismatch in terms).

**Comment by RealTracat** [comment]
As part of this is (just in case this isn't part of the above) a list of all your friends with a column, which is sortable, of how many times they have aided. with any of 3 or below (adjustable via a box?) shown in red.
Would be handy to see who is not aiding enough in the last 7 days so you can trim your friends list.

**Comment by lmgutman** [comment]
that would be great
