### ISSUE TITLE
Idea: Stats - table view - freeze top row (maybe first column) and move slider

### ISSUE THREAD

**Issue by scibuff** [mainIine/foe-helfer-extension#967]
I'm looking at the `table data` of the `Battleground` stats and I see that the horizontal slider is all the way at the bottom, so it is impossible to use (where are the many rows) unless you scroll all the way down (please see below)

![image](https://user-images.githubusercontent.com/722049/80954651-157dd880-8dfe-11ea-89d9-d5c07446599c.png)

![image](https://user-images.githubusercontent.com/722049/80954707-31817a00-8dfe-11ea-8b25-7e253e8ee83b.png)

Also, it would be useful (for this kind of view) to "freeze" the top row (with the player names) and maybe even the first column (`datetime`) so that you can see those as you scroll through the table (for example, the same way google spreadsheets do), i.e. the table sliders (scrollbars) should affect only the data

![image](https://user-images.githubusercontent.com/722049/80954851-760d1580-8dfe-11ea-8d73-13a6760256b9.png)

**Comment by osv** [comment]
I recommend you to export to CSV instead. You can click multiple time "view table data", and how to make work sticked 1st col/row in case is clicked several times "view data table"?

**Comment by osv** [comment]
Personally I'm using this table only for rewards

**Comment by osv** [comment]
Btw, there is standard way how to horizontal scroll "mouse wheel + shift" :)

**Comment by scibuff** [comment]
Right, I just thought overflowing the tbody should do it (if we don't care about IE support) ... but might be a bit more complex than I thought
