### ISSUE TITLE
Idea: Einstellungen erweitern / add. settings

### ISSUE THREAD

**Issue by Leuselator** [mainIine/foe-helfer-extension#971]
Die einzelnen Helfer-Module in den Einstellungen via Checkboxen An-/ Abschaltbar machen, so dass inject.js nur die aktivierten lädt.

En-/ Disable the helpers in settings via checkboxes so inject.js loads only the activated ones.

**Comment by andrgin** [comment]
Dies ist technisch nur mit großem Aufwand realisierbar, da die Module gegenseitig Abhängigkeiten haben. Das Technologiemodul enthält z.B. die Namen bzw. Nummern der Zeitalter. Diese Informationen werden z.B. beim Verhandlungsassistent, Einheitenübersicht, Produktionsübersicht etc. verwendet.

**Comment by Leuselator** [comment]
ok - checkboxen nur für die Neuzugänge (meine z.B.) ?
