### ISSUE TITLE
Eigenanteilsrechner zeigt Plätze als "gefährdet" an, obwohl Stufe nicht freigeschaltet

### ISSUE THREAD

**Issue by Andi47** [mainIine/foe-helfer-extension#980]
Wenn ein bei einem eigenen LG (z.B. mein StarGazer Stufe 47) die nächste Stufe nicht freigeschaltet ist, weil z.B. noch Blaupausen fehlen, zeigt der Eigenanteilsrechner trotzdem die Plätze 1 und 2 als "gefährdet" an.

Ich denke, in diesem Fall (d.h. wenn die nächste Stufe nicht freigeschaltet ist) sollte die Tabelle "ausgegraut" sein (mit Meldung "Stufe nicht freigeschaltet" - ähnlich wie beim Kostenrechner, wenn das LG des Spielers, bei dem man einzahlen will, nicht freigeschaltet ist.)

Edit: Windows 10 home
Google Chrome Version 81.0.4044.138 (Offizieller Build) (64-Bit)
zz1 (Betaserver)
Extension Version 2.4.5

**Comment by scibuff** [comment]
Isn't it good to see slots at risk before you open the next level?

**Comment by Andi47** [comment]
Yes, but it would be also good to see that the places are NOT opened. Many of our guild have the FOE-Helper, and closed GBs keep being posted in our "1.9"-chain.

(and it just happened to me: Leveled up my Stargazer, my helper displayed the places being at risk, and I posted them into the chain via the copy-functionality of the helper.)

The copy function of the helper DOES recognize, when a place is not save, but the helper (and its copy function) does NOT recognize when the building is still closed.

**Comment by andrgin** [comment]
I think the table showing the danger values is important so you know that it could get expensive if you unlock it without getting P1/2 populated very fast.

I think it would make more sense to integrate the check only into the copy function when using the auto select for safe places.

**Comment by Andi47** [comment]
Integrating a check into the copy function would make sense - AND maybe also a red (or red blinking) line above the table, so that you can see the warning"Building NOT open!!!" *and* the "danger" warning

**Comment by andrgin** [comment]
I dont think a warning in the table is needed as there is not really a danger by not opening it.

**Comment by Andi47** [comment]
Not really danger, but the guild is increasingly annoyed as closed Great Buildings keep being posted in the "factor 1.9"-chain. 
And this seems to happen because the helper shows the slots with "danger" without a hint that the building is not yet open.
